#+TITLE: 2015年6月技能「Orgmode」
#+TAGS: Emacs, Org

#+BEGIN_QUOTE
每月学项新技能!

15年6月要学的技术是Emacs里的Orgmode.

整体学习思路:

1. 边用边学
2. 参看手册和Emacs help, 以及同好Blog
3. 分解学习目标, 每天学习一项
#+END_QUOTE

** Todo items
** Hyperlinks
** Tags
** Tables
** Properties and columns
** Dates and times
** Capture-Refile-Archive

*** Capture

Q: 临时有待做事项进来, 如何快速添加该事项到GTD系统中?
A: 使用Org-capture, 一键打开临时添加窗口, 添加后, 可以立即返回原操作界面.

Q: 如何快速先体验下capture功能?
A: 添加下面的配置, 指定capture默认保存的文件和快速打开capture功能的快捷键.
#+BEGIN_SRC
(setq org-default-notes-file (concat org-directory "~/org/notes.org"))

(define-key global-map "\C-co" 'org-capture)
#+END_SRC

Q: 在Capture中输入完事项后, 如何保存以及回到原来的操作界面?
A: C-c C-c (M-x org-capture-finalize)

Q: 要是想把在Capture中输入的事项, 保存在另外一个文件中怎么办?
A: C-c C-w (M-x org-capture-refile)

Q: 我想在capture中插入不同类型的任务, 怎么办?
A: 可以通过定制变量 org-capture-templates 实现, 比如:

#+BEGIN_SRC
(setq org-capture-templates

'(("t" "Todo" entry (file+headline "~/org/gtd.org" "Tasks")
"* TODO %?\n %i\n %a")))
#+END_SRC

上面templates包含的元素有:

| keys | description | type  | target             | template    |
|------+-------------+-------+--------------------+-------------|
| "t"  | "Todo"      | entry | (file+headline ..) | "* TODO .." |

具体各项的含义, 以及template字段包含的转义符含义, 可以通过C-h v
org-capture-templates 查看帮助文档.

*** Refile

#+BEGIN_QUOTE
file v.

If you file a document, you put it in the correct file.

refile v.

顾名思义, 把文档中的内容再次放到合适的文件中去.
#+END_QUOTE

Q: 某一文件中的事项, 需要「移植」到其它文件中, 该如何快速操作?
A: 使用Org-refile, 很方便的可以实现上述目标.

*** Archive

Q: 在GTD中已经完成的事项, 想从文件中删除, 但又想后续可以查看, 怎么办?
A: 使用Org-archive, 可以将这些已完成事项保存在指定的archive文件中.


** Agenda views
** Exporting
