#+TITLE: 2015年6月技能「Orgmode」
#+TAGS: Emacs, Org

#+BEGIN_QUOTE
每月学项新技能!

15年6月要学的技术是Emacs里的Orgmode.

整体学习思路:

1. 边用边学
2. 参看手册和Emacs help, 以及同好Blog
3. 分解学习目标, 每天学习一项
#+END_QUOTE

** Todo items
** Hyperlinks
** Tags
** Tables
** Properties and columns
** Dates and times
** Capture-Refile-Archive

#+BEGIN_QUOTE
在工作中, 时不时地会有新的待办事项突然出现, 如何快速地将这些待办事项加入到
GTD系统中?

添加到GTD系统中的待办事项, 有可能分布在多个文件中, 如何快速地将某事项从一
个文件移植到另一个文件中?

已完成的待办事项, 如何存档?
#+END_QUOTE

*** Capture

Q: 临时有待做事项进来, 如何快速添加该事项到GTD系统中?

A: 使用Org-capture, 一键打开临时添加窗口, 添加后, 可以立即返回原操作界面.


Q: 如何快速先体验下capture功能?

A: 添加下面的配置, 指定capture默认保存的文件和快速打开capture功能的快捷键.

#+BEGIN_SRC
(setq org-default-notes-file (concat org-directory "~/org/notes.org"))

(define-key global-map "\C-co" 'org-capture)
#+END_SRC

Q: 在Capture中输入完事项后, 如何保存以及回到原来的操作界面?

A: C-c C-c (M-x org-capture-finalize)

Q: 要是想把在Capture中输入的事项, 保存在另外一个文件中怎么办?

A: C-c C-w (M-x org-capture-refile)


Q: 我想在capture中插入不同类型的任务, 怎么办?

A: 可以通过定制变量 org-capture-templates 实现, 比如:

#+BEGIN_SRC
(setq org-capture-templates
'(("t" "Todo" entry (file+headline "~/org/gtd.org" "Tasks")
"* TODO %?\n %i\n %a")))
#+END_SRC

上面templates包含的元素有:

| keys | description | type  | target             | template    |
|-+---+--++---|
| /    | /           | /     | /                  | /           |
| "t"  | "Todo"      | entry | (file+headline ..) | "* TODO .." |

具体各项的含义, 以及template字段包含的转义符含义, 可以通过C-h v
org-capture-templates 查看帮助文档.

*** Refile

#+BEGIN_QUOTE
file v.

If you file a document, you put it in the correct file.

refile v.

顾名思义, 把文档中的内容再次放到合适的文件中去.
#+END_QUOTE


Q: 某一文件中的事项, 需要「移植」到其它文件中, 该如何快速操作?

A: 使用Org-refile, 很方便的可以实现上述目标.

C-c M-w (M-x org-copy) 把事项拷贝到其它文件, 原文件中事项仍在.

C-c C-w (M-x org-refile) 把事项移动到新文件, 原文件中事项不在.

*** Archive

Q: 在GTD中已经完成的事项, 想从文件中删除, 但又想后续可以查看, 怎么办?

A: 使用Org-archive-subtree, 可以将这些已完成事项保存在指定的archive文件中.

C-c $ (M-x org-archive-subtree) 把当前光标所在处的subtree存档到
org-archive-location指定的位置去.

** Agenda views

#+BEGIN_QUOTE
GTD中的事项分散在各个不同的文件中, 如果方便地从不同的维度或视角来查看所有
事项?

Org提供了七种查看方式:

1. agenda view (C-c a a)
2. TODO list (C-c a t)
3. match view (C-c a m)
4. timeline view (C-c a L)
5. text search view (C-c a s)
6. stuck projects view (C-c a #)
7. custom view
#+END_QUOTE

Q: 如何快速调出agenda?

A: 设置一个全局快捷键如下
#+BEGIN_SRC
(global-set-key "\C-ca" 'org-agenda)
#+END_SRC


Q: 我有好多的GTD文件, 如果只想在agenda中查看某些文件的事项, 怎么设置?

A: agenda会从变量 org-agenda-files 指定的文件列表中, 抽取事项进行展示.


Q: 如何快速将当前GTD文件添加到org-agenda-files中?

A: C-c [ (M-x org-agenda-file-to-front)


Q: 如何快速将当前GTD文件从org-agenda-files中删除?

A: C-c ] (M-x org-remove-file)


Q: 显示的Agenda中默认的是两周时间, 这个显示天数可以改吗?

A: 可以设置变量org-agenda-span

** Exporting
