#+title: 互联网广告
#+author: 李继刚

互联网发展至今, 主要的商业模式主要有三类: 广告, 游戏和电商. 很多互联网内容之所以
可以免费访问, 除了边际成本极低这个特点以外, 主要原因就是这三类商业模式在支撑. 今
天主要记录下广告这种模式的相关内容.

假设你是一个游戏达人, 有自己的网站, 平时主要分享一些游戏攻略和游戏介绍等信息. 你
统计了一下自己网站的访问数据, 平均每个月有10000个人访问网站(UV, Unique Vistor),
一共访问了100000个页面(PV, Page View), 即UV = 1,0000; PV = 100,000; 这时你每天都
在支付流量费, 机房服务器的费用, 但并没有任何收入.

有一天, 广告主找过来, 想在你网站首部放一个Banner, 展示广告主的产品信息, 每天给你
100块钱, 先包一个月试试效果. 你接了下来, 这样你一个月就可以收入:
#+BEGIN_CENTER
100元/天 * 30天 = 3000元
#+END_CENTER

#+BEGIN_QUOTE
这种按时间定价的结算方式即为CPT(Cost per Time), 如果这里的时间是天计算的,可细化
为CPD(Cost per Day). 这种方式简单粗暴, 广告主和媒体方直接商定好每天价格和包断时
长, 不管谁来访问网站都能在这个时间段内看到广告主指定的广告内容.

计算方式也很简单:

Revenue(收入) = Value(每时间价格) * Time(包断时长)
#+END_QUOTE

但做为网站主, 你觉得可以再多挣些钱, 你与广告主沟通说, 我们再换一种结算方式吧. 不
按点击次数来计费, 我们按展示次数来计费, 每展示1次页面就付费0.05元. 业内一般定价
时使用每千次展示的价格, 在这个例子里, 即为每展示1000次页面就付费50元. 这样仍以之
前的数据来算, 你将获得收入:

#+BEGIN_CENTER
Revenue = CPM * PV / 1000 = 50元 * 100,000 / 1000 = 5000元
#+END_CENTER

#+BEGIN_QUOTE
这种结算方式即为CPM(Cost per Mille). 即每展示1000次页面, 能获得多少收入.
#+END_QUOTE

上面两种CPT和CPM的结算方式, 与没有互联网之前的传统线下媒体广告结算方式类似,都属
于是「合约广告」.

但上面这类的结算方式, 广告主是有意见的, 他们只知道广告费花出去了, 也给用户看到了,
但里面有多少生效了, 这些数据是无法统计到的. 他们提出要按效果计费,即当有人点击广
告时, 才支付你费用, 如果只是展示给某个用户, 但该用户没有点击广告, 广告主是不需要
支付任何费用的. 你也想尝试下该方式能不能多给你带来点收入. 于是就又签了一个月, 按
点击次数计费. 每点击一次广告主支付你0.5元. 假如说访问人数和页面访问次数和之前统
计数据保持不变, 广告一共被点击了5000次, 即

Clicks = 5000; UV = 1,0000; PV = 100,000; CTR = 5% (CTR, Click through Rate =
clicks / PV).

按之前的约定, 广告主共支付你:

#+BEGIN_CENTER
Revenue = Clicks * CPC = 5000 次点击 * 0.5元/每次点击 = 2500元
#+END_CENTER

#+BEGIN_QUOTE
这种按点击效果计费的结算方式即为CPC(Cost per click), 在这个例子里, CPC = 0.5元.
相比于CPT, 这种方式对广告主来说明显更为靠谱些, 广告费都花在了对广告感兴趣的人群
身上.
#+END_QUOTE

随着移动互联网的蓬勃发展, 广告主从一开始的购买「曝光」, 到后来的购买「点击」, 越
来越关注最核心的指标「ROI」, 即最终的转化率. 广告主又找到你沟通, 在CPC的基础上,
他们要再换一种更接近ROI指标的计费方式: CPA/CPS.

#+BEGIN_QUOTE
CPA(Cost Per Action): 每次操作行为的价格. 「操作行为」各广告主可能会有不同的定义,
一般为「注册」, 「验证信息」等等. 即每当有一个用户从你网站的广告位下载了APP, 并
进行了「注册」行为, 广告主将给你支付一定金额.

CPS(Cost Per Sale): 每次交易行为的价格. 「交易行为」比如说每当有一个用户从你网站
进入电商广告主网站购买了一件商品, 广告主会分你5%. 再比如每当有一个游戏用户从你网
站的广告位下载了游戏APP, 如果他在里面进行了充值, 你将获得充值金额的5%分成.
#+END_QUOTE

对你这个网站主来说, 这么多的结算方式, 看起来很复杂, 而且广告的点击次数还需要到统
计平台去看报表数据, 很是麻烦. 你想用一个统一的指标来估算自己网站流量的价值, 后续
再有新的广告主过来, 你也知道该要多少价钱.

于是有了eCPM (Effective cost per mille)这个指标, 可以用来统一的估量自己流量的商
业价值:

#+BEGIN_QUOTE
eCPM = (Revenue / PV) * 1000

Revenue = CPC * Clicks = CPC * (PV * CTR)

所以:

eCPM = CPC * CTR * 1000
#+END_QUOTE

CPC在一定时期内整个广告界内比较稳定, 要想提升广告收入, 就需要针对不同的人群, 做
到精准展示广告, 提升CTR, 从而提升eCPM, 获得更多收益.
