#+TITLE:       总结: 注意力管理
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-01-30 Sat
#+URI:         /blog/%y/%m/%d/attention-management
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t


又到了新的一年, 回顾过去一年, 在Emacs 和 Orgmode 上陆陆续续投入了不少的精力。其
中至少有一半的精力放在了时间管理上。 但经过了一整年的实践和反思, 最终发现, 时间
管理其实是个假命题。

时间并不能被管理, 每个人一天都是24小时, 抛开睡觉的8个小时, 剩下的16个小时怎么分
配, 就是个人差异体现的地方了。 而这16个小时的价值, 仔细往下再钻一层去看, 其实它
又由三个变量组成。

* 注意力价值公式

注意力总价值 = 单位注意力价值 * 时间总量 * 任务价值系数

** 单位注意力价值
人与人之间的单位注意力价值并不相同。你和你的老板之间的单位注意力价值就存在差异,
同样是在公司呆十个小时, 他收获的报酬要高你不少。你和你的同部门的同事之间也存在单
位注意力价值差异, 同样一件事, 因为你们的背景知识和工作效率差异, 把这件事做到80分,
你们所需的时间并不相同.

你需要做的是, 不断提升自己的单位注意力价值。你可以通过不断总结经验, 学习新技能知
识等办法 , 来提升完成目前手头工作的效率; 你也可以通过不断从你老板手上接走一部分
重复性地工作, 来提前熟悉下一关卡的工作内容和要求。

** 时间总量
两个同等级别的员工, 一个贡献8个小时给公司, 一个贡献10个小时给公司, 如果做的工作
内容和效率差不多的话, 两者对公司的总贡献值就体现在每天2小时的差异中了.

** 任务价值系数
同样背景同样级别的两个人, 每天都贡献8个小时的注意力在工作上, 怎么评判两者的贡献价值?

答案就在于 =任务价值系数= 这个变量上, 每项工作内容其实都有它自己的"价格标签", 有的
价格标签是1, 完成该任务, 对的起你的岗位职责; 有的价格标签是 0.8, 就算你每天花了
10个小时去做这项任务, 其实你还是亏的; 而有的价格标签是 1.3, 虽然完成这个任务的过
程会遇到更多问题和困难, 但完成该任务, 对你来说绝对是赚的。

有没有价格标签系数为10的任务? 是不是可以直接来个速成的? 可以先去看看马云和任正非
为什么会开除写万言书分析公司战略的员工。饭要一口一口吃, 路要一步步走。

你每天在工作上做出的选择, 其实都是在塑造你自己的形象。
