#+TITLE:       模型: 贝叶斯定理
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-05-06 Thu
#+URI:         /blog/%y/%m/%d/bayes
#+KEYWORDS:    <TODO: insert your keywords here>
#+TAGS:        <TODO: insert your tags here>
#+LANGUAGE:    en
#+OPTIONS:     H:5 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

两个事情A 和 B同时发生的概率, 如果以A 事情为坐标系, 则为:

$$P(AB) = P(A)P(B|A)$$

如果以B 事情为坐标系, 则为:

$$P(AB) = P(B)P(A|B)$$

这两个公式计算的是同一个事情P(AB), 所以

$$P(A)P(B|A) = P(B)P(A|B)$$

即

$$ P(A|B) = P(A) \cdot P(B|A) / P(B) $$

这就是大名鼎鼎的Bayes 定理。

对于上面的推演过程, 有两个人生启发。

** 人生就是一个Bayes 过程
  你做决定时不可能全知全能, 只能是基于当前你的认知, 来做出当下最好的判断。
  即使你知道现在做的判断离真实答案还有距离, 但也要勇于做出这个起步的判断。

  当后面有新的信息纳入时, 再基于新的信息，来更新其之前的判断。

  这就是Bayes 思维, 有这种思维的人, 心里会非常清楚自己并不是 =Mr. Right=,
  常常会说 *我所说的都是错的* 之类的话; 他会对信息透明非常在意, 因为只有当
  信息能高效传输时, 才能更快更好地更新自己的认知判断。

** 遇到难题多尝试切换视角

   什么是视角? 就是你 *怎么看* 一个东西, 你把这个东西 *看成什么* 。

   比如, 现在有一大盆鱼, 里面有各种品种:
   - 外行可能看到的是: 有的大, 有的小
   - 渔民可能看到的是: 思考这些鱼是怎么捕捞上来的
   - 卖鱼的可能看到的是: 哪个鱼贵些, 哪个鱼便宜些
   - 你可能看到的是: 那个好像更好吃些?

   这些不同的 *看法* , 就是视角。

   视角的选择，对于解题的难易, 影响非常大。

   你要描述一个正方形的顶点, 用直角坐标系非常方便; 而要描述一个圆弧, 那
   就最适合用极坐标。

   元素周期表, 就是使用了 *原子量* 的视角(质子的个数), 纷繁无序的各种元素
   一下子就有了章法。

    #+begin_quote
       对于任何一个问题, 都存在一个能让答案一目了然,脱颖而出的视角。
    #+end_quote

    这话说着容易, 但真要找到那个视角,可能非常困难。

    但是, 这个定理, 给了我们希望。当一道难题摆在你的面前, 可能当前谁都不
    知道怎么解决它, 但是你要相信，总有一个视角, 会让答案看上去那么简单,
    那么自然。
