#+title: 如何进行商业分析
#+author: 李继刚
#+options: toc:nil

商业分析九字诀: 问行市, 竞钱道, 团资产.

* 问(问题)

所有商业行为都是为了解决特定人群的特定问题, 通过提供使用价值从而获得商业价值. 在进行
商业分析的第一步, 首先要知道该公司或者该产品到底是解决了用户的什么问题.

* 行(行业)

理解了该公司或产品解决的特定问题后, 下一步就需要去了解该问题的解决方案所涉及到的 =产
业链=. 具体包括:

1. 企业链
2. 供需链
3. 空间链
4. 价值链

* 市(市场)

了解产业链之后, 下一步需要确定该需求所涉及的市场大小及阶段.

市场大小通常由该需求的人数多少来评估, 而市场阶段, 按「云梦秘叶」这本古书中的说法, 可
以分为「生、长、成、藏」四个阶段.

#+BEGIN_QUOTE
生: 刚刚诞生的市场(前期布局)
长: 迅速增长的市场(全力攻取)
成: 已经成熟的市场(巨头坚守)
藏: 不断衰退的市场(尽快撤离)
#+END_QUOTE

或者按[[http://t.cn/Rt2LnuG][「技术简史」]] 这书所分的「创新」、「商业化」、「混乱」、「规则」四个阶段, 异曲
同工.

* 竞(竞品)

即便你找到了一个很强的需求, 一个很大的市场, 产业链也很清晰, 但如果有一个已经强大到垄
断地位的竞品, 那最好在杀入该市场之前, 三思再三思.

竞品现在的市场份额为多少? 竞品现在有什么优势, 又有什么劣势? 是不是还有机会从中找到一
个突破点, 可以入局分羹?

* 钱(收支)

公司的成本结构是什么样的, 有限的现金资源是投入到了人力支出, 还是销售业务拓展? 烧掉的
钱是否换来了竞争门槛?

公司的收入模式是什么样的, 是通过免费做平台, 聚焦流量之后, 再导入到其它变现业务, 还是
直接通过前向收费?
* 道(渠道)

公司是如何接触用户的? 是通过自建销售和代理商渠道? 还是通过购买互联网流量? 还是通过与
线下渠道合作?
* 团(团队)

再好的战略规划都要靠人去实施, 互联网上从来不缺少好的 =idea=, 缺少的是令行禁止, 雷厉
风行的 =特种部队=.

同样的团购需求, 面对同样的市场, 最终活下来的也就一两家.

同样的直播需求, 面对同样的市场, 现在国内的 200+ 直播平台又有几家能活到最后.

* 资(资源)

公司有什么独特资源优势, 是否形成了进入门槛?

* 产(产品)

了解上述的所有方面之后, 公司对该问题的解决方案是什么? 该产品的使用价值是否有竞争优势?
