#+title: 商业本质
#+options: toc:nil num:nil

最近在学习 =得到= 上面 *刘润* 的五分钟商学院，很受启发，记录下学习总结。

#+begin_quote
生意的本质就是创造产品价值，然后把产品价值交换给有需要的人。
#+end_quote

产品价值的创造过程不是今天讨论的重点，今天主要想聊下产品价值交换出去并从中获利的过程。 这个过程可以用公式表达为：

#+begin_quote
_收入 = 流量 * 转化率 * 客单价 * 复购率_
#+end_quote

各行业的商业模型会有些差异, 对应到这个公式中的指标会有细拆或组合的情况. 但本质上, 都是这四个关键因素的乘积.

* 流量

** 流量洼地 = 低获客成本

在商人眼中，对于流量就是一句：如何以 =尽可能低的价格= 获得 =尽可能多的流量= 。

坐地铁上下班换乘的路上，是不是经常遇到面包店的妹子在人流中间推广当日特价面包？

早上在公司楼下，是不是经常遇到一个推着早餐车卖早饭的流动商贩？

晚上回家在小区门口，是不是时不时会遇到骑着三轮车卖鲜花或水果的流量商贩？

有想过为什么会在这些时间和地点遇到他们吗？ 他们就是找到了 =流量洼地= 。所谓流量洼地，就是获客成本比较低的流量渠道。

如果你明天要开一家快餐店，你是要找一个房租贼贵的商场或写字楼， 还是要找一个偏远
但便宜的小角落门店？ 只要算下你的获客成本就好了，如果算下来都不划算， 你就需要再
去找找有没有新的流量洼地存在。 一般来说，如果有一个新的技术改进或商业模式出现，
都会存在一个流量洼地红利期， 尽可能快地抓住这波红利， 狠狠赚上一票吧。

** 引流品 = 抓手

除了花钱买流量以外，还可以通过利润换流量的玩法来创造流量。

所谓引流品， 就是通过让出利润，以接近成本价甚至略赔的价格，吸引流量的产品。

同样是卖早餐，你的鸡蛋比旁边那家便宜3毛， 其它产品价格不变或者略贵。 鸡蛋就是你的引流品。

同样是卖咖啡，你的某一款咖啡卖的超便宜，吸引很多用户进来购买，这款咖啡就是你的引流品。

杭州西湖不要门票; 酒吧对女生免费，对男生收费； 电影院门票超便宜，但爆米花贼贵；
药店免费使用体重计，减肥药价格高； 超市限时限量供应超便宜鸡蛋， 这些都是引流品的
玩法。

** 关联流量 = 精准流量

想获得流量，要先分析你的用户群体都在哪，然后去他们经常在的地方吸引他们的注意力，把他们拉到你的地方去消费。

这些 =他们经常在的地方= 就是关联流量。 你和这些流量方不是同一个行业，没有直接竞争关系，但你们又都服务着同样的用户群体， 就有着合作的空间。

比如航空公司和酒店的积分打通， 比如生活用品品牌和酒店的合作， 比如Uber之前搞的一键呼叫面试官活动， 等等。

* 转化率

你通过购买流量或者创造流量的方式，吸引了大量目标用户进来。下一步就是要解决如何让他们掏腰包购买你产品的问题了。

** 展示设计

除了产品本身的包装设计以外， 还有一个 =动线设计= 的基本功需要修炼。

#+begin_quote
=动线= 就是注意力流动的路线。 动线设计就是把最希望用户购买的产品，放在用户必经的动线上。
#+end_quote

关于动线设计，宜家绝对是大师中的大师。 只要进了门， 一条路线让你从头走到尾， 不买东西出不来。

另外还有一个用户心理可以利用，就是 =影响力= 这本书中介绍的其中一项 =服从权威= 。

书店经常会在最显眼的位置摆一个畅销书专区， 超市会放一个热卖产品重点展示位， 酒店
或者私人医院经常会展示名人合影， 这些都是在利用 =服从权威= 的方法使人就范。

** 决策时间

消费者在线下购买一个产品，平均决策时间是13秒； 线上是19秒。

为了提升转化率，要想尽办法减少用户的决策时间。

电商平台在商品详情页的设计方案中， 一个只放购物车图标的方案和 =加入购物车= 文案的方案， 下单率能差30%以上。

特价优惠，最后十件； 跳楼价大甩卖，最后三天； 限量发行，先到先得。 这些文案都是
为了通过短缺来刺激用户减少决策时间。

还有一个减少用户决策时间的终极大招： =打折= 。

在使用打折过程，需要特别注意一点， 不能让用户感觉到你的产品价值低，原来的定价是虚高的。 具体玩法可以有下面几种：

1. 低价高购

   花较低价格，可以买到价格贵贵的东西，你会有赚到便宜的感觉。 很多服装店的 加价购， 消费满1000元，可加价149元，在原价300元区域任选一件。

2. 充值免单

   充值1000元，可以免掉今天消费的188元。 你算下这是打了几折？ 你充值后，以后是不是得经常来这家店消费？

3. 赠而不折

   你要买的这件商品不能再便宜了，但我们可以再赠送你一件新品小样或者赠送您一张50元折扣券，下次可随时用。

* 客单价

用户被你吸引到店里，也确实下单了，如何提升客单价？

上淘宝看看那些店铺是怎么玩的：

消费满199元包邮，你现在买的商品180元，会不会想多搞两个小件凑够199元省掉10元运费？

进店送50元优惠券，但满800元可用。 你下单的商品是700元， 会不会想再搞100元的商品来使用这张优惠券？

你本来就是想进去买一件T恤，下单时发现这衣服搭配的裤子和鞋子超好看， 会不会顺带着把这一身搭配全买了？

还有一种单产品的价格太高，用户有需求但就是买不起怎么办？ =分期= 。

看看出租车行业的每月份子钱，就是用这些钱分期还车钱； 更不用提买房子， 买车子这些典型的分期场景了。

* 复购率

** 会员制

用户永远想要更优惠的价格， 商家是想更多的流量，可以接受薄利多销。

但这里有一个鸡生蛋，收生鸡的问题。 到底是用户先涌入商家这里， 还是商家先让利降价？

#+begin_quote
会员制的本质，是一种类似于团购的契约关系：用户承诺在商家这里更多地消费，商家承诺给用户更便宜的价格或更多优惠。
#+end_quote

会员制有两种玩法： 一是设置进入门槛， 二是设置逃离成本。

如果商家的话语权更高， 就可以采用进入门槛的玩法。 Costco的会员制是典型的进入门槛玩法，加入会员需要收会员费。

如果用户的话语权更高， 就可以采用逃离成本的玩法。 会员免费加入，用户任意消费都有
积分，随着消费越多，积分也越多。航空公司和连锁酒店，都是这种玩法的典型。
