#+TITLE: 狗知道别人在叫它的名字吗
#+TAGS: Reddit, ELI5, Reposted

在 [[https://www.reddit.com/r/explainlikeimfive/comments/31fhbo/eli5_do_dogs_recognize_that_their_name_is_their/][Reddit]] 上有人提问「当狗听到别人在叫它名字的时候, 它是知道那名字就是在叫
它? 还是说只是通过识别不同的声音而知道有熟人在说话?」

最高票回答 @eternalquiet 是这么说的:

#+BEGIN_QUOTE
Dogs are capable of recognizing their names, and discerning it from other
sounds. Recent animal behavior studies have found that dog's brains behave
in much the same way our brains do when someone says our name. It appears
that they are able to recognize that their name is not just another sound
that someone is making, but is meant to specifically identify them.

Edit: Fun fact -- cats have been shown to do this as well. The research
suggests that cats can also tell when you're using their specific
name. The reason they often don't react? They don't care.
#+END_QUOTE

大概翻译下就是:

1. 狗在听到自己名字时候的大脑反应和人类听到自己名字时候的反应很类似
2. 狗确实是可以识别出自己的名字
3. 猫其实也可以识别出自己的名字

从这里可以得到两个结论:

1. 给狗和猫起名字就像给人起名字一样, 是很重要的一件事, 请不要敷衍了事
2. 猫之前识别出自己的名字, 却经常没啥反应的原因是, 它懒得理你!
