#+TITLE:       读书: 商业的本质和互联网
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-09-13 Mon
#+URI:         /blog/%y/%m/%d/essence-of-bussiness
#+LANGUAGE:    en
#+OPTIONS:     H:5 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

*商业的本质与互联网*, 许小年的这本书, 详细分析了互联网成长速度如此之快的理
论基础--网络效应, 新颖之处在于, 强调了网络节点之间, 不同类型用户之间正反
馈的交互所创造的价值。

如果一张网络只有两个类型的节点, 并且同类型的节点之间无交互, 那么这张网络
就没有网络效应, 只有双边效应。

基于这个分析洞见, 对互联网的几波风口模式进行了套用分析, 值得学习。

** 规模效应
#+begin_example
表述一:

产品的单位成本随着产量的增加而递减(分摊到单位产品上的固定成本的下降), 这
就是规模经济效应。
#+end_example

#+begin_example
表述二:
规模经济效应是 =边际成本递减= 的效应。

即产量越大, 新增一单位产品的成本越低。第N+1 吨钢的成本低于第N 吨钢。
#+end_example

固定成本占总成本的比重越高, 规模经济效应越好。

资本密集的钢铁,水泥，重化工,重型机械等行业中, 大型企业居于主导地位, 就是
因为规模经济效应。

互联网行业，具有明显的规模经济效应。它的边际成本更低, 规模经济效应更为显著。

** 协同效应
#+begin_example
协同效应依赖于品种增加所带来的收入。
#+end_example

微信开发和维护成本是固定的, 微信平台上面承载的服务越多, 公司的收益就越好。
你在京东上买了手电, 会很方便地再下单买几包电池。商品各类越是齐全, 客户购
买的便利性就越好, 公司的收入也就越高。

但是, 互联网公司的规模效应和协同效应在相当大程度上取决于 =供应商的生产规模= ，
而不是互联网公司的 =客户规模= 。

** 网络效应
   #+begin_example
    网络效应是 =边际收益递增= 的效应。

    即每一个新增节点的收益不断上升。
   #+end_example

   公式化呈现:

   $$V_m = K_1 * n^2$$

   式中, $V_m$ 代表具有网络效应的网络价值, $K_1$ 是常数, $n$ 是网络节点数。

   需注意的是:

   1. 该公式不是物理学意义上的精确定律, 只是从观察中得出的统计学意义上的
      近似公式。

   2. 网络节点数的增加带来的网络价值增加, 只是一个理论价值。实际价值取决
      于节点数之间的互动的活跃程度。

** 双边效应
   #+begin_example

    双边效应：

    不同类型用户之间正反馈交互所创造的价值。

   #+end_example

以天猫平台为例, 供应商和用户之间有交互, 供应商和供应商之间, 用户和用户之
间基本无(交易)交互。 滴滴平台上的司机和司机之间无交互, 乘客和乘客之间也
无(交易)交互, 有交互的只有司机和乘客。

从定义上, 双边效应就弱于网络效应。
