#+title: 优质文章每日精华选
#+options: toc:nil num:nil

微信公众号「卫夕聊广告」的作者组了一个微信群, 目的是每天挑选五篇当前最优质文章, 帮小伙伴们提升信息获取的效率和质量.

因每日发完文章列表后, 群里会有相关主题讨论, 时间一长, 再翻看历史文章就极其不便, 故起意将每日推荐文章列表整理到此文章, 方便随时查阅.

* 2018年8月文章
** 2018-08-31
- [[https://mp.weixin.qq.com/s/ZPPLna_VHhzSYMQWZ6zleA][《中国游戏监管史》]] 可曾想你可以在国内买到正版的《生化危机2》？在很长一段时间里，
  国内游戏市场处在一个监管力度非常弱的环境中，游戏行业都十分熟悉的审查制度在当时
  还没有建立，游戏沿用的是图书出版物的审查流程——只需要出版社的自审即可上市。

- [[https://mp.weixin.qq.com/s/Q9jxcak6d3nSTT1yQeFmtw][《学而思15年：野蛮生长的补习班与中国家长焦虑症》]] “学习改变命运”是学而思的第
  一句价值口号，也是深深烙在中国家长心中一段“咒语”。教育依旧是阶层跨越的唯一可
  控途径。从零开始到今天的教育巨无霸，学而思这15年的江湖，恰是一场中国社会跨越阶
  层的持久战。

- [[https://mp.weixin.qq.com/s/tYRaYJ68oVq2ClDeGTtXcw][《厌倦微信，拒绝陌陌，现在「地图社交」给你一种新方式 | 36氪新风向》]] 通常基于
  LBS 的社交软件，会优先展示附近的人并显示距离，但数字给人的感觉却不如直接显示他
  所在学校、小区或者街道来的直观，而视觉上的直观一定程度上可以带来心理上的亲近感。
  加入熟悉的互动场景这是地图社交的一种思路……

- [[https://mp.weixin.qq.com/s/ztoaAilt60g_4_8CrBWusg][《读者消费升级，自媒体的烦恼 》]] 从前在微信或是今日头条上开个订阅号，就能轻松获
  得不菲的广告收入。不过如今，大多数自媒体账号持有者都会告诉你，虽然订户仍然很多，
  但他们打开文章的欲望正在下降，快钱不那么好挣了。当初期近乎盲目的热情消退后，一
  个行业可能才会真正迎来良性发展。

- [[https://mp.weixin.qq.com/s/mRU6jliTqBtLFc3kSTd7gg][《既练轻功也练内功——面对风口的正确姿势》]] 公众号的福利退去后才显示出自媒体该有
  的样子，不过仍有人懊悔：为什么我没赶上公众号的福利？为什么错过风口的总是我？如
  何正确面对风口？这是一个极其复杂的战略战术问题！在这篇长文中，卫夕只提供一些最
  基础的原则……

** 2018-08-30
- [[https://mp.weixin.qq.com/s/NQfJXsiSODGu0vVR7-1Aug][《微商金字塔崩塌：普通代理消耗朋友 财富属于金字塔塔尖》]] 加他一次微信999元，郑
  九洲是深圳落地荟服务社群的联合创始人，工作是给想要在微商行业里发财的从业者提供
  建议，他从不直接卖货，而是制造了一个物欲世界。他们通过放大人们对权贵与生俱来的
  渴望，从而构建起自己的微商网络。

- [[https://mp.weixin.qq.com/s/RF8TPfrHSQ5Qc6GPUPeuXg][《如何给美团进行估值？》]] 我们认为美团的估值，最高可达到645亿美元。而在美团的收
  入当中，外卖是最大的一块资产，占收入总额的62%以上。我们就讲一下这部分的互联网
  基因……

- [[https://mp.weixin.qq.com/s/PtLwfR9OiXu5lRDs6YwH5A][《抖音最红的城市，为什么都在西部？》]] 城市得到的曝光率在抖音上重新洗牌，凡在抖
  音上火起来的城市，无一属于一线城市阵营。城市注意力被移动互联网重新分配，身在一
  线城市的用户，也更愿意把目光投向精彩纷呈的二三线城市。西部城市在抖音上更是红得
  发紫。

- [[https://mp.weixin.qq.com/s/zzKGdSUdlRhdyvWIFswu4g][《流量造假成风的年代，如何甄别真假博主？》]] 作者连续几天观察发现，10万+的阅读中，
  凌晨2点到6点，阅读量飙涨一大半，但点赞数据在第二天上午才开始上涨，很明显的刷量。
  人人都可以创富的环境下，数据造假者一个比一个凶猛。从早期的微博，到微信公众号、
  抖音、小红书等平台，反正有人的地方，就有真假。

- [[https://mp.weixin.qq.com/s/7EsyvEFrS0U00xoQxmhkLg][《创业、艺术家和量子物理》]] 她说有两种人真正能称得上好的创业者：一种是像画家一
  样去激情地创造产品，技术不技术的无所谓，用户觉得好用才行；另一种人是脚踏大地的
  技术问题解决者，让不可能变得可能，让困难变得简单。一面是艺术，一面是量子物理。

** 2018-08-29
- [[https://mp.weixin.qq.com/s/NfHP1B015t_Qyy34flpW8A][《从千亿跌至百亿，只用了一年！Q版“腾讯”到底做错了什么？》]] 2016年底，美图在港
  上市，成为了继腾讯之后12年来香港最大的互联网IPO，董事长蔡文胜曾说，美图是迷你
  版的腾讯。然而谁都没料想到美图坠落地如此之快。更糟糕的是，时至今日，美图依然没
  能意识到问题出在了哪里……？

- [[https://mp.weixin.qq.com/s/iEEvxYb7TcAEmnY6MojUdg][《Magic Leap的“虚拟梦境”，终于梦碎了》]] 由 Google、阿里、A16Z、高通、凯鹏华盈
  等顶级公司和机构大手笔联合投资的混合现实 (Mixed Reality) 技术创业公司Magic
  Leap的“虚拟梦境”，终于梦碎了。可能又要恭喜又一批投资人：花钱打水漂，买了个教
  训。

- [[https://mp.weixin.qq.com/s/rIOsRlPzjbdjo_FDypmH0g][《淘宝15年后「二次创业」：突出设计，押注原创》]] 在价格、品质和功能保持平均水平
  的基础上，如果能设计再稍微往前突出一点，设计就会成为商品的最大的卖点。这个商品，
  往往会在淘宝上特别受欢迎。淘宝降低店铺的门槛，目的就是为了突出这些设计。

- [[https://mp.weixin.qq.com/s/rO77mEwRNHg9_EGeLH6ZxQ][《为什么说大多数ICO都是诈骗？》]] 区别于IPO [4] （英文简称Initial Public
  Offering）首次公开发行，ICO（Initial Coin Offering缩写），首次币发行。都有着以
  股份换集资金的概念，而他们又有什么不同，为什么说ico都是诈骗?

- [[https://mp.weixin.qq.com/s/FnHdmwUHBav_TJLxjr1VtQ][《一位连续创业者复盘的支付简史：对手毁灭你，但与你无关》]] 在那个时代的创新举措
  不叫支付，叫代计费。2001年，中国移动发布“移动梦网创业计划”，通过扣除话费来缴
  费，电信运营商实际上可以充当支付通道的角色。但在2008年左右，随着移动互联网兴起，
  这就变成了被新技术革命掉的行业……
** 2018-08-28
- [[https://mp.weixin.qq.com/s/66YdYTcSQr4yjknxnMkSqg][《消费降级是否会催生“降级”品牌？》]] 谈得上降级品牌，优衣库算一个，那小米呢？
  投资人子柳在《小米是一家什么公司？》一文中提到，小米和优衣库两家公司很像，
  “‘优质低价’正是优衣库的产品理念，想这么做的人很多，但这两个词是相互矛盾的，
  真正做到的我只看到优衣库一家。”

- [[https://mp.weixin.qq.com/s/YilXyXNtJDXCg6dQH7di-Q][《一个小思考：为什么大家都不喜欢“罗氏交互”》]] 先下一个定义：“罗氏交互”，泛
  指要求用户调用各种感官、肢体进行运动（感官/肢体≥2），才能完成的交互方式。代表
  作有今年5月15日发布会上发布的TNT以及本次发布会上的无限屏。但大家对包含着未来美
  好愿景的“罗氏交互”似乎并不买账……

- [[https://mp.weixin.qq.com/s/OHAJeES7we0QoKGBXeupCg][《支付宝“扫盲”东南亚》]] 2017年7月，腾讯就申请到了马来西亚的第三方支付牌照。然
  而在2017年上半年，菲律宾本地电子钱包GCash的办公室里来了一群中国员工。这群中国
  加班狂来自蚂蚁金服。

- [[https://mp.weixin.qq.com/s/Eh0ytEs-M3eGKtTtAqRdWA][《明星转战短视频》]] 2018年以来，短视频平台的影响力提升和主流化速度越来越快，有
  两个表现：第一，国家部委、地方政府的政务号大批入驻快手、抖音两大平台；第二，社
  交形态的更迭明星比普通人有着更强的嗅觉，哪里有流量、哪里有注意力他们就走向哪里，
  这一波他们涌向了短视频。

- [[https://mp.weixin.qq.com/s/Kvxdzd4GDRitEUuKrEvk1g][《实地访山东新媒体村：农妇做自媒体收入破万 平均工资比上海还高》]] 现在，一支不一
  样的留守妇女军团出现了，她们每天与电脑为伴，在鲁北农村拿着一线城市的收入填补家
  用，家庭话语权也变得硬气起来。她们上班的地方，就是她们的家乡，不用担心住房，也
  不用担心孩子教育。她们做的便是自媒体，收入最高者，一个月拿了1.5万。

** 2018-08-27
- [[https://mp.weixin.qq.com/s/DeBzk80xybDMXOII5Prd6w][机器短信你会点广告: 写给普通人的CTR预估科普]]

- [[https://mp.weixin.qq.com/s/F-PgHZ55TpROzqeGWNODaQ][《是子弹短信真那么好用？还是逃离朋友圈的欲望太骚动》]] 8月20日的锤子科技发布会没
  让
人太记住新手机的特点，反倒让子弹短信出尽风头。一周过去，子弹短信仍然是 App Store
 免费排行榜的第一名。人们在脱离微信？

- [[https://mp.weixin.qq.com/s/yawxhPpLJ6XA9wUK9PvDqA][《40岁的于正，想要收获尊重了》]] 于正似乎翻身了。他担任制作的《延禧攻略》里一路
  开挂的女主角魏璎珞显然给他带来了好运气，好口碑让他有底气打开弹幕，在夸赞中享受
  逆袭快感……

- [[https://mp.weixin.qq.com/s/3WNUT0GMQnU3yEtJkA9CiQ][《小米想革新广告业，能成功吗？》]] 一线互联网公司都有自己的广告营销模式，可小米
  与BAT们有所不同，它主要通过硬件获客，别人获客需要花钱，它却还能赚钱。流量被小
  米及其，不再流动。

- [[https://mp.weixin.qq.com/s/j2lCpeyiOUiCBGhJqKg-hQ][《全球社交媒体遭遇中年危机，下一个用户增长点在哪里？》]] Snapchat Q2 的财报显示
  其日活用户数达到17年来首次下滑。对比 Facebook 和 Twitter 在面对隐私泄露和外部
  监管等等危机而笼上的阴霾，《卫报》和《纽约时报》分别刊文提出了疑问：社交媒体的
  增长是否已经到达了顶峰？

- [[https://mp.weixin.qq.com/s/SM6KUqTqtF6YcW6rIjl_WQ][《有品质的写作是最高效的社交》]] 潘乱的《腾讯没有梦想》微信后台阅读过100万。文章
  击穿了整个行业引起媒体大讨论，创造了一个公共议题。如果科技财经媒体也有像学术论
  文那样的单篇文章引用指数的话，2018年度被引用次数第一肯定是它。

** 2018-08-24
- [[https://mp.weixin.qq.com/s/V8zxgzoNGU_6Or5xNpxZmA][《可遇而不可求的李子柒终于商业化：田园视频造梦，食物走向市场》]] 8月初，李子柒在
  微博告诉粉丝：李子柒旗舰店正式营业。这一支品宣视频的转发量也能超过10万次，评论
  量超过8万，点赞数突破30万。已经趋于艺人化的经营和发展，有非常强的商业IP价值。

- [[https://mp.weixin.qq.com/s/o8-wY3YXo1WTRYZZII_8gg][《骗人要趁早？扒一扒福布斯中国30岁以下“掺水”精英榜》]] 一周前，号称国内自主内
  核的红芯浏览器获得2.5亿融资，随后被爆出山寨黑幕。而红芯（原云适配）背后公司联
  合创始人高婧则上了一个榜单，全称叫做福布斯中国30位30岁以下精英榜……

- [[https://mp.weixin.qq.com/s/lTav1QaEmy0Jk4slG1XQMw][《中国电商往事》]] 二十年，马云、刘强东、王峻涛、邵亦波、郭凡生、雷军、李国庆、
  陈年、黄峥，这些熟悉的、陌生的名字，或登上财富巅峰、或黯然离场。二十年，旧的故
  事还在继续，新的故事已经开始上演。

- [[https://mp.weixin.qq.com/s/_p3JprOpoeBhvcHfcai2eA][《上市，退市》]] 不止中国，美银美林银行年初预计，2018年IPO的美国科技初创企业多达
  50家，远超前两年。然而，在全球互联网公司的上市潮中，也有着一批退市的公司，有如
  特斯拉……
** 2018-08-23
- [[https://mp.weixin.qq.com/s/adVHxSVeOW66my5IDN7nPQ][《区块链媒体微信号被“团灭”：人人都想身价破亿，但财富自由是一碗毒鸡汤》]] 前日，
  深链财经、金色财经网、火币区块链、火币资讯、币世界、吴解区块链等一批区块链&币
  圈自媒体微信号被发现遭微信官方封禁。而被封的他们表示，这一次寒冬只会让他们更强
  大……

- [[https://mp.weixin.qq.com/s/4EBV4ljP5FIJIbKE6wWauQ][《存量战争》]] 目前存量的争夺，最典型的就是阿里和京东。两家日常的新货电商业务占
  据中国市场的八成以上，介于中国增量市场天花板已经到顶的局面下双方只得冒险争夺对
  方手中的存量寻求业绩突破，而当前最大的存量机会来自二手市场。

- [[https://mp.weixin.qq.com/s/a5NovYSMkMdD-ftbIncneg][《抄底腾讯？》]] 作者把股票分为三类，第一类股票超跌可以抄底，第二类要冷静分析，
  第三类即便到“地板价”也不要碰，地板下是十八层地狱。那腾讯属于哪一类，可以抄底
  吗？

- [[https://mp.weixin.qq.com/s/SRmjHZjdz77QazU0qeaRLQ][《王信文 | 让暴风雨来的更猛烈些》]] 赌博赢钱的人常常把赢钱归因为自己赌技超群，而
  忽略运气因素。越赢钱，越觉得是自己牛逼，越要加注。直到突然发现运气不在，输到血
  本无归。股市是这样，币圈也是这样。

- [[https://mp.weixin.qq.com/s/L98YI_gY-ZTCLgcFxdWgTQ][《广告业已经是夕阳产业了吗？》]] 麦迪逊大道是纽约曼哈顿区的一条大街，美国许多广
  告公司的总部都集中在这条街上, 因此麦迪逊大道逐渐成为了美国广告业的代名词，现在
  这条街要拆迁了。互联网公司正在瓦解传统广告业。

** 2018-08-22
- [[https://mp.weixin.qq.com/s/9Zk6o77P8E3fO-h0XjNQ3Q][《「网易人格测试」刷屏朋友圈，套路你都知道，为何还中招？》]] 昨日，网易云的人格
  测试再次刷屏。其实刷屏的爆款来来回回招数就这几样，为什么我们偏偏都愿意吃这套？
  说白了，这是用户和品牌之间一场心照不宣的“合谋”，用户要人设，品牌要转发量。

- [[https://mp.weixin.qq.com/s/U6JQ55aGKK7BmTAcpFPV0g][《信息流江湖未定》]] 网络广告市场正在迎来一个新变化，一是信息流广告的比重和比例
  正在提高，二是互联网广告即将结束高速增长期，效率竞争将取代增量竞争。从长远来看，
  在线广告依然是BAT三家的主流战场，并且随着时间的推移，其门槛和难度也会不断加大。

- [[https://mp.weixin.qq.com/s/9OPO6L9A1z0AnSev99i68Q][《智能手机零和博弈：用户的换机奥秘与厂商的中年焦虑》]] 在整理分析了约800万条换机
  行为记录后，今日头条发现了一些秘密：比如三星、锤子、魅族正在被自己的老用户抛弃；
  华为与苹果已经开始正面交锋；OPPO、vivo推出高端品牌其实另有图谋……

- [[https://mp.weixin.qq.com/s/mD0VcQFrPNRgJ_svUGDH5Q][《东南亚何以成为中国技术公司的淘金圣地》]] 600年前“郑和下西洋”的故事里，船队首
  先抵达的一个叫麻喏八歇国的地方，正是印尼境内的爪哇岛。现在，大批的中国技术企业
  也是遵循相同的轨迹，演绎了一个全新版本的“下南洋记”。

- [[https://mp.weixin.qq.com/s/_YggCL43xMqCMimmgCgasQ][《攒局者马云》]] 马云擅长攒局，但不是饭局。过去几天最热闹的事儿是马来西亚总理马
  哈蒂尔·穆罕默德到访中国，他首站选择了杭州，选择了阿里巴巴。毫无疑问，马云扮演
  了中马交流的使者。
** 2018-08-21
- [[https://mp.weixin.qq.com/s/0cFqB937RkZhWv_dcw9dWw][《百事可乐70年代的逆袭：我买的不是可乐，是理想中的自己》]] 上世纪70年代，可口可
  乐统治了美国市场。百事可乐深知，单从产品上无法与可口可乐抗衡。因此百事充满了革
  命色彩的，做出了有史以来第一次，品牌把注意力放在消费者身上。这个决定几乎是标志
  性、历史性的举动。他们说“不要再把重点放在产品本身上，我们把重点转移到用户身上。

- [[https://mp.weixin.qq.com/s/qPfgHIdzdZ4Wz1JFGR-p2g][《办公遇上社交，腾讯文档如何用4个月拉来1600万月活？》]]四个月前，腾讯正式推出腾
  讯文档，对标去年11月份被今日头条领投的“石墨文档”。截止目前腾讯文档的月活已经
  突破1600万，实现千万量级，其不过用了4个月。腾讯是如何杀入文档竞争的？而1600百
  万这个数字大都是c端用户，未来的腾讯文档该如何发展？

- [[https://mp.weixin.qq.com/s/YPczXl3OZBqrVhl18RR3tw][《房租上涨，资本无罪》]] 最近卷入舆论漩涡中的自如、蛋壳却颇受资本青睐。前者年初
  获得40亿元人民币的A轮融资，刷新中国长租公寓行业单笔记录。后者则在上半年完成两
  轮融资，合计1.7亿美元。然而，资本青睐一定与房租高低有关系吗？

- [[https://mp.weixin.qq.com/s/GewD-H7yj7brdudN1YIivA][《区块链火了这么久，为什么我们能用到的 DApp 还是没几个？》]] 区块链近期的火热，
  多源于其被过分夸大的金融属性。随着今年上半年金融有关部门的联合打击、区块链行业
  的自律和投资者的日趋冷静，区块链逐渐走向了应用化的「正途」。最终“区块链到底能
  不能实现普通用户的互联网应用场景？” 先说结论：能实现。

- [[https://mp.weixin.qq.com/s/BoFFzalB6m3ZWiT0ZC6XZw][《一个传销的神女子教会我的用户拉新和留存》]] 一个由很有趣的故事所探究出来的干货，
  一位传销大姐的分享有体系、有套路、有实例、有干货。进来看看一看有病治病，没病防
  身，不仅可以防骗，好多招数拿来用在写公众号，都是好使的。

** 2018-08-20
- [[https://mp.weixin.qq.com/s/BO211JD01XLbV3ZNtjkHXw][《六年，公号改变命运》]]故事开始于2012年八月，微信公众平台诞生，六年间，它孵化出
  超过2000万个大大小小的公号，彻底改变了内容传播的生态格局，也彻底改变了很多人的
  命运。那时的咪蒙还在《南方都市报》副刊工作，罗胖刚发出自己的第一条60秒语音。到
  如今……从写文章到成名、变现，从未像这样直接。

- [[https://mp.weixin.qq.com/s/ekD6daXqnxF4WLcxn7F9Bg][《上海不相信互联网》]] 据《中国互联网发展状况统计报告》，在102家互联网上市公司中，
  注册地上海的占比18.6%排名全国第二。乍看来，上海互联网行业发展总体上是好的，甚
  至远超杭州，深圳。但这数据像极了老底子上海人所说的：表面光鲜，外套一脱吓死人。

- [[https://mp.weixin.qq.com/s/8Rdaly1kHntyUAie8R6uVg][《中介风云：左晖与姚劲波的百亿美金豪赌》]] 你可能不知道左晖，但你很难不知道链家，
  因为它到处都是。如今在大小街头上，能跟链家拼门店数的只有兰州拉面和沙县小吃。有
  趣的是2015年07月13日，百度发生了一件怪事，中国最大的搜索引擎搜任何关键词出来的
  东西都是链家的广告信息，这让链家在互联网界赚足了鳌头。

- [[https://mp.weixin.qq.com/s/IjhDKvHjpwZQXq1vNTEavA][《负矿《爱情公寓》》]] 在《爱情公寓》电影上映之前，这个ip即使背负着抄袭的名头，
  还有超6成网友支持编剧汪远，还是有多年死忠粉们热切期待着《爱情公寓》电影带他们
  重走青春路。但《爱情公寓》电影直接给这一伤痕累累的IP进行了休克疗法，“爱情公
  寓”的人设彻底崩了。

- [[https://mp.weixin.qq.com/s/WOBWRHNfzT_cEGYrls8axg][《蔚来上市到底开了个好头还是坏头》]] 如何评价蔚来？有人说：从退出摩拜单车到建立
  蔚来社区，他依然在尝试连接用户的线上和线下。摩拜的李斌，李斌的蔚来，应该就是一
  家披着新造车企业外衣的互联网公司吧。

** 2018-08-18
- [[https://mp.weixin.qq.com/s/hBjKfQ2tnz6TqjCV3cFBjg][《进击的BA，模糊的T》]] 进入2018年，腾讯的业绩依然突出，盈利能力是BAT三家中最强
  的，但市场对它的看法却大变样。腾讯股价开始一泻千里，到8月，已经跌掉了1万亿港元
  （超过1400亿美元），约等于三个小米，创下史上最大的一年内跌幅。不到一年的时间，
  腾讯究竟怎么了？

- [[https://mp.weixin.qq.com/s/rE4weFmoyJVyarghVsU_qg][《币圈寒冬将近：韭菜暴富梦碎，资方被迫「从良」》]] 伴腾讯进入寒冬的还有币圈，终
  于各方都在回归理性。韭菜已经在涨跌中逐渐成长，他们暴富继而被套牢，在风浪中变得
  佛系；资本寒冬总是洗牌的机会，撑过了之后即是出头之日。但何时是出头之日？

- [[https://mp.weixin.qq.com/s/uVjkMY54DRZ-29hnmQZoMQ][《拿好，这是一份旧路径失效时代的方法清单》]] 生活中那些听上去或者看上去特别熟悉
  的名词，我们其实非常陌生。这种陌生感来自于我们思维认知的一种舒适性，又或者是天
  生的一种盲区。我们天生对身边的事情不那么敏感。如何走出天生盲区，这时候你需要
  “反”的思维。

- [[https://media.weibo.cn/article?id=2309351000894273982235889209][《白酒反叛者江小白，它质疑所有质疑》]] 江小白就是一款有“反”的思维的产品，它走
  出了“酒”凭口感竞争的盲区。一个贴开题为“江小白这么难喝为什么你还要买”，获得
  1.1万个赞。有人甚至说，江小白其实是一家营销公司，只是顺带着卖酒。

- [[https://mp.weixin.qq.com/s/ORUheX6I_wnb8UnMpEHs1A][《年轻人的群体失眠，养活了一批公司 》]] 都市人的睡眠状况越来越差，有电子产品的干
  扰，也因为生活节奏的加快。有些讽刺，但这是一个事实——很大程度上，技术的发展造成
  了人们的睡眠障碍，而如今，我们又通过技术来寻求解决方案。

** 2018-08-15
- [[https://mp.weixin.qq.com/s/GlI0-vmT1xldK1VD6wP9uw][《89天后，陆奇一箭三雕》]] 距离陆奇5月18日正式离开百度，过去了89天后，陆奇选择把
  创业与投资两件事融合在一块，担任YC的中国创始人兼首席执行官。同时，YC并不与百度
  在核心技术领域形成竞争关系，这样的选择还没得罪他曾希望“在这退休”的百度，堪称
  “一箭三雕”。

- [[https://zhuanlan.zhihu.com/p/23672766?utm_source=wechat_session&utm_medium=social][《Sam Altman: YC、硅谷与人类未来的天选之子？》]] 陆奇任职的YC是个什么样的公司？
  这家以Y Combinator函数为名的公司，在两年前就被称作硅谷与人类未来的天选之子，于
  是，哪怕录取率只有斯坦福大学的一半，每年还是有成千上万的年轻人们申请进入 YC。

- [[https://mp.weixin.qq.com/s/MR05RiXelfen2d1EA9YJbg][《以慢打快，如何定义唯品会这家公司？》]]转到唯快不破的中国互联网竞争里，唯品会近
  几年的新业务往往不是最快的那一个，但总是能以慢打快的那一个。两年前，所有的人都
  认为电商没机会了，这场战争已经结束，接下来是京东和阿里的事，唯品会上演了一场在
  巨头眼皮底下做大的精彩故事……

- [[https://mp.weixin.qq.com/s/hWhG6GMnMICOfptqZsSTuQ][《一家50平米小店的老板，如何用社群打垮平台电商？》]]电商进击如此汹涌，本地小店该
  如何抵挡？本地生活圈的垂直化经营是关键，而如何让本地化生活圈服务更容易取得凝聚
  力？何以提供“供应及时、挑选优化、体验强化”的线下服务？这家50平米小店是个不错
  的案例。

- [[https://mp.weixin.qq.com/s/5jzZeE-UDPdIe91T6V0Y4Q][《为什么高亏损公司会去布局新高亏损业务？》]] 8月6日的晚间，在美股上市公司爱奇艺
  和新英体育宣布成立“新爱体育”。在此之前，同是视频网站的乐视视频、PPTV，都把体
  育频道单出拆出来“重点建设”。爱奇艺为何会去布局不看好的新高亏损业务？难道他们
  忘记了乐视体育的故事了吗？
** 2018-08-14
- [[https://mp.weixin.qq.com/s/OQw3ezOtJ1_P10eTc_tZWA][《“特斯拉的门徒”蔚来汽车要上市了，不过它怎么越看越像小米的门徒？》]] 2014年11
  月，由李斌、刘强东、李想、腾讯、高瓴资本、顺为资本等企业家和投资机构联合发起创
  立的蔚来，广义上是一家汽车公司。此前，“蔚来汽车”曾拿掉“汽车”，统称“蔚来”
  品牌。拿掉“汽车”的蔚来现在算什么呢？

- [[https://mp.weixin.qq.com/s/C2Rqn7QKBZgWtJCYCwx30A][《谷歌双雄》]] 黄峥和蒋凡，分别代表着过去几年中国移动互联网大浪淘沙的两种典型成
  功者。奇妙的是，他们同从谷歌出发，一个坚持独立创业，一个在巨头内部建功立业，离
  开谷歌后走上两条截然不同的道路，辗转多年却又回到同一个地方，最终成为彼此最大的
  对手。

- [[https://mp.weixin.qq.com/s/ePj0ZkMN_uIZMlVQ15y5qA][《宣战前夜：陌陌变形记》]] 陌陌似乎越来越像一家直播公司，哪怕唐岩一直在强调这家
  公司的社交基因。陌陌的社交关系一直处于陌生人社交的弱关系链，对于它，其未来的想
  象空间的扩大就在于，它能够创造出多少种表达方式，将自己的弱关系不断向强关系延伸。

- [[https://mp.weixin.qq.com/s/C0tVK0mc7QnYQBrdfnXFug][《年轻人，没事别想不开去创业》]]腾讯企鹅智库曾对20多个省市的5万多网民做过一项创
  业意向调查，结果显示：从来没想过创业的人，只有3％。这篇文章，正是给给那些想创
  业的年轻人泼泼冷水，反正那些真正的创业者从来不怕泼冷水。

- [[https://mp.weixin.qq.com/s/ET5HtwbO1JKBLlNtXtH9sw][《工具产品面临瓶颈，美图把社交当做「二次创业」》]] 美图现在已经拥有 4.5 亿用户，
  很难依靠用户高速增长来推动营收和利润增长。美图必须在已有基础上，以更多业务来带
  动互联网业务营收，同时增加用户黏性和使用时长。于是，美图选择了社交，希望它能带
  动公司继续增长。
** 2018-08-13
- [[https://mp.weixin.qq.com/s/WsBS_khYtV0ehtWHuog6ew][《厦门房价下跌，网红城市的潮来潮去》]] 有一种不算新鲜的观点再次引起注意：厦门的
  房价，一直以来都与其城市发展水平不相匹配。很多非厦门人惊讶地发现，这座名声在外
  的城市，经济总量只排在全国五十名左右，房价却一度冲到了北京上海深圳后面。而在一
  排排洋楼的遮掩之下，是否是荒芜的现实？

- [[https://mp.weixin.qq.com/s/0sbPJkTXlpgIhBSE_hBx6Q][《潘越飞：世上已无捷径，“重”才是时代关键词》]] 文章来由潘越飞的一篇演讲，有人
  说：“小潘是在中国自媒体时代留下过自己烙印的人。”在锌财经上线的时候，很多人都
  说他是 “自媒体的上古神兽”。不管这样的封号是否带了点“过气明星”的揶揄，在那
  个只要有才华就可以信马由缰的自媒体草莽时期，这个钱江晚报的记者的确风华绝代。


- [[https://mp.weixin.qq.com/s/Oi6GuK1N0XVatrNvN5cqvQ][《市值堪比小米，比特大陆凭什么值500亿美金》]] 去年 11 月，在数字货币市场正沉浸在
  史无前例的狂欢之时。比特大陆这个掌握了全球超过 50% 的比特币算力，矿机市场份额
  也达到 70% 以上的公司，突然宣布调整战略方向：全力转向人工智能，要淡化矿机公司
  的外界印象？

- [[https://mp.weixin.qq.com/s/2W7YuTUCFIDhftJqgYKSkQ][《一头自媒体的供给侧改革》]] 互联网或者说中国人将不得不被迫的转入向内求的阶段，
  向外求的好日子到头了。王兴以前有个讲话，说互联网到了需要供给侧改革的时候。他估
  计餐饮业的效率和成本优化有25%的空间。所以就知道现在苦哈哈的美团以后赚钱的地方
  可能在哪了。

- [[https://mp.weixin.qq.com/s/6ydm-mskssyjDNaL45BcXQ][《生态会员是视频网站的破局之道吗？》]] 8月8日阿里“88VIP”发布，优酷在阿里大生态
  中的作用开始显现。88VIP会员将同时拥有购物优惠、优酷年度VIP会员、虾米音乐年度
  SVIP会员等权益。那为什么零售商都在布局视频流媒体？电商会员与视频网站会员能如何
  打通，相互赋能？打包会员的推出对于视频网站来说究竟是增量还是减量？

** 2018-08-10
- [[https://media.weibo.cn/article?id=2309351000894271099180365285][《想创业，就来新东方》]] 后来创业的新东方老师们，罗永浩创办了手机公司、李笑来成了
  币圈首富、李丰则是风险投资新贵。除了他们三个，新东方还孕育了各种神。这一长串名
  单有唐宁、胡敏、陈向东、包凡一、刘畅、李哲、印建坤、马薇薇等等200多人。

- [[https://mp.weixin.qq.com/s/xiSVuLGAZIyJ-97RqIaVYw][《惊魂一夜，马斯克713亿美元「私有化」特斯拉意欲何为？》]] 马斯克在特斯拉官网发布
  博客，详细阐述了以420美元每股价格私有化特斯拉的缘由，同时坐定这则消息的真实性。
  但特斯拉究竟为何退市？有人认为马斯克想要更大的控制权，摆脱华尔街的控制；还有人
  则认为拉高特斯拉股价……

- [[https://mp.weixin.qq.com/s/q0wkN6NNZ9e2sfhWEloR-g][《小镇青年的金融梦》]]因为众所周知的原因，这篇文章主人公的不能被叫做小吴或者小
  hui，姑且取他名字最后一个字的右边，把他称作小军吧……相较于大多数金融大佬令人
  发指的身材，50岁的小军总依旧风度翩翩，神采奕奕。多年来，小军总烟酒不沾，只在实
  在意思不过去的时候倒点葡萄酒意思一下。

- [[https://mp.weixin.qq.com/s/bnHiWG17mVAAn4Hr44-NeQ][《游戏人间太艰难》]] 2015年8月，以枪火联盟内测为主题的一篇帖子，下面有5条评论，其
  中三条是产品开发者甘来发的。可见，关注者之少。今年2月，公司进入清算模式。甘来
  已不在法兰游戏股东行列。 8月7日这一天，“谢谢。我会在天堂安好。”甘来最后一条
  朋友圈信息意味着他一生的急速坠落。

- [[https://mp.weixin.qq.com/s/hGfXIOdHOywyoQj3wdD8uQ][《人民呼叫网约车》]]今年7月1日开始“严查网约车”行动，那些不符合京车京人条件，以
  及三证不全的运营车辆，都会被扣押。这样的查处力度超出了所有司机和网约车平台的预
  期……而工信部下属的中国信息通信研究院研究发现，目前我国从事网约车运营的司机有
  3120万，而资质符合各地新规的共有34万，比例仅为1.1%……

** 2018-08-08
- [[https://mp.weixin.qq.com/s/6eo8q2NtLozZWu6U-WWOcg][割舍存量, 拥抱增量]]
** 2018-08-07
- [[https://mp.weixin.qq.com/s/QnevYCQABiXJOAVLc0sjXg][《谷歌要回中国？人民日报发文欢迎 李彦宏“有信心再PK，再赢一次”》]] 谷歌的退出使
  得他们错过了内地互联网发展的黄金机会。在谷歌缺席的过去八年，大陆的互联网市场格
  局迅速改变，移动互联网用户的数量翻了一倍多，从2010年的3.03亿增长到现在的7.53亿。
  而谷歌的回归能带来什么改变，人民日报的推文和李彦宏的朋友圈又意味着什么？

- [[https://mp.weixin.qq.com/s/O-aDr_v8vMEjDIjKjpXM9w][《直播这些年：狂欢、裂变和虚妄》]] 那一年， YY聚焦游戏语音，陌陌深耕LBS社交，相关
  行业热火朝天。刚失恋的MC天佑写了一首自己的喊麦作品，叫做《女人们你们听好了》。
  陈一发辞了工作搬到在上海，每周坚持至少播四天。开播前压力大到无法承受时，一个人
  哭一会。直播这些年：有着哪些狂欢、裂变和虚妄？

- [[https://mp.weixin.qq.com/s/lrcWJdimhvNpGJrkF-Utxw][《我走进"黑客交易中心"，看见有人在收智商税》]] 搜关键词 “黑客交易中心”后 ，一个
  号称“国内首家黑客交易站点”的网站排在百度搜索结果第一位。在里面有人把自己老公
  “弄丢了”，想找黑客定位，开价3000元：有人头顶绿意盎然，想查查老婆开房记录，开
  价5000元：还有俩同学挂了科想逆天改命，开价3000~3500元……

- [[https://mp.weixin.qq.com/s/dWJurca2gLUEMcvhmNI_0g][《吴声：未来一年，新物种的六大趋势预测》]] 文章根据吴声在8月5日「新物种爆炸·吴声
  商业方法发布2018」演讲内容整理。在整场180分钟的演讲中，带来的信息量同去年一样
  庞大：2.5次元、家庭会员、订阅万物、知识新零售、透明化机遇……涵盖了过去一年全
  部的商业爆发级现象，以及观点独特的深度预测。
** 2018-08-06
- [[https://mp.weixin.qq.com/s/IqjGWPnU2qhKFqYWhuIBig][《我闺蜜在龙泉寺禅修的5天》]] 创造了贤二动漫形象其及机器人的龙泉寺，并不会止步于
  动漫和机器人。从龙泉寺的官网来看，这个外表低调的京西寺庙，已经开始研究AI了。这
  究竟是个什么地方？

- [[https://mp.weixin.qq.com/s/trWiVKAdyvkqBeJvYGq_MA][《极路由风云》]] 极路由濒临破产，创始人王楚云一份内部信遭曝光，引起了不少创业者
  的同情，各种对王楚云的遭遇同情一边倒的时候，也有另外一种声音夹杂其中，极路由与
  i财富的真正关系被质疑……

- [[https://mp.weixin.qq.com/s/o1hE-MKnzMHDHVLPTtlghw][《他们曾在百度销售竞价排名》]] 在过去很长一段时间，竞价排名都被认为是一种自然的
  信息检索服务，但现如今，已令人嗤之以鼻，转折是2016年爆发的魏则西事件。而身处竞
  价排名内部的他们如何面对这转变？

- [[https://mp.weixin.qq.com/s/EQUwy17d_oJucgVSPyfkzw][《京沪白领图鉴：隐形土豪、无产中产阶级和猪猪女孩》]] 城市间总会有比较，文章这次
  谈及了城市规划，办公场合，吃喝玩乐以及最重要的住，各方面均有数据支撑，希望在您
  下次与人辩论时有所帮助。

- [[https://mp.weixin.qq.com/s/TQXIkwUzZHFOmZO2YFdvhw][《2018，捷径消亡史》]] 1980年，风靡全国长达半年的爆文是刊登在《中国青年报》上的，
  6万多人参与了后续大讨论，主题是“人为什么而活着”。2018年，占据朋友圈的爆文则
  是《你的同龄人，正在抛弃你》。捷径不再是捷径，捷径变成了救生艇。
** 2018-08-03
- [[https://mp.weixin.qq.com/s/04Ww9Ce32YO9MX8pwjsosA][《苹果市值登顶万亿美元！这家伟大公司如何走到今天》]] 谁是第一个市值万亿美元的公
  司，亚马逊、谷歌、微软、苹果一直前赶后超。终于美国当地时间8月2日，苹果股价在当
  天开盘后延续了前几日的涨势，盘中突破每股207.05美元，成功登顶市值1万亿美元！

- [[https://mp.weixin.qq.com/s/vrEeVBnfxNhWxWrcvxd93w][《星巴克+阿里=？》]] 对于阿里来说，与星巴克的合作有些“反常规”，在其铺展新零售
  业务以来，这是阿里第一次在没有资本介入的情况下开放自身的各项核心业务。实际上，
  两者一年前就已经“暗生情愫”了。而到今天才最终拍定，可以想见其中的难度。这种重
  量级的联盟不仅改变了合作的彼此，还会影响整个行业。

- [[https://mp.weixin.qq.com/s/sMM7wk0C-QZTF2UFC9BoDw][《2018年中国少儿编程教育创投及行业研究报告》]] 2018年以来，少儿编程的融资速度也
  逐渐加快，头部资本和教育科技公司也纷纷入局，这将会是一个火热的风口？在重度依赖
  Scratch的普遍情况下，国内团队如何创造核心竞争力？课堂教育与在线教育，在少儿编
  程领域分别有怎样的优势与劣势？该篇报告较长，可按目录阅读。

- [[https://mp.weixin.qq.com/s/jRuWymL_TThtn4-NjR5H_Q][《汪涵加持，抖音头条护航：西瓜视频为何、如何自制综艺？》]] 终于字节跳动（今日头
  条）旗下西瓜视频宣布全面进军自制综艺领域，将投入40亿打造移动原生综艺IP。首档综
  艺《头号任务》将由西瓜视频联合银河酷娱共同打造，湖南卫视主持人汪涵则将作为节目
  的主嘉宾。该综艺的亮点在于用户可以通过手机发布视频直接参与到综艺的进程中来。

- [[https://mp.weixin.qq.com/s/rNnagTO8dfxaYYn7tLlBng][《“30亿+”爆款频出的暑期档，为何却成为了韭菜收割机？》]] 七月连上的多部爆款影
  片，重新点燃了资本市场对国内影视公司久违的热情。每一部爆款影片背后，都有一颗影
  视资本跳动的心，但与不断抬高的票房相比，影视公司在资本市场的价值却成为更大的问
  号。爆款电影对定义影视公司价值的说服力也越来越无力。
** 2018-08-02
- [[https://mp.weixin.qq.com/s/4HmtMeC9YqGIw7iTJg7Plg][《P2P爆雷潮波及实业》]] 截至今年5月，邻家便利店共在北京开出160多家门店，与全时、
  便利蜂等一道，被看作北京市场上较有代表新的新型便利店品牌。8月1日，北京市朝阳路
  上的多家邻家便利店大门紧闭，门上贴上了“暂停营业”的牌。一天之内，多家邻家便利
  店整齐划一地关店，究竟出了什么问题？

- [[https://mp.weixin.qq.com/s/Ibqj3jl7rvVP4DTjwoNpsA][《46万条评论数据+人工智能，我们发现了986家网红餐厅的生存之道 》]] 文章分析了25个
  城市中一共986家网红餐厅。从城市，选址，评价等方面来分析一个餐厅成为网红的线索。
  比如：如果你想在上海开一家网红餐厅，费些心思想一些听起来复杂的菜名，可能会有意
  外的收获……

- [[https://mp.weixin.qq.com/s/Cwooc4lBdRGRKUAiBkrh1g][《为什么这个时代会出现这么多“新穷人”？》]] 英国著名思想家齐格蒙特·鲍曼在《工作、
  消费、新穷人》中首次提出“新穷人”概念，原指“有缺陷的消费者”，即手中没有足够
  的钱随心所欲购买必需品。用通俗的话说，就是拿着并不丰厚的薪水，却追逐中产的品味
  和生活方式，导致没有存款、透支消费甚至负债的贫穷。

- [[https://mp.weixin.qq.com/s/Hb8-tONBS1dxOHt3ikNAkw][《家乡啤酒兴亡史》]] 曾几何时，几乎每个人的家乡都产过自己的啤酒。而自古以来，酿
  酒业自带高税收、高利润，给地方财税带来的贡献非其他产业可以相比。既然如此，那家
  乡啤酒都哪儿去了？

- [[https://mp.weixin.qq.com/s/3iPEK_R5E8f_fqSnWOxDlg][《革命尚未成功，雷军仍需努力》]] 真实故事计划之雷军——雷军拖着助理和印度的同事走
  到车站，得知当天的全部火车都已经开出。刚听到了这个消息雷军很失望，但是一转身他
  突然跳下站台。踩着枕木向夕阳的方向跑去，身后的同事们也只好跟着跑了起来。这时从
  站台的方向看去，雷军好像是电影里的阿甘，在身后留下长长的拖影和一群跟随者……
** 2018-08-01
- [[https://m.huxiu.com/article/255332.html][《被封掉的陈一发和卢本伟》]] 关于网红陈一发，共青团、人民日报先后发声，现在谁都
  知道——陈一发也凉了。说到底，直播终究是草根的舞台，中间的佼佼者，也是草根中的王
  者，是平台和其他草根把他们推到了云端，现在也是平台和另一些人让他们重重摔下。

- [[http://www.tmtpost.com/3346104.html][《爆文、公关和网红大V背后，是刷流量的游戏规则》]] 草根中的佼佼者一旦有火的潜力，
  一系列的平台、公关便会主动找上门。然而随着行业竞争，内容已经渐渐变得不再重要。
  如何快速敛财，才是这部分他们所关注的重点。

- [[https://mp.weixin.qq.com/s/Rt5pM59zaxeYP2T8ZzeBgg][《百万粉丝启示录：普通人成为网红有N种方式》]] 看到国外，YouTube 有一个粉丝数奖项，
  十万是白银、百万是黄金，千万是钻石，美国网站Tubefilter开设了“YouTube百万俱乐
  部”访谈专题，新榜编译了其中几个故事 ，关于国外百万粉丝网红的故事。

- [[https://mp.weixin.qq.com/s/x2-qQRIUwXWu8QKs-8MzgA][《去香港，收割一个时代》]] 2018年7月9日，小米的上市，拉开了香港资本市场这一轮狂
  欢的序幕。之后，无论是体量庞大如美团、比特大陆，还是那些在各自垂直领域做到前几
  名的独角兽，都悉数交表，排队敲钟。有一天，港交所敲钟的公司有8家，但只有4面锣，
  只能两家“分享”一只锣……

- [[https://mp.weixin.qq.com/s/-0hLdVEcWtyAgdlUuyddug][《小程序推广难？这14种小程序的推广方式你不能不知道！》]] 这篇是大家喜闻乐见的
  “干货”，一年半时间，小程序成为了炙手可热的流量风口。对于很多企业来说，小程序
  的开发并不是什么难点，但是如何推广却难倒了不少企业。14种推广方法，有老酒新装，
  也有属于小程序的独特方式。
* 2018年7月文章
** 2018-07-31
- [[https://mp.weixin.qq.com/s/hatAwHFDWpm4aEq7WcXq8Q][一下科技踩中双响雷，秒拍、波波视频同时被无限期下架]] 短视频APP们像是迎来了本命年，
  而且遭遇了水逆。一下科技是此次唯一被下架两款产品的公司，也就是其过去的王牌产品
  “秒拍”，以及去年主要打造的“波波视频”。

- [[https://mp.weixin.qq.com/s/foXyYGweRfOdm7URaXzbMw][互联网早期是怎么发展起来的]] 1995 年比尔·盖茨给微软写了一封名为“互联网潮汐”的
  亲笔信，这封信解释了微软为什么下决心要 all in 互联网，部分奠定了它此后二十年雄
  踞互联网一方的格局。

- [[https://mp.weixin.qq.com/s/Gu0GkA8CcODnkBkh3ydRiQ][P2P 爆雷，小米给年轻人上的最后一堂课]] 据财经网报道，多位小米用户爆料，因在小米
  的 VIP 任务系统和小米运动 App 中看到了管家金服、秋田财富等 P2P 理财平台而购买
  的理财产品，如今这些平台却“跑路”，数万元的投资“折了”。而如今，P2P “爆雷”
  事件频发，小米也卷入其中。

- [[https://mp.weixin.qq.com/s/NNk_v2MR9sV4B9BnUUsjdg][网红复活记：1100万粉丝和他的困局]] 网红斯外戈以搞怪短视频爆红，容貌与表演与主流
  的“偶像”不符。这个骄傲的年轻人，还未做好准备，就被戏剧性地推向台前，接受大众
  的观看和审视。他的成与败，代表了当下年轻人的更多可能性吗？

- [[https://mp.weixin.qq.com/s/vy7cgT7y_F2VLBIqNTMlmg][转转斗闲鱼，争夺4000亿闲置市场，谁能问鼎王座？]] 转转和闲鱼生而不同却纠缠撕斗，
  谁能问鼎闲置交易市场的王座？龙争虎斗又向来暗潮汹涌的闲置交易市场，终于迎来一个
  关键节点。根据易观数据统计：后来的追赶者转转月活跃用户数快速增长，目前已突破1
  500万，与闲鱼相差无几。
** 2018-07-30
- [[https://mp.weixin.qq.com/s/NhQiEh0VauHlA26KdjagsQ][百度没有文化]] 百度的文化悲剧在于，最核心的几个产品都是靠技术推导出来的，最早期
  的MP3、图片检索，都是前端超级简单的产品，后端超级复杂的技术，技术在这里面话语
  权变大，大到漠视/践踏版权的地步......

- [[https://mp.weixin.qq.com/s/5KLqFUk9M4gwVWavrDVfwA][改版后的豆瓣，身上都是新浪微博曾经的影子]] 当商业化成为不得不考虑的问题，用户体
  验和商业利益之间的冲突就凸显出来。而豆瓣才刚刚开始上路，如果有一天豆瓣的广告也
  变得像微博一样多，也许用户也不用太过惊讶。

- [[https://mp.weixin.qq.com/s/_Wjp_fwi2KBTqVRspl9x6Q][雷军、黄峥、王兴，互联网江湖终于被撕开了一道口子]] 即便在看似垄断的互联网江湖，
  后来者依旧有机会。拼多多VS淘宝，美团VS阿里新零售，小米VS京东。在AT长期“对峙”
  之后，互联网江湖终于重新焕发了活力。

- [[https://mp.weixin.qq.com/s/JYD0HlIiIrBeHz1NAV9E2A][我的第一份工作]] 两年前黄峥公众号的一篇文，到现在阅读量也没过4000。文章记录了他
  在google工作收获，也是在google，黄峥早早地就实现财务自由。

- [[https://mp.weixin.qq.com/s/hwqjWAue80xmrL0TXm6Lrg][智慧零售：推动业态革命到科技革命]] 最近两年，零售搭配不同的前缀出现在大众面前，
  从新零售，到无界零售，再到智慧零售、智能零售。一系列概念陆续提出，不管最后哪个
  名称会被确定下来，都预示着零售业第四次变革的开展。
** 2018-07-27
- [[https://mp.weixin.qq.com/s/TmVZhm-hmLyuaLCCm1ykEQ][创办三年，三亿用户，市值三百亿美元：拼多多的本质是什么]] 拼多多被称为北京五环内
  居民无法理解的平行世界，黄峥曾表示，全品类扩张还是传统的流量逻辑，升级也是五环
  内人群的俯视视角，“我不认为拼多多要品牌升级，要全品类，我们要做的事情永远是匹
  配，让合适的人在合适的场景下买到合适的东西，拼多多的使命是多实惠多乐趣。”

- [[https://mp.weixin.qq.com/s/IH1MwhbWN54kQmaBd8kJLA][大疆走下神坛]] 做好飞行和影像这两件事，仍是大疆未来的核心，但是大疆并不想只做一
  家纯上游的技术公司。“生态搭建者”或是更准确的定位。不过，在成为“无人机界的苹
  果”之前，大疆要先走下神坛……

- [[https://mp.weixin.qq.com/s/n2o06UM7l6QLPEkEDAWQJg][创意人「大逃亡」，广告业的罗曼蒂克消亡史 | 营销观察]] 到如今，已经没有人怀疑互联
  网公司能够帮助广告主“找对人”和“找对场景”，但是“说对故事”的能力还需要补足。
  无论对于提升用户体验，还是提高商业变现的效率而言，这一点都至关重要。

- [[https://mp.weixin.qq.com/s/yZv19FUZI1i3cUFJAsleNw][虎扑硬刚吴亦凡背后，这是我们的观察与思考]] 这场史称7.25吴亦凡虎扑事件的事注定是
  一个大事件，是一个过了很久之后依然会不断被提起的事件。这是国内第一个跨圈层、跨
  平台的两个群体之间的正面硬刚。对于互联网人，则可以侧面观察这场神仙打架。

- [[https://mp.weixin.qq.com/s/SgfwO4jWydx3eshXvDZIlA][疫苗事件追踪：你最需要了解的七个真相 ]] 疫苗事件发展到现在，公众逐渐对此恢复了理
  性。第一财经之前给出的疫苗相关建议较为可观。比如：被狗咬伤，狂犬疫苗必须要打吗？
  国产疫苗抽验方式靠谱吗……
** 2018-07-26
- [[https://mp.weixin.qq.com/s/OdieBeX7iyIAk__4LOQVvQ][AI定价，算法卖车]] 二手车市场信息严重不对称，算法可以重构整个交易链条，提升效率，
  让这门生意大到前所未有。然而，总有一部分人为的、偶然的变量，会超出算法，甚至工
  程师们的常识范围。

- [[https://mp.weixin.qq.com/s/pfv-RZCXk3xoUW_uRWMaiQ][央妈“放水”是认真的：因为“清算”也是真的]] 为“松”与“紧”，央妈与财政部吵了
  一架后。7月23日，央妈通过MLF实现净投放5020亿，是MLF出现以来投放额度最高的一次。
  放水就是一场赌注，如果要赢的话，就只有让这笔资金流到它该去的地方。

- [[https://mp.weixin.qq.com/s/_OXkvHkG1A_YRGw4qRf72w][从OPPO/vivo到今日赴美上市的拼多多：幕后教父段永平再也无法保持神秘]] 2006年，段永
  平成为了第一位与股神共进晚餐的华人。这条消息在中国网民圈炸开了锅，一时间流言四
  起。有人说段永平是要去找巴菲特取经，有人说事作秀，也有人说他赚了中国的钱装阔气
  去硬充美国上层社会,而黄峥知道他不是。

- [[https://mp.weixin.qq.com/s/o-zoo4F2O9vPk93v4aDJyw][深山中的比特币矿场：网吧老板转型矿场主，大矿场每年交电费3.6亿]] 矿场里电线缠成一
  坨乱麻，几千台矿机在彩钢房里单调地嗡嗡作响，两侧墙体上挂着硕大的风扇，水冷系统
  随着矿机24小时不停地运转。到了晚上，矿机上几千盏绿色的灯光同时闪烁，让人觉得仿
  佛到了冰冷的幽冥之地……

- [[https://mp.weixin.qq.com/s/bPihNaX7t6_nJN-V-mRFYQ][《深度工作》万字实战笔记 | 21种可操作的深度工作方法，总有几种适合你]] 什么是深度
  工作？在无干扰的状态下专注进行职业活动，使个人的认知能力达到极限。这种努力能够
  创造新价值，提升技能，而且难以复制。举例：在无干扰的情况下专心完成一篇文章的创
  作、一本书的写作或一项技能的学习。
** 2018-07-25
- [[https://mp.weixin.qq.com/s/FxYUOVuYnwHXJVAmwXEQhA][《当社交电商“喜提”微商》]] 多层分销，虽然能带来爆发式增长，但处于监管的灰色地
  带；如果只有一级分销，又要以牺牲增长速度为代价。如何取舍，做自营和做平台的给出
  了答案。

- [[https://mp.weixin.qq.com/s/CoGaomxYKdS_jYmIEfvI6A][《新生代黑客群像：这个时代不再需要侠客》]] 这个时代不再需要侠客，而某种意义上说，
  他们每个人又都是侠客。不同的是，这些年轻人要面临的环境更加复杂，黑客不再单纯的
  是一门兴趣，年轻的黑客们化身“白帽子”开始以此为生。

- [[https://mp.weixin.qq.com/s/lej2KTgOW6MZf8s47rgajA][《他反对美团收购摩拜，3个月后，他再谈胡玮炜、王晓峰、美团和摩拜》]] 李论认为，一
  定有会属于00后自己的社交平台。当00后成为社会主流的时候，这个平台就会干掉微信，
  干掉QQ。他们投了几个新零售领域、和线下流量有关的项目，也在拼命寻找年轻人喜欢的
  项目。

- [[https://mp.weixin.qq.com/s/d3cFS65N2VYUO-eCdH4AAQ][《知识付费，还有哪些你能把握的机会？》]] 学习是一件痛苦的事情，要让人们心甘情愿
  买罪受，这很难。但事实证明，越是反人性、帮助用户客服自身弱点或者看似能帮助用户
  克服自身弱点的产品，用户反而愿意为其付费。健身、医美都是同一道理。

- [[https://mp.weixin.qq.com/s/6y61S735LHfBylPPFtdQ6w][《为什么很多炫酷的产品并没能流行起来？》]] 总有些你会惊呼“amazing”的物件，在发
  布会后鲜有关注。这就引出一个话题：为什么很多炫酷的产品并没能流行起来？其中有个
  原因是——炫酷本身没错，错的是炫酷的体验成本太高……
** 2018-07-24
- [[https://mp.weixin.qq.com/s/cfw9_VE39-YLzSmK5Qvbww][《电击健身、AI教练，「科技健身」能否为健身行业带来春天？》]] 过去随着互联网的普
  及、资本的助推以及AI的应用，教育行业已经为健身行业提供了模板与启示。而健身教练
  将如未来的老师一样，从过往的“重”教书“轻”育人”逐渐过渡为“轻”教书“重”育
  人……

- [[https://mp.weixin.qq.com/s/Cj0FnudV5wVGEJtCGupcjg][《价值观、米粉和生态链：小米的市场权力游戏》]] 创业公司的首要战略不是构建“护城
  河”，而是形成有效的权力。而在小米股票的认购者名单中，出现了从吴晓波到索罗斯，
  从李嘉诚到马云、马化腾等众多熟悉的名字，正如有香港股评专栏所说“这班投资者向来
  无宝不落”，他们的投资仅仅是为了友谊吗？

- [[https://mp.weixin.qq.com/s/4c4LIKQ2YbtGlb_h-irzew][《低调的快手要发力游戏直播了？》]] 在今年2月份，快手就已上线直播PC平台。整整5个
  月，快手直播都躲过了媒体的视线。这倒是很像这家公司的发展气质，快手用户达到4亿
  的时候，还没做过任何的免费或者付费的市场活动。就像另一个产品团队——微信。

- [[https://mp.weixin.qq.com/s/pAMitCWrh0cWOuJmAZTRYg][《深度调查行业的兴衰》]] 疫苗事件诞生数十篇十万＋，而腾讯棱镜团队发出《造假不断，
  6年销售上亿支，长生生物疫苗流通链调查》，这种有料有据的硬核报道，48小时过去了，
  阅读量还没到十万。调查记者面对的问题不仅有资本势力的威胁，还有群众的无感。

- [[https://mp.weixin.qq.com/s/9XlQTTwCYy3GvPee3pEZ4g][《50个广告趣味冷知识》]] 一些沉积在广告史角落的知识借此付出水面，广告是有魔力的，
  它不仅自身有趣，它的历史也伴随着风趣。比如：1993年，相声演员姜昆在央视说了一句
  文案金句：「劲酒虽好，可不要贪杯」。
** 2018-07-23
- [[https://mp.weixin.qq.com/s/ygvyAFNoHeWoTcM9e1zMAg][《网易云音乐王诗沐：我们是如何四年时间做到 4 亿用户的》]] 网易云音乐副总裁王师沐
  说：“对于一个产品经理来讲，最重要的不是抽象地去学习别人的方法论，而是通过自己
  的深度思考和用户洞察，不断总结和迭代自己的方法论，不断的形成闭环。”这是他的方
  法论，或许你可从中获益。

- [[https://mp.weixin.qq.com/s/xIagTfkUGkPgSyfJ7pzoQg][《拿下分众盯上头条，这源于阿里的流量焦虑》]] 7月18日，阿里150亿人民币入股分众传
  媒，公开资料显示分众传媒目前覆盖了300个城市的2亿城市中产。不难想象，写字楼电梯
  间被迫接受广告轰炸的白领，也是淘宝和天猫的主流消费力。面对微信月活9.3亿的流量，
  阿里别无选择……

- [[https://mp.weixin.qq.com/s/97TDDL5MrqmX3u4T4fp3jQ][《我是一个P2P投资者，我现在慌得一批》]] “投资有风险，理财需谨慎。”每个“韭菜”
  都被这句话教育过。而从2018年7月以来，有40家P2P平台纷纷跑路、自首、出清。从跃跃
  欲试到哭天抢地，投资者只用了几个月，而人性的贪婪与弱点也在其中展露无遗。这次潮
  水退去，裸泳之人还会得到惩罚吗？

- [[https://mp.weixin.qq.com/s/hsXoc_SphWr1sOx7uABMTA][《在分析了抖音近期最热的100条视频后，我们发现了如下规律……》]] 文章结合第一期抖
  音TOP100短视频，整理了如下8条爆品内容规律供大家参考。其中有两条爆红规律仍很明
  显——内容和明星，明星不多说。而何种内容更受人喜欢，文中有指出方向。

- [[https://mp.weixin.qq.com/s/XzNRDBPUkQv2vGg3nj1Trw][《转转与闲鱼PK，背后是阿里与腾讯的新战场》]] 极光大数据统计，2017年度渗透率排名
  方面，闲鱼以4.30%的渗透率排在首位，转转渗透率为1.96%。闲鱼与转转之间的差距，似
  乎是无法逾越的鸿沟，不过这种趋势在2018年有了反转式的发展。这背后自然是有推手，
  不过为什么资本会看上二手市场这块蛋糕？
** 2018-07-20
- [[https://mp.weixin.qq.com/s/8-dBiR4rO06PLN3-1qIleQ][《留给陆奇的工作机会不多了》]] 人们之所以对陆奇的去向感兴趣，除了对陆奇本人的期
  待和兴趣之外，还因为陆奇选择去哪家公司，实际上意味着这家公司具备了某种不可言说
  的地位——与BAT，至少是BAT当中的B——等量齐观的业界地位。但正是因为这个原因，陆奇
  的选择，其实是接下来一段大历史的序幕。

- [[https://mp.weixin.qq.com/s/-nse_ZAeMFF_rubMxUpQBw][《左手李嘉诚，右手贾跃亭》]] 李嘉诚正式退休了，他最后一次来到汕头大学，亲自把校
  董会名誉主席的职务传给了次子李泽楷。远在地球另一面的贾跃亭，会见许家印，FF大计
  不留余力地推动着……这两位，看似八竿子打不着，但对比起来看，会隐隐觉察到一股暗
  线连着他们。

- [[https://mp.weixin.qq.com/s/ZkHdSyZLN_OeGMliJYca0g][《上市破发启示录：2018年互联网公司能从泡沫时代学到什么？》]] 2000年的互联网IPO变
  得异常残酷：网易则是上市即破发，曾连续9个月跌破1美元，而在之后18年的发展中，截
  至目前，网易市值344亿美元。因此文章选取网易作为研究范本，试图厘清，在那波泡沫
  期上市浪潮中，网易如何“逆袭”成功，对于今日诸多破发的公司又有何借鉴意义。

- [[https://mp.weixin.qq.com/s/ZQtuqWevWSENbrCaAPnL1g][《拼多多的多和少》]] 摘取文章底部一条评论：“一篇写拼多多的文章却以孙彤宇开篇，
  然后整个电商江湖英雄粉墨登场，数尽风流人物，鲜衣怒马少年时，一日看尽长安花！”

- [[https://mp.weixin.qq.com/s/1aR6lmKh44P3IX3KmP_hQQ][《王信文 | 成年人也分对错》]] 成年人的世界也分对错，不过这对错有着更为严苛的标准。
  比如：对错有时候不重要，有人愿意信就好；对错没有绝对，有时候只是强者的共识；对
  错没有绝对，有时候只是文化差异……提出并长期坚持一个非共识的观点， 即勇敢笃定，
  不问西东，无所对错！
** 2018-07-18
- [[https://mp.weixin.qq.com/s/KsrfE7ocRuKR6Kj8I1Fmig][《百度的第二条命》]] 百度从一开始就相信，技术不仅仅是一种手段，技术可以创造前所
  未有的东西。正是这种对技术的关注，给了百度第一条命搜索……

- [[https://mp.weixin.qq.com/s/OoYzYo7wBQmDZL9xKKoyow][《“E时代”的网吧里，有毛片、聊天室和我的启蒙》]] “因特网”在中国城市普及开来时，
  已是千禧年初。网吧在那时展现出其最大的魔力，让“未成年禁止上网”变成“吸烟有害
  健康”一般的标语，而最终在隔壁网咖的照应下，也慢慢蒙上灰尘。

- [[https://mp.weixin.qq.com/s/gUxXnrXjIYgFCGswAFtrLA][《正式入局知识付费！流量变现的另类赌博？》]] 7月2日，今日头条上线付费专栏功能条，
  这款以数据辅以算法为导向的产品，这种数据导向的判断方式，今后在知识付费的探索中，
  相信会被不断践行下去。

- [[https://mp.weixin.qq.com/s/BFdRJQlQokC5VgMi--6UDw][《后互联网：无聊已死、社交危机、故事崛起》]] 人的大脑有神奇的可塑性，无论是认知
  科学、临床医学还是脑神经科学都有大量实验证明：无论是猴子还是人类，仅玩几天游戏
  便会使大脑皮层产生变化。而如果说，我们天天浸泡在互联网其中……？

- [[https://mp.weixin.qq.com/s/jD4Z2-S6zCVocGuLm7l1-g][《App Store 10岁了，它与移动互联网是如何互相成就的？》]] 很有意思的研究，不是从
  app store这十年来的变化历程方面做出探讨，更多是分析其这十年来与整个互联网的关
  系变化，毕竟十年前app store只是是一个小型分发平台。
** 2018-07-16
- [[https://mp.weixin.qq.com/s/kGYjEb5fD-u0IWWI_o8wow][《决赛夜，我们不谈世界杯》]] 足球和中国足球不是一回事！富了一批足球明星，似乎是
  中国足球职业化的唯一成果。白岩松在今年世界杯期间发出感叹：“中超太有钱了，中国
  球员因为太安逸而丧失了出国踢球的闯劲。”

- [[https://m.toutiaocdn.cn/i6578030103026991620/?iid=17759764755&app=news_article&timestamp=1531706147&wxshare_count=12&tt_from=weixin_moments&utm_source=weixin_moments&utm_medium=toutiao_android&utm_campaign=client_share&share_type=original&pbid=6578746429396518414&from=singlemessage&isappinstalled=0][《第一批被AI累死的人》]] 深度学习最关键的就是需要大量的数据训练，而在数据训练之
  前，又必须先对大量的数据进行标注，作为机器学习的先导经验。因此，催生了大量数据
  标注员的产生。简单的说，数据标注员类似于AI的老师，他们是第一批被AI累死的人。

- [[https://mp.weixin.qq.com/s/lBcct9FDtWhZvn7CeKfGoA][《快手产品副总裁徐欣：如何像玩好王者荣耀一样做好产品？》]] 王者荣耀作为策略游戏，
  自然是有着一定的潜在逻辑。你看，这篇文章便把这快节奏战局投射到产品经理身上。作
  者徐欣现任快手产品副总裁。此前供职于腾讯，先后参与QQ空间、QQ、腾讯开放平台、应
  用宝等项目。

- [[https://mp.weixin.qq.com/s/Q8rJAXEpyYQjoNuk5Yse4w][《真实跟踪记录：中国 3 个阶层孩子的 10 年人生轨迹，结果令人震惊》]] 对不同阶级孩
  子们的特写记录，在英国有《56up》，在中国则是《出路》。一加对比，好在今天的中国，
  社会分层还没有最终形成，教育分层还远着呢，所以这是一个大好的时机，去超越自己的
  阶层。
** 2018-07-12
- [[https://mp.weixin.qq.com/s/3FUyQnpTo8WjHYtlqKdtHg][《知识星球：如何才能做高品质社群？如何让社群持续产生价值？》]] 这是来自知识星球
  创始人的投稿，对于我们长讨论的知识付费问题，他又有了新的思考。所以，他希望用这
  篇文章来表达自己的一些观点和心得。一般我们看到的都是他人对一款产品的测评分析，
  而这次自我复盘角度难得。

- [[https://mp.weixin.qq.com/s/fzWQWKEI4HueKcMHmPw-Hw][《微信战抖音，映客当渔翁》]] 熬过了2017年的倒闭潮和政策监管，直播平台逐渐开始秀
  出肌肉。接连上市、行业合并、巨头布局，混沌过后直播平台似乎进入了秩序构建的世界。
  在微信激战抖音短视频同时，直播行业正迎来一场资本盛宴。

- [[https://mp.weixin.qq.com/s/0srzL84Wz1iHMXiL6wWXwA][《算法猛如虎？最通俗语言为你拆解算法分发全过程》]] 打开视频，新闻甚至是音乐软件，
  不管你愿意或不愿意，你我已经事实上被时代的浪潮所挟裹，走进了内容的算法分发时代。
  你我都知道算法会针对用户习惯个人定制，而具体操作是什么?这里有篇文章，深入浅出。

- [[https://mp.weixin.qq.com/s/rkQDFUuiKtGnyeVkMb4vBw][《特斯拉入沪 | 焦点分析》]] 7月10日，特斯拉与上海临港管委会、临港集团签署协议，
  将在临港地区独资建设集研发、制造、销售等功能于一体的特斯拉超级工厂。这也是上海
  有史以来最大的外资制造业项目。对于中国汽车市场这篇池塘，特斯拉的搅入，或许会让
  其更有生气。

- [[https://mp.weixin.qq.com/s/5rWG57GQt3dcrymllM6nMw][《独家：揭秘90后渡鸦创始人离职百度真相！》]] 百度的“all in AI”一提出，作为语音
  AI载体的“渡鸦”音箱便很快被推上舞台，而在百度内部的人事变动以及产品策略摇摆之
  间，这个团队又急流勇退，如烟花一般匆匆谢幕。度的产品路线将走向哪里，或许这一谜
  题最终还要由李彦宏最终来抉择……
** 2018-07-11
- [[https://mp.weixin.qq.com/s/w7KX7uMLQNuZs4xUGTmneg][《三万网站含挖矿代码：当你上网的时候，可能就在帮黑客挖矿了》]] 浏览即挖矿，如果
  你在上网的时候觉得自己的电脑和手机莫名其妙地发烫，那么你就要考虑是不是已经被网
  站利用来挖矿了。截止 7 月 9 日，全网有超过 3 万家网站内置了挖矿代码，全球约有
  5 亿台电脑曾被绑架挖矿。

- [[https://mp.weixin.qq.com/s/VMsRz8sfy1KPKBiIg-y7Kw][《共享经济10周年，这5个问题还没解决》]] 从08年Airbnb和Uber相继成立，再到我们已经
  习惯了使用滴滴叫专车、用摩拜租自行车、在旅行时使用Airbnb和小猪短租来预定民宿。
  共享经济已走过十年。而其与几百年来商业社会仍未兼容，主要存在着这五个问题。

- [[https://mp.weixin.qq.com/s/iv3SJeCs_jCqD2hu3m2r7g][《广告日流水过千万，像做公众号那样做小游戏？》]] 有预估，两年后内整个小程序一年
  的广告流水会超过1000亿，大过微信公众号广告市场如今500亿－600亿的规模。 在小游
  戏生态里，在不同的产品之间互相导流，逐渐形成矩阵，在可预见的未来，又有一家小程
  序的“量子云”会诞生。

- [[https://mp.weixin.qq.com/s/LAwaEDKyJSAnfg4unclnyw][《雷军敲钟，“金山帮”的创业浮沉》]] 不完全统计，“金山帮”里，成功IPO的就有王峰
  的蓝港、冯鑫的暴风、陈睿的B站，而傅盛也执掌了更名猎豹之前的金山网络。他们在金
  山获得财富自由后，分别开启了自己的新时代，而现在随着小米完成IPO一个新时代又要
  开始了……

- [[https://mp.weixin.qq.com/s/pZaDBgPkl5wvYiwDJl5nSA][《比腾讯赚得多，这家公司不足30岁，已是世界500强，没想到，又开启了新一轮转型》]]
  传统金融行业没有互联网那般渴望曝光，低调地获取了令人讶异的成绩，而这次传统行业
  也转过弯来了，朝着互联网进发……2017年的中报显示，平安集团上半年有1800万的新增
  客户，其中36%左右来自互联网客户，而一年前这一数字是22%。
** 2018-07-10
- [[https://mp.weixin.qq.com/s/I7h8woIksofUAaSVGVh_kg][《土创者哈罗单车》]] 当初ofo与摩拜激烈竞争时，外界就有声音称，这是阿里和腾讯的竞
  争。果然，从“百车大战”到如今的“三强争霸”，共享单车依旧是巨头“撑腰”下的资
  本游戏。那么不起眼的哈罗单车是如何活过资本围剿闯到现在的？

- [[https://mp.weixin.qq.com/s/8c99JIpfySI9hyOXdMLzDw][《商人徐峥》]] 荧幕中徐峥喜欢塑造的角色有点油腻，有点糙，甚至还动手打老婆。接着，
  小人物崩溃到极点，开始反弹。而荧幕外，徐峥也大秀了一把财技。从追IP，到打造IP，
  现在成为“中年流量”担当，并赚得盆满钵满，商人徐峥被推到台前。

- [[https://mp.weixin.qq.com/s/hZ_plrM1M1--9X-CA6-SMg][《滴滴要玩防守反击》]] 在6月30号前后，滴滴官方宣布专车品牌服务全新升级，滴滴专车
  将更名礼橙专车并将上线独立APP。临近上市，这时发布独立品牌“礼橙专车”，滴滴打
  了什么样的算盘？

- [[https://mp.weixin.qq.com/s/IGq28CXNxImO55yelW6JIw][《“中年海漂”归国潮渐起：在硅谷养老，还是回中关村搏命？》]] 不再同于“职业天花
  板”这样的个人原因，还因为硅谷这片曾经的蓝海越变越挤，生活变得愈发温吞之时，中
  国已经悄悄进入了互联网经济发展的黄金时代。告别硅谷养老，中关村搏命时代开启。

- [[https://mp.weixin.qq.com/s/8QIuhuFrNRlsZ_97q7TmWQ][《一支纪录片，解构《纪念碑谷》》]] 一只关于《纪念碑谷》的广告片，其实更算是访谈
  纪录片。去年同期腾讯游戏收购了很多手游，但《纪念碑谷 2》似乎有很特殊的位置和意
  义，为了宣传游戏，他们推出了包括直播、H5 和纪录广告片等一系列整合项目。一起来
  看看这支不一样的游戏广告片。
** 2018-07-06
- [[https://mp.weixin.qq.com/s/qfr0MZ13sBigMFUk8NgVTQ][《从《战狼》到《药神》，这家公司是怎么成为爆款挖掘机的？》]] 传统影视企业里，有
  一家公司尚处于第二梯队。发行的电影《心花路放》、《鬼吹灯之寻龙诀》、《战狼2》
  就分别拿下了2014、2015、2017年国产电影的票房冠军。这家便是今年出品发行《我不是
  药神》的“北京文化”。

- [[https://mp.weixin.qq.com/s/qsVNkrducS6aXLVmMFc2dw][《科普：你什么时候能用上5G？》]] 5g用于物联网的作用大于用于手机，然而每家手机厂
  商都在等着芯片厂商给到的时间表，就目前而言，或将在 2019 年才会推出第一款真正的
  5G 手机。这将是友商们期待已久的换机潮。

- [[https://mp.weixin.qq.com/s/3v-0RB3OBqv5b-NuNfbAmQ][《当我们谈战略，我们究竟在谈什么？》]] 战略这个词在中国被广泛应用，广义上甚至可
  以指代成一个目标，有时候显得大而空。其实战略也不是你看到了，想到了就是对的，做
  得到才是你的，只是这样说显得有点马后炮而已。


- [[https://mp.weixin.qq.com/s/0RCP41bNvfJALVqUZzyZJQ][《雷军怎么让5%成了靶子？》]] 前几天，在小米6X发布会上，雷军当众向所有用户承诺，
  小米硬件综合净利润率永远不会超过5%。尴尬的是友商的评论，让小米再次有了5%这个靶
  子。

- [[https://mp.weixin.qq.com/s/EPVq9XgWyebUl5cDB2bqcg][《世界上最遥远的距离，是我天天用你的产品，却不曾在意你的品牌》]] 对于一个中国移
  动的普通用户来说，它的产品本身的确给用户提供了非常大的价值但是其品牌却没有给用
  户提供价值（比如用户并没有在看到中国移动几个字的时候产生自信的感觉）。也就是说，
  中国移动给用户提供的，仅仅是产品的有形价值，而不是品牌带来的无形价值。
** 2018-07-05
- [[https://media.weibo.cn/article?id=2309404258483468911864][《海航非常48小时》]] 发布王健讣告的四个小时后，海航管理层向不知所措的员工下达了
  口头通知，让大家安静，不要妄意揣摩。

- [[http://www.ifanr.com/1059522][《你知道 App Store 在十年间赚了你们多少钱吗？》]] 2008 年，苹果 App Store 正式上
  线。2017 年，App Store 和 Google Play 的下载量份额基本呈「三七开」的局面。但这
  丝毫不影响 App Store 的吸金能力。在全球用户支出中，App Store 所占份额基本维持
  在 Google Play 的两倍左右。这十年间APP STORE究竟赚了多少钱？

- [[https://mp.weixin.qq.com/s/2IjUsW8DHTgLKNWB_iiFDQ][《为什么星巴克的“第三空间”越走越远？》]] 社会学家雷·奥尔登堡将居住的地方称之为
  “第一空间”，花大量时间用于工作的地方称为“第二空间”，而“第三空间”则是居住
  和工作地点以外的非正式公共聚集场所，“第三空间”的概念，更突出地强调了场所的社
  交作用。星巴克第三空间的理念在中国可以说发挥到了极致，而非其母国。

- [[https://media.weibo.cn/article?id=2309351000894258474962869526][《毕业季“抢人”比拼：新一线城市最受青睐》]] 根据调研数据，在毕业生求职前十五位
  城市中，一线城市占比39.06%；新一线城市占比56.36% 有49.05%的毕业生计划在30~34岁
  之间完成购房目标，另有35.61%的毕业生表示希望在25~29岁期间买房。

- [[https://mp.weixin.qq.com/s/foUx3cHuYsE5u90zT4AMkQ][《互联网公司上市的时机与命运》]] 18年，中国互联网企业迎来第三波上市潮。可以预期，
  随着第三次互联网企业上市潮的开启，一批拥有新技术、新模式的“互联网+”公司将迎
  来收获期。某种程度上，这也是中国经济转型升级交出的一份靓丽成绩单……
** 2018-07-04
- [[https://mp.weixin.qq.com/s/3SgHzbfrfZjet1sQ21grdw][《今日头条内测付费功能，全面开启粉丝红利期》]] 从一开始，张一鸣心目中的粉丝变现
  路径便是：流量—粉丝—付费用户。为了迎接这一时代，今日头条推出“千人百万粉计划”：
  未来1年内，在平台上扶持1000个拥有一百万粉丝的账号。但直到现在，变现手段才以付
  费专栏形式体现。

- [[https://mp.weixin.qq.com/s/QWbz0tzmnShfr6qJPeDAQg][《天不生你李笑来，币圈万古如长夜？》]] 7月3日深夜，几个币圈微博号突然曝出李笑来
  在年初和人谈话的录音。在这段长达53分钟的对话中，除了脏话连篇，李笑来也算是“妙
  语频出”。文章非公关，分析李笑来同时吐槽币圈。言辞犀利同时感情饱满。

- [[https://media.weibo.cn/article?id=2309351000894258089208550517][《中国手机往事》]] 从2009年开始，雷军四处向人科普智能手机，好几次在吃饭间隙，他
  都直接掏出一部魅族M8手机，现场讲解起这部手机的好处……雷军、黄章、罗永浩、刘作
  虎、贾跃亭……他们或没落，或挣扎，或成功，这是他们十年间发生的故事。

- [[https://mp.weixin.qq.com/s/rmuNmALqPyJO7tBGvpowpw][《华谊困局》]] 崔永元因为《手机2》的拍摄，揭露了一系列影视行业的税务问题，引发不
  少影视公司股票的下跌。作为《手机2》的主要出品方，华谊股价首当其冲。表面来看，
  这只是场舆论风波。但整个事件背后却暴露出大众对于影视行业的不信任感，危机一触即
  发。

- [[https://mp.weixin.qq.com/s/6ljWiMMjsFIoXEeQ_afu5g][《钱荒、人慌、项目黄，狂奔6年的资本遭遇寒冬，机构该“还债了”》]] 创投圈流行一个
  段子，资本寒冬来了，会有张颖内部信流出，王冉发文跟上，包凡总结陈词。近日，王冉
  再发朋友圈称“募资越来越难，GP（普通合伙人）们势必开始珍惜子弹。” “2018年是
  投资机构的清算期。”
** 2018-07-03
- [[https://mp.weixin.qq.com/s/gI1y9NptHYkD_yShaWE3tQ][《5G 会彻底改变我们的生活，但不是从手机开始》]] 世界移动大会如期在上海开展，三大
  运营商均大规模在场外试验了5G测试，距大家真正使用上5G指日可待。而5G实现的将不只
  是移动网络的提速，还有中国工业4.0时代的开启。

- [[https://mp.weixin.qq.com/s/UYS-uxYpg1vluXMDUT-Kog][《抖音被暂停广告业务，收入损失以外还有什么影响？》]] 2018年5月1日，《中华人民共
  和国英雄烈士保护法》正式施行，也是是保护英雄烈士的一部法律。暴漫和今日头条的事
  儿，刚刚好，发生在《英雄烈士保护法》正式施行一个月的后的6月。头条系产品的品牌
  形象带来严重伤害。江湖上对抖音积怨已久的不在少数。一看抖音被约谈，网友的留言常
  常是：这样的平台该关了。

- [[https://mp.weixin.qq.com/s/ifBg4jKMRJuCZELEJN_Hvw][《寻找下一个拼多多：资本抢滩微信生态》]] 资本不是从一开始就青睐微信生态。3年前，
  “看不懂”是很多投资人在看微信生态项目时面对的问题。所以在2015年、2016年入场的
  投资机构才是最大赢家。现在，明白过来的资本们开始抢夺向程序流量，本质是抢滩微信
  生态10亿月活。

- [[https://mp.weixin.qq.com/s/oKzBwRz1f3ReMk9uVMW_yg][《2018新媒体下半年深度预测：增长恐慌，流量洼地》]] 全文7500字讲到了公众号，看一
  看与小程序，还有抖音与知识付费，从微信这个新媒体巨头平台的近期改变，分析猜测下
  半年新媒体总体变化，值得阅读建立体系。

- [[https://mp.weixin.qq.com/s/zqQ6y39bsJx0Nse_6okv3w][《两万字深度揭秘 Amazon 千亿营收的增长黑客策略》]] 又是一篇两万字的长文，或许你
  可以收藏这消息再慢慢品尝。文章图文解说了亚马逊如何成为[世界上最大商店]。分8个
  部分，每个部分都可单独成文。
** 2018-07-02
- [[https://mp.weixin.qq.com/s/l4K6fCZOcYituvUrNyoJwg][《支付宝和微信躺着赚钱的日子结束了》]] 央行规定，从 2018 年 6 月 30 日起，微信、
  支付宝等支付机构受理的涉及银行账户的所有网络支付都必须“断直联”，通过“网联支
  付平台”处理。标志着巨头们再也不能用备付金躺着赚钱了。

- [[https://mp.weixin.qq.com/s/GElZ55bj7_uPdJc-bXZilg][《独角兽们着急上市在宣告什么？》]] 今年以来排队上市的独角兽们已经超过了20家，密
  集程度也是罕见。美联储调高基金利率，美元加息，人民币贬值，中美贸易战下经济局势
  不稳定，局势开始动荡。此时上市意味着可以获得一块免死金牌。随之，独角兽们的打法
  也要变了。

- [[https://mp.weixin.qq.com/s/Vu9JiqIlux7d-QfESJjnoQ][《拼多多是跑在微信上的一款游戏》]] 拼多多的获客之道无法复刻，因为可资利用的社交
  渠道只有微信、QQ，而腾讯又是坚决反对“诱导分享”的。鉴于腾讯持有拼多多18.5%股
  权，微信搞双重标准是天经地义的。向腾讯要公平好比跑到王健林面前说“王思聪有什么
  我也要什么！”

- [[https://mp.weixin.qq.com/s/qGp0b6EiUJOkjgbhvPJRSA][《600天后，这是我关于小程序生态、入局和流量的理解》]] 开发一款操作系统很难么？早
  在2016年，余承东（华为消费业务CEO）就说过“做操作系统对华为来说完全没难度，但
  做生态体系却十分的不容易，WP系统死掉就是生态体系出了问题。手机厂商无法实现的生
  态体系，微信或许可以做到。小程序的征途是星辰大海？

- [[https://mp.weixin.qq.com/s/_UI0q49mgELuA1VS3yBkWA][《去你的流量！》]] 流量指的不只是10+，还有被流量哄抬的IP鲜肉，基于点击率发明的
  “猜你喜欢”，为博得朋友圈关注的打卡旅游等。人们都渴望流量，就放佛渴望那15秒的
  聚光灯。
* 2018年6月文章
** 2018-06-29
- [[https://mp.weixin.qq.com/s/0XVM0ez7ivWsbIRqEweI5w][《20 支好看的世界杯广告片》]] 世界杯上除了叶茂中的洗脑广告，还有许多良品。这里有
  二十支优质世界杯广告索引集锦，欢迎进来洗眼睛。

- [[https://mp.weixin.qq.com/s/mnIdjfgvB9S1OdzIoIb1ZQ][《前南方周末评论员创业，曾被20家投资机构拒绝，如今项目估值3亿元》]] 盖得排行app
  声称：致力于公信力建设，竞价排名，工匠精神打造榜单。概不考虑盈利问题，而以科学
  公正为考量标准。然而其本身却充满非议。创始人李铁曾任《南方周末》首席评论员是个
  老媒体人，他也正是靠这些非议迅速出现在受众视野中。

- [[https://mp.weixin.qq.com/s/MH3C-84DxRQF8un0sxUlgw][《谁的FF | 棱镜》]] Faraday Future是美国一家公司，简称FF。经营范围为汽车。乐视于
  16年与其达成合作，之后的故事大家都知道了。不过这次贾跃亭找到了救星，18年6月25
  日，恒大67亿港元入股成为公司第一大股东，6月26日恒大健康单日涨幅66.16%！？

- [[https://mp.weixin.qq.com/s/0XVM0ez7ivWsbIRqEweI5w][《你还在喝可口可乐吗？不，要用穿的》]] 可口可乐与百事可乐这两家为买糖水厮杀百年
  的企业，终于意识到市场在加速抛弃碳酸饮料，速度快得让巨头们必须加快步伐，探索新
  增长点。除了本身的去碳酸化，高打健康牌，都开始推出联名周边，甚至自己做起了服装
  支线。

- [[https://mp.weixin.qq.com/s/mHVqkXRhXdmHlFbTCiNN3g][《AI、拍照、解锁、全面屏，这是一场定义未来手机的竞争》]] 中国手机市场停滞下滑，
  目前消费者持有手机均能满足其日常需求。如何在5 G到来前提早勾起消费者的购买欲望？
  很多厂商的选择时撩起袖子秀肌肉，于是乎AI、拍照、解锁、全面屏粉墨登场，争着定义
  未来手机。
** 2018-06-28
- [[https://mp.weixin.qq.com/s/nSsrqJv9bxa6ohbmZKZQHw][《广告狂人叶茂中》]] 叶茂中广告哲学的两个核心概念：制造冲突和不断重复。哪怕是无
  中生有，也要制造话题，不择手段追求传播效应，强行洗脑，并且乐此不疲。争议正是期
  望中的的二次传播，这也是中国的广告狂人们曾最常用的操作手段。

- [[https://mp.weixin.qq.com/s/LmlIuy6dDEut8TLI5kHrlw][《谁是中国第一网红城市？》]] 互联网时代，在各种报道下，一座有旗帜鲜明的城市，能
  迅速崛起成为“网红城市”。同时短视频放大了各城市特点，使新晋网红城市——西安、重
  庆与老牌网红成都、丽江面临着交接使命的时刻。

- [[https://mp.weixin.qq.com/s/ohx20ktd_MKfFcq6uAdTAA][《阿里巴巴副总裁：农村淘宝不怕跟社交电商抢流量》]] 虽然带着“淘宝”二字，村淘的
  模式其实与天猫更接近。村淘也有农村的线下零售店品牌“天猫优品”；村淘也需要对卖
  出去的商品负起更多的责任。王建勋说：村淘要卖的是真正的正品，我也不好说别人的问
  题，但我们是正品、好服务、全系列的东西。不知道友商听到会怎么想。

- [[https://mp.weixin.qq.com/s/IQ3LSv7fUKXmGp-2jihNbw][《美团的前景和隐忧》]] 一份招股书让美团再次来到聚光灯下，资料表明：在美团整体收
  入的339亿里，主要组成部分是三块：1、餐饮外卖，占比62%，到店业务，包括酒店和旅
  游，占比32%，3、新业务，包括单车和网约车业务，只占比6%。但作者认为这6%才是美团
  的未来。

- [[https://mp.weixin.qq.com/s/ueJ0OREZHCUKl4IpShL22A][《增长的接力棒》]] 一个业务在不同时期都有着最好的增长手段，因此，能否在业务迈入
  一个新的阶段时，调整增值的节奏，显得尤为重要。文中有facebook、微博、Line等增长
  节奏，可供参考。
** 2018-06-27
- [[https://mp.weixin.qq.com/s/79sGc_RbncD63Pw3LMWYXg][《“头腾大战”白热化，双方都暗示对方使用的“黑公关”，究竟是什么样的存在？》]]
  2010年，有网贴提到：伊利QQ星里加了鱼油，会导致孩子性早熟，这份黑伊利的计划，事
  后调查发现来自于对手蒙牛。简单来说，就是要大规模地在不同平台推送相同的信息，只
  要舍得砸钱，没有发不出去的稿件。无数的黑公关事件证明，成为黑公关是个高危动作。

- [[https://mp.weixin.qq.com/s/FQ6tCMBErD-SpUg88DdXKw][《杨超越政治学｜大象公会》]] 土创在选材阶段，打造了多元并斗争的政治学，这种政治
  学的首次高潮就是王菊，一个未必有革命家自觉的革命家。但针对杨超越的战争，却更为
  变本加厉。此前，杨超越和她的村民们还只是「不努力」，现在，他们已经是「独立女性
  的敌人」，是「男权社会的奴才」了。

- [[https://mp.weixin.qq.com/s/WObhbJvf6ODV56euYhUXoQ][《还在买买买？「新租赁经济」正在全面接管你的生活》]] 凭着共享经济对消费者的教育，
  新租赁经济兴起。不同于传统经济的押金租赁模式，新租赁采用个人信用系统降低了租赁
  的门槛。现在，打开芝麻信用生活版块，定位上海，显示“芝麻分705， 133个信用服务
  可使用”。

- [[https://mp.weixin.qq.com/s/O-sMJO6XTRq-K_uk6PgBrA][《毛泽东才是中国最顶尖的“产品经理”》]] 一家企业，实际上永远要雕琢两个产品：一
  个产品通常意义上的“产品”，卖给顾客的；另一个“产品”，才更是CEO的职责所在，
  就是这个组织。产品想要卖得掉，是不是要靠精雕细琢才能得比竞争对手优秀？组织要想
  壮大、充满活力乃至常青，是否也得花最多时间来“雕琢”？

- [[https://mp.weixin.qq.com/s/wv8HFFB0gFa7h9qnSTABBg][《思考的质量，让你比别人优秀十倍》]] 文章将人类思考系统分为“系统1”，“系统2”，
  定义并介绍两种系统，并以此对人类思考方式一次新的探索，或许会对你有些许启示。
** 2018-06-26
- [[https://www.ithome.com/html/it/366855.htm][《当年被所有人看衰的Twitter是怎么“重生”的？》]] 一个社交平台变得流行后，年轻用
  户就会溜出来寻找替代品。比如：国外的年轻仔们还在看twitter，不过是在新平台
  Instagarm上看。这导致年轻用户的大量流失，而最近两年，twitter只有复燃现象，这是
  为什么？

- [[https://mp.weixin.qq.com/s/Pj4Wz0XTkdpqJghShNbhPg][《在抖音，如何做出爆款内容？（认知篇）》]] 标题说是如何做出抖音爆款内容，实际上
  更是从底层分析抖音的传播与成瘾机制，理论意义大于实践意义，算是一篇不错的科普，
  其中的一些原则同样可以延伸到微博、公众号等各种自媒体。

- [[https://mp.weixin.qq.com/s/EQer-kwkCKNUSGS8zkCfqA][《谈谈商业分析的思维养成》]] 商业分析，用接地气的说法就是，琢磨怎么赚钱。通过数
  据来判断商业走向，已是当今人习惯的思维。文章有意思的地方是，还谈到了“人性”方
  面，颇有复古风味。

- [[https://mp.weixin.qq.com/s/5OCW82fB5b3sLfKr4MiCRw][《600天生死场：资本逃离共享经济》]] 据一位投资人回忆，一年前他收到的项目多还是
  “共享经济”，为了抢夺创业公司，他甚至半小时便确定了投资计划。而最近半年收到的
  项目中多是“区块链”、“新零售”，“共享经济”早已不见踪影。

- [[https://mp.weixin.qq.com/s/TZKH4seNSXNrj5wU2WkSmQ][《ofo，战斗到底的最后一刻 | 深氪》]] 据36氪今日连推两篇关于共享经济的文章，上一
  篇宏观局面分析共享经济为什么不被资本爱戴，这篇将角度放到其中的ofo本身，或许可
  以从两篇文章中找到ofo衰落的奥秘。
** 2018-06-25
- [[https://mp.weixin.qq.com/s/rIjF8RRtZFZf8tqRas6FyA][《微信的操作系统之路》]] 微信最初是借着邮箱名义做出来的聊天工具，之后发展出朋友
  圈公众号的内容生态，再然后加入“钱包”以接入多个app成商业生态，最后就是大动作
  频繁的小程序。从一而终，微信发展出的生态都遵循着简单的哲学理念……

- [[https://mp.weixin.qq.com/s/3_k5prmH0zFTx3d9YVKmEg][《13年创业，王兴终成王》]] 王兴又极其快速的学习能力，凭此2004年，王兴创立著名社
  交网站校内网，后被收购改名为人人网；2007，王兴创立中国第一家微型博客服务饭否；
  2010王兴传力中国最早的独立团购网站，现在的美团。

- [[https://mp.weixin.qq.com/s/SAjnF2UcfkoAhlKP9iaA0g][《GQ报道 | 杨超越变形记：这不是我的世界》]] 杨超越这个名字，从四月开始，反复出现
  微博热搜数十次。追寻这个热点，GQ智族用非虚拟写作的手法写出这个女孩的故事，比起
  采访更像是小说，映射已固化阶级的小说。

- [[https://app.myzaker.com/news/article.php?app_id=562&_appid=AndroidPhone&_version=8.22&_bsize1080_1920=&sharechannel=wx&pk=5b2f48d677ac643d9913bae4][《专访刘胜义：营销已进入智慧零售时代 | 科技公司在戛纳》]] 智慧时代的营销开始步入
  零售时代，刘胜毅认为：微信本身作为一个社交媒体，几乎已经衍变成用户的必需品。这
  个必需品里面将近一半的用户有支付行为。支付 + 算法 + 社交 + 卖场，当把这几个点
  连结在一起就变成了智慧零售。

- [[https://mp.weixin.qq.com/s/t-dgROlZ1yAFk_Ei5tyYEQ][《火锅店也能倍速扩张？海底捞招股书里藏了这几招》]] 近五年里，海底捞一直盛传即将
  上市的消息，但知道今年五月才提交上市申请。上市后，企业模式规范显得尤为重要，而
  这五年里，海底捞的制度规划最终确立下来，其中有供应链，有员工制，精确得很，一点
  也不像其表面充满人情味。
** 2018-06-22
- [[https://app.myzaker.com/news/article.php?app_id=10523&_appid=AndroidPhone&_version=8.22&_bsize1080_1920=&sharechannel=wx&pk=5b2c47c277ac64340e05d8aa][《性、暴力和无处安放的少年荷尔蒙：透视 TFBOYS、杨幂和鹿晗的“黑粉群”》]] 不留余
  力地调谑权威，是少年们荷尔蒙最好的释放场所。在一个 TFBOYS 黑粉群里，曾经有人在
  里面发出了一个鹿晗黑粉群的群号。两个群成员重合度很高，对不同的明星和粉丝，他们
  照骂不误，骂的词汇也都差不多。

- [[https://mp.weixin.qq.com/s/xFe5ZSXU6-j3wdHgDeALsg][《几点看法：关于微信订阅的改版（兼谈何为信息流）》]] 张小龙在去年回答说，不知媒
  体所谓的信息流，并说所谓针对头条的信息流只用在“看一看”就够了，所以此次的微信
  改版到底是不是信息留呢？文章给出了很坚定的答案。

- [[https://mp.weixin.qq.com/s/x_bfz9KM8tQ0iqanDO8Hpg][《为什么中国互联网公司起名喜欢用动物、植物和叠词》]] 动物形象，叠词，从视觉与听
  觉上能迅速霸占一个人的记忆。看来这并不是互联网发展出来的独特情趣，而是互联网相
  对于其他产业太超前了？

- [[https://mp.weixin.qq.com/s/jyhjuZhKYAqIbozjJCfcMQ][《16秒一条，一周产量破万，你看到的世界杯集锦可能都是AI剪辑的》]] 新华智云自主研
  发的国内首个媒体人工智能平台“Magic”首次惊艳亮相。不多说，贴文中的一个数据——“通
  过“Magic”平台生产的世界杯短视频达到10296条，占主要视频网站世界杯中文短视频总
  产量的78%”。

- [[http://www.qdaily.com/articles/54483.html?share_from=app&from=timeline&isappinstalled=0][《1.65 亿起价的世界杯广告，最后怎么被三个互联网公司打成了“脑白金”？》]] 互联网
  超前的发展在于“算得太清楚”，广告收益被直接一组数字摆在决策者的面前。如何让这
  数字看上去更好看，如何让广告不被突发热点变得被动，的这是驱动互联网广告完成的主
  要原因。
** 2018-06-21
- [[https://mp.weixin.qq.com/s/HlNIyEJhenK0ewFV-95RXA][《微信真的焦虑了》]] 微信改版，大举杀入满是奶和蜜的信息流分发领域，其中的好处甜
  头会使微信如打开潘多拉的魔盒，一直走下去。进而走入短视频领域，用更高频刺激霸占
  用户时间。被微信夺回分发权，订阅号运营者是否会成为单纯的“内容工人”？文章更多
  以微信和运营者的角度来解读此次改动，提供值得思考的独特视角。

- [[https://mp.weixin.qq.com/s/sfh3NZ7xhO_Wv_wX_FzhFw][《当 OV 亮出肌肉，最受伤的还是小米》]] 不到10天，vivo、oppo接连放出大招，一改高
  明星代言费、低性价比的固有印象，给国内用户带来惊喜。在此刻，最该焦虑的不是这两
  款手机定价对标的华为或三星，而是一直主打情怀，继MIX1后再无惊喜的小米。

- [[https://mp.weixin.qq.com/s/nhlVj53zPLx_U_49ns73kA][《市值 1526 亿 Netflix 教科书增长：如果别人对你有偏见，那就进取到让自己毛骨悚
  然》]] S型曲线是每个组织和企业在预测未来时一定会参考的工具，即当某事物发展到一定
  水平后将进入发展滞缓期，不科学地概括便是进入了瓶颈期。因此企业必须在S型曲线发
  展滞缓前寻求改变，以找到快速发展的“第二曲线”。Netfiix就是成功代表，过去10年，
  Netflix成为投资回报率第一高的股票，而非亚马逊……这依靠的便是——单一元素最大化。

- [[https://mp.weixin.qq.com/s/qwlTpo_-9pZHKRnGNn0Ucg][《腾讯之必攻》]] 每一个社会化媒体一般都希望走向门槛最高也最稳固的熟人社交网络，
  微博是这样，于是有了几年前的微博大战，腾讯虽败，但也把微博拖在明星与机构上，阻
  止其向熟人社交再一步前进。社交网络会对社会化媒体坚决劫杀，正如最近被针对的抖音。

- [[https://mp.weixin.qq.com/s/tMr_92JVi7O7mmk_To1z_g][《陌陌唐岩的 2.5 次创业和 9 次电话会 》]] 最初的陌陌做的是陌生人交友工具，既然是
  工具，就只有在有需求时才会被使用，当需求满足或长期得不到满足后，工具就失去了它
  的价值。而后的陌陌推出了及时性社交这一概念，效用讲的就是一种陪伴感，目的从认识
  一个陌生人转到在特定场景中与陌生人交流，这或许就是陌陌新的增长点？
** 2018-06-20
- [[https://mp.weixin.qq.com/s/Ne9xjnuBSuXlZAwxR6wgSA][《下一个知乎，是否会出现在短视频领域？》]] 知乎，果壳等问答网站近年正从工具型网
  站转型为内容社区你意图将知识分享社交化。而短视频作为新的内容社交形式，与问答模
  式能碰出怎样的火花？

- [[https://36kr.com/p/5139467.html][《QQ如何应对中年困境？》]] 到了qq诞生的19个年头，这个年龄放到互联网里qq刚好处于
  中年危机，已有不错成就，但面临这在市场中被更年期产品比下去的困境。既需需求改变，
  qq便把方向对准了年轻人……腾讯数据显示，2018年春节期间QQ上共收发红包44.5亿个，
  00后占比达39％，是最大群体。

- [[http://www.ifanr.com/app/776082][《关于用户体验的这个 5 个误区，你都中了吗？》]] 相比于写给职业设计师，文章更像是
  写给社会对用户体验设计的刻板映像，用来推翻大家之前所认知的观点。其中一些闪光点
  也值得单独百度深究一二。

- [[https://mp.weixin.qq.com/s/bizuPulIBdAlHLI7CG-f0w][《知乎1300万阅读：这7种思维方式，让你的生活慢慢变好》]] 知乎上有个话题，“哪些思
  维方式是你刻意训练过的”，有超过1300万人次浏览。文章将其中主要且有用的观点提取
  出来，整理成八个大点，或许其中就有解决你眼前难题的答案？

- [[https://mp.weixin.qq.com/s/XOxcRri-xftUrXkfqF-2tQ][《烂广告是世界杯盛宴上的苍蝇》]] 杨幂的“你没事吧”溜溜梅广告即使招人烦，也在大
  多数人脑中植入了溜溜梅的概念。同样地，此次世界杯此类简单重复大嗓门的广告比比皆
  是，产品的审美终究向高效、制造受众记忆点低头。
** 2018-06-15
- [[https://mp.weixin.qq.com/s/cHrjHaAziKSTSVrrF0RUDQ][《ofo的四种命运走向猜测》]] 互联网专家王越认为，目前，共享单车市场正从ofo、摩拜
  两家独大的格局演变成摩拜、ofo小黄车和哈罗单车“三足鼎立”的格局。哈罗属于阿里，
  摩拜属于美团，小黄车危机之时，不管哪家谁吞下小黄车都能完整占下一线城市战场。

- [[https://mp.weixin.qq.com/s/U5x9Guep_uS2yuNseZO9Bg][《硅谷归国精英这一年：飞上枝头、跌落谷底、集体出轨、中年危机和再次逃离》]] 亚裔
  在美国科技公司发展到了一定水平，如总经理或总监等职位，便会碰到职场天花板。这批
  人意识到这一点，便有了回国的念头。可惜的是，当他们已触到职场天花板时已快到了不
  惑之年，因此回国后走出的每一步，机会成本都特别大。

- [[http://www.ifanr.com/1049005][《「防沉迷」是一场事先张扬的骗局》]] 上瘾分为两类，一类是物质上瘾，通过药物直接
  刺激大脑；另一类叫行为上瘾，通过一种行为来促进大脑分泌多巴胺。这两种上瘾的生理
  机制其实是相似的，借由此文中提出一个有意思的观点：科技公司推出防沉迷功能，就跟
  买烟送尼古丁贴剂（用于戒烟）一个道理。

- [[https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzI5MDU1OTk1NA==&scene=110#wechat_redirect][《零售业也没能逃过腾讯阿里之争》]] 零售与消费，与每个人都有关，这也可以代表阿里
  的绝大部分业务，阿里对这方面投入很大，如：大润发，居然之家等。而腾讯，尽管不是
  主营此类，但他也绝不能下牌桌，尤其当对面牌手是阿里时。

- [[https://mp.weixin.qq.com/s/i2rMBWn9uRkC86vnXL-Xfw][《怎样让奥巴马、克林顿、小布什为中国微商站台》]] 去年“全球中小企业峰会”在上海
  举行，这个“会议”举起了二十多位全球的前总领导人。于是乎，一夜之间，微商就如集
  体参观蜡像馆一般，与各国前总领导人均会了个面。这究竟是个什么会议？
** 2018-06-14
- [[https://mp.weixin.qq.com/s/9lxKvtUcGvaPwE4cwmRy6g][《“头腾大战”的核心是公共利益》]] 公共利益看上去比商业利益更高，它关乎的并不只
  是两家公司的营收，更是我们是否能够拥有一种更好的、基于数字技术的公共生活。然而
  当评判公共利益碰上基于公众研究的算法时，什么是公益越来越判断。

- [[https://mp.weixin.qq.com/s/yNSa3WuFB-SG_yNvfyTkyw][《张一鸣的战争》]] 多年前，在腾讯宣布“不兼容”360的前夜，《新世纪》周刊记者曾经
  问时任360公司副总裁的刘峻：你估计接下来腾讯会如何应对？刘峻答道：宣布不兼容呗。
  360后来的震惊戏、愤慨戏和悲情戏，也仍然是早已规定好的戏份。这都是一出戏，门票
  是吃瓜群众的注意力。

- [[https://mp.weixin.qq.com/s/5aa3ul32i3QqytEpTRCT4w][《微信把购物搜索的入口给了京东，这是拉一把京东还是带小程序的节奏？》]] 在拼多多
  之前的2014年，腾讯与京东久长时联合社交与购物，将京东一级购物入口接入微信钱包，
  只是雷声大雨点小。而最近，当你尝试在微信搜索一件物品时，你将会看到一件件商品，
  商品来自京东。

- [[https://36kr.com/p/5137502.html][《六年6倍，Adobe的1000亿美金之路》]] 2013年Adobe宣布：从过去卖版权的模式，转向用
  户订阅收费，并将这种付费用户模式称为Creative Cloud，也就是所谓的云服务模式，这
  种模式最牛之处就是抓住了原本使用盗版的轻度用户。

- [[https://mp.weixin.qq.com/s/EH-4L2MpLRHCZ4uAVz4w5w][《十元店”的大生意 ——QQ会员业务转型及深度运营》]] qq会员成功的一个方面在于两个方
  面，一个是立体的多方面小功能打包按月收费，一方面是在qq用户中对qq会员特权的建
  立……
** 2018-06-13
- [[https://mp.weixin.qq.com/s/GISpCPi823NGO-lXhwEQcg][《从“合群”到“本我”： 细观中国时尚消费者六大新趋势》]] 咨询公司麦肯锡针对中国
  时尚消费者，既正给这个市场注入新鲜的血液的活力源泉，做了调研，发现了中国时尚消
  费者的六大消费新趋势。总体来说涵盖：追求多样化，获知渠道扁平化，更个性，更冲动，
  更注重体验等。

- [[https://mp.weixin.qq.com/s/hHolDbRbX9grjmrtbmH46w][《鄙视链生存法则》]] 360行没有贵贱之分的理念，从小学课本便扎根在我们思想里。到现
  在，我们不鄙视清洁工，不鄙视服务员，可是鄙视的矛头对准了销售驱动行业。销售驱动
  行业如：保险，微商给大家其实带来了不少便利，但行业未规范，让越来越多的人对其产
  生了鄙视……

- [[https://mp.weixin.qq.com/s/uXwTxzmn83bv-V_55VmTGw][《自从在租房网站填过电话，再也无法逃出全国骚扰诈骗目标名单》]] 文中提到了一项互
  联时代的新兴服务——消失服务。因为在目前的网络环境里，想“消失”是很困难的，即使
  你删光了自己的社交账号信息，也总有痕迹留下，况且很多情况下，你还不能“删除”，
  只能“冻结”。

- [[https://mp.weixin.qq.com/s/gZEn65cKL9F6-6LDG0xzOA][《西二旗“码农”的迭代生涯：收入不菲 焦虑依旧》]] 网上有个段子：在这个浮躁的社会，
  不知多少人都是月入一万假装月入十万，只有西二旗人，月入十万却过得像是月入几千。
  全世界的“收入装逼守恒”，大概都是由西二旗人来守护。所以说，西二旗人简直就是装
  逼界的一股清流。

- [[https://mp.weixin.qq.com/s/LAo8tfSyidGTgfc11AjGPQ][《湖畔三十六：《俞军产品论》》]] 俞军，1997年毕业于同济大学化学系，后加入百度，
  推出百度知道，百度贴吧等产品。这次的内容是从他的一个ppt里提取出来的，ppt共四页，
  每页写满关键词，没图片，乱顺序，无案例，单看ppt算是理工直男典范。
** 2018-06-12
- [[https://mp.weixin.qq.com/s/E0QHaZOqho4cmstxiBn6VQ][《没有红米就没有小米》]] 这一次不再是“小镇青年”的故事，其实红米手机的用户一线
  城市偏多，小米 2016 年公布的数据显示，从城市分布密度来看，一线城市每百人就有
  11.4 台红米手机，二线城市为每百人 9 台，三线城市为每百人 4.7 台。

- [[https://mp.weixin.qq.com/s/-mmfb7xUSC0hUOEy_Ag8-g][《为什么说中国to B时代终于来了？》]] BAT中，百度主卖搜索，阿里主卖电商，腾讯最为
  明显卖的是社交与游戏，中国目前的几家独角兽居然都是to c业务，是什么风水导致to B
  业务在中国发展不起来？

- [[https://media.weibo.cn/article?id=2309351000354248726469249057][《“抖音之城”西安》]] 单看标题以为是一篇软文，点开发现是“南方周末”出品。才了
  解到，抖音推广得最全民的地方不是北上广深。而是昔日的汉唐故都长安，今日的西安。

- [[https://mp.weixin.qq.com/s/YhoE_vXyOERMfLBK_zJjtw][《靠写公众号养活自己？这事没有想象的简单 》]] 有些自媒体人惋惜着自己错过了公众号
  的红利期，若是当年早入局便怎么怎么。可即使是早入局的公众号营生也没那么简单。这
  里有4位从几年前便开始公号内容创业的创业者，分享他们的际遇。

- [[https://mp.weixin.qq.com/s/WrPugwJnG40UzMe9mrxVqg][《咪咕能否成为真正的互联网公司？》]] 多少年前，在中国移动总部曾经有过一场讨论：
  要不要向联通电信用户开放飞信业务。最终的决定是：不开放。此后的故事大家都清楚，
  飞信的自封错过了使其成为微信的机会。多年后，咪咕也到了面临是否开放的局面……
** 2018-06-11
- [[https://mp.weixin.qq.com/s/qjwdHRcNcWcV_NBa3W_WnA][《为什么我的儿子不沉迷游戏？》]] 在游戏这件事上，如果孩子站在两个对立面的中间，
  一面就是苦口婆心的劝孩子不玩游戏的家长，另一面是深知孩子（游戏用户）需求喜好的
  一群游戏策划。所以，若家长只是单纯劝孩子“断绝”游戏，必然是行不通的。

- [[https://mp.weixin.qq.com/s/-wmpSxWKBZT0R3R24PtmQw][《中国散伙人》]] 从通过电影被大家知晓的新东方，到13年销量跃升世界第一的联想，再
  到被称为·房地产界“黄埔军校”的万通，中国这些年的“合伙人”企业许多都到了面临
  散伙的尴尬局面，似乎走进了“中国散伙人”的怪圈。

- [[https://mp.weixin.qq.com/s/xuvxKVp2L6zygZJUAMdJug][《社交广告正在杀死文案》]] 杜蕾斯文案赶热点及时，且幽默搞笑，以至于人们会养成，
  一有热点就上杜蕾斯官博看看的习惯。然而，杜蕾斯广告做得“这么好”，可大家还是更
  愿意买冈本。

- [[https://mp.weixin.qq.com/s/MFiqc2_xbo4HO4bCcopowQ][《傅盛：与焦虑共生，更以焦虑反抗平庸》]] 猎豹傅盛，京东金融陈生强，得到李翔，经
  纬万浩基……等六个完整经历中国从PC跃迁至移动互联网的人围座而谈。即使只是聊娱乐
  八卦，也能聊出打破固有模式的新鲜。

- [[https://mp.weixin.qq.com/s/K6T4iPbVN9_SuwAA5MMZBg][《互联网巨头终极战场：得开发者得天下》]] 微软上周一宣布计划以75亿美元股票收购软
  件开发商平台GitHub，此举预计将帮助该公司迎接新一代开发人员。开发者的地位越来越
  重要，而他们却在远离大公司，面临开发者青黄不接这问题的，可不止微软一家。
** 2018-06-08
- [[https://mp.weixin.qq.com/s/ChflfgzUBIp17ruYaiEgAw][《暴风，下一个乐视？》]] 暴风如乐视一般紧随热点VR、AR、DT、AI竟是一个都没错过，
  甚至推出了自己的挖矿机——“酷播云”。只是乐视编织出来的梦境，连贾跃亭自己都相信，
  暴风却知道自己一直都是在“小打小闹”。

- [[https://mp.weixin.qq.com/s/Aiuf-6uFjHhxE4VpE-TZ_w][《互联网人必须要懂的“幸存者偏差”》]] 高考落幕，全国卷中的作文之一便是：二战时，
  著名数学家亚伯拉罕·瓦尔德要求美军战机在弹痕少而非弹痕多处加强防护。故事背后的
  就是“幸存者偏差”理论。或许这是也是一次对互联网思维的考验？

- [[https://mp.weixin.qq.com/mp/appmsg/show?__biz=MjM5OTAwNTQ0MA==&appmsgid=10000614&itemidx=1&sign=e8cb37209f321355142caadc30be6358&mpshare=1&scene=1&srcid=1217cN745xtJpQQDp8te7zNo&uin=&key=&ascene=1&devicetype=Windows+10&version=6206021b&lang=zh_CN&winzoom=1][《对于腾讯，你必须搞懂的任宇昕》]] 任宇昕，辽宁人，1974年，腾讯公司coo。随boss小
  马哥的低调，很多人尤其是圈外人都没听说过他。但有个事实摆在那：腾讯旗下七大事业
  群中，三个（IEG、OMG、MIG）都归属任宇昕统领。

- [[https://mp.weixin.qq.com/s/DiU2d-85BDVt4yg_t3hogw][《聚美优品的关键时刻》]]陈欧的聚美优品去年几乎只做了一件事：花钱。导致最后17年财
  报显示聚美全年亏损3698万元。其中聚美投资的对象主要是：共享充电宝——街电，电视连
  续剧——《温暖的弦》。投资这两样看似风马牛不相干的东西，聚美在想什么呢……
** 2018-06-07
- [[http://36kr.com/p/5137704.html][《7分钟搞定120年营销进化史，我们都去装大师吧》]] 营销学诞生于上世纪初，当时还只
  是经济学的一个分支，终于在上世纪中期才正式与经济学分离，那时二战结束不久，为了
  刺激内需各种营销理论频出，罗斯福甚至说出:“不当总统，就做广告人”这经典大忽悠。

- [[https://media.weibo.cn/article?id=2309351002534248000821127011][《快手、抖音，龙头决战就在今年》]] 同为小视频行业的两个头部app，快手和抖音难免被
  拿来比较，但其实你知道吗，在定位上抖音更像是一家制造流行的媒体，而快手则像是带
  有互动社区性质的朋友圈……

- [[http://www.tmtpost.com/3287698.html][《A站B站的同根殊途，折射出二次元商业世界的AB两面》]] 同样瞄准Z世代喜好的二次元市
  场，B站在纳斯达克上市当天市值就超过30亿美元，A则在快手的收购下勉强度过了危机。
  同样是新潮好玩最欢乐的垂直视频聚集地，并共同引领国内视频弹幕风潮，A站B站为何同
  根殊途？

- [[https://mp.weixin.qq.com/s/oxa2jJKujQOQNXEc9beY_Q][《除了拼技术，谷歌、微软、IBM都争相给AI搞价值观》]] 前段时间，谷歌迎来了史上最大
  的辞职潮与声讨，辞职的原因皆为谷歌与军方合作，可能将AI运用到武器的制作中。从中
  看出，民众对于新兴技术的担忧，在一定程度上关系到AI公司的发展。

- [[https://mp.weixin.qq.com/s/hOgxVwLdAovVew-kjUMRjQ][《海草式上网：如何拯救我们摇摆的注意力？》]] 多线程处理任务已成为新世代人类的基
  本技能，然而即使是一边听歌一边工作，注意力也有被分散的可能。那么要如何脱离多线
  程任务的习惯呢？或者如何让多心程任务更据效率？
** 2018-06-06
- [[http://36kr.com/p/5088657.html][《互联网的两极：阿里和腾讯为什么未来市值能达到1万亿？》]] 互联网应该是强者恒强，
  巨头公司们掌握了大量用户数据，能更快地尽心产品迭代和创新。宏观来看，会产生巨头
  与新公司见会有越来越多的信息不对称。然而围观去看，每出现一样新事物都会充满不确
  定性，比如这两天躁动的腾讯。

- [[https://mp.weixin.qq.com/s/VZ_DeJa0pzByc3PlAVs-ew][《公众号赞赏全新升级，微信的作者体系终于浮出水面》]] 腾讯的躁动一方面体现在微信
  近期的频繁变化。比如今天早上，“微信公众平台”发布公告《公众号赞赏功能升级》，
  宣布在iOS版和Android版微信上，作者可以直接收到读者赞赏。在公众号体系外，增添作
  者体系，运用“喜欢作者”按钮更牢的拴住读者和作者。

- [[https://mp.weixin.qq.com/s/As-ev5YFSGs1qiXb61Mxqg][《抖音的抖》]] 腾讯躁动也体现在对头条抖音的态度。抖音的异军突起，着实让很多人都
  张大嘴巴。不过仔细探寻下其实有迹可循，比如抖音里的“抖”就是充满用户交互设计思
  想的一字。

- [[https://mp.weixin.qq.com/s/g61sOv0UMhsASuuMtLO0lA][《头条已经没那么重要了 | 42章经》]] 由于今日头条发展得太成功，人们把抖音等后起之
  秀视为头条旗下，出现了一批冠以“头条系”的app。人们不知道的却是随着“字节跳动”公
  司的布局，头条已不是那么重要了……

- [[https://mp.weixin.qq.com/s/qi1Ib8sl5B1xSpGaOb86HA][《谁都想杀死微博 | 过招》]] 腾讯和抖音闹得风风火火，让本也应是抖音“头号对手”之
  一的微博显得低调很多，其实在腾讯复推微视之前，微博就一直在调整短视频布局，“微
  博故事”等竖屏内容的引进创新，让微博也被行业暗中关注。
** 2018-06-04
- [[https://mp.weixin.qq.com/s/joLSJO7vemjfkKzx8EAUIg][《短视频发展简史：从20分钟到15秒的新秩序》]] 人的器官对于刺激感到兴奋的阀值，被
  称作刺激阀值。电影电视剧成功以更多感官的刺激取代了文字，短视频则以更快的刺激达
  到人的刺激阀值，紧接其后的是小视频。

- [[https://mp.weixin.qq.com/s/hEWDjzZckO3lCUzxiVjp9A][《特稿 | 耶鲁校长在2018届毕业典礼上“画了一个圈”》]] 一个圈可以理解为一个人的自
  我边界，当一个人与另一个人相接触，两个圆就有了融合扩大的可能。看上去有点抽象，
  其实道理类似于中文中的“圈子”一词。

- [[https://mp.weixin.qq.com/s/RXpa32AH3lL4TrRPDqWBig][《小黄车快黄了》]] 6月1日，有消息称ofo由于资金链紧张，总部已经开始大规模裁员，同
  时高管层变动剧烈。消息传出后，却立马又有辟谣传出。虎嗅这次的消息，从多个内部员
  工处获得消息，或许能从其中窥出一些端倪。

- [[https://mp.weixin.qq.com/s/42FQ46tHDH0L9Hi-TYRnwg][《《西部世界》，能给现实世界的人工智能带来怎样的启示》]] 若将电视剧《西部世界》
  划一个分类，他将被划到“软科幻”一类。这类科幻不管科技理论的限制，直接让观众接
  受设定。在这样的设定下，能让观众直接对未来产生思考，比如：不在可信的人工智能。

- [[https://mp.weixin.qq.com/s/6eVBz6KOTT20Rm8WTOZjWw][《头疼大战，一场短视频刺刀见红的白刃战》]] 信息量十足。文章作者分析腾讯与头条之
  争，将从刚冒出一点点苗头，到如今的自媒体报道得热火朝天的文章整理了一遍。可以算
  是一本“头疼”大战的札记。
** 2018-06-01
- [[https://mp.weixin.qq.com/s/moDaYUlMKrH6QjYqNdTABg][《全网独家首发｜2018互联网女皇报告中文完整版来了！》]] 互联网的世界里没有国王，
  但却有位女皇。“互联网女皇”这个看似夸张的称号，只属于玛丽-米克尔(Mary Meeker)
  一个人。二十年来，她一直被视为互联网行业的诺查丹玛斯(大预言家)，同时，她与互联
  网领域几乎所有成功的投资人和创业者都建立良好的关系。不用水晶球，点开链接就可以
  看到女皇的预言。

- [[https://mp.weixin.qq.com/s/s4vGggboo-DsfL0U1VDFLA][《在不可描述的网站上打广告是一种神马体验？》]] 印度饿了么——Zomato在不可描述的网
  站上打了广告。理念是这样:看不可描述内容用户找不到一起吃饭的小伙伴是大概率事件，
  选择外卖也就顺理成章。效果拔群：单次点击成本，仅仅为1.98卢比。可是这次营销的结
  局并不是皆大欢喜……

- [[https://xw.qianzhan.com/t/detail/508/180601-8f1268c3.html][《硅谷产品经理与国内产品经理的3大不同》]] 中国互联网往往更看重商业应用创新，而美
  国互联网则往往是由技术创新引领。着重商业权衡，使中国产品经理会对一条产品线上对
  于业务进行思考和关注，不过对纵向长期的关注也导致国内产品经理定位模糊。

- [[https://mp.weixin.qq.com/s/a9SfGV84oPQoxPzWpfdx9g][《杀入娱乐圈的小红书》]] 小红书营造了这种氛围：演员林允的“口碑逆转”便是上佳案
  例。这个小红书上最爱记录画妆和卸妆的女星成功改变了“在微博被负面传闻包围”的局
  面，转型成为了“美妆博主”，如今小红书粉丝数已经超过了670万。明星们愿意主动分
  享真我，或是说塑造另一种人设。

- [[https://mp.weixin.qq.com/s/w32qaJFBJaU2__Q4HvW36g][《比特大陆残酷物语 | 深氪》]] 比特大陆在B3矿机的销售中给出了“一个账号限购一台矿
  机”的限定策略。这激起了小白矿工们关于“去中心化”的理想，然而这终还是个乌托邦，
  在残酷的比特大陆上，蚂蚁矿工始终是被碾压的那一个。
