#+TITLE:       汇总: 优质文章每日精华选(2021 年)
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-01-05 Tue
#+URI:         /blog/%y/%m/%d/everyday-reading-2021
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

微信公众号「卫夕聊广告」的作者组了一个微信群, 目的是每天挑选五篇当前最优
质文章,帮小伙伴们提升信息获取的效率和质量.

因每日发完文章列表后, 群里会有相关主题讨论, 时间一长, 再翻看历史文章就极
其不便,故起意将每日推荐文章列表整理到此, 方便随时查阅.

* 一月
** 2020-01-06
- [[https://mp.weixin.qq.com/s/Chd2P4AFMrw9gMnOtIrcWw][《字节跳动怎么都十万人了？》]] 到 10 万人，字节用了 8 年，阿里用了 19 年，腾讯还
  没到。2020 年，字节跳动的员工总数从 6 万蹿到近 10 万，一个主业在线上的公司有
  10 万员工，这在几年前还是件难以想象的事。企业家往往警惕公司规模过快扩张，其它
  公司往往二三十年才能达到的规模，字节跳动压缩到了八年，但没有任何迹象表明，字节
  跳动将因此按下暂停键。


- [[https://mp.weixin.qq.com/s/l6zdiK9AlLe3rqAcACNeEw][《95 后厂哥厂妹口述：富士康不相信爱情，昆山处处是“单身大神”》]] 没有人一直年轻，
  却一直有年轻人。全球有 18 亿年轻人，互联网让这一代年轻人拥有了前所未有的自我表
  达权利，有了与广阔世界无限接近的渠道。他们从网络中汲取养分，又用自己的创造力反
  哺这个繁荣的生态，从爱好到职场，他们的人生观和职场观与父辈有了显著的区别，那么
  该如何正确认识这一代年轻人？


- [[https://mp.weixin.qq.com/s/-Sb2l0ArSEeCG0G7VvhNRA][《体检异常率 99%，这届打工人的身体有多差？》]] 2021 年的第一个工作日，996 的工作
  模式又冲上了热搜。一边是现代人越来越看重养生，一边却是越来越普遍的亚健康问题。
  每年让打工人们最心惊的可能不是年终总结，而是体检报告，从 2013 年开始到 2018 年，
  上海白领的体检异常率从 94%上升到了将近 99%——基数非常大，异常率更是不断逼近
  100%。


- [[https://mp.weixin.qq.com/s/ufYMN1kH7kkbhZTMY3Xv1Q][《比特币暴涨，独家解密谁在控盘比特币？》]] 过去两个月中，比特币的资产价格飙升，
  引领了整个全球加密资产行业的牛市回归，种种迹象表明比特币已不在局限于小范围的资
  本游戏中。究竟谁在控盘比特币？最大的利益攸关方是谁？谁在其中谋取了最大收益？未
  来比特币筹码还将以怎样的格局继续流动？人们一直以来都在探究全球比特币持仓排行的
  疑问。


- [[https://mp.weixin.qq.com/s/cfuMC3TiDkTGtzY2aMG59A][《涌动2020 | 社区卖菜的隐喻和终局》]] 每次创新，都意味着一整批人的就业被消灭。中
  国的社会环境过去对创新是鼓励的，但在经历几年的贸易摩擦和今年的疫情冲击后，社会
  大众在 2020 年突然重拾了对创新的审视，尤其是那些专注提升“效率”，却无法兼顾“公平”
  的创新。因此，围绕社区团购的争议，会给“优先效率，还是优先公平”这个问题赋予新的
  答案吗？

** 2020-01-05
- [[https://mp.weixin.qq.com/s/VhwjGkcIDPpIJ8tOxMjTCg][《那些离开互联网大厂的年轻人》]] 在 BOSS 直聘发布的《2020 年 Q3 人才吸引力报告》
  中，互联网行业在人才吸引指数排名中依然位居第二，第一则是和它紧密相关的 IT 行业。
  与此同时，脉脉发布的《人才迁徙与流动趋势报告 2020》也指出 ，2019 年，互联网行
  业里出现了可见的人才流出。一群人争先入局，一群人失望离开，互联网大厂，已经成为
  这一代年轻人新的围城。


- [[https://mp.weixin.qq.com/s/obhpjxEKpQwuyZV9wIS00Q][《独家调查 | 虾米真的被阿里巴巴耽误了吗？》]] 11 月末，一则“虾米音乐即将于明年 1
  月关闭”的传闻，触发很多虾米用户在社交网络上抒发各自对于这个音乐流媒体产品的怀
  旧之情，同时也有很多人在表达不满，认为“虾米是被阿里巴巴耽误的”。但虾米真的被阿
  里巴巴耽误了吗？


- [[https://mp.weixin.qq.com/s/HfrEhxIpT9XQTKZOWaUTpA][《2020 互联网没有新故事，只有新品牌》]] 2020 年是疫情下艰难的一年，处在互联网未
  诞生新风口、未出现现象级 App 的档口，资本市场因为大环境遇冷而格外谨慎，互联网
  行业极度缺乏新故事，但很少有投资机构会甘愿错过投资新消费品牌的机会，甚至，也有
  不少投资机构主动下场创立新品牌。开年之际，我们通过 6 个关键词，来回溯盘点 2020
  ——新品牌之年。

-[[https://mp.weixin.qq.com/s/j8MYW_zn2BXKo4luvb3xgA][《国内互联网公司为什么加班这么狠？》]] 互联网人似乎越来越忙了。就在最近，快手宣
 布展开全员大小周，为鼓励加班，字节跳动也表示要给周末加班的员工开出两倍薪水。但
 加班带来的劳累，有时候会成压死骆驼的最后一根稻草，1月 3 日晚，拼多多的一位年轻
 女员工在凌晨 1 点半回家的路上不幸猝死。是什么，让互联网人不得不以透支未来的方式
 奔跑？


- [[https://mp.weixin.qq.com/s/dBmSAzgIG-mR6g0YeUGntg][《2021，字节跳动的营收能折腾出广告圈吗？》]] 想到字节跳动，可能大部分人的第一反
  应就是“有钱”，字节重新定义了信息生产、分发、消费的关系，步步为营，字节正逐渐打
  造出了属于自己的“字节跳动系”王国。毫无疑问，字节跳动已经是中国最大的广告公司了，
  但是除了广告外，增长点在哪里？

** 2020-01-04
- [[https://mp.weixin.qq.com/s/zhIYcCMmIa-ipsurcyke3A][《特斯拉扔出了一片“二向箔”》]] 补齐轿车与 SUV 这两个最主流车型后的特斯拉，开启了
  中国本土化的新篇章。国产版 Model Y，使得特斯拉在包括燃油车在内的整个汽车市场竞
  争力大增，对比其他国产 SUV 新能源车，也是碾压级的存在；新品上市的同时，等于也
  顺手向中国汽车扔出了一片“二向箔”。特斯拉中国本土化策略由此迈入 2.0 时期，更紧
  张的贴身肉搏战揭开帷幕。


- [[https://mp.weixin.qq.com/s/DhVorf4GIqnbqXTVguY_Ww][《猝死、大小周、996：当互联网变成劳动密集型产业》]] 1 月 3 日晚，多多旗下多多买
  菜员工在凌晨一点半下班路上猝死，年仅 23 岁。有一个不可否认的趋势是，互联网对员
  工时间的挤占、对员工身体与心理造成的负担，已经成为互联网“造富”光环之下的灰暗一
  面。互联网人的工作时间正在不断延长，“996”正在取代 8 小时工作制，“大小周”也正在
  取代“双休”制度，互联网正在走向劳动密集型产业。


- [[https://mp.weixin.qq.com/s/1t2ayNR_HLSQY9fGfXpoMw][《为什么所有的 APP 都在炫富？》]] 你有没有这样一种感觉：无论打开什么 APP，都有人
  在展示自己的富裕生活，营造出一种“众人皆富你独穷”的氛围，可以说有社交的地方就有
  炫富。APP 们在变味，用户能感觉出来，从微博到知乎，从抖音到 B 站，从小红书到大
  众点评，为什么有内容分享的地方就有炫富？


- [[https://mp.weixin.qq.com/s/BN7uMLwEWdRxYXWCs1YfIQ][《榜单 | 真故 2020 年最值得阅读的 10 篇故事》]] 2020 年是一个宏大的话题，记叙
  2020 年的容器则是一个又一个渺小的个体。今天的推送中，编辑部票选出了 2020 年真
  故最值得阅读的十篇文章，并附上了推荐理由，作为记住 2020 年最后的仪式。2021 年
  我们依旧会坚持拾取、记录当下，跟我们一起，继续与真实为伍吧。


- [[https://mp.weixin.qq.com/s/Nn_b9Lv43xLFt9bY_pSwsA][《估值为什么是一种艺术而非科学 | 巴伦读书会》]] 无论是企业管理者还是普通投资者，
  都需要培养自己的金融直觉，以做出明智的金融决策。那么对于做出正确的金融决策来说，
  哪些才是最重要的财务数据，应该如何理解金融数据背后的意义？《什么是金融》总结了
  哈佛商学院金融学教授米希尔•德赛的在线热门 MBA 金融课程内容，本文整合《什么是金
  融》，解释了为什么估值是一种艺术而非科学，或者说披着科学外衣的艺术。
