#+TITLE: 优质文章每日精华选(2019)
#+DATE: <2019-01-02 Thu>
#+options: toc:nil num:nil

* 一月
** 2019-01-08
- [[https://mp.weixin.qq.com/s/YRByQPAgK3fTsWsNtqxCxQ][《繁荣抖音背后，焦虑的底层内容工厂》]] 一家 2018 年营收几千万的 MCN 负责
  人李祥（化名）表示，抖音下半年已经非常难做了，涨粉难是一方面，更让他没
  安全感的是，流量分发完全掌握在平台手里。据他测算，1000 万粉丝的大号，
  平台推送的粉丝可能连 1% 都不到……


- [[https://mp.weixin.qq.com/s/meKEDTS7D_NFBFCzjQnq0A][《中信出版 2018 年度好书榜》]] 2018 中信出版年度好书榜终于出炉！在本次年
  度好书的评选过程中，收到了来自全国各地读者的一千多封「推荐书评」。2019
  年，希望我们可以一起阅读更多优秀的好书，共同体会读书的乐趣与力量！


- [[https://mp.weixin.qq.com/s/HbBba5hiE_HO19c5Z_y7qw][《特斯拉 Model 3，或是重构汽车产业的那个车型》]] 如果整个电动车时代确如
  所料来到这个世界，若干年以后回望，也许 Model 3 的影响力可望企及福特 T
  型车。


- [[https://mp.weixin.qq.com/s/nuj55SowSu9I5vNoxTUIWg][《2018 年的海外播客圈复盘：泡沫破裂之后，音频下半场生意怎么做？》]]
  Nicholas Quah 是尼曼实验室 Hot Pod 栏目的创始人和作者，Hot Pod 是专注
  于报道播客节目相关新闻的通讯。Nicholas 回顾了 2018 年播客圈的热点话题：
  播客泡沫是否真的存在？老牌广播公司与新入局者的关系几何？哪些问题值得我
  们在新的一年继续跟进？


- [[https://mp.weixin.qq.com/s/jc8hEgCJdZj5Wr6hjBgSnw][《我们和 20 位顶级投资人聊了聊：2019 年的机遇与残酷，确定和不确定》]] 过去
  几个月，被反复提及的几个概念包括：移动互联网红利结束、创业黄金时代告终，
  以及已被高举但尚未达成共识的产业互联网。步入下半场，投资机构们对产业互
  联网定义各异，确定的是这一年会充满挑战，不确定的是人们面对挑战的信心。
** 2019-01-07
- [[https://mp.weixin.qq.com/s/YuJJL5QsBgcMHz3vOBfNAw][《周鸿祎：所有的商业模式都是试出来的》]] 本文为国民级产品打造者、360 集
  团创始人兼 CEO 周鸿祎倾囊相授从 0 到 1 打造爆品的实战指南《极致产品》
  精华笔记。所有的商业模式都是试出来的，重点在于试错的成本是否在你能够接
  受的范围内。


- [[https://mp.weixin.qq.com/s/dVxdvZ-O7CjQexZF9dsDSg][《"员外郎“王林清》]] 1995 年，91-1 班王林清考研失败了。次年，烟台人王林
  清考入烟台大学法律系……26 年后，“书读多了，不懂人情世故。”这是是对王林
  清最大的恶评。这句话曾经被一个人用于当面斥责王林清，远比“员外郎”的调侃
  来得恶毒。


- [[https://mp.weixin.qq.com/s/HCmlCQwGJihOPQ88u9IMgQ][《2019 CES 观察 | 一届“求生欲”很强的消费电子展》]] 对于我们这些普通观察
  者来说，报道 CES 与其说是期待上面会有些什么新玩意，不如说是借个机会各
  自总结上一年的硬件行业趋势，并预计下一年会发生什么。


- [[https://mp.weixin.qq.com/s/O5yKZXAFZ2ICKmMltVkohQ][《现代社会的“电车难题”：自动驾驶系统在意外来临时会撞向谁？》]] 闻名于哲
  学界的“电车难题（Trolley Problem）”在自动驾驶汽车时代”将不再只是一个哲
  学问题，而是每一个自动驾驶系统需要面对的真实问题，系统将决定在发生事故
  时撞向谁、保全谁。


- [[https://mp.weixin.qq.com/s/GO-48lTh0lKZ03W8BOd4JA][《国王的新衣：自媒体流量造假乱象》]] 从门户网站时代甚至报纸时代开始的以
  数字为唯一驱动的坏习惯，伴随着商人追求曝光与名声的天性——尽管如今网信办
  与平台自身整顿数次，自媒体经济也逐渐从几年前的资本红利期走向冷静，但买
  流量仍然是业内常态。
** 2019-01-04
- [[https://mp.weixin.qq.com/s/riw2rye54IopziBDe4yPOQ][《公众号的 2018》]] 公众号的 2018 到底过得怎么样呢？新榜为此梳理了年度回
  顾 H5 背后的大数据，从中我们多少能窥见一二。18 一整年，公众号发文总篇
  数超 1.7 亿亿，其中原创文章约 872 万万篇，占 5%。


- [[https://mp.weixin.qq.com/s/vUK1o3m8ak4iJE-21-b0JQ][《我如何成了腾讯架构调整的炮灰》]] 这是一个因腾讯内部矛盾而遭受重创的创
  业故事。这不是一篇标准的商业报道，更像是一则商业控诉。虎嗅思考再三还是
  决定将其刊发出来，原因有二：其一，创业不易，尤其是在当前这个市场环境中；
  其二，从这个案例中我们可以窥探出腾讯内部各个部门复杂的利益纠葛，以及跨
  部门协作的难度。


- [[https://mp.weixin.qq.com/s/Ihi6g_AFlHeQ2uho4CVf2g][《共享经济大败局》]] 作为共享经济的鼻祖，Airbnb 创始人布莱恩•切斯基一定
  没有想到，他以 Airbnb 为依托推崇的共享经济于 2018 年在中国市场上遇到了
  前所未有的挫折。我们很难把共享经济的衰退简单归结到一个原因。


- [[https://mp.weixin.qq.com/s/sSR_DC2nv7t-H-Dta4IY1A][《2018 游戏行业报告：游戏出海、女性玩家、游戏直播成关键增长点》]] 2018
  年中国移动游戏市场依然保持增长，但对比上年增速出现快速下滑，销售收入增
  长放缓。这主要受用户需求改变、用户获取难度提升、新产品竞争力减弱等因素
  影响。


- [[https://mp.weixin.qq.com/s/HLUqfFaE8jiioVL-gfGsDg][《震荡创投圈：“钱荒”来袭，资本市场步入调整期》]] 募资难的阵痛已经传导到
  投资端，投资机构二八效应明显，战略资本开始收缩，一二级市场估值倒挂，钱
  荒笼罩着整个创投圈。公司们冒着破发的风险扎推上市，8 家公司同一天 IPO 敲锣
  的港交所奇景，或许是这场恐慌情绪的最佳诠释。
** 2019-01-03
- [[https://atlas.yidianzixun.com/hotevent/page?id=5c171c7cc1d19e004a9b80f5&yidian_docid=0Kr6wSXX][《2018 中国上市公司盘点》]] 2018 有一批科技公司集中上市，尽管这些公司上
  市地点不尽相同，也不一定都是中资企业，但有一点是相同的，那就是它们都已
  中国市场为根基……


- [[https://mp.weixin.qq.com/s/nEytmgfy8qeusC_wc3pQKQ][《围剿 Netflix》]] 今影视节目占据了整个互联网下行流量近 58%，其中仅仅是
  流媒体平台 Netflix 就消耗了全球 15%的网络流量，是全球下行流量的最大贡
  献者。观看网络视频已经是如今最常规的休闲娱乐方式之一，而这恰恰也是流媒
  体平台们最好的机会。


- [[https://mp.weixin.qq.com/s/w2ceA9oe1R6UxrOxbC-DRQ][《中国人工智能产业全貌 都在这张 AI 势力范围图》]] 2018 年，区块链的浪潮
  和共享单车的大起大落，却一度让人工智能黯然失色、星光不再。这并非坏事，
  远离了喧嚣泡沫，资本寒冬到来后的 AI 行业更加脚踏实地，无论科技巨头还是
  创业公司，寻找基于自身技术能力和特点的应用场景成为重中之中，“落地”是这
  一年的主题。


- [[https://mp.weixin.qq.com/s/nN40qpzDWhwCjVB-tQjoEg][《苹果 CEO 致信，中国区成为滑铁卢，下一个「iPhone」在哪里？》]] 高速增长
  的大中华区怎么了？16 年来首次下调营收预期，也是 iPhone 推出以来的第一
  次，这对于苹果并不寻常，库克公开信中提到此次调整的原因主要有 4 个.


- [[https://mp.weixin.qq.com/s/tS39FSBkfHTWyIug7_7a8w][《盘点 2018 年最热门的 10 大增长黑客策略》]] 今天，“增长”依然是互联网圈最火
  的词，而增长策略也在慢慢脱离“野蛮时期”，更加注重产品本身和用户体验。我
  们觉得有必要为大家分享下过去一年的研究：彦哲@增长黑盒就来为大家一一拆
  解 2018 年国内最热门的 10 个增长黑客策略
** 2019-01-02
- [[https://36kr.com/p/5170184.html?from=singlemessage&tar_foid][《张一鸣的 APP 工厂》]] 抖音是唯一，成为抖音的路径却不唯一。这家公司批量
  生产 APP 能力如此之强，而且历史成绩显示，核心产品成功的概率很大。欢迎
  来到张一鸣的 APP 工厂。


- [[https://mp.weixin.qq.com/s/iPQ-fa-9WWGne9imMt_p2Q][《罗振宇跨年演讲 4 小时讲了什么？记住这 4733 字》]] 不同于吴晓波的宏大叙
  事，这一次罗振宇把视角对准了个体命运，用他自己的话说，“关注大环境里个
  人的行动策略”。罗振宇全场演讲 4 个小时，信息量有点大。以下是作者梳理的
  演讲精华——罗振宇的“七个主义”


- [[https://mp.weixin.qq.com/s/rNzApAqPZFfZniEurfDZ0w][《灾年：我看 2018 年》]] 每年 12 月 12 日，日本汉字能力检定协会都会在京
  都清水寺公布当年的年度汉字。2018 年的年度汉字是——灾。而这个字简直是为
  2018 年的中国互联网量身定制的，2018 年的中国互联网，当得起这个“灾”字。


- [[https://mp.weixin.qq.com/s/EqyqodFU0frJ4ADLAyMcHw][《海外支付大战》]] 《日经新闻》报道，腾讯将与日本即时通信平台 Line 合作，
  为日本小型零售商提供移动支付服务。而顺应移动互联和数字化支付趋势，银联
  国际也在悄无声息地加快境外移动支付布局，并拉起了豪华朋友圈一起发力。


- [[https://mp.weixin.qq.com/s/tOWfGsZFPBRjo_cFnxEN7w][《罗振宇吴晓波跨年演讲里的几个小错误》]] 谁能想到，卫视跨年晚会的竞争对
  手不是电视台或视频网站的歌舞演唱晚会，反倒是颜值一般的中年小男人的鸡汤
  演讲，这个世界真的有意思。感觉挺好的，但是里面有几个小错误小瑕疵……
