#+title: 优质文章每日精华选
#+options: toc:nil num:nil

微信公众号「卫夕聊广告」的作者组了一个微信群, 目的是每天挑选五篇当前最优质文章, 帮小伙伴们提升信息获取的效率和质量.

因每日发完文章列表后, 群里会有相关主题讨论, 时间一长, 再翻看历史文章就极其不便, 故起意将每日推荐文章列表整理到此文章, 方便随时查阅.

** 2018-08-31
- 《中国游戏监管史》可曾想你可以在国内买到正版的《生化危机2》？在很长一段时间里，
  国内游戏市场处在一个监管力度非常弱的环境中，游戏行业都十分熟悉的审查制度在当时
  还没有建立，游戏沿用的是图书出版物的审查流程——只需要出版社的自审即可上市。
  https://mp.weixin.qq.com/s/ZPPLna_VHhzSYMQWZ6zleA

- 《学而思15年：野蛮生长的补习班与中国家长焦虑症》“学习改变命运”是学而思的第一
  句价值口号，也是深深烙在中国家长心中一段“咒语”。教育依旧是阶层跨越的唯一可控
  途径。从零开始到今天的教育巨无霸，学而思这15年的江湖，恰是一场中国社会跨越阶层
  的持久战。https://mp.weixin.qq.com/s/Q9jxcak6d3nSTT1yQeFmtw

- 《厌倦微信，拒绝陌陌，现在「地图社交」给你一种新方式 | 36氪新风向》通常基于
  LBS 的社交软件，会优先展示附近的人并显示距离，但数字给人的感觉却不如直接显示他
  所在学校、小区或者街道来的直观，而视觉上的直观一定程度上可以带来心理上的亲近感。
  加入熟悉的互动场景这是地图社交的一种思
  路……https://mp.weixin.qq.com/s/tYRaYJ68oVq2ClDeGTtXcw

- 《读者消费升级，自媒体的烦恼 》从前在微信或是今日头条上开个订阅号，就能轻松获
  得不菲的广告收入。不过如今，大多数自媒体账号持有者都会告诉你，虽然订户仍然很多，
  但他们打开文章的欲望正在下降，快钱不那么好挣了。当初期近乎盲目的热情消退后，一
  个行业可能才会真正迎来良性发展。
  https://mp.weixin.qq.com/s/ztoaAilt60g_4_8CrBWusg

- 《既练轻功也练内功——面对风口的正确姿势》公众号的福利退去后才显示出自媒体该有的
  样子，不过仍有人懊悔：为什么我没赶上公众号的福利？为什么错过风口的总是我？如何
  正确面对风口？这是一个极其复杂的战略战术问题！在这篇长文中，卫夕只提供一些最基
  础的原则……https://mp.weixin.qq.com/s/mRU6jliTqBtLFc3kSTd7gg

** 2018-08-30
- 《微商金字塔崩塌：普通代理消耗朋友 财富属于金字塔塔尖》加他一次微信999元，郑九
  洲是深圳落地荟服务社群的联合创始人，工作是给想要在微商行业里发财的从业者提供建
  议，他从不直接卖货，而是制造了一个物欲世界。他们通过放大人们对权贵与生俱来的渴
  望，从而构建起自己的微商网络。
  https://mp.weixin.qq.com/s/NQfJXsiSODGu0vVR7-1Aug

- 《如何给美团进行估值？》我们认为美团的估值，最高可达到645亿美元。而在美团的收
  入当中，外卖是最大的一块资产，占收入总额的62%以上。我们就讲一下这部分的互联网
  基因……https://mp.weixin.qq.com/s/RF8TPfrHSQ5Qc6GPUPeuXg

- 《抖音最红的城市，为什么都在西部？》城市得到的曝光率在抖音上重新洗牌，凡在抖音
  上火起来的城市，无一属于一线城市阵营。城市注意力被移动互联网重新分配，身在一线
  城市的用户，也更愿意把目光投向精彩纷呈的二三线城市。西部城市在抖音上更是红得发
  紫。https://mp.weixin.qq.com/s/PtLwfR9OiXu5lRDs6YwH5A

- 《流量造假成风的年代，如何甄别真假博主？》作者连续几天观察发现，10万+的阅读中，
  凌晨2点到6点，阅读量飙涨一大半，但点赞数据在第二天上午才开始上涨，很明显的刷量。
  人人都可以创富的环境下，数据造假者一个比一个凶猛。从早期的微博，到微信公众号、
  抖音、小红书等平台，反正有人的地方，就有真假。
  https://mp.weixin.qq.com/s/zzKGdSUdlRhdyvWIFswu4g

- 《创业、艺术家和量子物理》她说有两种人真正能称得上好的创业者：一种是像画家一样
  去激情地创造产品，技术不技术的无所谓，用户觉得好用才行；另一种人是脚踏大地的技
  术问题解决者，让不可能变得可能，让困难变得简单。一面是艺术，一面是量子物理。
  https://mp.weixin.qq.com/s/7EsyvEFrS0U00xoQxmhkLg
** 2018-08-29
- 《从千亿跌至百亿，只用了一年！Q版“腾讯”到底做错了什么？》2016年底，美图在港
  上市，成为了继腾讯之后12年来香港最大的互联网IPO，董事长蔡文胜曾说，美图是迷你
  版的腾讯。然而谁都没料想到美图坠落地如此之快。更糟糕的是，时至今日，美图依然没
  能意识到问题出在了哪里……？https://mp.weixin.qq.com/s/NfHP1B015t_Qyy34flpW8A

- 《Magic Leap的“虚拟梦境”，终于梦碎了》由 Google、阿里、A16Z、高通、凯鹏华盈
  等顶级公司和机构大手笔联合投资的混合现实 (Mixed Reality) 技术创业公司Magic
  Leap的“虚拟梦境”，终于梦碎了。可能又要恭喜又一批投资人：花钱打水漂，买了个教
  训。https://mp.weixin.qq.com/s/iEEvxYb7TcAEmnY6MojUdg

- 《淘宝15年后「二次创业」：突出设计，押注原创》在价格、品质和功能保持平均水平的
  基础上，如果能设计再稍微往前突出一点，设计就会成为商品的最大的卖点。这个商品，
  往往会在淘宝上特别受欢迎。淘宝降低店铺的门槛，目的就是为了突出这些设计。
  https://mp.weixin.qq.com/s/rIOsRlPzjbdjo_FDypmH0g

- 《为什么说大多数ICO都是诈骗？》区别于IPO [4] （英文简称Initial Public Offering）
  首次公开发行，ICO（Initial Coin Offering缩写），首次币发行。都有着以股份换集资
  金的概念，而他们又有什么不同，为什么说ico都是诈骗?
  https://mp.weixin.qq.com/s/rO77mEwRNHg9_EGeLH6ZxQ

- 《一位连续创业者复盘的支付简史：对手毁灭你，但与你无关》在那个时代的创新举措不
  叫支付，叫代计费。2001年，中国移动发布“移动梦网创业计划”，通过扣除话费来缴费，
  电信运营商实际上可以充当支付通道的角色。但在2008年左右，随着移动互联网兴起，这
  就变成了被新技术革命掉的行业……https://mp.weixin.qq.com/s/FnHdmwUHBav_TJLxjr1VtQ
** 2018-08-28
- 《消费降级是否会催生“降级”品牌？》谈得上降级品牌，优衣库算一个，那小米呢？投
  资人子柳在《小米是一家什么公司？》一文中提到，小米和优衣库两家公司很像，“‘优
  质低价’正是优衣库的产品理念，想这么做的人很多，但这两个词是相互矛盾的，真正做
  到的我只看到优衣库一家。” https://mp.weixin.qq.com/s/66YdYTcSQr4yjknxnMkSqg

- 《一个小思考：为什么大家都不喜欢“罗氏交互”》先下一个定义：“罗氏交互”，泛指
  要求用户调用各种感官、肢体进行运动（感官/肢体≥2），才能完成的交互方式。代表作
  有今年5月15日发布会上发布的TNT以及本次发布会上的无限屏。但大家对包含着未来美好
  愿景的“罗氏交互”似乎并不买账……
  https://mp.weixin.qq.com/s/YilXyXNtJDXCg6dQH7di-Q

- 《支付宝“扫盲”东南亚》2017年7月，腾讯就申请到了马来西亚的第三方支付牌照。然
  而在2017年上半年，菲律宾本地电子钱包GCash的办公室里来了一群中国员工。这群中国
  加班狂来自蚂蚁金服。https://mp.weixin.qq.com/s/OHAJeES7we0QoKGBXeupCg

- 《明星转战短视频》2018年以来，短视频平台的影响力提升和主流化速度越来越快，有两
  个表现：第一，国家部委、地方政府的政务号大批入驻快手、抖音两大平台；第二，社交
  形态的更迭明星比普通人有着更强的嗅觉，哪里有流量、哪里有注意力他们就走向哪里，
  这一波他们涌向了短视频。https://mp.weixin.qq.com/s/Eh0ytEs-M3eGKtTtAqRdWA

- 《实地访山东新媒体村：农妇做自媒体收入破万 平均工资比上海还高》现在，一支不一
  样的留守妇女军团出现了，她们每天与电脑为伴，在鲁北农村拿着一线城市的收入填补家
  用，家庭话语权也变得硬气起来。她们上班的地方，就是她们的家乡，不用担心住房，也
  不用担心孩子教育。她们做的便是自媒体，收入最高者，一个月拿了1.5万。
  https://mp.weixin.qq.com/s/Kvxdzd4GDRitEUuKrEvk1g
** 2018-08-27
- [[https://mp.weixin.qq.com/s/DeBzk80xybDMXOII5Prd6w][机器短信你会点广告: 写给普通人的CTR预估科普]]

- 《是子弹短信真那么好用？还是逃离朋友圈的欲望太骚动》8月20日的锤子科技发布会没让
人太记住新手机的特点，反倒让子弹短信出尽风头。一周过去，子弹短信仍然是App Store
免费排行榜的第一名。人们在脱离微信？
https://mp.weixin.qq.com/s/F-PgHZ55TpROzqeGWNODaQ

- 《40岁的于正，想要收获尊重了》于正似乎翻身了。他担任制作的《延禧攻略》里一路开
  挂的女主角魏璎珞显然给他带来了好运气，好口碑让他有底气打开弹幕，在夸赞中享受逆
  袭快感……https://mp.weixin.qq.com/s/yawxhPpLJ6XA9wUK9PvDqA

- 《小米想革新广告业，能成功吗？》一线互联网公司都有自己的广告营销模式，可小米与
  BAT们有所不同，它主要通过硬件获客，别人获客需要花钱，它却还能赚钱。流量被小米
  及其，不再流动。https://mp.weixin.qq.com/s/3WNUT0GMQnU3yEtJkA9CiQ

- 《全球社交媒体遭遇中年危机，下一个用户增长点在哪里？》Snapchat Q2 的财报显示其
  日活用户数达到17年来首次下滑。对比 Facebook 和 Twitter 在面对隐私泄露和外部监
  管等等危机而笼上的阴霾，《卫报》和《纽约时报》分别刊文提出了疑问：社交媒体的增
  长是否已经到达了顶峰？
https://mp.weixin.qq.com/s/j2lCpeyiOUiCBGhJqKg-hQ

- 《有品质的写作是最高效的社交》潘乱的《腾讯没有梦想》微信后台阅读过100万。文章
  击穿了整个行业引起媒体大讨论，创造了一个公共议题。如果科技财经媒体也有像学术论
  文那样的单篇文章引用指数的话，2018年度被引用次数第一肯定是它。
  https://mp.weixin.qq.com/s/SM6KUqTqtF6YcW6rIjl_WQ
** 2018-08-24
- 《可遇而不可求的李子柒终于商业化：田园视频造梦，食物走向市场》8月初，李子柒在
  微博告诉粉丝：李子柒旗舰店正式营业。这一支品宣视频的转发量也能超过10万次，评论
  量超过8万，点赞数突破30万。已经趋于艺人化的经营和发展，有非常强的商业IP价值。
  https://mp.weixin.qq.com/s/V8zxgzoNGU_6Or5xNpxZmA

- 《骗人要趁早？扒一扒福布斯中国30岁以下“掺水”精英榜》一周前，号称国内自主内核
  的红芯浏览器获得2.5亿融资，随后被爆出山寨黑幕。而红芯（原云适配）背后公司联合
  创始人高婧则上了一个榜单，全称叫做福布斯中国30位30岁以下精英
  榜……https://mp.weixin.qq.com/s/o8-wY3YXo1WTRYZZII_8gg

- 《中国电商往事》二十年，马云、刘强东、王峻涛、邵亦波、郭凡生、雷军、李国庆、陈
  年、黄峥，这些熟悉的、陌生的名字，或登上财富巅峰、或黯然离场。二十年，旧的故事
  还在继续，新的故事已经开始上演。
  https://mp.weixin.qq.com/s/lTav1QaEmy0Jk4slG1XQMw

- 《上市，退市》不止中国，美银美林银行年初预计，2018年IPO的美国科技初创企业多达
  50家，远超前两年。然而，在全球互联网公司的上市潮中，也有着一批退市的公司，有如
  特斯拉……https://mp.weixin.qq.com/s/_p3JprOpoeBhvcHfcai2eA
** 2018-08-23
- 《区块链媒体微信号被“团灭”：人人都想身价破亿，但财富自由是一碗毒鸡汤》前日，
  深链财经、金色财经网、火币区块链、火币资讯、币世界、吴解区块链等一批区块链&币
  圈自媒体微信号被发现遭微信官方封禁。而被封的他们表示，这一次寒冬只会让他们更强
  大……https://mp.weixin.qq.com/s/adVHxSVeOW66my5IDN7nPQ

- 《存量战争》目前存量的争夺，最典型的就是阿里和京东。两家日常的新货电商业务占据
  中国市场的八成以上，介于中国增量市场天花板已经到顶的局面下双方只得冒险争夺对方
  手中的存量寻求业绩突破，而当前最大的存量机会来自二手市场。
  https://mp.weixin.qq.com/s/4EBV4ljP5FIJIbKE6wWauQ

- 《抄底腾讯？》作者把股票分为三类，第一类股票超跌可以抄底，第二类要冷静分析，第
  三类即便到“地板价”也不要碰，地板下是十八层地狱。那腾讯属于哪一类，可以抄底吗？
  https://mp.weixin.qq.com/s/a5NovYSMkMdD-ftbIncneg

- 《王信文 | 让暴风雨来的更猛烈些》赌博赢钱的人常常把赢钱归因为自己赌技超群，而
  忽略运气因素。越赢钱，越觉得是自己牛逼，越要加注。直到突然发现运气不在，输到血
  本无归。股市是这样，币圈也是这样。
  https://mp.weixin.qq.com/s/SRmjHZjdz77QazU0qeaRLQ

- 《广告业已经是夕阳产业了吗？》麦迪逊大道是纽约曼哈顿区的一条大街，美国许多广告
  公司的总部都集中在这条街上, 因此麦迪逊大道逐渐成为了美国广告业的代名词，现在这
  条街要拆迁了。互联网公司正在瓦解传统广告业。
  https://mp.weixin.qq.com/s/L98YI_gY-ZTCLgcFxdWgTQ
** 2018-08-22
- 《「网易人格测试」刷屏朋友圈，套路你都知道，为何还中招？》昨日，网易云的人格测
  试再次刷屏。其实刷屏的爆款来来回回招数就这几样，为什么我们偏偏都愿意吃这套？说
  白了，这是用户和品牌之间一场心照不宣的“合谋”，用户要人设，品牌要转发量。
  https://mp.weixin.qq.com/s/9Zk6o77P8E3fO-h0XjNQ3Q

- 《信息流江湖未定》网络广告市场正在迎来一个新变化，一是信息流广告的比重和比例正
  在提高，二是互联网广告即将结束高速增长期，效率竞争将取代增量竞争。从长远来看，
  在线广告依然是BAT三家的主流战场，并且随着时间的推移，其门槛和难度也会不断加大。
  https://mp.weixin.qq.com/s/U6JQ55aGKK7BmTAcpFPV0g

- 《智能手机零和博弈：用户的换机奥秘与厂商的中年焦虑》在整理分析了约800万条换机
  行为记录后，今日头条发现了一些秘密：比如三星、锤子、魅族正在被自己的老用户抛弃；
  华为与苹果已经开始正面交锋；OPPO、vivo推出高端品牌其实另有图
  谋……https://mp.weixin.qq.com/s/9OPO6L9A1z0AnSev99i68Q

- 《东南亚何以成为中国技术公司的淘金圣地》600年前“郑和下西洋”的故事里，船队首
  先抵达的一个叫麻喏八歇国的地方，正是印尼境内的爪哇岛。现在，大批的中国技术企业
  也是遵循相同的轨迹，演绎了一个全新版本的“下南洋记”。
  https://mp.weixin.qq.com/s/mD0VcQFrPNRgJ_svUGDH5Q

- 《攒局者马云》马云擅长攒局，但不是饭局。过去几天最热闹的事儿是马来西亚总理马哈
  蒂尔·穆罕默德到访中国，他首站选择了杭州，选择了阿里巴巴。毫无疑问，马云扮演了
  中马交流的使者。https://mp.weixin.qq.com/s/_YggCL43xMqCMimmgCgasQ
** 2018-08-21
- 《百事可乐70年代的逆袭：我买的不是可乐，是理想中的自己》上世纪70年代，可口可乐
  统治了美国市场。百事可乐深知，单从产品上无法与可口可乐抗衡。因此百事充满了革命
  色彩的，做出了有史以来第一次，品牌把注意力放在消费者身上。这个决定几乎是标志性、
  历史性的举动。他们说“不要再把重点放在产品本身上，我们把重点转移到用户身上。
  https://mp.weixin.qq.com/s/0cFqB937RkZhWv_dcw9dWw

- 《办公遇上社交，腾讯文档如何用4个月拉来1600万月活？》四个月前，腾讯正式推出腾
  讯文档，对标去年11月份被今日头条领投的“石墨文档”。截止目前腾讯文档的月活已经
  突破1600万，实现千万量级，其不过用了4个月。腾讯是如何杀入文档竞争的？而1600百
  万这个数字大都是c端用户，未来的腾讯文档该如何发展？
  https://mp.weixin.qq.com/s/qPfgHIdzdZ4Wz1JFGR-p2g

- 《房租上涨，资本无罪》最近卷入舆论漩涡中的自如、蛋壳却颇受资本青睐。前者年初获
  得40亿元人民币的A轮融资，刷新中国长租公寓行业单笔记录。后者则在上半年完成两轮
  融资，合计1.7亿美元。然而，资本青睐一定与房租高低有关系吗？
  https://mp.weixin.qq.com/s/YPczXl3OZBqrVhl18RR3tw

- 《区块链火了这么久，为什么我们能用到的 DApp 还是没几个？》区块链近期的火热，多
  源于其被过分夸大的金融属性。随着今年上半年金融有关部门的联合打击、区块链行业的
  自律和投资者的日趋冷静，区块链逐渐走向了应用化的「正途」。最终“区块链到底能不
  能实现普通用户的互联网应用场景？” 先说结论：能实现。
  https://mp.weixin.qq.com/s/GewD-H7yj7brdudN1YIivA

- 《一个传销的神女子教会我的用户拉新和留存》一个由很有趣的故事所探究出来的干货，
  一位传销大姐的分享有体系、有套路、有实例、有干货。进来看看一看有病治病，没病防
  身，不仅可以防骗，好多招数拿来用在写公众号，都是好使的。
  https://mp.weixin.qq.com/s/BoFFzalB6m3ZWiT0ZC6XZw
** 2018-08-20
- 《六年，公号改变命运》故事开始于2012年八月，微信公众平台诞生，六年间，它孵化出
  超过2000万个大大小小的公号，彻底改变了内容传播的生态格局，也彻底改变了很多人的
  命运。那时的咪蒙还在《南方都市报》副刊工作，罗胖刚发出自己的第一条60秒语音。到
  如今……从写文章到成名、变现，从未像这样直接。
  https://mp.weixin.qq.com/s/BO211JD01XLbV3ZNtjkHXw

- 《上海不相信互联网》据《中国互联网发展状况统计报告》，在102家互联网上市公司中，
  注册地上海的占比18.6%排名全国第二。乍看来，上海互联网行业发展总体上是好的，甚
  至远超杭州，深圳。但这数据像极了老底子上海人所说的：表面光鲜，外套一脱吓死人。
  https://mp.weixin.qq.com/s/ekD6daXqnxF4WLcxn7F9Bg

- 《中介风云：左晖与姚劲波的百亿美金豪赌》你可能不知道左晖，但你很难不知道链家，
  因为它到处都是。如今在大小街头上，能跟链家拼门店数的只有兰州拉面和沙县小吃。有
  趣的是2015年07月13日，百度发生了一件怪事，中国最大的搜索引擎搜任何关键词出来的
  东西都是链家的广告信息，这让链家在互联网界赚足了鳌头。
  https://mp.weixin.qq.com/s/8Rdaly1kHntyUAie8R6uVg

- 《负矿《爱情公寓》》在《爱情公寓》电影上映之前，这个ip即使背负着抄袭的名头，还
  有超6成网友支持编剧汪远，还是有多年死忠粉们热切期待着《爱情公寓》电影带他们重
  走青春路。但《爱情公寓》电影直接给这一伤痕累累的IP进行了休克疗法，“爱情公寓”
  的人设彻底崩了。https://mp.weixin.qq.com/s/IjhDKvHjpwZQXq1vNTEavA

- 《蔚来上市到底开了个好头还是坏头》如何评价蔚来？有人说：从退出摩拜单车到建立蔚
  来社区，他依然在尝试连接用户的线上和线下。摩拜的李斌，李斌的蔚来，应该就是一家
  披着新造车企业外衣的互联网公司吧。
  https://mp.weixin.qq.com/s/WOBWRHNfzT_cEGYrls8axg
** 2018-08-18
- 《进击的BA，模糊的T》进入2018年，腾讯的业绩依然突出，盈利能力是BAT三家中最强的，
  但市场对它的看法却大变样。腾讯股价开始一泻千里，到8月，已经跌掉了1万亿港元（超
  过1400亿美元），约等于三个小米，创下史上最大的一年内跌幅。不到一年的时间，腾讯
  究竟怎么了？https://mp.weixin.qq.com/s/hBjKfQ2tnz6TqjCV3cFBjg

- 《币圈寒冬将近：韭菜暴富梦碎，资方被迫「从良」》伴腾讯进入寒冬的还有币圈，终于
  各方都在回归理性。韭菜已经在涨跌中逐渐成长，他们暴富继而被套牢，在风浪中变得佛
  系；资本寒冬总是洗牌的机会，撑过了之后即是出头之日。但何时是出头之日？
  https://mp.weixin.qq.com/s/rE4weFmoyJVyarghVsU_qg

- 《拿好，这是一份旧路径失效时代的方法清单》生活中那些听上去或者看上去特别熟悉的
  名词，我们其实非常陌生。这种陌生感来自于我们思维认知的一种舒适性，又或者是天生
  的一种盲区。我们天生对身边的事情不那么敏感。如何走出天生盲区，这时候你需要
  “反”的思维。https://mp.weixin.qq.com/s/uVjkMY54DRZ-29hnmQZoMQ

- 《白酒反叛者江小白，它质疑所有质疑》江小白就是一款有“反”的思维的产品，它走出
  了“酒”凭口感竞争的盲区。一个贴开题为“江小白这么难喝为什么你还要买”，获得
  1.1万个赞。有人甚至说，江小白其实是一家营销公司，只是顺带着卖酒。
  https://media.weibo.cn/article?id=2309351000894273982235889209

- 《年轻人的群体失眠，养活了一批公司 》都市人的睡眠状况越来越差，有电子产品的干
  扰，也因为生活节奏的加快。有些讽刺，但这是一个事实——很大程度上，技术的发展造成
  了人们的睡眠障碍，而如今，我们又通过技术来寻求解决方案。
  https://mp.weixin.qq.com/s/ORUheX6I_wnb8UnMpEHs1A
** 2018-08-15
- 《89天后，陆奇一箭三雕》距离陆奇5月18日正式离开百度，过去了89天后，陆奇选择把
  创业与投资两件事融合在一块，担任YC的中国创始人兼首席执行官。同时，YC并不与百度
  在核心技术领域形成竞争关系，这样的选择还没得罪他曾希望“在这退休”的百度，堪称
  “一箭三雕”。https://mp.weixin.qq.com/s/GlI0-vmT1xldK1VD6wP9uw

- 《Sam Altman: YC、硅谷与人类未来的天选之子？》陆奇任职的YC是个什么样的公司？这
  家以Y Combinator函数为名的公司，在两年前就被称作硅谷与人类未来的天选之子，于是，
  哪怕录取率只有斯坦福大学的一半，每年还是有成千上万的年轻人们申请进入 YC。
  https://zhuanlan.zhihu.com/p/23672766?utm_source=wechat_session&utm_medium=social

- 《以慢打快，如何定义唯品会这家公司？》转到唯快不破的中国互联网竞争里，唯品会近
  几年的新业务往往不是最快的那一个，但总是能以慢打快的那一个。两年前，所有的人都
  认为电商没机会了，这场战争已经结束，接下来是京东和阿里的事，唯品会上演了一场在
  巨头眼皮底下做大的精彩故事……https://mp.weixin.qq.com/s/MR05RiXelfen2d1EA9YJbg

- 《一家50平米小店的老板，如何用社群打垮平台电商？》电商进击如此汹涌，本地小店该
  如何抵挡？本地生活圈的垂直化经营是关键，而如何让本地化生活圈服务更容易取得凝聚
  力？何以提供“供应及时、挑选优化、体验强化”的线下服务？这家50平米小店是个不错
  的案例。https://mp.weixin.qq.com/s/hWhG6GMnMICOfptqZsSTuQ

- 《为什么高亏损公司会去布局新高亏损业务？》8月6日的晚间，在美股上市公司爱奇艺和
  新英体育宣布成立“新爱体育”。在此之前，同是视频网站的乐视视频、PPTV，都把体育
  频道单出拆出来“重点建设”。爱奇艺为何会去布局不看好的新高亏损业务？难道他们忘
  记了乐视体育的故事了吗？https://mp.weixin.qq.com/s/5jzZeE-UDPdIe91T6V0Y4Q
** 2018-08-14
- 《“特斯拉的门徒”蔚来汽车要上市了，不过它怎么越看越像小米的门徒？》2014年11月，
  由李斌、刘强东、李想、腾讯、高瓴资本、顺为资本等企业家和投资机构联合发起创立的
  蔚来，广义上是一家汽车公司。此前，“蔚来汽车”曾拿掉“汽车”，统称“蔚来”品牌。
  拿掉“汽车”的蔚来现在算什么呢？
  https://mp.weixin.qq.com/s/OQw3ezOtJ1_P10eTc_tZWA

- 《谷歌双雄》黄峥和蒋凡，分别代表着过去几年中国移动互联网大浪淘沙的两种典型成功
  者。奇妙的是，他们同从谷歌出发，一个坚持独立创业，一个在巨头内部建功立业，离开
  谷歌后走上两条截然不同的道路，辗转多年却又回到同一个地方，最终成为彼此最大的对
  手。https://mp.weixin.qq.com/s/C2Rqn7QKBZgWtJCYCwx30A

- 《宣战前夜：陌陌变形记》陌陌似乎越来越像一家直播公司，哪怕唐岩一直在强调这家公
  司的社交基因。陌陌的社交关系一直处于陌生人社交的弱关系链，对于它，其未来的想象
  空间的扩大就在于，它能够创造出多少种表达方式，将自己的弱关系不断向强关系延伸。
  https://mp.weixin.qq.com/s/ePj0ZkMN_uIZMlVQ15y5qA

- 《年轻人，没事别想不开去创业》腾讯企鹅智库曾对20多个省市的5万多网民做过一项创
  业意向调查，结果显示：从来没想过创业的人，只有3％。这篇文章，正是给给那些想创
  业的年轻人泼泼冷水，反正那些真正的创业者从来不怕泼冷水。
  https://mp.weixin.qq.com/s/C0tVK0mc7QnYQBrdfnXFug

- 《工具产品面临瓶颈，美图把社交当做「二次创业」》美图现在已经拥有 4.5 亿用户，
  很难依靠用户高速增长来推动营收和利润增长。美图必须在已有基础上，以更多业务来带
  动互联网业务营收，同时增加用户黏性和使用时长。于是，美图选择了社交，希望它能带
  动公司继续增长。https://mp.weixin.qq.com/s/ET5HtwbO1JKBLlNtXtH9sw
** 2018-08-13
- 《厦门房价下跌，网红城市的潮来潮去》有一种不算新鲜的观点再次引起注意：厦门的房
  价，一直以来都与其城市发展水平不相匹配。很多非厦门人惊讶地发现，这座名声在外的
  城市，经济总量只排在全国五十名左右，房价却一度冲到了北京上海深圳后面。而在一排
  排洋楼的遮掩之下，是否是荒芜的现实？
  https://mp.weixin.qq.com/s/WsBS_khYtV0ehtWHuog6ew

- 《潘越飞：世上已无捷径，“重”才是时代关键词》文章来由潘越飞的一篇演讲，有人说：
  “小潘是在中国自媒体时代留下过自己烙印的人。”在锌财经上线的时候，很多人都说他
  是 “自媒体的上古神兽”。不管这样的封号是否带了点“过气明星”的揶揄，在那个只
  要有才华就可以信马由缰的自媒体草莽时期，这个钱江晚报的记者的确风华绝代。
  https://mp.weixin.qq.com/s/0sbPJkTXlpgIhBSE_hBx6Q

- 《市值堪比小米，比特大陆凭什么值500亿美金》去年 11 月，在数字货币市场正沉浸在
  史无前例的狂欢之时。比特大陆这个掌握了全球超过 50% 的比特币算力，矿机市场份额
  也达到 70% 以上的公司，突然宣布调整战略方向：全力转向人工智能，要淡化矿机公司
  的外界印象？https://mp.weixin.qq.com/s/Oi6GuK1N0XVatrNvN5cqvQ
- 《一头自媒体的供给侧改革》互联网或者说中国人将不得不被迫的转入向内求的阶段，向
  外求的好日子到头了。王兴以前有个讲话，说互联网到了需要供给侧改革的时候。他估计
  餐饮业的效率和成本优化有25%的空间。所以就知道现在苦哈哈的美团以后赚钱的地方可
  能在哪了。https://mp.weixin.qq.com/s/2W7YuTUCFIDhftJqgYKSkQ

- 《一头自媒体的供给侧改革》互联网或者说中国人将不得不被迫的转入向内求的阶段，向
  外求的好日子到头了。王兴以前有个讲话，说互联网到了需要供给侧改革的时候。他估计
  餐饮业的效率和成本优化有25%的空间。所以就知道现在苦哈哈的美团以后赚钱的地方可
  能在哪了。https://mp.weixin.qq.com/s/2W7YuTUCFIDhftJqgYKSkQ

- 《生态会员是视频网站的破局之道吗？》8月8日阿里“88VIP”发布，优酷在阿里大生态
  中的作用开始显现。88VIP会员将同时拥有购物优惠、优酷年度VIP会员、虾米音乐年度
  SVIP会员等权益。那为什么零售商都在布局视频流媒体？电商会员与视频网站会员能如何
  打通，相互赋能？打包会员的推出对于视频网站来说究竟是增量还是减量？
  https://mp.weixin.qq.com/s/6ydm-mskssyjDNaL45BcXQ
** 2018-08-10
- 《想创业，就来新东方》后来创业的新东方老师们，罗永浩创办了手机公司、李笑来成了
  币圈首富、李丰则是风险投资新贵。除了他们三个，新东方还孕育了各种神。这一长串名
  单有唐宁、胡敏、陈向东、包凡一、刘畅、李哲、印建坤、马薇薇等等200多人。
  https://media.weibo.cn/article?id=2309351000894271099180365285

- 《惊魂一夜，马斯克713亿美元「私有化」特斯拉意欲何为？》马斯克在特斯拉官网发布
  博客，详细阐述了以420美元每股价格私有化特斯拉的缘由，同时坐定这则消息的真实性。
  但特斯拉究竟为何退市？有人认为马斯克想要更大的控制权，摆脱华尔街的控制；还有人
  则认为拉高特斯拉股价……https://mp.weixin.qq.com/s/xiSVuLGAZIyJ-97RqIaVYw

- 《小镇青年的金融梦》因为众所周知的原因，这篇文章主人公的不能被叫做小吴或者小
  hui，姑且取他名字最后一个字的右边，把他称作小军吧……相较于大多数金融大佬令人
  发指的身材，50岁的小军总依旧风度翩翩，神采奕奕。多年来，小军总烟酒不沾，只在实
  在意思不过去的时候倒点葡萄酒意思一下。
  https://mp.weixin.qq.com/s/q0wkN6NNZ9e2sfhWEloR-g

- 《游戏人间太艰难》2015年8月，以枪火联盟内测为主题的一篇帖子，下面有5条评论，其
  中三条是产品开发者甘来发的。可见，关注者之少。今年2月，公司进入清算模式。甘来
  已不在法兰游戏股东行列。 8月7日这一天，“谢谢。我会在天堂安好。”甘来最后一条
  朋友圈信息意味着他一生的急速坠落。
  https://mp.weixin.qq.com/s/bnHiWG17mVAAn4Hr44-NeQ

- 《人民呼叫网约车》今年7月1日开始“严查网约车”行动，那些不符合京车京人条件，以
  及三证不全的运营车辆，都会被扣押。这样的查处力度超出了所有司机和网约车平台的预
  期……而工信部下属的中国信息通信研究院研究发现，目前我国从事网约车运营的司机有
  3120万，而资质符合各地新规的共有34万，比例仅为1.1%……
  https://mp.weixin.qq.com/s/hGfXIOdHOywyoQj3wdD8uQ
** 2018-08-08
- [[https://mp.weixin.qq.com/s/6eo8q2NtLozZWu6U-WWOcg][割舍存量, 拥抱增量]]
** 2018-08-07
- 《谷歌要回中国？人民日报发文欢迎 李彦宏“有信心再PK，再赢一次”》谷歌的退出使
  得他们错过了内地互联网发展的黄金机会。在谷歌缺席的过去八年，大陆的互联网市场格
  局迅速改变，移动互联网用户的数量翻了一倍多，从2010年的3.03亿增长到现在的7.53亿。
  而谷歌的回归能带来什么改变，人民日报的推文和李彦宏的朋友圈又意味着什么？
  https://mp.weixin.qq.com/s/QnevYCQABiXJOAVLc0sjXg

- 《直播这些年：狂欢、裂变和虚妄》那一年， YY聚焦游戏语音，陌陌深耕LBS社交，相关
  行业热火朝天。刚失恋的MC天佑写了一首自己的喊麦作品，叫做《女人们你们听好了》。
  陈一发辞了工作搬到在上海，每周坚持至少播四天。开播前压力大到无法承受时，一个人
  哭一会。直播这些年：有着哪些狂欢、裂变和虚妄？
  https://mp.weixin.qq.com/s/O-aDr_v8vMEjDIjKjpXM9w

- 《我走进"黑客交易中心"，看见有人在收智商税》搜关键词 “黑客交易中心”后 ，一个
  号称“国内首家黑客交易站点”的网站排在百度搜索结果第一位。在里面有人把自己老公
  “弄丢了”，想找黑客定位，开价3000元：有人头顶绿意盎然，想查查老婆开房记录，开
  价5000元：还有俩同学挂了科想逆天改命，开价3000~3500元……
  https://mp.weixin.qq.com/s/lrcWJdimhvNpGJrkF-Utxw

- 《吴声：未来一年，新物种的六大趋势预测》文章根据吴声在8月5日「新物种爆炸·吴声
  商业方法发布2018」演讲内容整理。在整场180分钟的演讲中，带来的信息量同去年一样
  庞大：2.5次元、家庭会员、订阅万物、知识新零售、透明化机遇……涵盖了过去一年全
  部的商业爆发级现象，以及观点独特的深度预测。
  https://mp.weixin.qq.com/s/dWJurca2gLUEMcvhmNI_0g

- 《吴声：未来一年，新物种的六大趋势预测》文章根据吴声在8月5日「新物种爆炸·吴声
  商业方法发布2018」演讲内容整理。在整场180分钟的演讲中，带来的信息量同去年一样
  庞大：2.5次元、家庭会员、订阅万物、知识新零售、透明化机遇……涵盖了过去一年全
  部的商业爆发级现象，以及观点独特的深度预测。
  https://mp.weixin.qq.com/s/dWJurca2gLUEMcvhm
