#+TITLE:       汇总: 优质文章每日精华选(2021 年)
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-01-05 Tue
#+URI:         /blog/%y/%m/%d/everyday-reading-2021
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

微信公众号「卫夕聊广告」的作者组了一个微信群, 目的是每天挑选五篇当前最优
质文章,帮小伙伴们提升信息获取的效率和质量.

因每日发完文章列表后, 群里会有相关主题讨论, 时间一长, 再翻看历史文章就极
其不便,故起意将每日推荐文章列表整理到此, 方便随时查阅.

* 三月
** 2021-03-26
- [[https://mp.weixin.qq.com/s/RPL0D6BQoI3r0ZFOlBO0VA][《100 亿美元，微软收购了一个有 3 亿人口的「互联网社会」》]]

  又一家「中型创业公司」顶不住了。微软正考虑收购 Discord，价格超百亿美元。后者去
  年夏天刚获得 1 亿美元投资，估值 35 亿美元。如果收购最终成立，意味着 Discord 的
  价值在一年内翻了三倍。对微软来说，收购 Discord，一方面意味着能接触到 1 亿多粘
  性用户，另一方面也意味着，它能从一个新的角度，尝试构建未来的「互联网社会」。

- [[https://mp.weixin.qq.com/s/Mz5IW7kOMIzdCLxdHMa9lA][《拼多多没有二号人物》]]

  3月17日，黄峥宣布辞职，将董事长一职交给了联合创始人兼CEO陈磊。由此，拼多多正式
  迈入陈磊时代。在外界看来，拼多多是“属于”黄峥的，陈磊只是黄峥退居幕后选出来的
  “影子武士”。但实际上，从黄峥创业初始，陈磊就一直伴随左右共同进退，扮演着合伙人
  的重要角色，从某种意义来说，陈磊不是黄峥的接班人，而是合伙人。

- [[https://mp.weixin.qq.com/s/TooIHw70U11bW6UlX99SLQ][《新兴国家正濒临货币危机》]]

  三月，土耳其里拉崩盘。自今年二月以来，土耳其里拉已经跌去逾23%。里拉崩盘引发土
  耳其金融地震，土耳其里拉崩盘，只是个开始。如今，美元正在进入流动性拐点，新一轮
  紧缩周期的预期越来越强，土耳其里拉率先崩盘，紧接着，俄罗斯、巴西、阿根廷、印尼、
  印度等会遭遇何种命运？中国会受到怎样的冲击？新兴国家的这种“幽灵”为何会如期而至？
  本文从经济学的角度分析新兴国家的周期性货币危机。

- [[https://mp.weixin.qq.com/s/0BimvA-Hu6cqRS0CzcN_dQ][《全网最便宜硕士” ：留学白俄罗斯，泡沫还是骗局？》]]

  不需要雅思成绩、个人简历，也不需要教授推荐信，只花了不到3万元人民币，李建波就
  成为白俄罗斯某大学的一名留学生。每年的职称评定，雷冬都因为本科学历而无法晋升，
  虽然他毕业于QS排名前50的高校，但依旧被研究生学历“卡”住脖子。由于上网课的人太多，
  有些大学的老师已经不够用了，乃至于中介还要帮忙招聘老师上课。“很多人在国内一直
  被学历所限制，内卷得很严重，来读一个白俄罗斯的硕士，难道不是避免内卷的一个方式
  吗？”

- [[https://mp.weixin.qq.com/s/LNY8XE9sS4e36CVaahyrfg][《长期主义者的10条认知 ｜ 深度》]]

  最近“长期价值主义”这个提法比较火。之所以火，我认为是源于中国企业的现实生存问题。
  其实，长期和短期本来是不可分割，从时间这个维度来讲，长期和短期两者是一体的，并
  不是说追求长期就不要短期，长期目标恰恰是由短期目标积累起来的。如何平衡长期战略
  和短期策略？如何兼顾理想与现实？如何在战略、组织能力、绩效管理等方面实践长期主
  义？

** 2021-03-22
- [[https://mp.weixin.qq.com/s/L0VOUpRiqeGhrBlaeXvSxg][《一人食，一人玩，一人住，为孤独埋单的9200万单身青年》]]

  2018年中国单身成年人口高达2.4亿人，超过英法德三国人口总数，其中超过7700万处于
  独居状态。预计到2021年，这个数字将上升到9200万。半份菜、一斤装大米、一人嗨火
  锅……针对单人消费的餐饮业态正在涌现。外观小巧、方便快捷的小家电抓住了绝大多数年
  轻人的心理：宁愿单身，也不愿将就。单身一族在宠物主中占比达32.5%，人均单只宠物
  犬、宠物猫的消费分别达6082元、4755元。

- [[https://mp.weixin.qq.com/s/8v7a6zggout-Y0g89SnKkQ][《搜索广告代理商讲述：灰色广告是怎么洗白的？》]]

  互联网上的虚假广告是历年315晚会的常客了，今年315，360搜索、UC浏览器上的虚假医
  药广告中招了。只要投放资金到位，这两个平台的广告代理公司可以提供从广告资质、广
  告内容，到网页设备、账户维护、虚假评论和点赞等一条龙服务。这类广告是从何而来？
  央视记者只提供了一个微信号和产品类型，很快，代理公司就复刻出了类似的广告内容。

- [[https://mp.weixin.qq.com/s/xbVRPxohjs5QfPqUEjgVYg][《所有东西都涨价，为什么大家只骂海底捞》]]
  近日，#海底捞牛肉粒变素了#成了刷屏话题。起因是有消费者反映，部分海底捞门店将牛
  肉粒替换成了大豆素肉制品“味伴侣”。其后，海底捞客服回应称味伴侣目前仅在上海试点，
  主要是“为了应对顾客无限量使用牛肉粒小料造成的浪费”。看似只是一次简单的小料替换，
  网友却反应激烈，这不是海底捞第一次因涨价被吐槽。同是涨价，有些消费品却可以明目
  张胆，并且消费者还依旧买单。那么为什么有些消费品能轻易涨价，有些却一涨就被吐槽？

- [[https://mp.weixin.qq.com/s/AMdLu0RfgjHOzQA1S4fEbA][《李丰独家授课：华为、戴森、三顿半崛起背后的新消费底层逻辑》]]
  谁取悦用户取悦得更好，就会在供过于求的时候有更大的机会。所以，峰瑞资本的李丰老
  师告诉我们：任何一类商品，从供不应求，到供求平衡，再到供过于求之后，很可能会出
  现另一个新的“供不应求”，这被称为消费升级。大部分情况下你要分清楚，你所在领域的
  供求关系，处在哪个位置？将技术创新“翻译”成用户可感知的产品力创新，可以更好地放
  大品牌。优秀的产品力+流量媒介+供应链，是持续获得品类红利、创造持久力品牌的公式。

- [[https://mp.weixin.qq.com/s/ANVur2w_0VfjXK6SBHhV6g][《芒格：我如何用五个通用观念，解决复杂问题》]]

  这篇文章是一篇芒格的演讲，来自最新版本的《查理·芒格传：巴菲特幕后智囊》，本书
  是国内唯一经过芒格及巴菲特授权的传记，从这篇演讲中我们可以看到芒格独特的逆向思
  维，以及五个他自称“超级简单”的通用观念。在演讲中，芒格给读者出了一道思考题，如
  果你穿越回1884年，那么你该做些什么，才能够创造一个在150年后价值达到2万亿美元的
  公司呢？如果有一家公司全都做到了，那么它值不值得投资呢？

** 2021-03-15

- [[https://mp.weixin.qq.com/s/evtV5om1yC3DMCGcqZ7ZJw][《新冠之谜：为什么疫情在某些国家看起来更严重？》]]

  新冠疫情在不同地区导致的死亡率是无差别的吗？答案是否定并且出人意料的。简单来说，
  与拥有完善医疗体系的富裕国家相比，那些相对贫困的国家——特别是南亚和撒哈拉以南非
  洲大部地区——死亡率竟然低得令人惊讶。获得普利策奖的印度裔美国医生、科学家
  Siddhartha Mukherjee，他在全球范围内访谈了多位统计学家、病毒学家和公共卫生专家，
  试图解释这一令人困惑的现象。

- [[https://mp.weixin.qq.com/s/SM-ghDv5SvTvo48dxuZbFg][《国内刚开始萌芽的播客，已经成了美国巨头们的主战场》]]

  在全球市场上，苹果音乐服务还在紧紧追赶 Spotify，但它原本领先的播客服务却被
  Spotify 突袭超越了。自 2015 年 Apple Music 问世，苹果花了 4 年，在美国本土超越
  Spotify，成为全美付费订户最多的流媒体音乐服务。在世界范围内，Spotify 保持着用
  户数上的绝对领先，且优势越来越大。Spotify 2021 年在美国的播客用户数将增至 2820
  万，超越苹果的播客 App。

- [[https://mp.weixin.qq.com/s/uP54h70ebCOT4bv6bQxkaA][《第一个投中快手的人》]]

  9年前，一个人给一个工具产品投资了一笔钱，在后来的融资中又多次下注，如今，按公
  司上市当天的收盘价，他所在的投资机构获利216亿美元，回报超过107倍。跟暴涨的财富、
  从天而降的运气相关的故事，总是能最快引发人们的兴趣。随着快手今年2月初在香港上
  市，这个名叫张斐的投资人与他担任合伙人的五源资本的故事，开始在互联网上传播。

- [[https://mp.weixin.qq.com/s/zX9a6g7WyHAdjLbpyy1SOw][《一切中国互联网产品的归宿都是相亲网站？》]]

  从网友们在中国互联网各个角落里的真实行为来看，他们虽然一边吐槽着父母催婚一边拒
  绝着线下被“包办”的相亲，其实另一边身体还是很诚实——相亲交友不仅对他们来说很重要，
  而且还被这届年轻人玩出了新花样。现在最热闹的互联网相亲地，早就不是那些垂直领域
  的交友软件，也不是基于微信微博豆瓣等泛社交平台的交友小组。如今最积极相亲的年轻
  人们活跃在一些跟恋爱交友八杆子打不着的App上，比如时下正处于风口浪尖的基金圈。

- [[https://mp.weixin.qq.com/s/6d52e9Gyhp02nFVGBw-HaQ][《为什么中国现在老被骂》]]

  皮尤研究中心最近在2021年2月对美国成年人的调查，对中国的看法呈现负面的美国人比
  例从2018年的46%上升到了2021年的67%, 呈现较大的上升。这里面因为疫情怪罪中国是一
  个很大的因素，但是更大的背景是美国特朗普政府对中国的敌对态度，简单的说，疫情只
  不过是一个加速项，实际上随着中美国力的不断逼近，美国必然会开始对中国的压制，其
  中就包括舆论上的攻击，而这必然会影响到民众对中国的看法。

** 2021-03-12
- [[https://mp.weixin.qq.com/s/KTFPHcXg9zzx9H9U72poWQ][《抖音电商大变局：品牌自播吃肉 达人喝汤 小主播被迫转行｜深网》]]

  抖音直播电商是一片蓝海，也是一座待挖掘的金矿。在抖音电商不断变化的流量规则里，
  主播、达人、品牌方都成了其战略目标的“螺丝钉”。随着抖音电商战略和布局的变化，这
  些“螺丝钉”在平台的位置、生态乃至生死等都在随之改变。在2021年抖音电商将品牌自播
  作为战略级项目的背景下，品牌自播“吃肉”，达人“喝汤” ，小主播被迫转行的局面正在
  形成。

- [[https://mp.weixin.qq.com/s/JhAulBaTdq0o1DelCZsT3g][《科技公司集体进军养猪，底层逻辑是什么？》]]

  要致富，少生孩子多养猪。人们没有想到，这句农村经典刷墙语录，现在成了科技公司的
  「座右铭」。过去几年间，华为、网易、阿里巴巴、京东、万科、碧桂园、恒大都盯上了
  养猪行业。尽管，它们来自 ICT、互联网、房地产不同行业，却都因养猪事业有了共同交
  集。「不好好读书，回家养猪」在今天可能需要反向解读，好好读书才能有机会科学养猪。
  养猪究竟有多香，让大厂不惜跨界争相布局，而不是牛羊禽类养殖？

- [[https://mp.weixin.qq.com/s/I2HYj4YhOhokPZCoVLSpFg][《Mac 版微信 3.0，可以看朋友圈了》]]

  Mac 版微信 3.0 还没正式发布，拿到的是 beta 8，这个版本最吸引的功能自然是可以在
  Mac 上刷朋友圈喽。这次 Mac 版微信 3.0 提供了三个新特性：1、可以浏览朋友圈；2、
  可以浏览聊天中分享的视频号视频和视频号直播；3、在OS X 10.14 版本及以上系统支持
  深色模式。目前的 3.0 还是 beta 版，估计大家很快就能见到正式版了。

- [[https://mp.weixin.qq.com/s/fJNeOSq45qVPBJn8euzsKw][《实探山东“拉面哥”：疯狂燃烧的荒诞和欲望》]]

  程运付“拉面哥”，因15年坚持以3元价格卖一碗面而忽然间在抖音、微博、快手等平台走
  红。最近的两个星期，无数全国各地的主播和围观者涌入这个偏僻山村，将镜头对准“拉
  面哥”的家门口；也有当地人在闹剧中寻找商机，兜售流量卡、WIFI设备、充电宝；也有
  人什么都不要，一切免费。在沂蒙山余脉的春日迷蒙雨雾中，刺猬公社亲眼目睹了这场略
  显荒诞的乡村直播秀。

- [[https://mp.weixin.qq.com/s/2kHHw55Zs95xOYUbQUqx_Q][《何加盐：影响10位企业大佬的10本书》]]

  很多企业界的大佬都有一个共同点：特别爱看书。甚至有些企业家，其今天的成功，跟他
  年轻时看过的某一本书，有很大关系。今天我们盘点一下曾经影响过10位企业大佬的10本
  书：1. 雷军与《硅谷之火》2. 马云与《人生》3. 马斯克与《基地》4. 孙正义与《龙马
  来了》5. 芒格与《富兰克林自传》6. 段永平与《穷查理宝典》7. 王兴与《有限与无限
  的游戏》8. 张一鸣与《少有人走的路》9. 贝佐斯与《从优秀到卓越》10. 任正非与《毛
  泽东选集》

** 2021-03-11
- [[https://mp.weixin.qq.com/s/o-1QSeNFFJphwjPIvOrqEg][《大熊市，才是改变人生的最好机会》]]

  在股市里，做容易的选择是轻松的。涨的时候进场，跌的时候离场。这样的选择，是大多
  数人的做法，也是大多数人在股市里赚不到钱的原因。什么是艰难的选择？是下跌时耐得
  住，守得住，还能坚持加仓，受得了回撤，守得了云开。经历这次大跌，我们一起来复盘，
  怎么磨出自己的性子，怎么磨出回报。大熊市，才是改变人生的最好机会。

- [[https://mp.weixin.qq.com/s/bnGu2I6-XR2qAaHhhc_cSA][《真正的高手，相信逻辑而不是现实》]]

  人类日常生活中常用的两种基本逻辑方式：一种是归纳法；另一种是演绎法。归纳法是人
  类最基础、最常见的用智形式，这是一种内置在人类基因中的思维定式。演绎法是理性思
  维的主要方式之一，它是一种很奇怪的思维，它是一种逻辑自证的学问。归纳法与演绎法
  是人类主要的两种思维方式，只有了解了这两种思维方式，我们才能进入第一性原理的语
  境当中，才能知道第一性原理能够在哪些领域发挥作用。

- [[https://mp.weixin.qq.com/s/Go6lx9_btuzgNAHVAW-8TQ][《中国广告的两大路线之争》]]

  中国广告几十年来的两大路线：一个叫用户路线，一个叫产品路线。产品路线回答三个问
  题：1、产品是干啥的？2、产品有什么功能作用？3、相比于竞品，产品有什么优势？中
  国的本土营销公司喜欢走产品路线。而用户路线回答另外三个问题：1、品牌的目标用户
  是谁？他们是一群什么样的人？2、用户有什么样的情感、个性与态度？3、品牌带给消费
  者的体验和心理价值是什么？4A公司喜欢走用户路线。

- [[https://mp.weixin.qq.com/s/X0dCy2Ys470CQj7678cBcA][《比尔·盖茨再度警示：下一次灾难，将是疫情的5倍》]]

  对于领导者来说，主要做两件事，一个是看到未来的机会，一个是看到未来的灾难。没有
  看到未来的机会，就无法激励员工；相反，如果能看到社会未来一定会遇到的麻烦，提前
  做好解决的准备，就会获得成功。所以，当所有的人都开始提心吊胆，对未来没有信心的
  时候，领导者必须看到希望所在；而当所有人都在畅想未来的时候，领导者必须看到灾难
  所在。

- [[https://mp.weixin.qq.com/s/ACti_o5Uno3TSijXsm9cng][《湖南人为什么最爱嚼槟榔｜大象公会》]]

  中国什么地方的人最爱嚼槟榔？台湾、海南、广西等槟榔原产地都有嚼槟榔的习俗，其中
  台湾更发展出闻名世界的「槟榔西施」文化。但在湖南人面前，他们通通相形见绌——据统
  计，台湾约 10%的人口有嚼槟榔习惯，而湖南人嚼槟榔的比例达到 38.42%，其中 30 至
  40 岁人群更高达 50.36%，作为中国最大的槟榔产地，海南对槟榔的热爱也远不及湖南。
  那么湖南人为什么这么爱吃槟榔？

** 2021-03-10
- [[https://mp.weixin.qq.com/s/t48bbKDDWcAsLYwG5aw6rQ][《推荐和视频开始侵蚀各行各业》]]

  过去十年，在人跟信息连接这个领域里面，其实最大的机会在我看来就是两个，第一个就
  是信息怎么组织，明显的就是从搜索变到了推荐。另外一个就是内容怎么生产，就是从图
  文变向短视频。视频未必是最高效率的信息消费方式，但视频化的信息却是最容易消费的，
  理论上视频可以触达所有人群。内容生产端，短视频大规模扩大了创作者数量，让人人都
  是创作者成为可能。

- [[https://mp.weixin.qq.com/s/u1x9x7z6d7VQQKeew3YVsg][《35岁，他们决定考研》]]

  教育部公布的数据显示，全国硕士研究生招生考试报考人数从2015年的164.9万人增加到
  2021年的377万人。学生们的「画像」是：35岁上下，大部分已经成家，职业多样，百分
  之七八十考非全日制研究生。「成年人生活的苦，你躺在床上它就来了。但学习上要吃的
  苦，是自找的。」，很多人不能理解这群逆行的大龄考研人，但「甭管抱着什么目的考研，
  至少是求变求进步的一群人」。

- [[https://mp.weixin.qq.com/s/iBbuqHKaLLU5492HjdhYCg][《中国人最爱的算命项目，星座和塔罗牌输给了它》]]

  互联网算命这事儿并不新鲜，毫不夸张地说，在某搜索引擎上打下“免费算命”四个字，相
  关结果多达 6 千万个。昔日的街头算命先生，如今已经转战线上，迎来了事业的第二春。
  这里面甚至还有看面相的“AI 算命”，分分钟就能生成一篇比你毕业论文还长的命理分析
  报告。有多少年轻人算过命？玄学的背后有多少生意？热衷于算命背后又是什么心理？

- [[https://mp.weixin.qq.com/s/MBvnW97Bi5CaVeydOkGGkQ][《中国芯片“卡脖子”，造芯怎么这么难？》]]

  国内之前掀起了百城造芯热，但是目前相对成功的仅有上海无锡合肥西安北京这几个城市，
  前段时段武汉弘芯项目更是把我国芯片制造业推上风口浪尖。这次将会在制程技术，资金，
  人力，设备，市场，供应链，水电气，环保，政策九个维度和读者们聊聊建立一座现代化
  晶圆厂的难度（晶圆是指制作硅半导体电路所用的硅晶片），试图用寥寥千言展示如何完
  成一项大工业项目的全貌，以及我国当下芯片产业的难处。

- [[https://mp.weixin.qq.com/s/ES4uv4uRZfGdm1HLQSUSgA][《焦虑的抖音，要做另一个“微信”》]]

  TikTok在海外受挫后，字节跳动一直焦虑未来的增长在哪，而日活突破6亿的抖音被寄予
  厚望。面对增长放缓的短视频行业，抖音四处出击：电商、支付、社交、搜索以及最近突
  然大力招兵买马的本地生活，字节跳动试图把抖音打造成另一个超级APP“微信”。为了承
  载张一鸣的野心，也为了促成今年港交所最大的一笔IPO，抖音急了。

** 2021-03-09
- [[https://mp.weixin.qq.com/s/yc0b-cYYdDIK2TpQbPN3WQ][《深V反弹失败，A股跌够了吗？》]]

  3月9日，A股依然一片绿，市场仍在跌跌不休，机构纷纷做起了“心理按摩”。综合受访机
  构人士观点来看，近期市场的波动一方面是由美债收益率上行对估值造成的压力，另一方
  面来自于市场情绪层面的担忧。随着第一阶段调整到位，部分资产的投资价值逐步显现。
  我国的经济增长动能仍较为强劲，将对A股提供盈利端的支撑，无需过度悲观。

- [[https://mp.weixin.qq.com/s/IsLzc3WBSY5DElED-QndlQ][《抖音搜索降维打击微博》]]

  春节后，抖音公布其视频搜索月活已超5.5亿，字节跳动CEO张楠表示，未来一年，抖音将
  加大对搜索的投入力度。这被视作字节与百度搜索战争的扩大化，一个重要角色却被忽略
  了，那就是微博。抖音主动发起的搜索战争，明面上是在和百度争搜索商业化的市场份额，
  实则是一项双线任务。这场搜索战争的另一任务，是成为批量制造热搜话题的舆论广场，
  而在中文互联网世界，这一位置已由微博担当多年。

- [[https://mp.weixin.qq.com/s/Zfy68uH-356_cGPrybkFPQ][《大厂月入3万，不如回家考公？| 谷雨数据》]]

  2020年，在互联网大厂做游戏工程师的李洋决定辞职，月入三万的他从西二旗回到小城市
  参加公务员考试。经过疫情，他终于“想明白了”：在大厂里收入可观，但因为长期加班失
  去生活；大城市里租房的生活让人感到漂泊不定，小镇里的安全感则相比起来更让人安心。
  李洋选择考公的理由，可能也是如今众多考公年轻人心态的缩影。

- [[https://mp.weixin.qq.com/s/ruIfpT3pHtP-p7sfh9u8BA][《互联网不幸福》]]

  根据脉脉官方发布的2020年职场报告，IT互联网行业是人才净流入最多的行业，但与此同
  时，IT互联网行业是整体幸福感最低的三大行业之一，并列的是零售、贸易、批发与农林
  牧渔产业。在脉脉平台“职言”社区里，则到处流传着互联网大厂中关于“内卷”的轶闻与糗
  事，在亿万营收与技术创新的幕布下，这里就像互联网大厂的“聊斋志异”。互联网到底幸
  不幸福，这是一个复杂的问题。

- [[https://mp.weixin.qq.com/s/XxhwdodfuUOaR3mwf7O5Rg][《传道士与雇佣兵：“电商之王”杰夫·贝佐斯传奇》]]

  从1994年成立亚马逊并就任CEO，到2021年离任，贝佐斯创造了无限的辉煌，也留下了无
  限的争议。人从来都是复杂的，企业家更复杂。我们很难用一个简单的标签来形容如此深
  刻地影响过世界的一个企业家，也许，这样的企业家，本身就是一半传道士，一半雇佣兵，
  没有传道士的精神，他们走不远；没有雇佣兵的手段，他们活不长。左手持经、右手执剑，
  才造就了今天的他们。

** 2021-03-04
- [[https://mp.weixin.qq.com/s/-G6HBaW7IDlpJukTlTQYEw][《为什么老板画大饼越来越没用了？》]]

  一个完整的战略思维通常包含三个层次的内容：战略起点（认知层）、战略结构（结构层）
  和战略涌现（业务层），今天我们先来探讨第一个层次：战略起点。其中有两种不同的战
  略逻辑，第一种是从愿景出发，从“是什么”开始；第二种是从使命出发，从“为什么”开始。
  这两种逻辑孰优孰劣？愿景和使命各自的内涵是什么？为什么相对愿景，使命才是一个更
  好的战略起点？实现使命的方法又有哪些？

- [[https://mp.weixin.qq.com/s/Y1jyF7Boc3JY3vmZFbNZXQ][《为什么你身边的东北人感觉都很有钱？》]]

  很多人不解，东北明明经济不行，为啥还给人感觉贼有钱？首先，东北人“有钱”，绝对不
  是错觉。国家统计局数据显示，2020年居民人均可支配收入，辽宁在全国31个省份中排名
  第九，人均住户存款仅次于北上浙，位居全国第四。民间有种说法，东北只有有钱人和穷
  人两种，没有中间层。不是说东北没有穷人，而是跟其他地区相比，东北人更会“花钱”。
  同样是100块钱，到东北人手里就能花出110块的感觉。

- [[https://mp.weixin.qq.com/s/BKS6G8pSrVSitjDqIKAF-Q][《人口危机》]]

  最近，生育及养老问题，再次引发广泛关注。低生育及老龄化这两大难题，在未来会越来
  越突出，将深刻地影响经济增长和社会演变。人口危机已是一个世界性问题，但很少人意
  识到，中国面临的问题与欧美日等国存在根本性差异。本文从经济学角度简单探讨中国的
  人口危机。

- [[https://mp.weixin.qq.com/s/cz_3cxYUEpE_C02S2HM0Lw][《小镇青年的秘密，都藏在手机APP里》]]

  在过去几年，移动互联网快速下沉，小镇青年被贴上了“收入不高”、“没啥文化”、“缺乏
  品位”的标签。尤其是在一些一二线城市所谓的“精英互联网人士”眼中，小镇青年是处在
  互联网底端的一群人，但真实的小镇青年们，可能并不服气。我们通过手机里的APP，一
  窥小镇青年的真实生活，让我们能够知道，他们在做什么、想什么、玩什么。

- [[https://mp.weixin.qq.com/s/dk2STHQ7A7mfke7K2aADPw][《请不要叫我做题家》]]

  在2003年，“寒门贵子”是个100%的励志词汇，但到了2020年，这个词却被一个充满戏谑的
  “做题家”所取代了。做题家全称“小镇做题家”，多指出身低线城镇或者农村、通过题海战
  术杀入名校、坚信读书能够改变命运、但毕业后在大城市却只能勉强立足的普通人。很多
  人对“做题”以及背后等若国本的高考体系也产生了怀疑。为什么人们质疑“做题”？如何正
  确看待“做题”？社会欠年轻人们一个答案。

** 2021-03-01
- [[https://mp.weixin.qq.com/s/_ZfrE38z7g3fHtaxiZx__w][《为了劝我妈，我开了个老年公众号》]]

  如果你家里的长辈总转发一些看着就荒唐的鸡汤和谣言，而且已经影响到他们和你的生活
  怎么办？最近，豆瓣的哈组上出现了一个热帖——朋友开了个老年公众号劝自己的妈妈。发
  帖人的朋友为了抵制老妈的“深度好文”，让老妈听得进自己的话，专门模仿“深度好文”的
  模式开了个号，取名为“国学爱生活”。

- [[https://mp.weixin.qq.com/s/0wcM7X_49mZ8NrHhlL1TIg][《医美机构是不是下一个“爱尔眼科”？》]]

  如果说中年人的过年三件套是中华烟、茅台酒和金华火腿，那么对于年轻爱美女性，她们
  的过年三件套正在渐渐变成水光针、玻尿酸和光子嫩肤。在这个原地过年的春节里，生意
  红火的除了电影院、电商平台以外，还有近年来在一二线城市如雨后春笋般涌现的医美机
  构。医美生意火爆的背后，是医美机构狂轰滥炸的低价营销。

- [[https://mp.weixin.qq.com/s/FSzaRhJY2WnY15egZdWWig][《金球奖得主赵婷：“我这辈子都是个局外人”》]]

  第78届美国金球奖揭晓，华人女导演赵婷凭借《无依之地》获得最佳导演奖。她成为首位
  获得这一奖项的亚裔女性导演。以小成本独立制作成名，到执导大IP漫改电影、进入主流
  工业体系，赵婷走过的路，比她身上所有标签所传达出的含义要丰富许多。国族、性别与
  时代选择，最终都要落在一个具体的创作者身上，由她讲述那些她必须去讲的故事。

- [[https://mp.weixin.qq.com/s/cpLStfBtqqLmjvQobPFi7Q][《生育“零成本”，为何无法阻止日本生育率断崖式下降？》]]

    日本年轻人的问题并不在于生育时，而在于生育前的结婚意愿，以及生育后的抚养阶段。
  随着房子单价和总价都越来越高，日本年轻人发现一个问题，住20平米的房子怎么找对象
  呢？女性社会地位、收入水平不断抬高，择偶的标准、要求也相应提高，因此能够匹配并
  结婚的适龄男女数量大大减少。

- [[https://mp.weixin.qq.com/s/-n1gJh-4UqBInwSqe3BDig][《单身经济没有下沉市场》]]

    据民政部数据显示，2018年我国的单身成年人口高达2.4亿人，其中有超过7700万成年
  人是独居状态，预计到2021年，这一数字会上升到9200万人。正如克里南伯格在《单身社
  会》一书中所预言，单身社会正在成为一次空前强大、无可避免的社会变革。而单身群体
  扩大的背后，则蕴藏着无限的商机。但这场备受资本追捧的单身经济的狂欢似乎只发生在
  一二线城市，与下沉市场并无很强关联，单身经济没有下沉市场。

* 二月
** 2021-02-25
- [[https://mp.weixin.qq.com/s/1-RUPpkImyJEp5H8rUNilw][《7图深扒中国百亿票房演员，第5名你想不到》]]

    在刚过去不久的春节档，电影《你好，李焕英》成为一匹黑马，贾玲的这部导演处女作，
  甚至在整个中国电影市场都诞生了不少属于它的纪录，2月21日冲进了中国影史票房的前
  五名。影视寒冬阴霾下的电影市场，因为春节档的火热而激起不小的水花，在电影票房增
  长的背后，关于百亿票房演员的讨论也变得热闹起来。今天我们就用票房数据来看看，代
  表中国影人票房巅峰的百亿俱乐部里又发生了什么变化，哪些影人成为百亿黑马？他们又
  是凭什么登顶？


- [[https://mp.weixin.qq.com/s/ZwuTo11iz6z24u_YUJ3XbQ][《狂奔的视频电商，撑起万亿GMV？》]]

    视频电商已经杀到古典电商城下。快手市值已经飙到1.5万亿港元，超过京东，直逼拼
  多多。如果古典电商解决了传统零售品类不足的问题，视频电商则在解决古典电商的用户
  消费意愿问题。流量瓶颈下，传统电商的获客成本骤然攀升，以短视频平台为代表，优质
  流量入口成为品牌商家们的重点争夺对象。视频电商的强势，集中体现在GMV数据上。


- [[https://mp.weixin.qq.com/s/KedJcO1S1hEJO-Kwf0HfoA][《张一鸣怎样跳出“增长的痛苦”？》]]

    高薪加公司上市在即的期权诱惑，让字节跳动像一个巨大的磁铁，不断吸引人从五湖四
  海涌入，截至2020年年底，字节跳动的员工数突破了10万人。字节跳动之所以能够高速成
  长，得力于“人才充足率”这一指标与公司营收增长高度匹配。张一鸣曾在采访中承认自己
  “不合适掌兵”，然而他现在却实打实地统帅十万员工，同时还最大程度地激发了他们的创
  新能力——张一鸣的魔法到底是什么？


- [[https://mp.weixin.qq.com/s/T7BZlX68md1_OC-dSGRHHw][《朝夕光年，字节跳动的游戏梦》]]

    字节跳动和腾讯的竞争愈发贴身肉搏。2月22日，字节跳动又放出一个大瓜，旗下游戏
  官网——朝夕光年正式上线，字节跳动在中重度游戏内容研发上迈出了第一步。中重度手游
  需要较长时间的积累，字节跳动要在游戏领域拉近与腾讯、网易等游戏巨头的身位，小程
  序游戏就成了另一条捷径。


- [[https://mp.weixin.qq.com/s/-y4DY_Jmc0ffInqP6dBIyQ][《Clubhouse：网红App究竟能火多久》]]

    Clubhouse的成功在哪儿呢？可以肯定的是，显然不是由技术力量驱动的。从产品的生
  命周期看，Clubhouse现在应该还处在幼年，因而要预测其未来的走向是十分困难的。不
  过，如果这款产品要保持持续的成功，并不是那么容易。它需要解决的问题还有很多。

** 2021-02-23
- [[https://mp.weixin.qq.com/s/7rsEbd3qojgYQi_EapRsSw][《有钱的码农，基金募资最后的「新大陆」》]]

    如果说，每家投资机构都有一张潜在LP的“捕猎”名单，伴随着过去几年声势浩荡的IPO
  钟声，那些获得惊人财富的founders正在成为GP们的关键目标。中国一级市场基金再次看
  见了新大陆：一拨new money正风尘仆仆而来，相比尽调周期更长、投资决策更为审慎、
  极度偏好“白马”的机构LP们，new money开始成为很多GP募资的最后希望。


- [[https://mp.weixin.qq.com/s/ij8au8ZPDR9GJ3GsfMbj_Q][《哔哩哔哩80页深度——从“人货场”看B站社区生态的养成》]]

    这篇专题深度报告，核心解决了以下问题：B站相比其他视频平台的核心竞争力在哪里？
  B站独特的社区生态是如何养成的？B站如何实现破圈？B站组织架构和管理团队有何特征？
  B站用户画像？B站用户未来还有多少增长空间？如何理解B站内容与创作者生态？B站在内
  容生态上采取怎样的发展策略？B站OGV和PUGV内容各自发展情况和差异化优势所在？B站
  UP主生态如何实现正向循环？B站平台的运营政策以及产品的底层设计如何帮助建立良性
  社区？


- [[https://mp.weixin.qq.com/s/Gmg3me-0_YTb2uh7fVPJFw][《李录：中国未来20年的经济大趋势》]]

    当我们投资一个国家的一家企业时，从某种意义而言，我们也是在投资这个国家。我们
  需要对这个国家有大致的了解。作为投资人，我们关注的是对未来大概率正确的预测，我
  们的分析尽量保持客观理性，摒弃任何意识形态及情感带来的偏见。今天会分为五个部分
  讲：中西方的历史文化差异；中国的现代化历程及近四十年的经济奇迹；当前投资人尤其
  是海外投资人对中国的悲观情绪；经济发展的三个不同阶段：今天中国与西方的位置；中
  国经济的增长潜力。


- [[https://mp.weixin.qq.com/s/zVsOa1jkPyrTQCUCllXOOw][《中国婚姻报告2021》]]

    婚姻是家庭的基本组成部分，但近年来，多种选择和无奈之下，中国人结婚少了、结婚
  晚了、离婚多了。随着社会发展，一方面新一代年轻人追求独立自由，认为婚姻是束缚。
  另一方面，高婚育成本使年轻人实现家庭变得更加困难。从人口角度看，人口少子老龄化
  问题正在削减适婚年龄人数，结婚“主力军”减少。“婚都不想结，还生什么孩子”，正成为
  一批年轻人的选择，结婚率下降、生育率下降和老龄化加重是互为因果的。


- [[https://mp.weixin.qq.com/s/qYnopUvEIfAtkHG8ML4xQg][《长期主义：做你余生中最重要的事》]]

    长期主义到底是什么？如何兼顾“长期主义”和“当下行动”呢？长期主义追求不变，而行
  动需要随机应变。这二者如何调和呢？本文将以乔布斯人生中最重要的决策原则为例，用
  一个独特的“双线模型”，来回答这个问题。这个“双线模型”，用大白话来说，就是：永远
  去做你余生中最重要的那件事。
** 2021-02-22
- [[https://mp.weixin.qq.com/s/w0wNA6rKjxAqW4OsLACxwg][《这个「视频版 Clubhouse」，成立一年就盈利，估值 21 亿美元》]]

    马斯克的「站台」让上线不到一年的 Clubhouse 彻底火了，然而无论是 Clubhouse 还
  是它的学徒们，都没能解决盈利的问题，但Hopin 做到了，在一年的时间里实现了
  ARR(年度经常性收入)3000 万美元，从 2020 年 2 月份开始，8 个月的时间里，Hopin
  的注册用户从 5000 增长到 350 万，企业会员达到 5 万个，估值达到 21 亿美元。

- [[https://mp.weixin.qq.com/s/guJQPKqFB2ivGYKMiZhP0g][《疯狂涌入整形医院的年轻人》]]

    市场飞速增长、消费观念变化、医美生活化、行业洗牌来临，随着资本入局、医美概念
  股引起资本市场注意，这一千亿级市场已然成为备受追捧的黄金赛道，不过不可否认的是，
  黑医美、安全问题依然是阻碍行业发展的绊脚石。同时在疫情的试炼之下，大浪淘沙的时
  代很快来临，医美行业将走向何方？

- [[https://mp.weixin.qq.com/s/lvPiMvpEaiQSsxiqbuyf-Q][《为什么这届年轻人不愿多生娃》]]

    “生孩子是一个非常复杂的系统，不单纯是经济原因，一对适婚适孕的夫妻背后面临很
  多东西，除了孩子，还有父母养老的问题，以及35岁以后自己的社会竞争力能不能保持
  住。”一位采访对象的观点或许代表了生育率低背后的普遍原因。提高生育率并非一朝一
  夕就能实现，我们采访了几位处于不同人生阶段的东北人和北漂，了解他们对生育率低的
  看法。

- [[https://mp.weixin.qq.com/s/GcIq_2yVbCkM-PuF4RUAVw][《芯征程丨苹果造芯三十年》]]

    从2010年拿出首款自研手机芯片A4开始，围绕着苹果芯片实力的争议始终未曾间断。事
  实上，在过去30年间，苹果已经通过一系列的自研、并购，甚至是打压、挖角、“威逼利
  诱”，即便在老首领去世后也未曾失去方向，坚定不移地践行着乔布斯当年的路线，最终，
  建立起一个庞大的芯片帝国。跟所有伟大的故事一样，苹果芯片帝国的成功，始于一次失
  败。

- [[https://mp.weixin.qq.com/s/4kN65Eu_mYKmC-GLig082g][《“打工”不是一切——与五位学者对谈互联网加班文化及其他》]]

    近两年，互联网公司的员工们开始越来越多地反思自己为了工作究竟付出了什么。
  “996”、“打工人”，与超时工作相关的关键词被反复提起，让更多人质疑，推动技术进步
  的大公司正在将我们带入一个怎样的未来。互联网公司在颠覆市场之后应当承担怎样的社
  会责任？企业追逐效率与员工追求幸福之间应当存有怎样的边界？奋斗精神与个人自由空
  间应当如何平衡？

** 2021-02-18
- [[https://mp.weixin.qq.com/s/INbSIgFtCiaIKzyajGdaeA][《你殊死进攻，也拼不过巨头一个部门？王兴切了三刀后……》]]

    很多创业公司老板都喜欢把“没有想不到，只有做不到”这句话贴在墙上，认为只要有伟
  大的梦想，就一定能够做到。但我们往往忽视了，创业是为了生存，不是为了死于竞争之
  中。竞争不过是创业中的一个环节而已，不到万不得已，没必要把自己逼到跟巨头正面殊
  死进攻的路上去。在竞争当中如何扬长避短，以弱胜强，这对每一个人都是第一命题。那
  么，该如何破题？

- [[https://mp.weixin.qq.com/s/vhNDY9YE6YrZwNurCNzUXw][《为什么年轻人都不愿生孩子了》]]

    人人都在担忧新生人口的骤减。在猝死频发、福报996、狼性007下生活的我们，曾有网
  友评论：这样的环境，生孩子给资本家做奴工？上野千鹤子还曾发出警告：当生育成本如
  此之高时，变得让“饱食穷民”们无法企及，养育孩子是否形成了再生产分配的新的阶级等
  级？

- [[https://mp.weixin.qq.com/s/gcvDoXmdReNX_Tt62PXVQg][《国运2021 | 后疫情时代的中国及世界》]]

    2020，大疫之年，艰难之年。新冠疫情及救市行动加剧了世界的分化与撕裂：穷人在通
  缩，富人在通胀。2021年，世界进入后疫情时代。各国头号政治任务是加紧注射新冠疫苗，
  打破一年来的“与世隔绝”。如此，人们将逐渐回到那熟悉的生活状态。然而，在回归熟悉
  与稳定的路上，大疫之年显现的冲突依然延续。本文从系统、空间与时间三大冲突，回顾
  2020，展望2021。

- [[https://mp.weixin.qq.com/s/eRAsxlkHTRAyYAUNV_Rd3Q][《辣条即将上市，深扒卫龙如何靠营销狂赚500亿》]]

    辣条，是许多人小时候魂牵梦萦的神级美食。然而，就像我们早已不是当年在学校门口
  分一包零食的小学生，辣条也不是当年的辣条了。前段时间，辣条界一哥卫龙爆出今年将
  赴香港IPO，募资10亿美元。接下来，我们就一起来看看，刘卫平是如何带着卫龙踏上IPO
  之路的。

- [[https://mp.weixin.qq.com/s/G6ZAOikQMWJLJc_ESrHczQ][《温顺的人，必将继承世界》]]

    说起温顺，你也许会想起羔羊，温顺，温柔，温和。不错，我们喜欢这些词汇，然而，
  喜欢并不代表“立场”，就像我们喜欢好人，却未必愿当好人，我们的话语体系里，温顺象
  征着弱势：人善被人欺，没本事才老实。我们推崇胜者为王，重利害而轻是非，愿意先有
  屠刀然后再放下来成佛。既然如此，温顺的人，何以继承这个世界？

** 2021-02-05
- [[https://mp.weixin.qq.com/s/gXgPgxRDuvfbTyCQYIv8zw][《核酸检测是门好生意吗？上市公司净利润暴涨数十倍》]]

    随着春节一天天临近，核酸证明成了归乡人必不可少的通行证。据交通运输部预计，今
  年全国春运期间发送旅客17亿人次左右，日均约4000万人次。若以80元/次官方指导价且
  不计隔7日需复测来算，光一趟春运，核酸检测市场收入就至少高达1360亿元。拥有对千
  亿级别的市场增量，核酸检测跃上风口，很多人没发现，这笔生意可太赚了。

- [[https://mp.weixin.qq.com/s/pF67tcyL9cQCmlAOdENE_Q][《从降维打击到败走中国，谁偷走了ZARA们的光环》]]

    今年1月，Inditex宣布将关闭旗下ZARA姐妹品牌Bershka、Pull&Bear和Stradivarius在
  中国的所有实体门店，在疫情冲击下，Inditex2020年上半年净销售额缩水超30%，亏损约
  15亿元。行业龙头尚且如此，其他快时尚品牌的境况不言自明，从2018年以来，国外快时
  尚品牌在中国市场接连受挫，从光芒万丈到跌落神坛，是什么拿走了快时尚的光环？

- [[https://mp.weixin.qq.com/s/hw1aR8HqsgytUK_hqhALow][《散户能赢，只是个传说》]]

    散户抱团斗华尔街的神话正在破灭，北京时间2月5日美股收盘，散户抱团股游戏驿站暴
  跌42%。2021年开年，美股为全球投资者上演了一场散户和华尔街空头机构的对决大戏，
  双方暗流涌动，较量远未停止。散户的钱包是有限的，他们背后的对冲基金才是真正的华
  尔街之狼，这是美国金融界两大狼群之间的战争，散户不一定赚到了钱，以散户之名默默
  操作这些的才是真正的赢家。

- [[https://mp.weixin.qq.com/s/155MoO8uPGQQ4T6lfULqnQ][《快手暴涨造富：有人三年狂揽9000万，创始人财富逼近刘强东》]]

    今日快手在港上市，钟声响起，交易开始，快手的涨幅迅速冲至193%，开盘股价报338
  港元每股，市值突破13880亿港元，折合11592亿人民币，1791亿美元。以此计算，快手市
  值超过京东（1466.65亿美元），成为中国互联网第五大上市公司。而快手两大创始人宿
  华、程一笑身家分别为1637.38亿港元（211.20亿美元）和1299.06亿港元（167.56亿美
  元）。

- [[https://mp.weixin.qq.com/s/JLeHWb4Ks7Oa053LWRjOfg][《年入几十万的硅谷人，失去了外卖奶茶自由》]]

    湾区10米家底，仍然外卖不自由，疫情这一年，财富上升的速度好像永远赶不上菜价、
  房价，甚至是奶茶外卖价格往上跑的速度，生活用品的价格上涨速度不断加快，这让美国
  大多数人的日常花销增加。但是谁剥夺了硅谷人民的外卖自由呢？这些在硅谷年收入几十
  万，甚至上百万美金的家庭却又说不清楚。

** 2021-02-04
- [[https://mp.weixin.qq.com/s/RwA4FH80MY-1GaMovFa-gQ][《快手上市，高光与隐忧》]]

    2月5日，“短视频第一股”快手科技将在港交所正式挂牌上市。然而，在响亮的敲锣声背
  后，面对前路的未知和强大的竞争对手，以及各种风险和隐忧，快手必须跑得更快，才能
  为解决这些已知的问题争取更充足的时间。

- [[https://mp.weixin.qq.com/s/kbXDyjwKmDpaJWj7jWz8ug][《5家门店，50亿估值；素颜进去，全妆出来》]]

    疫情笼罩下的2020年，线下零售业哀鸿遍野，但一股美妆新势力却在猛然崛起。美妆集
  合店话梅（HARMAY）靠着仓储式购物场景，颜值极高的装潢风格，以及琳琅满目的大牌小
  样，迅速成为全国潮流男女的时尚风向标。话梅爆火的背后，其实是本土美妆集合店崛起
  的大趋势，以话梅为代表的新一代美妆集成店，为什么能在这两年逆势爆发？

- [[https://mp.weixin.qq.com/s/tMsxexOLh1vWCE5OQotM4w][《抖音起诉腾讯，反垄断开年“第一枪”如何收场？》]]

    抖音和腾讯又“打”起来了。 2月2日，抖音在北京知识产权法院向腾讯提起反垄断诉讼。
  有专家认为，此次抖音对腾讯的诉讼应避免上纲上线，有利于平台经济的发展，“至少减
  少了关于未来发展的不确定因素。很多情形下，规则的模糊性要比规则本身更致命”。

- [[https://mp.weixin.qq.com/s/6QBOquI0i356OcdvSsoGXw][《如何快速判断一个行业是否值得加入？》]]

    俗话说：“男怕入错行，女怕嫁错郎。”其实对任何人来说，选择一个行业都是一件值得
  斟酌的事。但是，很多人想尝试拓展一下职业道路的可能性，却也苦于找不准方向。 这
  时，快速判断一个行业是否值得加入，就尤为重要。

- [[https://mp.weixin.qq.com/s/Uc2ZY42bAhqXwdGCRYv4pg][《贝索斯全职追赶马斯克》]]

    零售巨头亚马逊宣布，公司创始人杰夫·贝索斯将于今年第三季度卸任CEO，贝索斯解释
  未来在继续参与亚马逊重要项目之外，更多时间将被分配给蓝色起源（Blue Origin）太
  空飞船公司，他曾说蓝色起源是他手头最重要的工作，没有之一，而埃隆·马斯克旗下的
  Space X，更是成为蓝色起源最大的竞争对手，这场太空竞赛也是彼时的世界首富和第二
  富之间的较量，太空探索开始成为两人之间的一场另类“星球大战”。

** 2021-02-03
- [[https://mp.weixin.qq.com/s/Q5D0xJZjKTV-mC_1G6asig][《我所经历的字幕组消亡》]]

    字幕组，曾被誉为近五十年最出色的文化交流使者，让无数影视发烧友折腰。随着版权
  保护的加强，字幕组的风云江湖日渐凋零。国内的字幕组，兴起于2001 年，2006 年字幕
  组走进公众视野并进入鼎盛期。这种风光没有持续太久，2014 年，美国电影协会列出一
  批提供影视盗版下载链接的网站，其中就包括国内最大、也最具代表性的人人影视字幕组。
  人人影视在微博中说：「需要我们的时代已经离去。」

- [[https://mp.weixin.qq.com/s/s2hH8tsQIqn9mf1hejB_FA][《Ray Dalio最新万字长文：比特币，我是这么看的》]]

    那些支持比特币的人，把它吹成了一边倒的一个模样，而那些反对比特币的人，把它吹
  成了另一边倒的另一个模样。这种观点的分化，让我很担心。就像我过去写的所有文章那
  样，我尽量、尽量尝试展示事物的机遇与风险、好与坏、正与反，我尽量精确地传达、描
  述我理解的，比特币的真实价值和现实意义。

- [[https://mp.weixin.qq.com/s/in4FZS-_wynotz2-shmmHg][《独家 | 美团登顶之后：饿了么前高管首度披露与王兴对决的日子》]]

    美团、达达、饿了么的未来竞争焦点在于，谁更能满足消费者的即时需求？从外卖到即
  时零售，阿里本地生活能否“一剑封喉”？近日，多名从饿了么出走的管理层接受了独家采
  访，经过近十年创业，在一场又一场的大战中，他们收获成功的喜悦，也经历了不得不退
  场的暗淡。他们依然认为，当年阿里巴巴给出95亿美元的估值，是没有选择的选择，又是
  最好的选择，而美团被他们称为“无情的执行机器”。

- [[https://mp.weixin.qq.com/s/WeJ4VfWfMm2C7AR0jyNCsw][《我不看好 Clubhouse 在国内能火起来！》]]

    Clubhouse 这两天很火，是一个实时在线的语音聊天室，而Clubhouse 上的国内房间，
  大部分都是聊 Clubhouse 本身的，单独的声音体验，毕竟有局限性。所以Clubhouse 在
  国内之所以受到关注，大部分都是猎奇，圈内一些优质人群的关注，也带来了一拨观众。
  但是，热度终将过去。话题谢幕后，用什么来维持Clubhouse 的热闹呢。

- [[https://mp.weixin.qq.com/s/LfaH-PipPYO-kz5HMTGlpQ][《如何避免陷入“内卷化”的系统》]]

    每个人付出的努力更多，但总收益并没有变化，甚至变少了，这就是“内卷化”，“内卷
  化”一旦发生，在没有外力作用的情况下，身处局中的人是很难避开的。不过，“内卷化”
  这个本来很严谨的学术名词被全民讨论了半年后，有被滥用的趋势，常常跟“竞争”混淆。
  事实上，并非所有的竞争都是“内卷化”，所以讨论的前提是要分清楚，这个现象是不是
  “内卷化”。

** 2021-02-02
- [[https://mp.weixin.qq.com/s/quRq8zrUUXeOwlYnZx5RrA][《2021，残酷的K型复苏》]]

    跟很多人印象中大灾之后是大萧条不同， 2021被普遍认为会大反弹。疫情按下的是暂
  停键，金融体系、生产体系等没有崩溃。疫苗推广，刺激加码，社会重回常态，立马会迎
  来大反弹。IMF预测全球增长会达到5.2%，中国则会达到8%-10%。但这次复苏的轨迹会很
  特别，诸多机构认为是K型复苏。

- [[https://mp.weixin.qq.com/s/4X6O7JNQJmixezP6fQNzgg][《“互联网留守儿童”：大厂员工的下一代》]]

    在一线城市，新闻联播开始的时候往往是大厂员工加班的开始，尤其是在互联网双职工
  家庭看来，陪伴孩子更成了一种奢侈。作为互联网职工的父母，孩子虽然在大城市由老人
  或保姆照顾，但父母忙碌于工作，孩子几乎得不到陪伴，“互联网留守儿童”的苗头随之出
  现，说“互联网留守儿童”是新一代的“留守儿童”，并非危言耸听。

- [[https://mp.weixin.qq.com/s/MX6xvCC9TqfqRWF8hnHsDQ][《爆火全网的Clubhouse怎么玩？中国用户这样说》]]

    Clubhouse 是近期很火热的一个产品，除了在“本土市场”美国火，在日本已经窜到了
  App Store 总榜第一。目前采用邀请制，中国用户不多。用了几天，在此记录一些零碎的
  想法。后面还有几位 Clubhouse 用户的使用感受，也一起分享下。

- [[https://mp.weixin.qq.com/s/yJVab1kLWdfw0cFPnSqtWw][《为什么美国版「今日头条」长成了「58同城」？》]]

    字节跳动旗下的海外版「今日头条」——TOPBUZZ 已经逐步关闭。而由华人创立的News
  Break却快速增长，开始长期盘踞在美国新闻类第一的位置，人们可以在上面买卖二手车、
  找工作、叫家政服务、获取优惠券、报名本地活动、失物招领等等——俨然是一个「58 同
  城」。一家华人主导的新闻 App，为何能在美国的舆论环境中迅速崛起？一个新闻 App
  为何要干「58 同城」的活儿？这或许源自其独特的产品价值观。

- [[https://mp.weixin.qq.com/s/N7FPOAZkczzm_Pt9LTEmzQ][《TikTok 改变美国》]]

    2020年上半年，突如其来的疫情给势头正劲的 TikToK加了一把火，下载量稳居全球第
  一，下半年，来自美国的“禁用危机” 步步紧逼，TikTok在重压下挣扎求生，和美国商务
  部之间的拉锯战至今还未落下帷幕，在进入美国短短3年多的时间里，这个诞生于中国、
  年轻的应用程序，已经悄然渗入到了美国社会的方方面面，并推动各个领域发生着意想不
  到的改变。

** 2021-02-01
- [[https://mp.weixin.qq.com/s/Q_0swDRzP7TXbdoHNSp8WQ][《吴声：2021，疫后商业的新去处》]]

    如何总结数字商业的2020？对于用户更加数字化、更有效率的深入，「私域流量」成为
  过去两年的商业主命题。但我们谈论「以数字化运营人」太久，而这个关系与尺度的问题，
  在不确定环境中更加逼近答案。对私域流量的反思，是亲密场景的思考缘起。从「私域流
  量」到「亲密场景」，指向商业与人更合理关系的可能。人是场景，而非流量。

- [[https://mp.weixin.qq.com/s/1umcs74trh1OcZA8yijuWw][《香橼投降后，中概股们在被窝里笑出了声》]]

    这两天，美利坚韭菜揭竿而起闹得沸沸扬扬，坚决要把大空头按在地上摩擦摩擦，整个
  晋西北哦不华尔街已经乱成了一锅粥。甚至把香橼逼到了对大家说“对不起，我不做空了”。
  为啥机构这么热衷于做空？因为你不知道做空有多赚钱，知道做空机构有多赚后，你就知
  道为什么散户揭竿而起了。

- [[https://mp.weixin.qq.com/s/WQhaITPuefcvJSqRCrss4g][《独家｜抖音大战春晚红包： 社交、支付、电商齐上阵》]]

    今年抖音成为春晚独家红包互动伙伴，在玩法上实现了多样化的突破，包含锦鲤红包、
  春晚红包、点亮灯笼分红包等。抖音借春晚拉新和引流的巨大流量池，推动刚推出不久的
  抖音支付的快速启动，同时切入社交。抖音逐渐从一种娱乐方式变成一种社交方式，甚至
  是一个生活方式。而春节大战，对于抖音的这场改变而言，无疑是一次绝佳的机会。

- [[https://mp.weixin.qq.com/s/S1n7g0kH_plTb29hStig7w][《社区团购没熄火，他们春节还要发动一场「战争」》]]

    疯狂的低价促销让监管在2020年12月出台社区团购“九不得”政策，但这一盆冷水并未浇
  灭玩家们的热情。巨头们一方面拼命下沉，另一方面在北京、上海等一线城市悄悄扩土，
  以送券打起新价格战。疫情反复给社区团购打开了新的窗口期，农历春节就是一场关键战
  役。

- [[https://mp.weixin.qq.com/s/WdXurDCc_3_GAKlKbNzVaA][《B站底层UP主生存图鉴》]]

    墨茶的去世，撕开了B站部分底层UP主残酷生存真相的一角。基于对墨茶的缅怀，采访
  了数位90后底部UP主，他们中有人逃离，有人把UP主当作救命稻草，有人在忙碌的996之
  外，用UP主治愈孤单……他们的流量价值在B站内容生态中或许无足轻重，但作为“沉默的大
  多数”，他们的选择却更能展露B站生态中的生存真相。

* 一月
** 2021-01-29
- [[https://mp.weixin.qq.com/s/Pkv0ooZ2POkn-no2qW7YwQ][《为什么微信的“视频动态”失败了，但视频号却成功了？》]]

    什么是微信的视频动态？从数据的角度，微信的“视频动态”毫无疑问是一个失败的功
  能，对比“视频号”两者的渗透率是1.25%VS16.5%，这两个数据可谓天壤之别。那么为什
  么会出现如此悬殊的结果呢？为什么一个被国外证明过的成熟功能会如此水土不服呢？为
  什么视频动态在微信重视的情况下数据却如此难看呢？

- [[https://mp.weixin.qq.com/s/ijoc4zi-M_qRm7eAtg8gKQ][《为什么苹果、微软现在才开始造芯？》]]

    放眼国际，谷歌、苹果、亚马逊在芯片方面也相继投资，使用自行研发的芯片。芯片行
  业整体的风向变了，这仅仅是因为英特尔在制程上落后了吗？为什么这些顶尖的公司都不
  约而同在这个在这个时间节点上开始自研芯片呢？明明是产业分工的发展逻辑，现在又闯
  入了几个实力强劲的搅局者，苹果、微软、谷歌们可以成功吗？

- [[https://mp.weixin.qq.com/s/SD7c9XWPbmxIrjqYXK4S0Q][《李一诺：女性别把评判自己的权力拱手让人》]]

    在长江商学院的课堂上，主持人问李一诺。如果评价自己的人生和选择，她会打多少分。
  李一诺想也不想：“100分。”她说，其实这是一个典型的女性更频繁提出，也更在意答
  案的问题。“男性才不会到处问别人，你给我打多少分。”她语速极快：“女性总是把评
  判自己的权力拱手让人。”

- [[https://mp.weixin.qq.com/s/wOITKe7lOhLjufz-hi5RwA][《小众社交围剿腾讯》]]

    关于腾讯在社交上的动作，大多数人的目光都只会聚集到微信和QQ身上，鲜有人注意到，
  在过去的两年时间里，腾讯在小众社交赛道做了诸多尝试。近些年层出不穷的陌生人社交
  产品，不断分食着社交这块“大饼”，使得以社交起家的腾讯不得不战略性反击，频频推
  出陌生人社交产品试水。社交赛道已然暗潮涌动，腾讯亟需找到行业突破口，再次为自己
  续命。

- [[https://mp.weixin.qq.com/s/jRq7pgazhUfhlRwlnIXYdQ][《科技巨头都来造车，打的什么算盘？》]]

    继社区卖菜之后，科技巨头又盯上了造车。一年前，新造车这个赛道里，最活跃的是特
  斯拉，以及以蔚来、小鹏、理想为代表的造车新势力，如今，名单里增加了百度、阿里、
  华为、富士康、苹果，如果算上投资这种形式，还有腾讯、美团——大大小小的科技巨头，
  都在抢造车这块蛋糕。为什么科技巨头都在造车？新造车股价暴涨、疯狂造富之后，巨头
  们又在打一个什么样的算盘？

** 2021-01-28
- [[https://mp.weixin.qq.com/s/tEW8npHbzX84-TV2ogmm5g][《美国政治的起源与挑战》]]

    全球政治秩序的不确定性将成为21世纪第三个十年的首要挑战。中美脱钩、科技泡沫、
  债务危机、贫富分化、中产下沉、社会撕裂……政治成为了全球主要矛盾的制造者。当政
  治正确、政治选票与政治自利压倒了国民理性、国民诉求与国民利益时，这场斗争便给全
  球政治学界带来了极大的困扰：是民主政治正在退化，还是一切矛盾正被美国宪政内化？
  到底是群体大众的反叛，还是知识精英的背叛？

- [[https://mp.weixin.qq.com/s/WugAqSDdzehE3I41lK09mQ][《大浪淘沙：中国保险三十年》]]

    复盘中国保险三十年，沉浮起落，皆是时势使然。如果一家公司只想着利用金融牌照套
  取各种融资，买贷循环，在政商关系中纠葛不清，注定难以走远。而如果一家公司可以沉
  潜下来稳扎稳打，并能够抓住历史进程中的金融和科技关键节点，它又怎么会走不远？大
  浪淘沙，谁能立于浪潮不倒？归根结底，在不忘初心、守正出奇。

- [[https://mp.weixin.qq.com/s/XE7bqR3w0IGBTofyqSS_cw][《抖音抢走了拼多多的支付 “核按钮”》]]

    支付宝和微信支付双雄并峙，并不意味着支付市 场上缺乏竞争——争夺移动支付第三名
  的发令枪在2020年就已打响，而决出雌雄的关键时刻已经到来，那就是近在眼前的2021年
  春节。这场竞争的参与者壁垒分明：一类是交易型公司，如美团、滴滴、拼多多、携程；
  另一类是内容型公司，如字节跳动、快手、B站。

- [[https://mp.weixin.qq.com/s/FAi05CRrT6DfmDRCt1MxkQ][《深氪｜深度调查：千亿芯片大骗局》]]

    为什么仅仅时隔一个月，千辛万苦求来的宝贝“光 刻机”，就被抵押出去换钱了？诸
  多地方官员愤怒声讨：“凭什么说（弘芯）投了1000 个亿？那不就是骗子！”弘芯最初
  的几个攒局人是怎么把武汉政府、业绩泰斗蒋尚义，以及众多合作公司，一步步骗进入了
  这个“千亿骗局”？更重要的是，对于诸多急于“造芯”的各地政府、各路资金，怎么避
  免再次踏入“弘芯式骗局”？

- [[https://mp.weixin.qq.com/s/SFfpWxaizhdIJCNNNIAVoA][《视频号不是抖音》]]

    随着视频号的出圈，很多人对于视频号的分发推荐逻辑感到好奇。为什么同样的一条内
  容，在不同的平台差别这么大？一条内容究竟是如何出现在视频号上的？如何才能让自己
  的视频号被更多人关注到？另外，微信是一个去中心化的工具，视频号却有中心化的推荐
  机制，二者如何平衡？本文将从视频号的推荐机制，分析到底是谁在影响你所看到的视频
  号。

** 2021-01-27
- [[https://mp.weixin.qq.com/s/9P7vmpTNvsbJxGsdLT5tsw][《职场生存指南 2021 版》]]

    过去没有所谓的铁饭碗，现在没有铁饭碗，以后也不会有。即使是国企，也未必有机会
  一路轻轻松松做到退休。所以，随时要琢磨自己职业生涯的各种可能性。如果你已经可以
  看到自己职业的终点，那我建议还是趁早换工作。一眼望到头的日子，不会有什么乐趣。

- [[https://mp.weixin.qq.com/s/KqGsAu0SNqKlwewOudop2Q][《中金：就地过年影响几何？》]]

    近期国内多地报告本土散发病例和聚集性疫情，就地过年将是不少人的选择，这个变化
  如何影响一季度GDP增长？就地过年和疫情防控对于2021年第一季度GDP的影响有正有负，
  总体影响可能尚需视疫情的演变以及春节期间生产和其他活动的安排而定。目前我们仍然
  维持2021年第一季度实际GDP同比增速19.5%的预测。

- [[https://mp.weixin.qq.com/s/MyYaOWuUx3bcaAbsJOuyMg][《新消费品牌崛起的动力与创业机会 | 2021创业何处去》]]

  2020，百年一遇的疫情让许多满怀信心的创业者折戟沉沙。幸运的是，中国经济环境因果
  断的防疫措施而稳定，产业结构的调整，技术与商业模式的更替，因为稳定的国内环境而
  继续。2021年开年系列文章以「2021创业何处去」为主题，梳理一些我们看好的方向赛道，
  希望对创业CEO们找方向有帮助。

- [[https://mp.weixin.qq.com/s/kOqtDv5lzvqpvby8rFFsjg][《潜望｜专访比尔·盖茨：新冠疫情正在重新定义我们这一代人的生活》]]

    作为将关注全球健康作为使命的盖茨基金会，在过去一年不仅见证了新冠疫情的发展，
  积极投身到抗击疫情的第一线。在2021年题为“全球健康与你我休戚与共”的公开信发布
  之际，比尔·盖茨他表示，正如第二次世界大战是我们父母那一代的决定性事件，我们正
  在经历的这场新冠肺炎疫情也将重新定义我们这代人的生活。

- [[https://mp.weixin.qq.com/s/m2EqAP0EncAn2LLfy_64fQ][《暴富制造机，茅台通往全民信仰之路》]]

    绞尽脑汁抢茅台的消费者、“哄抢”茅台股的基金公司、茅台股价越长越高......疯狂
  之下所有人都恐慌：何时会崩？当前1322家基金持有茅台，仍然稳坐公募基金第一大重仓
  股宝座， 跌不起的茅台同样焦虑，如何维持长期暴利是茅台要为二级市场续写的神话。
  经销商、电商、机构、股民、消费者都坐上了茅台这张赌桌，现在他们都想赢，现实吗？

** 2021-01-26
- [[https://mp.weixin.qq.com/s/2zs8gS09-ubS12tzf1PNwQ][《新消费创业狂欢背后：95% 的品牌是平庸的》]]

    从渠道、消费者、品牌三个角度去分析，新的渠道是否加速了新品牌的出现与消失，消
  费者正在发生怎样的变化，下一个新品牌到底会 以怎样的方式出现？

- [[https://mp.weixin.qq.com/s/_y6d43VvzRoL_OLndSREWQ][《QuestMobile2020 中国移动互联网年度大报告》]]

    今天跟大家分享2020年中国移动互联网总结，将从全盘维度，以八大关键词，全面展示
  新变化，跟大家分享一下大盘存量时代，沉闷而压抑的市场格局中，新生如何在寒冬中孕
  育，变局如何在僵局中破茧、后浪如何在困顿中突围！

- [[https://mp.weixin.qq.com/s/LOxVudqdzJ8J1TUSOrfZJQ][《便利蜂庄辰超：人的效率低下，我们用算法大规模扩张》]]

    便利蜂创始人庄辰超曾非常细致地讲述了他是如何分析市场机会，找到了创业切入点，
  创立了便利蜂，并且如何用一套强大的算法系统来实现经营决策的无人化。人类员工很难
  综合考量做出决策，大家都在说数据赋能人类决策，但对于一个复杂的店铺，数据就算赋
  能，一个店长也无法决策。今天我们回顾一下庄辰超的经典课《便利蜂：算法驱动，升级
  便利店体验》

- [[https://mp.weixin.qq.com/s/dcHmLA_iclaX6_UZx0YIFw][《快手失去4000万“老铁”》]]

    2020年在春晚庞大的流量冲击下，快手抗住了前所未有的峰值，远超快手制定的K3战役
  目标——3亿DAU。然而2021年1月24日，在上市前夕，快手更新了招股书，并披露了2020年
  下半年的用户数据：截至2020年11月30日止11个月，快手的平均DAU为2.638亿，和之前的
  峰值相比，至少4000万“老铁”消失了。

- [[https://mp.weixin.qq.com/s/Rl0Ks-v25Aa5EyIYp_QmJQ][《电商大战二十年》]]

    亚马逊的CEO贝索斯曾说：“个人品牌就是你离开房间后，房间里这群人对你的评价。”
  随后，贝首富的负面新闻被曝光，这位大佬一度被美国劳工协会称为“魔鬼”。不过，这并
  不阻碍贝索斯个人品牌的漂洋过海，在中国做电商创业的，几乎都是贝索斯的信徒，在贝
  爷的影响下，风起云涌，一场绵延二十年的电商大战就此拉开序幕。

- [[https://mp.weixin.qq.com/s/OCJCpBeLNZoM0WHV8JigsA][《中国为什么需要“双循环”》]]

    今年下半年，国家提出“深化供给侧结构性改革，充分发挥我国超大规模市场优势和内
  需潜力， 构建国内国际双循环相互促进的新发展格局”。中国外贸的“动脉”供应链，“双
  循环”战略之下，在疫情、国际政治、国内变局的多重影响下，供应链是否还是优势？中
  国外贸业将会迎来什么变局？

** 2021-01-25
- [[https://mp.weixin.qq.com/s/nS_x7ldRXsfH0-xZX8eqUw][《微信为什么要做输入法？》]]

     张小龙公开课演讲中提到的五大实验性项目，大部分都已经 在微信8.0版更新中得到
  呈现，唯一漏掉的是在张小龙看来依然“值得投入”去做的微信输入 法。张小龙点出市面
  上已有的输入法产品存在监控用户聊天记录的弊端，其实微信做输入法 除了提到的保护
  用户隐私外，还有更深层次考量:通过输入法优化聊天体验，提高微信搜索的效率，并借
  此加 大对微信内部公域流量的开发运营。

- [[https://mp.weixin.qq.com/s/BB5i4-IJhkcQqI30Muql9w][《连麦张小龙：谈微信 8.0 背后的思考》]]

    时隔两年， 微信终于在它十周 年之际发布了最新 的 8.0 版本。涉及表情、状态等一
  些功能的 迭代，引发了不少讨论。1 月 22 日晚间，在 视频号直播间里，极客公园创始
  人张鹏和科技评论作者潘乱跟微信创始人张小龙进行了一场 连麦，聊了聊微信 8.0 背后
  的思考。

- [[https://mp.weixin.qq.com/s/9VhMwivL6Dp1gTK7plWHTQ][《脉脉成为互联网大厂公敌》]]

     拼多多和B站的两件大事，把脉脉推上了舆论漩涡。这家2013 年成立的公司因为“职场
  匿名”正在逐渐成为“各大互联网公司的内幕中心”，有人将之成为树 洞，也有人将之称为
  “互联网茶 水间”，但同时，脉脉也引起了越老越多的互联网大厂的不满， 成为互联网大
  厂 们的“公敌”。

- [[https://mp.weixin.qq.com/s/vlLZoN-4aUHlBQvprtXSaQ][《我的年终奖，泡汤了》]]

    还 有半个月就要放假过春节了，北上 广深的打工人，纷纷开始讨 论起两个话题，一
  是春节能不能回 老家，二是今年还有没有年终奖。随着疫情又开始出现， 有人开始盘算，
  今年估计是回不 了老家了，这剩下半个月打工的日子，就指望年终奖了。但 是，对于一
  些人而言，老家回 不了，年终奖，可能也没了。

- [[https://mp.weixin.qq.com/s/S3YpNBi_ddlw6NI1OGki3A][《独家丨虾米关停之际，抖音快手借道音乐暗战TME》]]

    2月5日，走过12个年头的虾米音乐将正式关停，国内的头部音乐公司仅剩下腾讯音乐娱
  乐集团和网易云音乐。有行业人士认为，以后除了这两家外，很难再有新的竞争者出现，
  打破音乐市场两极的格局。但是，随着抖音、快手等两家短视频的崛起，其音乐属性正在
  不断被发掘出来，并开始转为向音乐平台进发，抖音快手两家的强势入局，或为国内的音
  乐市场带来新的改变。

** 2021-01-22
- [[https://mp.weixin.qq.com/s/iLUb8EPmZ77QYZinpbk0QA][《春晚红包里的巨头权力变迁史》]]

    2021年，“谁在春晚给全国观众发红包”这件事出现了一些波折和悬念。从2015年的微信
  摇一摇、2016年的支付宝集五福，再到2020年快手的10亿现金红包，以及2021年即将上场
  的抖音，互联网公司你方唱罢我登场，春晚这方舞台上，见证着互联网老牌巨头的更迭和
  新贵的诞生。谁在春晚上发红包，成了每年春节的一大悬念。而每次春晚谁来发红包，背
  后反映的是巨头之间的地位和格局变化。


- [[https://mp.weixin.qq.com/s/LFJ5915hFVwZusUD-G7qxA][《谁先在视频号上赚到钱了？》]]

    “如果你在2012年错过了公众号，在2018年错过了抖音，那么在2020年，你不能再错过
  视频号了。”去年今日，全网最会赚钱的那批人集体闻风而动，视频号千呼万唤始出来。
  尽管视频号想要激发的是每个普通人创作的意愿，让每个个体都能被看见，但这并不妨碍
  有志者在这片“大水”里成为“大鱼”。


- [[https://mp.weixin.qq.com/s/zZg2Kiavda7N1Eu4eYpQ4A][《快手往事：得老铁者，失天下》]]

    2017年7月，快手总部数据团队为老板们分析了一款来势凶猛的产品：抖音。耐人寻味
  的是，汇报结束后，在座高管没反应。一年后抖音日活突破1.5亿，超过了快手，彼时，
  前者上线五百天，后者上线七年。一个产品的命运，当然要靠自我奋斗，但是也要考虑到
  历史的进程，曾经坐拥绝佳历史机遇的快手，是如何一步步沦为配角的？在快手上市前夕，
  我们复盘这个过程，看看当年到底是哪出了问题。


- [[https://mp.weixin.qq.com/s/AukVk7vTd0gLl1_rirOy9Q][《基金经理的收入有多高？》]]

    在很多人的传统印象里，基金经理是超级金领，超高收入群体，年收入随随便便几百万，
  那么基金经理的收入有多高？实际上公募基金帮客户赚的钱再多，都只能赚个管理费，而
  且大部分利润还是公司股东的，基金经理也只是拿工资的打工人。


- [[https://mp.weixin.qq.com/s/TXXjqqldkIn1J5-H9jJVbw][《虾米倒了，网易云音乐还好吗？》]]

    虾米宣布倒闭之后，在线音乐平台的生存问题重新回到公众视野。音乐平台之间的竞争
  提高了版权成本，用户尚未形成付费习惯让平台盈利难上加难。已经拥有8亿用户的网易
  云音乐，能顺利“破圈”，找到新的盈利点吗？

** 2021-01-20
- [[https://mp.weixin.qq.com/s/vTF_7tlrGuRtA-0tFK-2QQ][《腾讯控股(0700.HK) 2021年微信公开课：生态能力愈发稳固，商业化大有可为》]]

  1月19 日，2021年微信公开课PRO以“激发WeBuild”为主题开讲，并通过线上方式呈现。会
  上微信 团队带来了小程序、微信支付、企业微信、搜一搜、小游戏、视频号的最新产品
  动态。1 月19日晚，张小龙亮相“微信之夜”，发表对微信十年的产品思考。


- [[https://mp.weixin.qq.com/s/feSZkGsE4ecivPhoR2bYNg][《乔布斯罕见亲撰檄文——苹果如何加速Flash的死亡？》]]

    Flash终于在2020年12月31日正式宣布死亡了，尽管在中国还以特殊的版本苟延残喘，
  但毫无疑问Flash终将穷途末路已经板上钉钉。在此过程中，苹果是加速其死亡的关键变
  量。今天，卫夕和大家讲一讲苹果和Flash母公司Adobe交锋的一个精彩片段，这个交锋过
  程集中展示了苹果创始人乔布斯的雄辩与远见。



- [[https://mp.weixin.qq.com/s/DQs4WmfykyqVtURF8F-4xQ][《张小龙：微信十年的产品思考（附万字全文）》]]

    1月19日消息，在微信成立十周年之际， 一年一度的“微信之夜”也正式启动。在微信之
  夜上，腾讯公司高级执行副总裁、微信事业 群总裁张小龙亮相。在接近一个半小时的分
  享中，张小龙提到了关于视频号、直播等多个功 能诞生的点点滴滴，并对微信十年做了
  总结。以下为张小龙演讲实录全文。


- [[https://mp.weixin.qq.com/s/wgZEf1bJ3BZeyz5LLQrnPQ][《沸腾十五年 | 游族林奇和远去的网页游戏江湖》]]

     左林大叔今天八一八游族林奇和网页游 戏江湖。2009年，宋辰创办游族，林奇成为其
  天使。2011年，担任游族的CEO，自此，游族 也走上一条ARPG页游为王，收入狂涨的上升
  路线，2014年，游族得以借壳梅花伞上市。在 2014年后，页游江湖再无波澜，手游的全
  面崛起，诸多先行者在拥抱资本市场后并没有取得 预期是更为关键的外部因素。江 湖已
  经远去，但江湖上的人尤在，故事也还在发生。


- [[https://mp.weixin.qq.com/s/0Nqh1wz-kHOKrqOiJmFylA][《为什么长视频没有强算法推荐的产品》]]

      当算法推荐在图文、短视频领域大杀四方、所向 无敌时，我们曾经一度以为在内容
  分发领域，算法就是无敌的、是降维打击。但是奇怪的是， 现在算法在长视频领 域依然
  没有取得主导权。那么为什么长视频没有强推荐的产品？如果要 找一个正确的维度 去看
  待这件事的话，那么考虑的点主要有两个：长视频与算法的匹配以及 商业上ROI是否可行。

** 2021-01-19
- [[https://mp.weixin.qq.com/s/xr5YxtxFZC960WA8s4ROVQ][《2021年微信公开课PRO最全干货集合，划重点啦！》]] 一年一度的微信公开课，终于来了。今日早上，期待已久的2021微信公开课PRO在广州正式开讲，本届大会以“WeBuild 激发”为主题，对视频号、小程序、微信搜一搜、企业微信、微信支付、微信小游戏等六大生态领域进行了内容分享。


- [[https://mp.weixin.qq.com/s/PnpVTrmKIXDEgDq2NYzCrA][《快手槽点重重，投资价值在哪？这篇说清楚了》]] 快手不同于B站，长线和短线逻辑确定性都很强。快手在游戏与改版上的一系列动作，明显显示出加速变现的意图，从而提高短中期业绩的成长性与确定性。因此，我们认为当前中短期变现加速才是快手当前的核心逻辑。


- [[https://mp.weixin.qq.com/s/ffHQXc9Q6s1bfeAYyJa_Hg][《维基 20 周年，为什么它是「互联网奇迹」？》]] 如果维基百科当年没有被创立，恐怕在今天这个碎片化、商业化的互联网世界，它根本无法诞生。在创始人Wales 看来，当下有不少人被困在「信息茧房」，也有人对国家、种族分裂异常狂热，而维基百科会永远是那道促进人们理解的桥梁。Wales 曾亲自讲述了维基百科的往事，探讨了知识和平台的关系……他所说的，最终能你更明白维基百科为什么是一个奇迹，一个关于革新的奇迹。


- [[https://mp.weixin.qq.com/s/u9-epDfMQwUaSuXRyf1iSw][《年轻人拿考公赌明天，机构用焦虑割韭菜》]] 在公考这条路上，为求“上岸”，所有人都在全力奔跑，在社会和家庭共同编制的焦虑网下，公考培训机构正在成为最大的受益者。巨大的需求刺激下，公考培训市场还在不断地扩张、再扩张，对于如何贩卖这场“焦虑”，公考教育培训产业链上的每一个参与者都在绞尽脑汁。这是一个巨大的赌场，每一个参与者都在赌。


- [[https://mp.weixin.qq.com/s/f7Nrsd0dNtddZGE9zadHlw][《郑爽回应“代孕弃养”，这背后是一条怎样的产业链？》]] 郑爽前男友张恒的一条微博“引爆”热搜，他滞留美国是因为要照顾两个孩子，而根据时间推测孩子为代孕所生。此事也引发了网友对代孕产业链的讨论，事实上，目前国内明令禁止代孕，但在美国、乌克兰、俄罗斯等国家的部分地区，代孕已经形成一条成熟的产业链。我们来看看网上流传的张恒、郑爽孩子的出生证明透露了哪些信息，以及网友们热议的代孕背后是一门怎样的生意。

** 2021-01-18
- [[https://mp.weixin.qq.com/s/MYvZ1zcGj9NO-EHcBzmQow][《B站，终于活成了抖音的样子》]] 近日，B站APP端在内测单列信息流的沉浸模式，从外表看来和抖音的播放界面别无二致，最大的不同是，B站的“短视频模式”仍保留着弹幕功能和横屏切换选项。去年抖音博主大规模“入侵”B站，一年过去了，随着越来越多不同平台视频创作者的入驻，遗世独立了十年的B站，逐渐出现了被同化的迹象。B站越来越火，却越来越不像“B站”了。


- [[https://mp.weixin.qq.com/s/VYddE5d94FWNSAdVL9LEUg][《2020研究洞察：新消费品牌的8大增长驱动力》]] 2020年，我们研究和拜访了近百家消费零售企业后，决定思考几个更深刻、更本质的问题：为什么有的品牌能够比别人增长更快？是什么驱动了它们的高速增长？这其中既有年轻的新锐品牌，又有做出革新的传统品牌 - 我们统一将这些取得爆发式增长的品牌称之为新物种。接下来，用数据和案例为大家阐述高速增长的新物种所具备的8大特征。


- [[https://mp.weixin.qq.com/s/0Bdgk0zJljtF0tuWUGriWA][《陆铭：大城市不够大，中国区域发展的三个趋势》]] 有一个话题在接下来的十四五期间以及更为久远的时期会决定中国经济下一阶段是否能够健康可持续地发展，这个话题就是中国的城镇化。首先，我们来讨论一下在城乡和区域发展方面的结构调整空间；第二个方面，结合经济双循环的背景，来谈一谈城乡和区域的发展；最后，讨论一下城乡和区域发展方面的政策建议。


- [[https://mp.weixin.qq.com/s/TF4C80nVUwzzKUxwXNjv_Q][《抖音需要春晚》]] 据称，拼多多不再担任2021年春晚独家红包互动合作伙伴，抖音将补位。铁打的春晚，流水的赞助商，广告争夺赛的背后，是一部中国商业权力变迁史。这其中不仅是对流量与商业话语权的争夺，也是对商业地盘的争抢。从支付领域到短视频，通过被称为“中国经济晴雨表”的春晚，可以窥探出下一个风口。


- [[https://mp.weixin.qq.com/s/4Q4GmTwnHvtD_OyXC4DooA][《2020年，全村女孩都去割了双眼皮》]] 在“容貌焦虑”的背后，是一个数千亿的医美市场。中国医美市场兴起于2008年前后，2014年前后进入爆发期，到2018年前后，一二线城市的增速开始放缓，随后，更多的医美机构，开始在下沉市场中探索机会。下沉市场相对于一二线城市来讲，竞争压力小，成本低，所以更容易盈利，因此众多医美机构也需要打开下沉市场，从而降低获客成本和扩张市场。

** 2021-01-15
- [[https://mp.weixin.qq.com/s/IPlNQjQ1mBDJTRiNaQBcuw][《腾讯华为之争背后，一个时代正在落幕》]] 华为游戏中心在1月1日发布公告宣布，因“腾讯单方面就双方合作做出重大变更”，华为应用商店将全面下架腾讯游戏。腾讯与华为的这次下架事件，让游戏公司与硬件分发渠道的冲突逐渐从幕后走向台前，应用商店的黄金时代正在过去，牢不可破的市场地位已经在悄然消融，也并非是两家公司层面的斗争，而是两个行业和一个时代变革的缩影。


- [[https://mp.weixin.qq.com/s/9WfxyseqGsSIIUx4L4GcMQ][《科技公司“出硅谷记”》]] 2020年，大量的科技公司正在出走硅谷，它造成这一现象的，除了摆在台面上的加州房价、税收、监管环境因素之外，还有一些更深层次的东西：就像美国在过去几年展现出来的系统性分裂一样，硅谷也在分裂。谁走了？谁留了下来？从这些公司的对比中，你或许也能观察出不同硅谷公司，已经展现出的文化、意识形态上的分裂。而这种分裂，伴随着四年前特朗普的上任和自那以后愈发严重的美国社会整体的撕裂，早已有表征浮现。


- [[https://mp.weixin.qq.com/s/gEDCeQ905y6P_xHUzIVs2w][《在闲鱼和小红书上，我们找到了年会存在的最大意义》]] 每到年底，一些打工人的心里就越没底。这种不安的情绪常常来自两个方面，年终奖的额度和年会的组织力度。今年由于疫情影响，多地出台了相关政策，公司年会或是取消或是延期，但最近社交网络上关于年会的话题仍然不绝于耳。 我们来看看大家对于年会都在吐槽什么？大家在年会上都是怎么争奇斗艳？抽奖环节又有哪些有意思的现象？


- [[https://mp.weixin.qq.com/s/HfYNd3WY5-VXWSwlajHi2Q][《悟空问答关停：字节跳动的第一场败仗》]] 被“战略放弃”的悟空问答，即将退出字节跳动的App阵营。2021年，当初一时风光的“悟空问答”落幕，重新回复到原本的名字，以头条问答的形式继续存在。悟空问答宣布关停的头一天，恰逢知乎10周岁生日。来势汹汹的对手划上阶段性句号，知乎成了与字节跳动对阵的各领域竞争者中，少有的获胜者。


- [[https://mp.weixin.qq.com/s/cyywLfN2YT3CLDasOGAA_g][《谁还去KTV？》]] KTV如今已不再是年轻人眼中时髦的代名词。社会的发展和互联网的普及给年轻人带来了更多元化的社交渠道和多样化的娱乐场所，对于曾经奉KTV为“潮流”的80、90后而言，深受追捧的KTV显然已成为过去，他们已经“背叛”KTV。

** 2021-01-14
- [[https://mp.weixin.qq.com/s/SOMTvXZP_dD1YISXf39Hsw][《围剿 B 站》]] 一年股价翻三倍、最新市值达 414.5 亿美元、坐拥“Z 世代”年轻人，破
  圈后的 B 站是这两年视频行业绝对的主角。B站已经向港交所正式提交上市申请，此次上
  市融资规模直线飙升，但这并不意味着它没有成长的烦恼，有一个最明显的现象是，野心
  勃勃的 B 站，正被卷入更为残酷的互联网竞争中。它赖以生存并引以为傲的 UP 主生态，
  正遭受着 BAT 们的“围剿”。


- [[https://mp.weixin.qq.com/s/RXrTI4fbNiBzxvyITlEijg][《从热爱到生意，中文播客走出「隐秘角落」| 反光镜》]] 播客是去年起被广告主新近重
  视的渠道，在 2020 年中国大陆播客的数量激增，这是继知识付费后，内容领域又一次有
  多家头部平台参与的罕见热潮。有一个现实是，在中国过往对于声音这一载体的挖掘太过
  有限，无论是生产端、消费端还是整个生态链条都没有充分发展，更别提如何赚到钱，但
  一切正在慢慢改变。


- [[https://mp.weixin.qq.com/s/gXZwukRgyN4Q59tdiA-V5Q][《2020 年，十佳 IPO 捕手》]] 2020 年，成为名副其实的全球 IPO 大年，伴随着的是创
  业者和投资机构们的狂欢，作为陪伴其成长的投资机构更是等到收获时刻。数据显示，在
  A 股 IPO 上市背后，PE/VC 渗透率超过 70%，除 PE/VC 还包括国有创投机构、产业基金、
  上市公司旗下创投基金、券商直投和险资旗下股权投资平台等。以下是按照各家机构在
  2020 年新收获的上市公司数量统计的前十名。


- [[https://mp.weixin.qq.com/s/XA_solDnK_wUPy3pCwb_Gw][《新冠疫苗已接种一个月，这里有 5 个你可能关心的问题》]] 自 2020 年 12 月 2 日起，
  人类正式列装抵御新冠病毒的 “生物防具”，疫苗。目前中国、美国、英国、欧盟等国家
  和地区已经批准六款疫苗上市。按照当前的接种速度和疫苗产能，乐观估计发达经济体在
  年中实现群体免疫，全球群体免疫可能要再等等，但满足的条件包括疫苗有效率足够高、
  接种人群足够多且快、病毒变异有限、各国面持续时间同步等。那么到目前为止，新冠疫
  苗接种出现了哪些不确定性？


- [[https://mp.weixin.qq.com/s/suOO1rxaEIqe_pzeTZZpjg][《我如何掌握了爆款IP的创作秘诀？》]] 2017 年，两点十分动漫获得了阿里巴巴数亿投资，
  跻身成为全国前五的动漫企业。曾经不被大众认可的“动画片”为什么会呈现出惊人的市场
  活力？马斯洛需求模型还能预判行业内容趋势，洞悉爆款 IP 创作逻辑？消费升级时代背景
  下，“动漫+X”的 IP 共建模式如何为品牌赋能？小行业，大格局。如何迁移行业经验、立足
  产业看企业发展布局？两点十分动漫创始人兼 CEO 王世勇就上述核心问题进行了分享。

** 2021-01-13
- [[https://mp.weixin.qq.com/s/DyCJNLCX3DVVD_1UmGyuww][《拼多多员工自杀背后：什么在逼迫年轻人至死方休？》]] 拼多多员工谭某林从家中 27
  楼坠落，他毕业于 2020 年，刚在拼多多转正。我们无法判断小谭究竟为何选择自杀，但
  作为入职互联网大厂的应届毕业生之一，小谭曾与入职该公司的其他年轻人一起，深嵌电
  商巨头拼多多之中。当创新、自由、尊重逐步剥离，员工们陷于打卡、绩效、和监视之中，
  除了一笔高薪，我们该怎样定义这样的工作？


- [[https://mp.weixin.qq.com/s/BVk6td8JQjBF3VLfAl3twg][《信仰、教义和狂欢：蔚来卖的是车吗？》]] 蔚来最大的竞争力到底是什么？传统的 4P
  理论已经无法完全套用在蔚来身上，无论是互联网基因、中国版特斯拉、车界海底捞、小
  米衣钵的继承者，还是饭圈经济，都只是对它的片面解读甚至是误读，简单的“用户思维”
  四个字似乎也无法解释。在争议和噪音背后，这家市值已经 1000 亿美金的公司到底是在
  卖什么？


- [[https://mp.weixin.qq.com/s/b109dGf6y2Dpu47iV_cz5g][《为什么贝壳、百度、蔚来值得放在一起研究？》]] 贝壳、蔚来、百度，这三家公司的业
  务南辕北辙，放在一起比较未免有些“关公战秦琼”，完全不同的行业、完全不同历史阶段
  产生的公司、完全不同的业务阶段及财务状况，他们的可比之处在于哪里？实际上正因为
  基因与经历的不同，他们的估值涨跌正好体现出目前二级市场最主流的投资思路，也是最
  有希望在近期冲击千亿美元市值的公司。


- [[https://mp.weixin.qq.com/s/o-9sY2Nnx9CwleiII_01Eg][《为什么这届年轻人都去考公务员了？》]] 疫情的发生加重了中小企业的生存危机，公司
  举步维艰，每个身在其中的公司人都受到了直接影响，这也让原本就持续了十多年的“公
  考热”在今年继续升温，把国考的激烈竞争再次推向高潮。外面风雨太大，体制内成了年
  轻人最后的避风港。


- [[https://mp.weixin.qq.com/s/TnZ2YzF8nKDO0rueSvAN6w][《被算法监控的打工人》]] 越来越多的数字化管理手段进入企业，最普通的场景是使用 OA
  系统完成对员工考勤和工作量的全面监控，甚至可以根据企业需求编写算法，接管管理者
  的决策权乃至员工的主观能动性。对企业来说，将管理流程通过算法实施，无疑更高效精
  准，也能够降低管理成本；但对于一线的普通员工而言，则别有一番风味——这张数据大网
  密不透风，令人无处可逃，原本的工作方式和节奏被改变。

** 2021-01-12
- [[https://mp.weixin.qq.com/s/tUfTwDHheOhHhYV_K2zNKQ][《施展：一种新的世界秩序，正在到来……》]] 美国大选终局几乎落定，特朗普却仍在上演
  “最后的疯狂”。2021 年才刚开始，中美关系就迎来了一些全新变数：特朗普给制裁加码，
  禁止微信、支付宝等中国企业的准入，紧接着特朗普支持者又占领美国国会，民主党提出
  弹劾决议，指控特朗普“煽动叛乱”。高度撕裂的美国社会，还能好吗？中美两个超级大国
  的关系，又将走向何方？我们到底该如何与美国相处？


- [[https://mp.weixin.qq.com/s/7kMTN0ahCHII0ChBfawwjw][《QuestMobile2020 “Z 世代”洞察报告：3.2 亿“Z 世代”引爆消费潮流大迁移，如何抓住
  他们？》]] QuestMobile 数据显示，截止到 2020 年 11 月，95、00 后 Z 世代活跃用户
  规模已经达到 3.2 亿，占全体移动网民 28.1%；Z世代年轻、接受新事物的能力，带来了
  移动网络使用上的显著特性，社交、视频、网购、音乐、团购、游戏方面，活跃度都很高。
  这种趋势背后引发的消费潮流如何变化？又该如何抓住他们的？不妨看报告。


- [[https://mp.weixin.qq.com/s/9qPTAtm2H-bw3du19PufUA][《外卖骑手，巨头的炮灰》]] 外卖骑手是典型的平台经济下的非正规就业者，这个群体还
  包括网约车司机、代驾、快递员等。当一家家平台型公司采用外包、众包模式，快速招揽
  成千上万人为其工作，甚至简单到在 APP 上申请即可时，平台享受着廉价劳动力带来的
  资本市场溢价，但骑手的风险由谁来买单？


- [[https://mp.weixin.qq.com/s/k4Z94P4k7kFxQYPykqXCnw][《负债后，我才知道原来 200 块可以活一个月》]] 尼尔森 2019 年 11 月发布的《中国消
  费年轻人负债状况报告》显示，扣除把花呗、借呗等当做支付或理财工具并且当月还清的
  人群，90 后职场人实质欠债人群比例达到 57%，95 后职场人该指标也接近 40%。我们邀
  请了三位深陷（或曾经深陷）债务深渊的年轻人，聊聊他们都在过着怎样的生活。


- [[https://mp.weixin.qq.com/s/EZQorAzh3UQSw-awEveHvw][《燕郊离北京再近，也是河北》]] 从河北省三河市燕郊开发区进入北京，只需要跨过一条
  直线距离几百米的潮白河，隔着一条潮白河，通州的房价至少是燕郊的两倍。潮白河隔断
  的不仅仅是房价，也是北三县的尴尬地位。京津冀一体化也好，通州与北三县协同发展也
  罢，从燕郊的发展和房价来看，尚未有明显成效。“潮白河之隔，燕郊仍然是河北的燕郊。
  距离再近，北三县也不可能是北京。”

** 2021-01-11
- [[https://mp.weixin.qq.com/s/VW9KeeRGgvETJNoB-ip7KA][《张一鸣：CEO 总想招一些便宜的人，这才是最贵的》]] 历数中国互联网圈的高光并购事
  件，创始人出走的案例并不少见。然而在新巨头字节跳动的身上，却一批优秀的被收购团
  队创始人，仍然冲锋在字节跳动的一线。字节跳动如何做到低流失率网络互联网核心人才？
  今天，聊聊字节跳动的超高人效法则，以及他们和牛逼人才的相处之道。


- [[https://mp.weixin.qq.com/s/5_wFGsu4dVoP1yaqmciceg][《长沙可以没有互联网，但不能没有吃喝玩乐》]] 纵观湖南本土互联网企业，大众能想到
  与长沙相关的公司，除传统重工企业外，几乎都与吃喝玩乐相关。长沙独特的娱乐生态系
  统，反哺了一个独特的线下娱乐消费生态，从芒果 TV 到茶颜悦色、文和友、三顿半，长
  沙就这样，靠着看似闲散的吃喝玩乐生态成了当下的城市网红顶流。


- [[https://mp.weixin.qq.com/s/7X7xQq8lkaAJ3_Xyhf7URg][《江南春：两大红利消失，商业的逻辑变了》]] 分众传媒董事长江南春出席发表了最新演
  讲，他表示，5亿新中产存在巨大消费升级空间，企业家需要好好研究，这些中产到底爱
  什么？怕什么？缺什么呢？爱吃、爱美、爱健康，怕老、怕死、怕孤独，缺爱、缺心情、
  缺刺激，三爱、三怕、三缺，如果企业家的生意在三爱、三怕、三缺当中，那么这个企业
  在未来是有空间的。


- [[https://mp.weixin.qq.com/s/5gZMcKzhOORe6EvHc3OphA][《植发、整牙、祛痘广告充斥的微博，何至于此？》]] 作为中文互联网最高效的信息集散
  地，2020 年，平均每月有 5.11 亿人在微博上浏览话题和参与讨论。然而，热闹背后，
  是微博逐渐放缓的商业化，以及战略性产品的缺失。当刷量造假成为常态，优质广告主也
  正在离开微博，这使得微博的变现之路更加困难。


- [[https://mp.weixin.qq.com/s/-7Y4qiMwYh9jWvVyMTgSrg][《大众点评变味了？》]]众多网友最直观的感受是，大众点评变味了，看到的真实评价越来
  越少，虚假好评和恶意差评却越来越多。曾经小而美的大众点评，在被美团合并后，商业
  化导流的氛围越来越重，内容越来越杂，当一个以高质量 UGC 内容为生的社区，失去了它
  的口碑，大众点评的灵魂还在吗？

** 2021-01-08
- [[https://mp.weixin.qq.com/s/mXvAAXmeH40h6cgnaR9dvA][《李善友：2021，人生皆有意义，使命终将降临！》]] 越早的临在当下，越早找到自己的
  使命，你将越早的成为自己。我们怎么感知到自己的使命呢？我们可以间接感知它，即使
  不知道自己的使命是什么，只要我们相信使命的存在，它已经起作用了。而找到使命的关
  键一步就是把当下自己做的事作为一种修行，保持此时、此地、此事的“临在当下”状态。


- [[https://mp.weixin.qq.com/s/H923YnDSy6KAiv3qe_dFvA][《自动驾驶汽车的道德困境：如何拒绝乘客的错误命令？》]]我们对阿西莫夫的三条定律在
  自动驾驶汽车上的应用不得不有所保留，人工智能驾驶系统可以根据这些定律来设计，将
  其作为总体架构的一部分，但这些定律是一种愿望，而不是不可改变的法则。在自动驾驶
  汽车常态化之前，我们必须解决其中的道德困境。


- [[https://mp.weixin.qq.com/s/oCfHnuh9IwkZMFFulqWxnQ][《先生特稿 | 逃离拼多多的年轻人：“它的文化是不吝于用最强的恶意去揣测你”》]] “我
  不知道是从什么时候开始，有点恶意的对待身边发生的所有的事情。我觉得可能在拼多多
  这两年，让我对很多事情都充满了一种警惕性，因为它的文化是不吝于用最强的恶意去揣
  测你，就算是自己的员工。”一位离职员工如此说道。


- [[https://mp.weixin.qq.com/s/22NQIqkym8SXYhGK6b9PCw][《输赢之间：电影圈背后的资本江湖》]] 自 1994 年中国随着引进大片开始，走过近三十
  年的中国电影市场早已学会了拥抱资本，2019 年，中国电影市场已经达到 642 亿，成为
  北美之外的世界第二大电影市场，无数的资本愈加想吃下这块蛋糕，但资本可不讲蛋糕的
  味道如何，蚕食吃净才是本性。中国电影要做大，也要做好，最重要的，不能忘了来时的
  路。


- [[https://mp.weixin.qq.com/s/4N2H1bpTi3hOpeXP7tP5Qg][《微博输给了抖音们，还是输给了自己？》]] 微博近期公布了 2020 年第三季度业绩：收入
  与去年同期基本持平，归母净利润只相当于去年的约 1/4，录得 3380 万美元，看上去依旧
  普通平淡，但是竞争对手表现亮眼，令微博掉队态势明显。同期腾讯、百度，都超出市场
  预期，还有尚未上市的头条系公司也在不断蚕食着微博等竞争对手的份额。这些都令投资
  者为微博捏一把汗。微博是输给了抖音们？还是输给了它自己？翻盘还有希望吗？

** 2021-01-07
- [[https://mp.weixin.qq.com/s/m_0uHKe0KkMM1-iMmp394w][《冲刺“方便面第一股”》]] 中国快消品行业进入了一个高强度竞争的节点，今麦郎发展也
  需要突破，需要在多品牌、多场景、多品类、多渠道、多人群布局，投入会加大。如果不
  以上市的方式增强自身抗风险能力，挖宽企业护城河，企业就存在掉队风险。


- [[https://mp.weixin.qq.com/s/R6RjcNyDf1vjsS4A00QlQQ][《996、竞争与内卷化：穿透现实，得见真实》]] 新一轮关于 996 的争议热潮已经席卷而
  来，996 是如何席卷互联网行业的？很多人在谈及 996 时也总不忘补上一句“你不愿意
  996，有的是愿意干 996 拿高工资的人。”这个事实判断引发下一个话题：与 996 有着千
  丝万缕联系的内卷化。从 996 到内卷化，本质都是时代红利过后的泡沫。


- [[https://mp.weixin.qq.com/s/0XmjwPaO6obrAJEuIoN4Zw][《拼多多女孩“润肺”之死》]] 这个凌晨下班的女孩，生命结束在 22 岁的最后一个午夜，
  乌鲁木齐飘过雪的街头。激荡的舆论中，不少声音提醒，拼多多能开出两倍于行业的薪水，
  应届毕业生就能拿到五十万甚至更高的薪水——但这并不是属于润肺的故事。


- [[https://mp.weixin.qq.com/s/rkGw5QMbRR-w1mh12qH--g][《疯狂的在线教育：巨头进场、烧钱、二三梯队出局》]] 2020 年在疫情和资本的催化下，
  在线教育成为互联网公司最想长出的翅膀。2020 年的在线教育市场规模将达 4800 亿，
  千亿的市场同样受到了资本的热捧，融资、烧钱、并购成为了 2020 年在线教育的关键词。
  用一句话来形容 2020 年互联网巨头做在线教育的境况就是，腾讯稳中求进，阿里在摸索，
  字节意图大力出奇迹，百度在专注 AI 教育，网易在精炼平台......


- [[https://mp.weixin.qq.com/s/xu6O34YxIBRkoT81giX2PQ][《张一鸣会造车吗？》]] 不设边界的字节跳动，2020 年除了加码在线教育外，还有一个值
  得注意的动向：进军车联网领域。5月，字节跳动向媒体确认，已组建车联网团队，并计
  划推出自己的车辆信息娱乐系统方案，实现旗下抖音、今日头条等移动互联网产品在汽车
  终端落地。在巨头掀起的第二波造车浪潮中，围绕华为、百度，相继都被传出造车消息，
  字节跳动会不会成为下一个？

** 2021-01-06
- [[https://mp.weixin.qq.com/s/Chd2P4AFMrw9gMnOtIrcWw][《字节跳动怎么都十万人了？》]] 到 10 万人，字节用了 8 年，阿里用了 19 年，腾讯还
  没到。2020 年，字节跳动的员工总数从 6 万蹿到近 10 万，一个主业在线上的公司有
  10 万员工，这在几年前还是件难以想象的事。企业家往往警惕公司规模过快扩张，其它
  公司往往二三十年才能达到的规模，字节跳动压缩到了八年，但没有任何迹象表明，字节
  跳动将因此按下暂停键。


- [[https://mp.weixin.qq.com/s/l6zdiK9AlLe3rqAcACNeEw][《95 后厂哥厂妹口述：富士康不相信爱情，昆山处处是“单身大神”》]] 没有人一直年轻，
  却一直有年轻人。全球有 18 亿年轻人，互联网让这一代年轻人拥有了前所未有的自我表
  达权利，有了与广阔世界无限接近的渠道。他们从网络中汲取养分，又用自己的创造力反
  哺这个繁荣的生态，从爱好到职场，他们的人生观和职场观与父辈有了显著的区别，那么
  该如何正确认识这一代年轻人？


- [[https://mp.weixin.qq.com/s/-Sb2l0ArSEeCG0G7VvhNRA][《体检异常率 99%，这届打工人的身体有多差？》]] 2021 年的第一个工作日，996 的工作
  模式又冲上了热搜。一边是现代人越来越看重养生，一边却是越来越普遍的亚健康问题。
  每年让打工人们最心惊的可能不是年终总结，而是体检报告，从 2013 年开始到 2018 年，
  上海白领的体检异常率从 94%上升到了将近 99%——基数非常大，异常率更是不断逼近
  100%。


- [[https://mp.weixin.qq.com/s/ufYMN1kH7kkbhZTMY3Xv1Q][《比特币暴涨，独家解密谁在控盘比特币？》]] 过去两个月中，比特币的资产价格飙升，
  引领了整个全球加密资产行业的牛市回归，种种迹象表明比特币已不在局限于小范围的资
  本游戏中。究竟谁在控盘比特币？最大的利益攸关方是谁？谁在其中谋取了最大收益？未
  来比特币筹码还将以怎样的格局继续流动？人们一直以来都在探究全球比特币持仓排行的
  疑问。


- [[https://mp.weixin.qq.com/s/cfuMC3TiDkTGtzY2aMG59A][《涌动2020 | 社区卖菜的隐喻和终局》]] 每次创新，都意味着一整批人的就业被消灭。中
  国的社会环境过去对创新是鼓励的，但在经历几年的贸易摩擦和今年的疫情冲击后，社会
  大众在 2020 年突然重拾了对创新的审视，尤其是那些专注提升“效率”，却无法兼顾“公平”
  的创新。因此，围绕社区团购的争议，会给“优先效率，还是优先公平”这个问题赋予新的
  答案吗？

** 2021-01-05
- [[https://mp.weixin.qq.com/s/VhwjGkcIDPpIJ8tOxMjTCg][《那些离开互联网大厂的年轻人》]] 在 BOSS 直聘发布的《2020 年 Q3 人才吸引力报告》
  中，互联网行业在人才吸引指数排名中依然位居第二，第一则是和它紧密相关的 IT 行业。
  与此同时，脉脉发布的《人才迁徙与流动趋势报告 2020》也指出 ，2019 年，互联网行
  业里出现了可见的人才流出。一群人争先入局，一群人失望离开，互联网大厂，已经成为
  这一代年轻人新的围城。


- [[https://mp.weixin.qq.com/s/obhpjxEKpQwuyZV9wIS00Q][《独家调查 | 虾米真的被阿里巴巴耽误了吗？》]] 11 月末，一则“虾米音乐即将于明年 1
  月关闭”的传闻，触发很多虾米用户在社交网络上抒发各自对于这个音乐流媒体产品的怀
  旧之情，同时也有很多人在表达不满，认为“虾米是被阿里巴巴耽误的”。但虾米真的被阿
  里巴巴耽误了吗？


- [[https://mp.weixin.qq.com/s/HfrEhxIpT9XQTKZOWaUTpA][《2020 互联网没有新故事，只有新品牌》]] 2020 年是疫情下艰难的一年，处在互联网未
  诞生新风口、未出现现象级 App 的档口，资本市场因为大环境遇冷而格外谨慎，互联网
  行业极度缺乏新故事，但很少有投资机构会甘愿错过投资新消费品牌的机会，甚至，也有
  不少投资机构主动下场创立新品牌。开年之际，我们通过 6 个关键词，来回溯盘点 2020
  ——新品牌之年。

- [[https://mp.weixin.qq.com/s/j8MYW_zn2BXKo4luvb3xgA][《国内互联网公司为什么加班这么狠？》]] 互联网人似乎越来越忙了。就在最近，快手宣
 布展开全员大小周，为鼓励加班，字节跳动也表示要给周末加班的员工开出两倍薪水。但
 加班带来的劳累，有时候会成压死骆驼的最后一根稻草，1月 3 日晚，拼多多的一位年轻
 女员工在凌晨 1 点半回家的路上不幸猝死。是什么，让互联网人不得不以透支未来的方式
 奔跑？


- [[https://mp.weixin.qq.com/s/dBmSAzgIG-mR6g0YeUGntg][《2021，字节跳动的营收能折腾出广告圈吗？》]] 想到字节跳动，可能大部分人的第一反
  应就是“有钱”，字节重新定义了信息生产、分发、消费的关系，步步为营，字节正逐渐打
  造出了属于自己的“字节跳动系”王国。毫无疑问，字节跳动已经是中国最大的广告公司了，
  但是除了广告外，增长点在哪里？

** 2021-01-04
- [[https://mp.weixin.qq.com/s/zhIYcCMmIa-ipsurcyke3A][《特斯拉扔出了一片“二向箔”》]] 补齐轿车与 SUV 这两个最主流车型后的特斯拉，开启了
  中国本土化的新篇章。国产版 Model Y，使得特斯拉在包括燃油车在内的整个汽车市场竞
  争力大增，对比其他国产 SUV 新能源车，也是碾压级的存在；新品上市的同时，等于也
  顺手向中国汽车扔出了一片“二向箔”。特斯拉中国本土化策略由此迈入 2.0 时期，更紧
  张的贴身肉搏战揭开帷幕。


- [[https://mp.weixin.qq.com/s/DhVorf4GIqnbqXTVguY_Ww][《猝死、大小周、996：当互联网变成劳动密集型产业》]] 1 月 3 日晚，多多旗下多多买
  菜员工在凌晨一点半下班路上猝死，年仅 23 岁。有一个不可否认的趋势是，互联网对员
  工时间的挤占、对员工身体与心理造成的负担，已经成为互联网“造富”光环之下的灰暗一
  面。互联网人的工作时间正在不断延长，“996”正在取代 8 小时工作制，“大小周”也正在
  取代“双休”制度，互联网正在走向劳动密集型产业。


- [[https://mp.weixin.qq.com/s/1t2ayNR_HLSQY9fGfXpoMw][《为什么所有的 APP 都在炫富？》]] 你有没有这样一种感觉：无论打开什么 APP，都有人
  在展示自己的富裕生活，营造出一种“众人皆富你独穷”的氛围，可以说有社交的地方就有
  炫富。APP 们在变味，用户能感觉出来，从微博到知乎，从抖音到 B 站，从小红书到大
  众点评，为什么有内容分享的地方就有炫富？


- [[https://mp.weixin.qq.com/s/BN7uMLwEWdRxYXWCs1YfIQ][《榜单 | 真故 2020 年最值得阅读的 10 篇故事》]] 2020 年是一个宏大的话题，记叙
  2020 年的容器则是一个又一个渺小的个体。今天的推送中，编辑部票选出了 2020 年真
  故最值得阅读的十篇文章，并附上了推荐理由，作为记住 2020 年最后的仪式。2021 年
  我们依旧会坚持拾取、记录当下，跟我们一起，继续与真实为伍吧。


- [[https://mp.weixin.qq.com/s/Nn_b9Lv43xLFt9bY_pSwsA][《估值为什么是一种艺术而非科学 | 巴伦读书会》]] 无论是企业管理者还是普通投资者，
  都需要培养自己的金融直觉，以做出明智的金融决策。那么对于做出正确的金融决策来说，
  哪些才是最重要的财务数据，应该如何理解金融数据背后的意义？《什么是金融》总结了
  哈佛商学院金融学教授米希尔•德赛的在线热门 MBA 金融课程内容，本文整合《什么是金
  融》，解释了为什么估值是一种艺术而非科学，或者说披着科学外衣的艺术。
