#+TITLE: 优质文章每日精华选(2019)
#+DATE: <2019-01-02 Thu>
#+options: toc:nil num:nil

* 一月
** 2019-01-04
- [[https://mp.weixin.qq.com/s/riw2rye54IopziBDe4yPOQ][《公众号的 2018》]] 公众号的 2018 到底过得怎么样呢？新榜为此梳理了年度回
  顾 H5 背后的大数据，从中我们多少能窥见一二。18 一整年，公众号发文总篇
  数超 1.7 亿亿，其中原创文章约 872 万万篇，占 5%。


- [[https://mp.weixin.qq.com/s/vUK1o3m8ak4iJE-21-b0JQ][《我如何成了腾讯架构调整的炮灰》]] 这是一个因腾讯内部矛盾而遭受重创的创
  业故事。这不是一篇标准的商业报道，更像是一则商业控诉。虎嗅思考再三还是
  决定将其刊发出来，原因有二：其一，创业不易，尤其是在当前这个市场环境中；
  其二，从这个案例中我们可以窥探出腾讯内部各个部门复杂的利益纠葛，以及跨
  部门协作的难度。


- [[https://mp.weixin.qq.com/s/Ihi6g_AFlHeQ2uho4CVf2g][《共享经济大败局》]] 作为共享经济的鼻祖，Airbnb 创始人布莱恩•切斯基一定
  没有想到，他以 Airbnb 为依托推崇的共享经济于 2018 年在中国市场上遇到了
  前所未有的挫折。我们很难把共享经济的衰退简单归结到一个原因。


- [[https://mp.weixin.qq.com/s/sSR_DC2nv7t-H-Dta4IY1A][《2018 游戏行业报告：游戏出海、女性玩家、游戏直播成关键增长点》]] 2018
  年中国移动游戏市场依然保持增长，但对比上年增速出现快速下滑，销售收入增
  长放缓。这主要受用户需求改变、用户获取难度提升、新产品竞争力减弱等因素
  影响。


- [[https://mp.weixin.qq.com/s/HLUqfFaE8jiioVL-gfGsDg][《震荡创投圈：“钱荒”来袭，资本市场步入调整期》]] 募资难的阵痛已经传导到
  投资端，投资机构二八效应明显，战略资本开始收缩，一二级市场估值倒挂，钱
  荒笼罩着整个创投圈。公司们冒着破发的风险扎推上市，8 家公司同一天 IPO 敲锣
  的港交所奇景，或许是这场恐慌情绪的最佳诠释。
** 2019-01-03
- [[https://atlas.yidianzixun.com/hotevent/page?id=5c171c7cc1d19e004a9b80f5&yidian_docid=0Kr6wSXX][《2018 中国上市公司盘点》]] 2018 有一批科技公司集中上市，尽管这些公司上
  市地点不尽相同，也不一定都是中资企业，但有一点是相同的，那就是它们都已
  中国市场为根基……


- [[https://mp.weixin.qq.com/s/nEytmgfy8qeusC_wc3pQKQ][《围剿 Netflix》]] 今影视节目占据了整个互联网下行流量近 58%，其中仅仅是
  流媒体平台 Netflix 就消耗了全球 15%的网络流量，是全球下行流量的最大贡
  献者。观看网络视频已经是如今最常规的休闲娱乐方式之一，而这恰恰也是流媒
  体平台们最好的机会。


- [[https://mp.weixin.qq.com/s/w2ceA9oe1R6UxrOxbC-DRQ][《中国人工智能产业全貌 都在这张 AI 势力范围图》]] 2018 年，区块链的浪潮
  和共享单车的大起大落，却一度让人工智能黯然失色、星光不再。这并非坏事，
  远离了喧嚣泡沫，资本寒冬到来后的 AI 行业更加脚踏实地，无论科技巨头还是
  创业公司，寻找基于自身技术能力和特点的应用场景成为重中之中，“落地”是这
  一年的主题。


- [[https://mp.weixin.qq.com/s/nN40qpzDWhwCjVB-tQjoEg][《苹果 CEO 致信，中国区成为滑铁卢，下一个「iPhone」在哪里？》]] 高速增长
  的大中华区怎么了？16 年来首次下调营收预期，也是 iPhone 推出以来的第一
  次，这对于苹果并不寻常，库克公开信中提到此次调整的原因主要有 4 个.


- [[https://mp.weixin.qq.com/s/tS39FSBkfHTWyIug7_7a8w][《盘点 2018 年最热门的 10 大增长黑客策略》]] 今天，“增长”依然是互联网圈最火
  的词，而增长策略也在慢慢脱离“野蛮时期”，更加注重产品本身和用户体验。我
  们觉得有必要为大家分享下过去一年的研究：彦哲@增长黑盒就来为大家一一拆
  解 2018 年国内最热门的 10 个增长黑客策略
** 2019-01-02
- [[https://36kr.com/p/5170184.html?from=singlemessage&tar_foid][《张一鸣的 APP 工厂》]] 抖音是唯一，成为抖音的路径却不唯一。这家公司批量
  生产 APP 能力如此之强，而且历史成绩显示，核心产品成功的概率很大。欢迎
  来到张一鸣的 APP 工厂。


- [[https://mp.weixin.qq.com/s/iPQ-fa-9WWGne9imMt_p2Q][《罗振宇跨年演讲 4 小时讲了什么？记住这 4733 字》]] 不同于吴晓波的宏大叙
  事，这一次罗振宇把视角对准了个体命运，用他自己的话说，“关注大环境里个
  人的行动策略”。罗振宇全场演讲 4 个小时，信息量有点大。以下是作者梳理的
  演讲精华——罗振宇的“七个主义”


- [[https://mp.weixin.qq.com/s/rNzApAqPZFfZniEurfDZ0w][《灾年：我看 2018 年》]] 每年 12 月 12 日，日本汉字能力检定协会都会在京
  都清水寺公布当年的年度汉字。2018 年的年度汉字是——灾。而这个字简直是为
  2018 年的中国互联网量身定制的，2018 年的中国互联网，当得起这个“灾”字。


- [[https://mp.weixin.qq.com/s/EqyqodFU0frJ4ADLAyMcHw][《海外支付大战》]] 《日经新闻》报道，腾讯将与日本即时通信平台 Line 合作，
  为日本小型零售商提供移动支付服务。而顺应移动互联和数字化支付趋势，银联
  国际也在悄无声息地加快境外移动支付布局，并拉起了豪华朋友圈一起发力。


- [[https://mp.weixin.qq.com/s/tOWfGsZFPBRjo_cFnxEN7w][《罗振宇吴晓波跨年演讲里的几个小错误》]] 谁能想到，卫视跨年晚会的竞争对
  手不是电视台或视频网站的歌舞演唱晚会，反倒是颜值一般的中年小男人的鸡汤
  演讲，这个世界真的有意思。感觉挺好的，但是里面有几个小错误小瑕疵……
