#+TITLE:       汇总: 优质文章每日精华选(2021 年)
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-01-05 Tue
#+URI:         /blog/%y/%m/%d/everyday-reading-2021
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

微信公众号「卫夕聊广告」的作者组了一个微信群, 目的是每天挑选五篇当前最优
质文章,帮小伙伴们提升信息获取的效率和质量.

因每日发完文章列表后, 群里会有相关主题讨论, 时间一长, 再翻看历史文章就极
其不便,故起意将每日推荐文章列表整理到此, 方便随时查阅.

* 一月
** 2021-01-15
- [[https://mp.weixin.qq.com/s/IPlNQjQ1mBDJTRiNaQBcuw][《腾讯华为之争背后，一个时代正在落幕》]] 华为游戏中心在1月1日发布公告宣布，因“腾讯单方面就双方合作做出重大变更”，华为应用商店将全面下架腾讯游戏。腾讯与华为的这次下架事件，让游戏公司与硬件分发渠道的冲突逐渐从幕后走向台前，应用商店的黄金时代正在过去，牢不可破的市场地位已经在悄然消融，也并非是两家公司层面的斗争，而是两个行业和一个时代变革的缩影。


- [[https://mp.weixin.qq.com/s/9WfxyseqGsSIIUx4L4GcMQ][《科技公司“出硅谷记”》]] 2020年，大量的科技公司正在出走硅谷，它造成这一现象的，除了摆在台面上的加州房价、税收、监管环境因素之外，还有一些更深层次的东西：就像美国在过去几年展现出来的系统性分裂一样，硅谷也在分裂。谁走了？谁留了下来？从这些公司的对比中，你或许也能观察出不同硅谷公司，已经展现出的文化、意识形态上的分裂。而这种分裂，伴随着四年前特朗普的上任和自那以后愈发严重的美国社会整体的撕裂，早已有表征浮现。


- [[https://mp.weixin.qq.com/s/gEDCeQ905y6P_xHUzIVs2w][《在闲鱼和小红书上，我们找到了年会存在的最大意义》]] 每到年底，一些打工人的心里就越没底。这种不安的情绪常常来自两个方面，年终奖的额度和年会的组织力度。今年由于疫情影响，多地出台了相关政策，公司年会或是取消或是延期，但最近社交网络上关于年会的话题仍然不绝于耳。 我们来看看大家对于年会都在吐槽什么？大家在年会上都是怎么争奇斗艳？抽奖环节又有哪些有意思的现象？


- [[https://mp.weixin.qq.com/s/HfYNd3WY5-VXWSwlajHi2Q][《悟空问答关停：字节跳动的第一场败仗》]] 被“战略放弃”的悟空问答，即将退出字节跳动的App阵营。2021年，当初一时风光的“悟空问答”落幕，重新回复到原本的名字，以头条问答的形式继续存在。悟空问答宣布关停的头一天，恰逢知乎10周岁生日。来势汹汹的对手划上阶段性句号，知乎成了与字节跳动对阵的各领域竞争者中，少有的获胜者。


- [[https://mp.weixin.qq.com/s/cyywLfN2YT3CLDasOGAA_g][《谁还去KTV？》]] KTV如今已不再是年轻人眼中时髦的代名词。社会的发展和互联网的普及给年轻人带来了更多元化的社交渠道和多样化的娱乐场所，对于曾经奉KTV为“潮流”的80、90后而言，深受追捧的KTV显然已成为过去，他们已经“背叛”KTV。

** 2021-01-14
- [[https://mp.weixin.qq.com/s/SOMTvXZP_dD1YISXf39Hsw][《围剿 B 站》]] 一年股价翻三倍、最新市值达 414.5 亿美元、坐拥“Z 世代”年轻人，破
  圈后的 B 站是这两年视频行业绝对的主角。B站已经向港交所正式提交上市申请，此次上
  市融资规模直线飙升，但这并不意味着它没有成长的烦恼，有一个最明显的现象是，野心
  勃勃的 B 站，正被卷入更为残酷的互联网竞争中。它赖以生存并引以为傲的 UP 主生态，
  正遭受着 BAT 们的“围剿”。


- [[https://mp.weixin.qq.com/s/RXrTI4fbNiBzxvyITlEijg][《从热爱到生意，中文播客走出「隐秘角落」| 反光镜》]] 播客是去年起被广告主新近重
  视的渠道，在 2020 年中国大陆播客的数量激增，这是继知识付费后，内容领域又一次有
  多家头部平台参与的罕见热潮。有一个现实是，在中国过往对于声音这一载体的挖掘太过
  有限，无论是生产端、消费端还是整个生态链条都没有充分发展，更别提如何赚到钱，但
  一切正在慢慢改变。


- [[https://mp.weixin.qq.com/s/gXZwukRgyN4Q59tdiA-V5Q][《2020 年，十佳 IPO 捕手》]] 2020 年，成为名副其实的全球 IPO 大年，伴随着的是创
  业者和投资机构们的狂欢，作为陪伴其成长的投资机构更是等到收获时刻。数据显示，在
  A 股 IPO 上市背后，PE/VC 渗透率超过 70%，除 PE/VC 还包括国有创投机构、产业基金、
  上市公司旗下创投基金、券商直投和险资旗下股权投资平台等。以下是按照各家机构在
  2020 年新收获的上市公司数量统计的前十名。


- [[https://mp.weixin.qq.com/s/XA_solDnK_wUPy3pCwb_Gw][《新冠疫苗已接种一个月，这里有 5 个你可能关心的问题》]] 自 2020 年 12 月 2 日起，
  人类正式列装抵御新冠病毒的 “生物防具”，疫苗。目前中国、美国、英国、欧盟等国家
  和地区已经批准六款疫苗上市。按照当前的接种速度和疫苗产能，乐观估计发达经济体在
  年中实现群体免疫，全球群体免疫可能要再等等，但满足的条件包括疫苗有效率足够高、
  接种人群足够多且快、病毒变异有限、各国面持续时间同步等。那么到目前为止，新冠疫
  苗接种出现了哪些不确定性？


- [[https://mp.weixin.qq.com/s/suOO1rxaEIqe_pzeTZZpjg][《我如何掌握了爆款IP的创作秘诀？》]] 2017 年，两点十分动漫获得了阿里巴巴数亿投资，
  跻身成为全国前五的动漫企业。曾经不被大众认可的“动画片”为什么会呈现出惊人的市场
  活力？马斯洛需求模型还能预判行业内容趋势，洞悉爆款 IP 创作逻辑？消费升级时代背景
  下，“动漫+X”的 IP 共建模式如何为品牌赋能？小行业，大格局。如何迁移行业经验、立足
  产业看企业发展布局？两点十分动漫创始人兼 CEO 王世勇就上述核心问题进行了分享。

** 2021-01-13
- [[https://mp.weixin.qq.com/s/DyCJNLCX3DVVD_1UmGyuww][《拼多多员工自杀背后：什么在逼迫年轻人至死方休？》]] 拼多多员工谭某林从家中 27
  楼坠落，他毕业于 2020 年，刚在拼多多转正。我们无法判断小谭究竟为何选择自杀，但
  作为入职互联网大厂的应届毕业生之一，小谭曾与入职该公司的其他年轻人一起，深嵌电
  商巨头拼多多之中。当创新、自由、尊重逐步剥离，员工们陷于打卡、绩效、和监视之中，
  除了一笔高薪，我们该怎样定义这样的工作？


- [[https://mp.weixin.qq.com/s/BVk6td8JQjBF3VLfAl3twg][《信仰、教义和狂欢：蔚来卖的是车吗？》]] 蔚来最大的竞争力到底是什么？传统的 4P
  理论已经无法完全套用在蔚来身上，无论是互联网基因、中国版特斯拉、车界海底捞、小
  米衣钵的继承者，还是饭圈经济，都只是对它的片面解读甚至是误读，简单的“用户思维”
  四个字似乎也无法解释。在争议和噪音背后，这家市值已经 1000 亿美金的公司到底是在
  卖什么？


- [[https://mp.weixin.qq.com/s/b109dGf6y2Dpu47iV_cz5g][《为什么贝壳、百度、蔚来值得放在一起研究？》]] 贝壳、蔚来、百度，这三家公司的业
  务南辕北辙，放在一起比较未免有些“关公战秦琼”，完全不同的行业、完全不同历史阶段
  产生的公司、完全不同的业务阶段及财务状况，他们的可比之处在于哪里？实际上正因为
  基因与经历的不同，他们的估值涨跌正好体现出目前二级市场最主流的投资思路，也是最
  有希望在近期冲击千亿美元市值的公司。


- [[https://mp.weixin.qq.com/s/o-9sY2Nnx9CwleiII_01Eg][《为什么这届年轻人都去考公务员了？》]] 疫情的发生加重了中小企业的生存危机，公司
  举步维艰，每个身在其中的公司人都受到了直接影响，这也让原本就持续了十多年的“公
  考热”在今年继续升温，把国考的激烈竞争再次推向高潮。外面风雨太大，体制内成了年
  轻人最后的避风港。


- [[https://mp.weixin.qq.com/s/TnZ2YzF8nKDO0rueSvAN6w][《被算法监控的打工人》]] 越来越多的数字化管理手段进入企业，最普通的场景是使用 OA
  系统完成对员工考勤和工作量的全面监控，甚至可以根据企业需求编写算法，接管管理者
  的决策权乃至员工的主观能动性。对企业来说，将管理流程通过算法实施，无疑更高效精
  准，也能够降低管理成本；但对于一线的普通员工而言，则别有一番风味——这张数据大网
  密不透风，令人无处可逃，原本的工作方式和节奏被改变。

** 2021-01-12
- [[https://mp.weixin.qq.com/s/tUfTwDHheOhHhYV_K2zNKQ][《施展：一种新的世界秩序，正在到来……》]] 美国大选终局几乎落定，特朗普却仍在上演
  “最后的疯狂”。2021 年才刚开始，中美关系就迎来了一些全新变数：特朗普给制裁加码，
  禁止微信、支付宝等中国企业的准入，紧接着特朗普支持者又占领美国国会，民主党提出
  弹劾决议，指控特朗普“煽动叛乱”。高度撕裂的美国社会，还能好吗？中美两个超级大国
  的关系，又将走向何方？我们到底该如何与美国相处？


- [[https://mp.weixin.qq.com/s/7kMTN0ahCHII0ChBfawwjw][《QuestMobile2020 “Z 世代”洞察报告：3.2 亿“Z 世代”引爆消费潮流大迁移，如何抓住
  他们？》]] QuestMobile 数据显示，截止到 2020 年 11 月，95、00 后 Z 世代活跃用户
  规模已经达到 3.2 亿，占全体移动网民 28.1%；Z世代年轻、接受新事物的能力，带来了
  移动网络使用上的显著特性，社交、视频、网购、音乐、团购、游戏方面，活跃度都很高。
  这种趋势背后引发的消费潮流如何变化？又该如何抓住他们的？不妨看报告。


- [[https://mp.weixin.qq.com/s/9qPTAtm2H-bw3du19PufUA][《外卖骑手，巨头的炮灰》]] 外卖骑手是典型的平台经济下的非正规就业者，这个群体还
  包括网约车司机、代驾、快递员等。当一家家平台型公司采用外包、众包模式，快速招揽
  成千上万人为其工作，甚至简单到在 APP 上申请即可时，平台享受着廉价劳动力带来的
  资本市场溢价，但骑手的风险由谁来买单？


- [[https://mp.weixin.qq.com/s/k4Z94P4k7kFxQYPykqXCnw][《负债后，我才知道原来 200 块可以活一个月》]] 尼尔森 2019 年 11 月发布的《中国消
  费年轻人负债状况报告》显示，扣除把花呗、借呗等当做支付或理财工具并且当月还清的
  人群，90 后职场人实质欠债人群比例达到 57%，95 后职场人该指标也接近 40%。我们邀
  请了三位深陷（或曾经深陷）债务深渊的年轻人，聊聊他们都在过着怎样的生活。


- [[https://mp.weixin.qq.com/s/EZQorAzh3UQSw-awEveHvw][《燕郊离北京再近，也是河北》]] 从河北省三河市燕郊开发区进入北京，只需要跨过一条
  直线距离几百米的潮白河，隔着一条潮白河，通州的房价至少是燕郊的两倍。潮白河隔断
  的不仅仅是房价，也是北三县的尴尬地位。京津冀一体化也好，通州与北三县协同发展也
  罢，从燕郊的发展和房价来看，尚未有明显成效。“潮白河之隔，燕郊仍然是河北的燕郊。
  距离再近，北三县也不可能是北京。”

** 2021-01-11
- [[https://mp.weixin.qq.com/s/VW9KeeRGgvETJNoB-ip7KA][《张一鸣：CEO 总想招一些便宜的人，这才是最贵的》]] 历数中国互联网圈的高光并购事
  件，创始人出走的案例并不少见。然而在新巨头字节跳动的身上，却一批优秀的被收购团
  队创始人，仍然冲锋在字节跳动的一线。字节跳动如何做到低流失率网络互联网核心人才？
  今天，聊聊字节跳动的超高人效法则，以及他们和牛逼人才的相处之道。


- [[https://mp.weixin.qq.com/s/5_wFGsu4dVoP1yaqmciceg][《长沙可以没有互联网，但不能没有吃喝玩乐》]] 纵观湖南本土互联网企业，大众能想到
  与长沙相关的公司，除传统重工企业外，几乎都与吃喝玩乐相关。长沙独特的娱乐生态系
  统，反哺了一个独特的线下娱乐消费生态，从芒果 TV 到茶颜悦色、文和友、三顿半，长
  沙就这样，靠着看似闲散的吃喝玩乐生态成了当下的城市网红顶流。


- [[https://mp.weixin.qq.com/s/7X7xQq8lkaAJ3_Xyhf7URg][《江南春：两大红利消失，商业的逻辑变了》]] 分众传媒董事长江南春出席发表了最新演
  讲，他表示，5亿新中产存在巨大消费升级空间，企业家需要好好研究，这些中产到底爱
  什么？怕什么？缺什么呢？爱吃、爱美、爱健康，怕老、怕死、怕孤独，缺爱、缺心情、
  缺刺激，三爱、三怕、三缺，如果企业家的生意在三爱、三怕、三缺当中，那么这个企业
  在未来是有空间的。


- [[https://mp.weixin.qq.com/s/5gZMcKzhOORe6EvHc3OphA][《植发、整牙、祛痘广告充斥的微博，何至于此？》]] 作为中文互联网最高效的信息集散
  地，2020 年，平均每月有 5.11 亿人在微博上浏览话题和参与讨论。然而，热闹背后，
  是微博逐渐放缓的商业化，以及战略性产品的缺失。当刷量造假成为常态，优质广告主也
  正在离开微博，这使得微博的变现之路更加困难。


- [[https://mp.weixin.qq.com/s/-7Y4qiMwYh9jWvVyMTgSrg][《大众点评变味了？》]]众多网友最直观的感受是，大众点评变味了，看到的真实评价越来
  越少，虚假好评和恶意差评却越来越多。曾经小而美的大众点评，在被美团合并后，商业
  化导流的氛围越来越重，内容越来越杂，当一个以高质量 UGC 内容为生的社区，失去了它
  的口碑，大众点评的灵魂还在吗？

** 2021-01-08
- [[https://mp.weixin.qq.com/s/mXvAAXmeH40h6cgnaR9dvA][《李善友：2021，人生皆有意义，使命终将降临！》]] 越早的临在当下，越早找到自己的
  使命，你将越早的成为自己。我们怎么感知到自己的使命呢？我们可以间接感知它，即使
  不知道自己的使命是什么，只要我们相信使命的存在，它已经起作用了。而找到使命的关
  键一步就是把当下自己做的事作为一种修行，保持此时、此地、此事的“临在当下”状态。


- [[https://mp.weixin.qq.com/s/H923YnDSy6KAiv3qe_dFvA][《自动驾驶汽车的道德困境：如何拒绝乘客的错误命令？》]]我们对阿西莫夫的三条定律在
  自动驾驶汽车上的应用不得不有所保留，人工智能驾驶系统可以根据这些定律来设计，将
  其作为总体架构的一部分，但这些定律是一种愿望，而不是不可改变的法则。在自动驾驶
  汽车常态化之前，我们必须解决其中的道德困境。


- [[https://mp.weixin.qq.com/s/oCfHnuh9IwkZMFFulqWxnQ][《先生特稿 | 逃离拼多多的年轻人：“它的文化是不吝于用最强的恶意去揣测你”》]] “我
  不知道是从什么时候开始，有点恶意的对待身边发生的所有的事情。我觉得可能在拼多多
  这两年，让我对很多事情都充满了一种警惕性，因为它的文化是不吝于用最强的恶意去揣
  测你，就算是自己的员工。”一位离职员工如此说道。


- [[https://mp.weixin.qq.com/s/22NQIqkym8SXYhGK6b9PCw][《输赢之间：电影圈背后的资本江湖》]] 自 1994 年中国随着引进大片开始，走过近三十
  年的中国电影市场早已学会了拥抱资本，2019 年，中国电影市场已经达到 642 亿，成为
  北美之外的世界第二大电影市场，无数的资本愈加想吃下这块蛋糕，但资本可不讲蛋糕的
  味道如何，蚕食吃净才是本性。中国电影要做大，也要做好，最重要的，不能忘了来时的
  路。


- [[https://mp.weixin.qq.com/s/4N2H1bpTi3hOpeXP7tP5Qg][《微博输给了抖音们，还是输给了自己？》]] 微博近期公布了 2020 年第三季度业绩：收入
  与去年同期基本持平，归母净利润只相当于去年的约 1/4，录得 3380 万美元，看上去依旧
  普通平淡，但是竞争对手表现亮眼，令微博掉队态势明显。同期腾讯、百度，都超出市场
  预期，还有尚未上市的头条系公司也在不断蚕食着微博等竞争对手的份额。这些都令投资
  者为微博捏一把汗。微博是输给了抖音们？还是输给了它自己？翻盘还有希望吗？

** 2021-01-07
- [[https://mp.weixin.qq.com/s/m_0uHKe0KkMM1-iMmp394w][《冲刺“方便面第一股”》]] 中国快消品行业进入了一个高强度竞争的节点，今麦郎发展也
  需要突破，需要在多品牌、多场景、多品类、多渠道、多人群布局，投入会加大。如果不
  以上市的方式增强自身抗风险能力，挖宽企业护城河，企业就存在掉队风险。


- [[https://mp.weixin.qq.com/s/R6RjcNyDf1vjsS4A00QlQQ][《996、竞争与内卷化：穿透现实，得见真实》]] 新一轮关于 996 的争议热潮已经席卷而
  来，996 是如何席卷互联网行业的？很多人在谈及 996 时也总不忘补上一句“你不愿意
  996，有的是愿意干 996 拿高工资的人。”这个事实判断引发下一个话题：与 996 有着千
  丝万缕联系的内卷化。从 996 到内卷化，本质都是时代红利过后的泡沫。


- [[https://mp.weixin.qq.com/s/0XmjwPaO6obrAJEuIoN4Zw][《拼多多女孩“润肺”之死》]] 这个凌晨下班的女孩，生命结束在 22 岁的最后一个午夜，
  乌鲁木齐飘过雪的街头。激荡的舆论中，不少声音提醒，拼多多能开出两倍于行业的薪水，
  应届毕业生就能拿到五十万甚至更高的薪水——但这并不是属于润肺的故事。


- [[https://mp.weixin.qq.com/s/rkGw5QMbRR-w1mh12qH--g][《疯狂的在线教育：巨头进场、烧钱、二三梯队出局》]] 2020 年在疫情和资本的催化下，
  在线教育成为互联网公司最想长出的翅膀。2020 年的在线教育市场规模将达 4800 亿，
  千亿的市场同样受到了资本的热捧，融资、烧钱、并购成为了 2020 年在线教育的关键词。
  用一句话来形容 2020 年互联网巨头做在线教育的境况就是，腾讯稳中求进，阿里在摸索，
  字节意图大力出奇迹，百度在专注 AI 教育，网易在精炼平台......


- [[https://mp.weixin.qq.com/s/xu6O34YxIBRkoT81giX2PQ][《张一鸣会造车吗？》]] 不设边界的字节跳动，2020 年除了加码在线教育外，还有一个值
  得注意的动向：进军车联网领域。5月，字节跳动向媒体确认，已组建车联网团队，并计
  划推出自己的车辆信息娱乐系统方案，实现旗下抖音、今日头条等移动互联网产品在汽车
  终端落地。在巨头掀起的第二波造车浪潮中，围绕华为、百度，相继都被传出造车消息，
  字节跳动会不会成为下一个？

** 2021-01-06
- [[https://mp.weixin.qq.com/s/Chd2P4AFMrw9gMnOtIrcWw][《字节跳动怎么都十万人了？》]] 到 10 万人，字节用了 8 年，阿里用了 19 年，腾讯还
  没到。2020 年，字节跳动的员工总数从 6 万蹿到近 10 万，一个主业在线上的公司有
  10 万员工，这在几年前还是件难以想象的事。企业家往往警惕公司规模过快扩张，其它
  公司往往二三十年才能达到的规模，字节跳动压缩到了八年，但没有任何迹象表明，字节
  跳动将因此按下暂停键。


- [[https://mp.weixin.qq.com/s/l6zdiK9AlLe3rqAcACNeEw][《95 后厂哥厂妹口述：富士康不相信爱情，昆山处处是“单身大神”》]] 没有人一直年轻，
  却一直有年轻人。全球有 18 亿年轻人，互联网让这一代年轻人拥有了前所未有的自我表
  达权利，有了与广阔世界无限接近的渠道。他们从网络中汲取养分，又用自己的创造力反
  哺这个繁荣的生态，从爱好到职场，他们的人生观和职场观与父辈有了显著的区别，那么
  该如何正确认识这一代年轻人？


- [[https://mp.weixin.qq.com/s/-Sb2l0ArSEeCG0G7VvhNRA][《体检异常率 99%，这届打工人的身体有多差？》]] 2021 年的第一个工作日，996 的工作
  模式又冲上了热搜。一边是现代人越来越看重养生，一边却是越来越普遍的亚健康问题。
  每年让打工人们最心惊的可能不是年终总结，而是体检报告，从 2013 年开始到 2018 年，
  上海白领的体检异常率从 94%上升到了将近 99%——基数非常大，异常率更是不断逼近
  100%。


- [[https://mp.weixin.qq.com/s/ufYMN1kH7kkbhZTMY3Xv1Q][《比特币暴涨，独家解密谁在控盘比特币？》]] 过去两个月中，比特币的资产价格飙升，
  引领了整个全球加密资产行业的牛市回归，种种迹象表明比特币已不在局限于小范围的资
  本游戏中。究竟谁在控盘比特币？最大的利益攸关方是谁？谁在其中谋取了最大收益？未
  来比特币筹码还将以怎样的格局继续流动？人们一直以来都在探究全球比特币持仓排行的
  疑问。


- [[https://mp.weixin.qq.com/s/cfuMC3TiDkTGtzY2aMG59A][《涌动2020 | 社区卖菜的隐喻和终局》]] 每次创新，都意味着一整批人的就业被消灭。中
  国的社会环境过去对创新是鼓励的，但在经历几年的贸易摩擦和今年的疫情冲击后，社会
  大众在 2020 年突然重拾了对创新的审视，尤其是那些专注提升“效率”，却无法兼顾“公平”
  的创新。因此，围绕社区团购的争议，会给“优先效率，还是优先公平”这个问题赋予新的
  答案吗？

** 2021-01-05
- [[https://mp.weixin.qq.com/s/VhwjGkcIDPpIJ8tOxMjTCg][《那些离开互联网大厂的年轻人》]] 在 BOSS 直聘发布的《2020 年 Q3 人才吸引力报告》
  中，互联网行业在人才吸引指数排名中依然位居第二，第一则是和它紧密相关的 IT 行业。
  与此同时，脉脉发布的《人才迁徙与流动趋势报告 2020》也指出 ，2019 年，互联网行
  业里出现了可见的人才流出。一群人争先入局，一群人失望离开，互联网大厂，已经成为
  这一代年轻人新的围城。


- [[https://mp.weixin.qq.com/s/obhpjxEKpQwuyZV9wIS00Q][《独家调查 | 虾米真的被阿里巴巴耽误了吗？》]] 11 月末，一则“虾米音乐即将于明年 1
  月关闭”的传闻，触发很多虾米用户在社交网络上抒发各自对于这个音乐流媒体产品的怀
  旧之情，同时也有很多人在表达不满，认为“虾米是被阿里巴巴耽误的”。但虾米真的被阿
  里巴巴耽误了吗？


- [[https://mp.weixin.qq.com/s/HfrEhxIpT9XQTKZOWaUTpA][《2020 互联网没有新故事，只有新品牌》]] 2020 年是疫情下艰难的一年，处在互联网未
  诞生新风口、未出现现象级 App 的档口，资本市场因为大环境遇冷而格外谨慎，互联网
  行业极度缺乏新故事，但很少有投资机构会甘愿错过投资新消费品牌的机会，甚至，也有
  不少投资机构主动下场创立新品牌。开年之际，我们通过 6 个关键词，来回溯盘点 2020
  ——新品牌之年。

- [[https://mp.weixin.qq.com/s/j8MYW_zn2BXKo4luvb3xgA][《国内互联网公司为什么加班这么狠？》]] 互联网人似乎越来越忙了。就在最近，快手宣
 布展开全员大小周，为鼓励加班，字节跳动也表示要给周末加班的员工开出两倍薪水。但
 加班带来的劳累，有时候会成压死骆驼的最后一根稻草，1月 3 日晚，拼多多的一位年轻
 女员工在凌晨 1 点半回家的路上不幸猝死。是什么，让互联网人不得不以透支未来的方式
 奔跑？


- [[https://mp.weixin.qq.com/s/dBmSAzgIG-mR6g0YeUGntg][《2021，字节跳动的营收能折腾出广告圈吗？》]] 想到字节跳动，可能大部分人的第一反
  应就是“有钱”，字节重新定义了信息生产、分发、消费的关系，步步为营，字节正逐渐打
  造出了属于自己的“字节跳动系”王国。毫无疑问，字节跳动已经是中国最大的广告公司了，
  但是除了广告外，增长点在哪里？

** 2021-01-04
- [[https://mp.weixin.qq.com/s/zhIYcCMmIa-ipsurcyke3A][《特斯拉扔出了一片“二向箔”》]] 补齐轿车与 SUV 这两个最主流车型后的特斯拉，开启了
  中国本土化的新篇章。国产版 Model Y，使得特斯拉在包括燃油车在内的整个汽车市场竞
  争力大增，对比其他国产 SUV 新能源车，也是碾压级的存在；新品上市的同时，等于也
  顺手向中国汽车扔出了一片“二向箔”。特斯拉中国本土化策略由此迈入 2.0 时期，更紧
  张的贴身肉搏战揭开帷幕。


- [[https://mp.weixin.qq.com/s/DhVorf4GIqnbqXTVguY_Ww][《猝死、大小周、996：当互联网变成劳动密集型产业》]] 1 月 3 日晚，多多旗下多多买
  菜员工在凌晨一点半下班路上猝死，年仅 23 岁。有一个不可否认的趋势是，互联网对员
  工时间的挤占、对员工身体与心理造成的负担，已经成为互联网“造富”光环之下的灰暗一
  面。互联网人的工作时间正在不断延长，“996”正在取代 8 小时工作制，“大小周”也正在
  取代“双休”制度，互联网正在走向劳动密集型产业。


- [[https://mp.weixin.qq.com/s/1t2ayNR_HLSQY9fGfXpoMw][《为什么所有的 APP 都在炫富？》]] 你有没有这样一种感觉：无论打开什么 APP，都有人
  在展示自己的富裕生活，营造出一种“众人皆富你独穷”的氛围，可以说有社交的地方就有
  炫富。APP 们在变味，用户能感觉出来，从微博到知乎，从抖音到 B 站，从小红书到大
  众点评，为什么有内容分享的地方就有炫富？


- [[https://mp.weixin.qq.com/s/BN7uMLwEWdRxYXWCs1YfIQ][《榜单 | 真故 2020 年最值得阅读的 10 篇故事》]] 2020 年是一个宏大的话题，记叙
  2020 年的容器则是一个又一个渺小的个体。今天的推送中，编辑部票选出了 2020 年真
  故最值得阅读的十篇文章，并附上了推荐理由，作为记住 2020 年最后的仪式。2021 年
  我们依旧会坚持拾取、记录当下，跟我们一起，继续与真实为伍吧。


- [[https://mp.weixin.qq.com/s/Nn_b9Lv43xLFt9bY_pSwsA][《估值为什么是一种艺术而非科学 | 巴伦读书会》]] 无论是企业管理者还是普通投资者，
  都需要培养自己的金融直觉，以做出明智的金融决策。那么对于做出正确的金融决策来说，
  哪些才是最重要的财务数据，应该如何理解金融数据背后的意义？《什么是金融》总结了
  哈佛商学院金融学教授米希尔•德赛的在线热门 MBA 金融课程内容，本文整合《什么是金
  融》，解释了为什么估值是一种艺术而非科学，或者说披着科学外衣的艺术。
