#+TITLE:       汇总: 优质文章每日精华选(2021 年)
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-01-05 Tue
#+URI:         /blog/%y/%m/%d/everyday-reading-2021
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t

微信公众号「卫夕聊广告」的作者组了一个微信群, 目的是每天挑选五篇当前最优
质文章,帮小伙伴们提升信息获取的效率和质量.

因每日发完文章列表后, 群里会有相关主题讨论, 时间一长, 再翻看历史文章就极
其不便,故起意将每日推荐文章列表整理到此, 方便随时查阅.

* 六月
** 2021-06-01
- [[https://mp.weixin.qq.com/s/0GjDcvveyRDwuAo_ANrMSA][《中国哪里人最不愿生孩子｜大象公会》]]

  三胎政策来了。与之相伴的背景，是此前几年二胎政策成效不尽如人意，中国总
  和生育率跌破警戒线。根据国家统计局的数字，全面二胎政策实施的第二年，出
  生人口远低于国家卫计委的预测数值，在出生率最拖后腿的 10 个省市中，江浙
  沪很是显眼，在同等人口体量的地域范围上堪称出生率最低的地区。事实上，早
  在 200 多年前，江南的人们已经不想生孩子了。

- [[https://mp.weixin.qq.com/s/F5Z6qStaSGhfSMnEKtx4VQ][《万字拆解Ubras：年销15亿、暴涨10倍，内衣新秀的春天到了？》]]

  标品化并不少见，但将女性内衣标品化，推出“无尺码内衣”，Ubras是全球首家。
  仅用了1年多的时间，Ubras一举拿下了2020年双11天猫内衣销量榜TOP1，增长
  800%，年销售额突破了15亿元，将一众“前浪”品牌结结实实按在了沙滩上。
  Ubras这个“新物种”的成长路径究竟是什么？难道通过一个概念的包装就能撑起
  十几亿的生意吗？这背后又有哪些值得新品牌学习和反思的地方？

- [[https://mp.weixin.qq.com/s/2tDcKSnD3GxyRSM2lu6DPQ][《字节跳动放不下社交》]]

  做社交是字节跳动全球产品战略布局的一部分。从字节跳动在社交领域曲折的探
  险来看，被封杀、产品失败都未打消它做社交的念头，还颇有愈挫愈勇的意味。
  抖音作为一个6亿日活的短视频娱乐平台，在商业模式上已逐渐跑通，可以说涨
  势也已经凶猛到让各平台都开启了战略防御，一时全都研究起短视频了，为什么
  还要对不赚钱的社交如此觊觎、非做不可呢？况且微信在前，抖音做社交的机会
  又在哪里？

- [[https://mp.weixin.qq.com/s/o0GzV1sd8JRPuSHWTodoGQ][《【中企出海系列】“中东小淘宝”兴衰记》]]

  中国电商Jollychic（执御）来到中东四年，就实现了五十倍以上的销售增长，
  成为首家中东电商出海“独角兽”。然而，蓝海底下除了镶金嵌银的宝箱，或许还
  藏着一个致命漩涡。Jollychic的盛景并没有维持太久，这家公司在2019年后频
  频传出新业务失败、资金链断裂的传闻，疫情后更是遭遇生存危机，从中东电商
  铁王座滚落至供应商追讨的地步。

- [[https://mp.weixin.qq.com/s/p_XhQv8H3zSRsiqcRvbBqg][《抖音快手本地生活激战100天，能否颠覆霸主美团？》]]

  进军万亿级市场的本地生活赛道，“流量大户” 抖音快手有着商业变现的天然诉
  求，短视频+直播的形态也的确拥有图文形式无可比拟的到店转化率优势。但在
  不少行业人士看来，业务创新遇到在本地生活领域业务积累沉淀11年的巨头美团，
  抖音快手成功概率还是需要打上一个大大的问号。

* 五月
** 2021-05-28
- [[https://mp.weixin.qq.com/s/xlLF7gE5oZCru0BO09Stsw][《深氪丨「西二旗谍战」如何摧毁「硅谷信仰」》]]

  无论是BAT还是TMD，每年公开的风控通报中，因为窃取商业机密通报、开除员工，
  已经越来越频繁出现。这让身处其中者心惊肉跳——这意味着失业、期权股票作废，
  而且未来的职业前景也堪忧。谎言、真实、利益、情报……层层传导之下，信息谍
  战正在创造一个越加不互信、越加管控严密的互联网生态。

- [[https://mp.weixin.qq.com/s/NZDUO6luyjN6HWdtGkoJCA][《拼多多的新难题和新故事》]]

  眼下，拼多多所面对的电商江湖，不再是仅有阿里、京东的围猎，也有跨界玩家
  抖音和快手的争食；而在拼多多发力的社区团购、农产品赛道上，还面临着美团、
  滴滴的狙击。不仅前有迷雾，后有追兵，流量红利也即将触及天花板。拼多多还
  将如何讲出新故事？

- [[https://mp.weixin.qq.com/s/rYIfrFbAkX6AY7N_lTESvQ][《快手“失手”，追不上海外老铁？》]]

  快手，重拾了出海赛道的目光。本周，快手发布了 2021 年第一季度财报。据最
  新财报数据，其海外市场第一季度月活用户均值超过1亿，今年4月进一步增长至
  1.5亿以上。去年年中，快手旗下海外产品 Zynn 也传来过不错的“战报” —— 上
  线不到20天即登上美区 iOS 总榜第一，将 Zoom、HBO Max 和 TikTok    甩在身后。

- [[https://mp.weixin.qq.com/s/h1dRRCR_usNKCAeH2kqNHA][《鸡娃、躺平与内卷》]]

  一考定终身，鸡娃现象不止；一房定终身，躺平主义盛行。鸡娃是一种内卷化，
  城市中产的父母与娃深陷教育焦虑之中；而躺平主义是对内卷化的一种消极反应，
  城市青年在表达一种不合作的态度。该如何理解这两类社会现象？本文从经济学
  的角度分析鸡娃、躺平与内卷。

- [[https://mp.weixin.qq.com/s/xh7PN9GAYDOQ3STc2mfzRw][《互联网烧钱战争：10年6.7万亿，谁是赢家？》]]

  如果用一个词概括过去的10年，烧钱或许是最形象的。外卖大战、网约车大战、
  共享经济大战、生鲜电商大战、社区团购大战……无一不以补贴起步，而后慢慢涨
  价。战局已定，烧钱的时代已经过去。站在5G爆发的时间节点上，我们不妨来看
  看，过去10年，热钱都烧到了哪里？

** 2021-05-26
- [[https://mp.weixin.qq.com/s/R4WNUtAnHmlr0RcDp3x-rg][《液体印钞机：瓶装水的新王和旧王》]]

  在2010年，娃哈哈创始人宗庆后荣登中国首富，而宗庆后当年的老部下钟晱晱也
  在10年后的2020年，凭借着农夫山泉的IPO荣登首富，身家一度超过了600亿美元。
  瓶装水这个不起眼的行业，为何能跟巨擘林立的地产和互联网相提并论？显然卖
  水不是门简单的生意。翻开财报，你会发现农夫山泉的毛利率接近60%、净利率
  高达23%——中国人每喝掉一瓶两块钱的水，钟首富就赚4毛6。所谓“大自然的搬运
  工”为何这么赚钱？瓶装水为何能成为液体印钞机？

- [[https://mp.weixin.qq.com/s/FLpVSD52s55WVa3HrJcbHA][《全球新冠疫苗平均接种不足9%，谁在拖后腿？》]]

  疫苗接种速度虽然在加快，但进程仍被很多不利因素阻挠，围绕疫苗的地缘政治
  博弈和民族主义情绪，影响了一些国家和地区的接种速度。一些国家没有疫苗供
  应，因为欧美富国很难在为本国公民免疫和向他国提供疫苗之间取得平衡。而在
  疫苗供应充足的国家和地区，疫苗政治化、虚假信息以及个人对疫苗有效性和安
  全性的怀疑等种种因素都在掣肘接种行动的推广。

- [[https://mp.weixin.qq.com/s/cQMrebTmD4KVhFvtIRg8rQ][《超过亚马逊！美国下载量最多的购物 App，居然来自中国》]]

  美国安装最多的电商应用是哪一个？这个问题要是在街上随便找十个人问问，很
  可能五个都会说是亚马逊，三个猜测是淘宝，剩下两个表示不知道。但今天真正
  被美国用户安装最多的购物 app，却是大部分人都没听过的 Shein——一个土生土
  长的中国应用。Shein 的目标是把中国完善的服装产业链搬到外网，把中国制造
  的商品卖给外国人，不让中间商赚差价。

- [[https://mp.weixin.qq.com/s/8MPg7tjr1otHbm4SY39fpw][《“创新经济”开启下一个十年超级周期丨华兴报告》]]

  过去十年，随着移动设备的普及和软件应用的快速增长，我们见证了以移动互联
  网为标志的十年科技周期。我们认为，4G等科技基础设施超前建设、摩尔定律延
  续及全球技术开放、发达的私募股权市场，以及宽松、友好的创新环境成为过去
  十年中国经济获得成功的主要因素。随着互联网用户增速与时长增速双双下滑，
  流量红利逐渐消失，移动互联网周期已走到了末端。与此同时，新一轮十年科技
  周期逐渐拉开帷幕，我们正处于新周期的起点。

- [[https://mp.weixin.qq.com/s/IMo4OVb_Pikf-sr12rUhWw][《从张一鸣和黄峥的离职信中，我们发现了四个共同点》]]

  在80后创业家中，张一鸣和黄峥是最具有代表性的两个，然而张一鸣和黄峥在
  2021年先后主动从公司关键岗位上卸任，有一种不约而同的感觉。他们人生的路
  径也是相似的，从国际大公司离职、连续创业、快速崛起、急流勇退。甚至连他
  们的辞职信，都有很多共同点和“默契”。两人兼有的这些共同点，或许是他们成
  功的秘密。
** 2021-05-25
- [[https://mp.weixin.qq.com/s/b6u2cez2NIge5WOrjC1GQA][《比特币•魔戒•马斯克》]]

  电影《指环王》中的人类英雄阿拉贡，这样评价九大“戒灵”： 他们曾经是伟大
  的人类国王，最终变成魔君的奴仆。魔戒蛊惑心智，无论是对于人 类、精灵、
  矮人还是霍比特人而言，它都是巨大诱惑，戴上魔戒的人，仅有少数强 者不被
  腐蚀。加密货币圈有魔都气场，戴上这枚戒指后，没有多少人能够保持心性 坚
  定，一旦身陷其中，除非内心特别强大，否则就会成为戒指的奴隶。

- [[https://mp.weixin.qq.com/s/uzMaCH6gcUFkhc7qA0mRVQ][《城市的难题》]]

  第七次全国人口普查数据显示，最近十年，人口进一步向大城市集中，城市化是
  近代社会的文明标志。然而，城市化的进程可能引发公共资源的争夺，城市土地、
  教育、住房、医疗与公共交通的分配面临挑战。如果公共资源的分配不当以及使
  用效率低下，容易催生“大城市病”，比如高房价、贫民窟、产业空心、交通拥堵、
  犯罪猖獗、城市衰落等。

- [[https://mp.weixin.qq.com/s/jVGfrUmpFSIRl66frH-7TA][《14000字深挖唐吉诃德——靠打折上市的日本零售“廉价王”》]]

  2020年，唐吉诃德以800家门店，约1000亿人民币收入，成为了日本收入排名第4
  的零售企业。唐吉诃德采用了全直营、3000平米以上大店，上万SKU密集陈列、
  30%低价尾货+70%正价折扣混合销售的模式，给消费者带来一种价格便宜选择丰
  富的印象。唐吉诃德模式的成功得益于其能力与日本零售流通的特殊性之间的匹
  配。本文将从日本零售宏观角度切入到折扣店行业的发展，尝试解码日本折扣之
  王的致胜之道。

- [[https://mp.weixin.qq.com/s/IFNdRam9yd29v2ksoixEeg][《腾讯游戏的帝国裂缝：为什么没能诞生〈原神〉？》]]

  “因为和群友们一起挖矿特别爽，这群人可太有意思了！”他口中的“有意思的群
  友”，是一个近2000人的《原神》玩家QQ群。群里除了大锤这样的“打金人”，还
  有Lo娘、直男、重度3D爱好者、剧情控等，几乎涵盖了《原神》玩家的众生相。
  而他们是腾讯游戏或得不到、或正在流失的玩家。

- [[https://mp.weixin.qq.com/s/pI2KTi1uyh5hQ_pdfF3s7A][《梁晶，奔跑者逝于荒野》]]

  徒弟严颜见到了梁晶的遗体。他的膝盖磨损非常严重，几乎没了皮，能直接看到
  肉。他们猜测，这是因为去世之前，他跪着爬行了很久。他们分析，也许是因为
  他失温严重且没有补给，风雨中上坡不可能，下坡又可能被吹到附近的沟里，实
  在进退两难，只能靠强烈的求生欲，在地上爬行，直到生命最后一刻。

** 2021-05-21
- [[https://mp.weixin.qq.com/s/cqsY5YmuIQZxR-5miOiLWw][《贝壳创始人左晖因肺癌过世：年50岁 彭永东发文“别老左”》]]

  贝壳昨日发布公告，称公司怀着深切的悲痛宣布，公司创始人兼董事长左晖先生
  因疾病意外恶化于2021年5月20日去世，年50岁。就在2021年5月13日发布的
  “2021新财富500富人榜”中，左晖以2220.3亿元财富排名第八位，成为地产行业
  新首富，超越了碧桂园控股的杨惠妍、万达集团的王健林王思聪父子等。

- [[https://mp.weixin.qq.com/s/ti1kqykR97PU20M_83ETxg][《扎克伯格的野心和斯特罗姆的美学》]]

  扎克伯格和斯特罗姆是截然不同的两类人。前者野心巨大，热爱竞争，有强烈的
  不安全感，扎克伯格对一份产品的价值观这几个字不屑于顾，这是一个极其傲慢
  的商人。斯特罗姆在扎克伯格的衬托下，简直太像一个艺术家，INS就是展示最
  美好的生活的。换言之，他根本不在乎增长。这是一个极其傲慢的产品经理。

- [[https://mp.weixin.qq.com/s/r3u9qAcInczBTXnBcvHR0A][《巴以冲突：战争与和平》]]

  2021年5月10日，恰逢以色列纪念1967年占领耶路撒冷的“耶路撒冷日”，犹太人
  的庆祝活动，引发了部分巴勒斯坦人极度不满，最终再次引爆了巴以冲突，自4
  月中旬的斋月以来，二者冲突持续升级。如何理解冲突与战争？如何争取自由与
  和平？本文从经济学的角度分析“暴力的陷阱”。

- [[https://mp.weixin.qq.com/s/kreph7gff6njVanIaLmCQA][《在东南亚，阿里怎么打腾讯？》]]

  「印尼小淘宝」Tokopedia 和「印尼小滴滴」Gojek 正式合并了，合并后的实体
  定名为 GoTo Group。Tokopedia 的 logo 是一只购物袋形状的鸟，管理层设计
  GoTo 品牌标识的时候，曾想把 Gojek 的 logo 直接放进鸟的眼眶里。但 GoTo
  却一点也不像这只小鸟那样「憨态可掬」，在吞并了「印尼小淘宝」和「印尼小
  滴滴」之后，新实体是一个估值 180 亿美元的「生猛」超级生态，一个涵盖叫
  车、配送、支付和电商业务的综合巨头。

- [[https://mp.weixin.qq.com/s/tu89YtAoASus5xMepqB1AQ][《Netflix为什么做砸了爱死机》]]

  上线一周，观众期待两年的《爱，死亡和机器人》第二季已遭遇口碑崩盘。相比
  第一季由35万人打出的9.2高分，第二季的豆瓣评分已跌到7分以下。如果说外媒
  影评人对它还尚有留情的话，脱离了东方世界的叙事则让中国观众毫不客气地撂
  下了三个字：不满意。而除了制作上的反思，人们可能更关心一个背后的问题：
  拥有一手好牌的Netflix是如何把《爱死机》做砸的？它还是那个做出轰动亚洲
  的《王国》的Netflix吗？

** 2021-05-18
- [[https://mp.weixin.qq.com/s/AZzU_IF9yP34ylggDTXQtA][《互联网卖房，就差那么一点点》]]

  房地产是门好生意，国家统计局数据显示，房地产交易市场未来三年将维持并发
  展到25万亿元左右规模，其中，房地产营销费用支出整体市场容量大约是
  5000-6000亿元左右的规模。这也是阿里、京东等互联网公司虎视眈眈的下一个
  增长点。

- [[https://mp.weixin.qq.com/s/xA9zATl-iKH4ySHwUb41ZA][《你点的外卖，可能365天前就做好了 | 【经纬低调分享】》]]

  你有没有想过，为什么点一份外卖，30分钟送到，20分钟花在配送小哥的路上，
  商家烹饪只需10分钟？这背后是外卖行业的一个共识内幕：提前做好的料理包。
  成本只需5元钱，毛利高达80%，保质期365天。对于大部分个人来说，料理包是
  个陌生词汇，但现实中它早已大量进入过很多人的胃，比如通过外卖。

- [[https://mp.weixin.qq.com/s/0GWExZYQBm9G9ljDTbnQqg][《字节游戏急需一份成绩单》]]

  作为搅动游戏行业格局的新势力。字节跳动在今年出手了两笔轰动业内的投资。
  自2018年首度入局轻度游戏，到2019年成立“绿洲计划”预备切入中重度游戏市场，
  再到今年高举高打收购多家游戏研发公司，字节跳动旗下游戏业务早该交出一份
  成绩单。今年4月底上线的《航海王：热血航线》被看作是这份成绩单下的最后
  一根稻草，留给字节游戏的时间明显不多了。

- [[https://mp.weixin.qq.com/s/o4rkT3Bm7l8gRcnH6ojdgQ][《华尔街传奇罗杰斯：一场比2008年更大的变局，正在靠近…》]]

  世界经济似乎拿到了一个“疯狂”的剧本。华尔街著名投资家吉姆·罗杰斯近日推
  出新书《危机时代》，一语惊人：“一场比‘雷曼时刻’更大的危机，必定会到
  来。”那么，罗杰斯对时局大势又有哪些最新看法？第3期《商业风向标》，我们
  摘取、精编罗杰斯新书中的核心要点，涉及他对大势的判断、对商业、投资、人
  生的经验之谈。

- [[https://mp.weixin.qq.com/s/B2vJk3Xy-rGsMme9doAdUQ][《微短剧的“春天”是个假象吗？》]]

  2020年，平均几分钟一集的小短剧开始快速吸引用户的关注，在视频行业掀起内
  容迭代的波澜。快速升温、进入“春天”的微短剧，是否意味着短视频内容趋向专
  业化和系列化，抑或影视内容消费走向短视频化？无论如何，微短剧已成为长短
  视频的交集地带，讲述着视频内容进化的一个新可能，也昭示着影视文娱行业的
  下一个机会。
** 2021-05-17
- [[https://mp.weixin.qq.com/s/CFnE-B5r1AKKPwaKkd0rvg][《当下与未来，两个最大的基本面》]]

  魏晋不只有暴乱、动荡、战争、死亡，还有累累白骨砌成的魏晋风骨。任何一个
  民族在发展过程中,均不可能一帆风顺。总会遇到各种天然的灾难和人为的灾难。
  当灾难降临之时,民族是否具有自我修复能力，是一个民族是否可以延续民族生
  存及民族发展的根本标志。修复靠什么？骨子里的气节与底线，是谓风骨。

- [[https://mp.weixin.qq.com/s/YnV0PdssL2UknyynvY6sFg][《中国新造车出海：底气不少，挑战很多》]]

  进军欧美市场，打开“第二增长曲线”，这一直是中国车企的梦想，但在很长一段
  时间内，由于产品力、合规等方面的原因，中国汽车难以在欧美等成熟市场有大
  的突破。无奈之下，只能“取道”东南亚、中东地区、俄罗斯、南美和非洲，希望
  实现“农村包围城市”。如今，中国车企开始了又一次尝试。相比之前的出海浪潮，
  这次换做了“新造车”当先锋，直取欧洲市场。

- [[https://mp.weixin.qq.com/s/itkcm7O9FdbSY90WLaSGqQ][《人们为什么要无休止的工作？》]]

  工作似乎主导了中国人，并肆无忌惮地侵袭到生活领域。对于相当多的人来说，
  即便不喜欢自己的职业，但为了生存和收入，仍不得不为此投入过多的时间和精
  力。当一个人为了工作而放弃与家人相聚的时间，放弃娱乐和休闲，这无疑是一
  种煎熬。于是，工作为何如此重要？这种现象是合理的吗？

- [[https://mp.weixin.qq.com/s/VUBsq4HwbvxxFmel0PdbUg][《一条微博引发的中小票屠杀》]]

  对于今天的冰火两重天的行情走势，叶飞绝对起到了推波助澜的重要贡献。毫无
  意外，叶飞于近期在微博上陆续曝光的十多只股票在今天莆一开盘就以集体暴跌
  吸引全市场的关注。他以一己之力，对今天的A股小市值股造成的冲击，不亚于
  一次“加息”带来的利空冲击。

- [[https://mp.weixin.qq.com/s/ivdNKhwe6UPFAG5-Zs8m8Q][《茶颜悦色能不能走出长沙？》]]

  新茶饮品牌茶颜悦色能够成为长沙这座城市的一张名片，固然与其中茶西做的调
  性、“宠粉”的服务有很大的关联，但一个更基础的原因是明摆着的：这里的茶颜
  悦色太多了。高密度开店这一招看似简单粗暴，却也不是谁都可以学得来的。背
  后既关乎位置和租金，也有时代和业态的因素——在电商冲击后，不是所有业态都
  适合在线下大力开店。
** 2021-05-14
- [[https://mp.weixin.qq.com/s/LgKJeRtc5QQy-1GlYmukdg][《长视频们的“焦虑” ：YouTube走向TikTok》]]

  Alphabet 公司旗下的 YouTube 本周二宣布，将出资1亿美元，在其新推出的短
  视频平台 Shorts 上设立1亿美元创作激励基金。自基金推出到2022年底，
  Shorts 上热门视频的创作者可获得该基金的现金奖励。此前 TikTok 与
  Snapchat 也推出了短视频创作激励计划。

- [[https://mp.weixin.qq.com/s/baIlQ5pZkcYEZD3FAdtTHg][《警惕“马斯克神教”的蔓延》]]

  特斯拉CEO埃隆·马斯克（Elon Musk）在社交媒体上宣布特斯拉暂停用比特币支
  付，理由是对比特币挖矿和交易中使用化石燃料频率迅速增加对环境造成的影响
  表示担忧。当日，全部虚拟货币价格应声大跌。马斯克看上去越来越像是一个
  “圣人”了，他做的每一件事看上去都具备无比的正当性和对未来的预见力，是时
  候揭下来马斯克的神教面具了。

- [[https://mp.weixin.qq.com/s/93cogJ1eI6rvOLMEn5SJOw][《互联网的尽头是内容》]]

  过去，百度、微信等互联网工具，被人津津乐道的产品理念是“用完即走”，现在，
  这种理念正在被抛弃，包括滴滴、钉钉、携程、Boss直聘等工具都希望用户来了
  别着急走，而内容是它们用来留人的法宝，用户在哪里消费内容，流量就在哪里，
  时长也在哪里，而拥有流量和时长，就意味着掌握了商业化的主动权。

- [[https://mp.weixin.qq.com/s/8su8f2vc53UJM8MBivx1og][《垄断阴霾下，阿里迎首亏》]]

  2021财年第四季度，阿里巴巴新财报迎上市以来季度首亏。资本市场给予了消极
  反馈，在美股大涨的情况下，阿里直泄6.2%。阿里巴巴集团董事会主席兼CEO张
  勇表示，阿里巴巴集团于2021财年达到了全球年度活跃消费者10亿的历史性里程
  碑，生态体系于本财年也实现了1.2 万亿美元 GMV 的新纪录。得益于生活及工
  作等各方面均在加速数字化，阿里巴巴集团对中国消费驱动的经济增长充满期待。

- [[https://mp.weixin.qq.com/s/SHfoInKwTOjxpjn1WKpkHg][《B 站一季报点评：广告主对小破站早已心向往之》]]

  哔哩哔哩发布了2021年Q1财报，本季B站实现净营收39亿元人民币，同比增长68%，
  经营数据中，除了用户数增长回归正常，表现最突出的则是广告业务进展。B站
  相对于其他平台，社区调性依然突出，具备资本一直追逐的稀缺性特征。而广告
  收入的超预期增长，印证了B站的品牌影响力已加速得到广告主的认可。因此对
  于投资者来说， B站信仰还可以持续，小破站的未来也值得坚守。

** 2021-05-13
- [[https://mp.weixin.qq.com/s/dywfHyPeMcZMiB_oZZnkFA][《未来30年，中国互联网路向何方？》]]

  1994年4月20日，中国通过一条64K的国际专线全功能接入国际互联网，到今年已
  是27年整。在这27年中，互联网逐渐成为影响中国社会发展的重要基础设施之一，
  它改变了社会的流向、商业的模式、产业的形态，以及万千中国人的人生轨迹。
  鉴往知来，互联网未来的发展，必须建构在对互联网过去几十年发展的充分了解
  的基础之上。让我们一起回望互联网过去几十年的发展故事，洞见互联网的未来。

- [[https://mp.weixin.qq.com/s/auck-IMB993L6Nw_CkwWHw][《互联网到处是老年人》]]

  近年来，很多人都可以清晰感知到，那些常用的APP里，出现了越来越多的老年
  人。中老年人是互联网巨大的增量群体，这个庞大的增量群体也是抖音、快手等
  互联网公司的必争之地。而如今，这些互联网产品越来越在乎老年人的体验，如
  抖音，就在今年推出了“老友计划”，以吸引更多的老年用户；即使是Z世代的代
  表B站，也开始吸入老年UP主。老年人能给互联网带来什么？答案值得期待。

- [[https://mp.weixin.qq.com/s/ZApRrLFODTXyx_WLwDijsQ][《看完北大博士卧底外卖员写的三篇论文，我更迷茫了。。。》]]

  前几天，有个北大博士生为了做研究写论文，当了将近半年外卖员的事情，又一
  次把外卖小哥的问题拉回到了人们的视野。实际上，北大博士卧底当外卖小哥是
  2018 年的事情，那几篇相关研究的论文则是 2019 年的论文，这些事情都是好
  久之前了。只不过，因为这几篇论文内容详实，又有着难得一见的实际田野调查
  的内容，所以又被翻出来了。看完之后，感受只有一个就是： “ 外卖行业，也
  太内卷了吧。”

- [[https://mp.weixin.qq.com/s/lf1GVfOvxzhlu3-36EhqaA][《电商“反叛军”Shopify：登顶全球增速第一，为什么亚马逊阿里都在“抄”它？》]]

  本月初，联合国贸易与发展会议发布了一份关于全球电商发展的报告，按照全球
  商家商品交易总额对各大电商进行了排名。2019年和2020年相比，前四名的座次
  纹丝不动，依然是阿里、亚马逊、京东和拼多多，但第五的位置却被Shopify强
  势夺下，并且在2019年-2020年里，Shopify的增长速度远超其他所有平台，登顶
  全球第一。

- [[https://mp.weixin.qq.com/s/Huf6cCHAemMeQYhSpFWgkQ][《拆解「华为造车」概念股：谁在鱼目混珠？》]]

  4月12日华为轮值董事长徐直军表示，华为已与北汽、广汽、长安三家车厂展开
  了合作；紧接着，4月15日，首款搭载华为自动驾驶ADS的汽车进行测试。受这些
  消息影响，华为汽车相关概念股开始逐渐走强。其中，广汽集团、北汽蓝谷、长
  安汽车、小康股份因为与华为的合作最深，最受资本市场关注。在这些公司股价
  大涨背后，除了华为的“加持”，它们在新能源造车方面的实力，到底如何呢？
** 2021-05-12
- [[https://mp.weixin.qq.com/s/4YIzsyz3p5Hy9YQNXOXElw][《老龄化二百年——全球化视角下的中国人口问题》]]

  备受关注的第七次全国人口普查数据，终于在5月11日发布。老龄化、少子化问
  题日益成为中国社会热点，与经济发展内卷、都市房价过高、教育资源受限等问
  题交织在一起，看似在讨论人口问题，其实是在讨论机会和公平问题。对今日中
  国老龄化问题的思考，需要突破“当下”和“本国”的局限，应当站在历史和全球的
  高度，全面梳理全球人口膨胀及老龄化的成因及其影响。

- [[https://mp.weixin.qq.com/s/Tbs2bLTZDSN17V0BjUk7vA][《未来十年，结婚、生子、买房有什么挑战？人口普查报告里都有答案》]]

  第七次人口普查的数据在鸽了1个月后终于姗姗来迟，要想知道我国现在的人口
  现状到底什么样，还是要看全第七次人口普查的数据后再做判断。这份人口普查
  数据，展现出中国未来怎样的发展走向？关乎未来结婚、生子、买房，一起来解
  读一下这份关键性数据，人口普查数据中又藏着哪些机遇和挑战？

- [[https://mp.weixin.qq.com/s/SBpPtMzmum-Viui4dpDdNQ][《巨头再战「搜索」：微信字节都在加码，但思路变了》]]

  自 PC 时代，百度一统搜索江湖后，中国的搜索领域已接连数年无战事了。然而
  近期，随着字节、微信、阿里等巨头密集入局，搜索赛道又迎来了久违的兴奋。
  今年以来，包括微信、抖音、手机淘宝、手机百度、今日头条在内，还有多款产
  品正围绕「搜索」能力的升级频繁出手。这似乎是一场抢占搜索大盘的二次竞赛，
  可引发巨头扎堆入局的原因，远不止分食市场这么简单。

- [[https://mp.weixin.qq.com/s/B9FrmshbrX2ZT6OyiR-I7w][《中产为什么爱跑马拉松｜大象公会》j]]

  在你的微信朋友圈中，什么是中产阶层晒生活方式的标志？住学区房？开好车？
  穿品牌？吃日料、潮汕火锅？大概还少不了一样：跑马拉松。在各种值得一晒的
  生活成就中，马拉松可能是经济花销和学习成本不高，但腔调相当高的一种，马
  拉松的主要难度在于坚持。为什么只有马拉松，成了风靡世界的时尚运动？

- [[https://mp.weixin.qq.com/s/jn5WJPXOTWxjIHKfrqiMQQ][《李佳琦、薇娅转型记》]]

  在过去三年中，薇娅和李佳琦建立了属于自己的直播带货王国，但对于超级主播
  而言，直播大环境的变化和垂类主播崛起，正在让他们不得不尽早思考转型。薇
  娅和李佳琦正在走向不同的转型路：前者谋求建立最大的“百货大楼”，并聚集更
  多的顶级售货员；后者则深挖个人IP，并开始向偶像化之路靠拢。

** 2021-05-10
- [[https://mp.weixin.qq.com/s/El22KsfvsZ8ltAenDsLzKw][《万字长文｜复盘Netflix与百视达的10年「商战史」》]]

  在百视达的影片租赁门店遍布全美之时，Netflix 开始创业做线上租片，与当时
  如日中天的百视达进行对抗。这场「战争」说是蚂蚁战大象一点也不为过。毕竟
  鼎盛时期的百视达拥有的店面总数超过 9000 家，员工超过 8.4 万人。并且，
  在和百视达竞争的同时，Netflix 也遇到了亚马逊和沃尔玛两只「拦路虎」试图
  抢占市场。所以，Netflix 是如何突破重围再到今天市值近 2300 亿美金？

- [[https://mp.weixin.qq.com/s/vBAZkYamTRaQ5J86YXZ3Ng][《戴志康复制唐彬森》]]

  数字世界才是真实的，现实世界的东西反倒没那么真实。是信息决定了物质，而
  不是物质决定了信息。并且，数字世界是我们这些孩子能够亲手创造出来的，而
  在现实世界，我们可能无能为力。戴志康把伙伴云做成无代码的应用搭建平台，
  帮助企业数字化，获得红杉和五源的投资。

- [[https://mp.weixin.qq.com/s/I3IjIUPQnt01hxV00QBGhg][《抖音快手GMV冲万亿，阿里怕了吗？》]]

  淘宝从电商走向直播，抖音从视频走向电商，两者在交汇处的成绩接近了。在电
  商上，抖音跟淘宝走了两条不同的路：淘宝强调“还能买这些”，抖音强调“在这
  也能买”。但无论区别是什么，电商背后的核心逻辑并没有改变，依然围绕着前
  端流量和后端供应链效率的提升。抖音快手正在快速蚕食前端流量。阿里将如何
  攻防？

- [[https://mp.weixin.qq.com/s/kaGch_jK59oC6VmDC2cnEQ][《舆论风暴后，谁还在买特斯拉？》]]

  特斯拉维权事件，在引发“舆论风暴”后，大部分人都在等着看特斯拉“笑话”。然
  而在此之前，特斯拉刚交出一份靓丽的“成绩单”。其中，一季度中国市场特斯拉
  交付量达6.9万辆，是去年同期的3倍，占全球销量的近37%；中国市场仍是特斯
  拉全球第二大市场，但与美国市场的规模进一步缩小。特斯拉的潜在客户会因为
  此次事件远离它吗？

- [[https://mp.weixin.qq.com/s/EsK5VGfqI_mGp6VD5bF82Q][《腾讯：你们负责造「元宇宙」，我负责收购》]]

  人们在 Roblox 打造的虚拟世界里玩乐、工作、消费，甚至他们还能赚钱「反哺」
  现实生活。现实世界不断虚拟数字化，且现实和虚拟互相联通。一时间，「元宇
  宙」这个概念在创投圈获得了无出其右的关注，但这阵热风刮了快两个月也还没
  消停，因为人们发现这种造「元宇宙」的兴奋和紧张，已经传导到了腾讯等互联
  网巨头那边，甚至发现，他们早已提前布局。

** 2021-05-07
- [[https://mp.weixin.qq.com/s/S3JzSDflzxpb08Sf6zHXgA][《传奇永不落幕 —— 纪念大卫·史文森》]]

  “受托人”这个词所代表的行业原则指导了大卫一生中的许多重要决定。这些年来，
  大卫成为了一个典范，证明了作为一个受托人意味着什么：保护投资者的利益，
  并使你的利益与信任你的投资人、你的合作伙伴保持一致。大卫还有句话，“管
  理好风险，收益自然就有了”。后来，“风险管理”和“受托人责任”也刻进了高瓴
  的DNA。


- [[https://mp.weixin.qq.com/s/qXlvzQpQEHrw0SHP7P2qwQ][《互联网大厂，到底该如何致敬青年》]]

  向这届年轻人致敬这件事上，互联网大厂可谓是不遗余力。五四青年节，快手、
  B站、京东、知乎、小红书等数家互联网大厂，接连推出了以“致敬青年”为主题
  的系列短视频。在种种因素的作用之下，这场大厂们集体参与的青年节策划，连
  带着和青年节系列短视频有关的话题很快“出圈”，成为了人们热议的话题。而在
  这背后，都体现了互联网大厂做传播的哪些趋势？又有哪些槽点和爽点值得评说？


- [[https://mp.weixin.qq.com/s/Qk7EQD5GICChbmsOzNzPwA][《看完段永平的100条思考，终于知道他为什么这么牛…》]]

  今天一起来看看段永平这些年来关于企业管理、关于投资、关于认知、关于人的
  这些思考。时间是优秀企业的朋友，是平庸企业的敌人。对企业如此，对人亦如
  此。我花20年理解的东西，如果你能花10年搞懂就至少比我厉害多了。与大家互
  勉，以下，请享用。


- [[https://mp.weixin.qq.com/s/jrs_MnByhozJM7QcxnUfqA][《全球不均衡复苏的经济后果》]]

  疫苗正在重新划分这个世界：一个是欧美群体免疫世界，疫情急转直下，经济强
  势复苏，货币转向可期。另一个是依然深陷疫情泥潭的亚非拉世界，疫苗有效性
  差，医疗资源不足，经济持续低迷。若亚非拉国家不快速解决疫苗短缺问题，全
  球经济不均衡复苏将成为大势，并可能引发严重的经济后果。本文从货币政策的
  角度分析全球经济不均衡复苏的问题。


- [[https://mp.weixin.qq.com/s/hFkbYFz1b34fZvl64XANXA][《那些涌向上海的人才、热钱和新造车》]]

  2020年，新能源汽车股票集体上演疯狂飙涨，蔚来市值年涨幅超过12倍、特斯拉
  更是站上全球车企市值之巅。新能源汽车产业一片火热，引发各地政府极大投资
  热情。上海、合肥、南京等城市“抢项目”、“抢人才”，一场关于“新能源之都”的
  角逐悄然开场。本篇为《谁才是“新能源之都”》系列报道第二篇。

* 四月
** 2021-04-28
- [[https://mp.weixin.qq.com/s/_gRPoA_AdWs3bduepD3V_Q][《深度复盘：亚马逊AWS帝国，是如何被微软奇袭的？》]]

  数据显示，2019年亚马逊总经营利润136.81亿美元，AWS贡献了92亿美元，占比
  67%。如此“吸金”能力，让外界洞察AWS实力的同时，也让大众清楚地认识到了云
  计算的广阔前景。“云计算”进入下半场，谷歌云新任CEO托马斯·库里安宣称，要
  加码云计算销售投入，与亚马逊一较高下。从挑战者到被挑战者，AWS角色转变
  的背后，是云计算行业竞争环境的变化：由战略布局速度的竞争，转变为增值价
  值的较量。

- [[https://mp.weixin.qq.com/s/yKxk3C49G0YBvl73YqyBtw][《为什么所有科技公司，都害怕 iOS 14.5 更新？》]]

  「苹果的隐私保护政策和用户隐私毫无关系」，Facebook 认为，苹果宣称能够
  保护用户隐私是为了更好地获得利润，尤其在用户可感知的产品创新难度提升时，
  把用户的注意力从产品本身转移到自己是一个提升销量的有效办法。从
  Facebook 的立场看，苹果一刀切的做法像是一种「懒政」。但在人人都对用户
  数据被滥用惶恐万分的当下，苹果的「懒政」赢得了喝彩。

- [[https://mp.weixin.qq.com/s/KNNqrKTWmRHb3DMQxnMZhg][《2021中国科技创新20条判断：大变局中，万物生长 | 甲子光年》]]

  过去一年，中国作为世界第二大经济体，在疫情冲击中的复苏速度令外界感到惊
  讶，尤其是在国际关系紧张之际，中国经济超预期加速，体现了中国强劲的复苏，
  2020年12月26日，英国智库经济与商业研究中心预测：中国将在2028年超过美国
  成为世界最大经济体，比此前估计的时间提前五年。这是因为两国在疫后的复苏
  情况形成鲜明对比。

- [[https://mp.weixin.qq.com/s/JSNSLD71c7WjO1D73kvAuA][《万字拆解孩子王：充满矛盾的母婴零售之王》]]

  母婴零售行业的龙头企业——孩子王。在今年4月8日通过了深交所上市委的批准，
  将于不久后正式敲钟上市。虽然近两年孩子王的营收逐步放缓，甚至呈现下降趋
  势。但是重振旗鼓冲击创业板成功的孩子王，多少有点“王者归来”的意思。不过，
  孩子王的增长是可以持续的吗？对于零售行业来说，应该从孩子王身上学到什么？

- [[https://mp.weixin.qq.com/s/QnOGmR0a9IWGmRy0abDoKA][《对话心动创始人黄一孟：做游戏不是去理解和操纵人性》]]

  创业已经18年的黄一孟，从 VeryCD 到心动，他用 Netflix 创始人的话总结心
  动必须经历的改变，“公司不应该是一个 family，而应该是一个 team。”。一个
  组织的文化是组织里每个人做决策的惯性，是它成功的根基。这也是文化难以调
  整的原因——鲜有企业文化转型的成功案例。作为 CEO 的黄一孟，推动了公司的
  转变，也在把自己从和平时期转入战时状态。现在，他要追回错过的时间。

** 2021-04-27
- [[https://mp.weixin.qq.com/s/EWOHA4AQDiBDAX5EdzItIg][《后厂村的秘密，都在网约车里》]]

  对于大厂内部的风吹草动，这些网约车司机往往也最敏感，比如谁家的业务线要
  整合，哪家在准备造车，甚至谁要打算把某个海外分公司关了，他们也会知道。
  不少网约车司机甚至还和经常坐车的大厂年轻人加了微信，成了朋友。对这里的
  网约车司机来说，互联网大厂没有秘密。

- [[https://mp.weixin.qq.com/s/mWhMYSz-CT6J0YSgaxK9vA][《特斯拉终于找到了盈利之路：炒比特币和卖碳积分》]]

  在刹车失灵、自动驾驶致命车祸等诸多质疑和全球汽车缺芯大潮之下，特斯拉交
  出一份看似十分靓丽的财报，并没有调动投资者的兴奋情绪。财报发布后，特斯
  拉盘后股价一度跌超3%。作为全球电动汽车行业的标杆性企业，特斯拉的每一份
  财报都是视为整个电动汽车行业的风向标。盈利同比增长数十倍、交付量同比翻
  倍的成绩单，为何没有让投资人兴奋？光鲜财报背后有哪些不为人注意的细节？

- [[https://mp.weixin.qq.com/s/0GEmENIPDJQNWH1LMGMfhQ][《段永平10年50条思考：高手与普通人的区别》]]

  段永平，是与小霸王、步步高、OPPO、vivo、一加、拼多多存在千丝万缕关联的
  人，也是丁磊、黄峥人生转折点中重要的参与者，他作为投资人，通过投资网易、
  GE、苹果、腾讯等企业，获得超过当初做实业利润的巨额回报，成为中国著名
  “价值投资人”之一，他本人的身价如今也达到了115亿元之高。本文提取了段永
  平十余年间分享的精彩内容，包括其思考的底层逻辑，以及对管理、企业文化、
  团队建设、投资的40条建议。

- [[https://mp.weixin.qq.com/s/BsQqZ7_WdH9LJfH13Uyr-Q][《投资人朱啸虎：给创业者和新品牌的五大建议》]]

  知名天使投资人、金沙江创投合伙人朱啸虎做了名为“新品牌创业和投资”的演讲，
  朱啸虎专注于互联网、无线和企业信息应用领域的创业投资，本次演讲干货满满，
  刀刀见血。他认为当前是创业好时机，应该把握住好赛道，学会运用资本的力量，
  找到品牌的突破点，做出差异化和品牌化。这依旧是一个好的时代，属于创业者
  和新品牌的时代。

- [[https://mp.weixin.qq.com/s/m9iPZTkRflbEG6y4Q5eOag][《从美团实习生到年入30亿，沈鹏带着水滴冲刺纽交所》]]

  4月17日，水滴公司向美国SEC递交招股书，准备在纽交所上市。在招股书公布之
  前，水滴公司主动关停了其“水滴互助”业务，这一动作被广泛解读为：面对监管
  带来不确定性，水滴公司有意为顺利上市扫除障碍。问题在于，水滴互助是水滴
  公司的起家业务，是其流量的重要来源，关停将带来什么影响，互联网式增长魔
  力能否持续？此外，近年来关于水滴公司的讨论很多，其收入结构究竟如何？融
  资的钱都花在哪儿了？未来又将向何处去？
** 2021-04-26
- [[https://mp.weixin.qq.com/s/2pWM-ho7Vbl66BUkl4RejA][《掘金本地生活，抖音和快手的新战场》]]

  手握六亿日活的抖音和3亿日活的快手，一直在尝试流量变现的新可能，作为强
  有力的流量入口，仅将流量红利用在广告营收和直播带货上，显得过于局限。面
  对流量变现焦虑，抖音和快手在各个细分领域展开搏斗，这一次，战火蔓延到本
  地生活。对于抖音和快手而言，手握庞大的用户和流量，只是打开本地生活业务
  的基础，真正的攻坚战是商家和用户的忠诚度。

- [[https://mp.weixin.qq.com/s/x4RMNBHVdHzScUVYQWJlWQ][《五虎将齐出，腾讯PCG大调整解读：都是字节惹得祸！》]]

  林松涛孙忠怀可比桃园结义的关张，守住在线视频的大本营；常山梁柱收编腾讯
  音乐；郄小虎宝刀未老，堪比老黄忠；姚晓光镇西线，憋元宇宙大招西出岐山。
  且看诸葛宇昕调兵遣将，北上对抗字节。

- [[https://mp.weixin.qq.com/s/vhAbjP_eSqxWdKBq_JAAxQ][《快手和抖音越来越“差异化”》]]

  2020年，快手平台创作者中，私域收入达400亿元，内容的粉丝触达率高达62%，
  且快手80%的打赏来自私域流量。400亿元的私域营收备受市场关注，私域更是成
  为快手高管的高频词汇，“未来十年，得私域者得天下”，私域流量将是短视频市
  场的又一爆发点吗？如今从底层逻辑来看，愈加“成熟”的抖音、快手已逐渐分道
  扬镳，分别走向公域和私域。

- [[https://mp.weixin.qq.com/s/cKMcG6YCNefiUNutBw709g][《中国住房市值报告》]]

  现有住房市值研究均存在明显问题，或夸大其辞，或混淆口径。网文流传“2017年中国房产市值达65万亿美元，超美国、欧盟、日本总和”，在量上错误地把商品房等同于商品住宅，且误以高估的人均住房面积计算导致高估住房存量，在价上把规模庞大、但缺乏流动性的农村住房按商品房价格计算。本文的研究思路是：以市价法测算中国不同类别的城镇住房市值，以成本法测算中国农村住房市值，并主要以OECD公布的国际住房市值数据为基础推算当前值作为比较。

- [[https://mp.weixin.qq.com/s/MbkNnXkD9pJpDqtMkRbWrQ][《特斯拉行驶数据归谁？》]]

  2021年4月19日，上海车展上一位特斯拉车主身穿“刹车失灵”白T恤站上车顶维权。
  特斯拉方坚称，刹车未失灵，对方搞事情。公众舆论迅速聚焦到一个点：行驶数
  据。三天后，特斯拉对外公布了车辆事故发生前一分钟的数据。数据公布后，车
  主家属指责特斯拉侵犯个人隐私权，要求撤销数据。同时，一些人质疑，特斯拉
  可能修改过数据。这起特斯拉维权事件终于把数字经济的关键问题推到了前台：
  数据的产权界定、隐私保护以及风险监管。

** 2021-04-22
- [[https://mp.weixin.qq.com/s/QNxwjYJax4dXCL-ubKR6Kg][《小程序之争，支付宝输了吗？》]]

  阿里与腾讯始于四年前的小程序之争，如今高下渐渐清晰。目前已经或计划开设
  微信小程序的阿里系业务，覆盖下沉市场、二手和生鲜电商，以及物流配送、互
  联网出行等多个板块。阿里诸多业务争相进驻微信小程序，给腾讯出了道难题，
  但这件事里最尴尬的不是腾讯，而是同为阿里系的支付宝小程序——“同袍”出奔，
  难免导致外界产生这样的质疑：“支付宝小程序的流量已经不足以支持阿里系业
  务发展了吗？”

- [[https://mp.weixin.qq.com/s/7SEDUpSvhhv1pIxbit6sPw][《揭秘文和友：怎样用排队创造排队》]]

  集成式饮食消费不稀奇，但像超级文和友这样火的却少见，在文和友的消费场景，
  吃饭、购物与直播几乎同时发生。但超级文和友的真正价值是商业地产，跟做饭、
  吃饭没啥关系，就像加油站的商业价值跟卖汽油其实没啥关系一样。本篇文章将
  专注回答三个问题：1. 文和友怎么选商户？2. 为什么要做成封闭式的店中店？
  3. 为什么年轻人喜欢去文和友？

- [[https://mp.weixin.qq.com/s/QFXLiva9LZc8PhnAPG-38g][《中国服装大败局》]]

  在中国一二线城市的任何一个繁华商圈，还能坚守的国货服装，真的不多了。
  “中国是最大的时尚消费国，也是最大生产国，但却没有什么时尚话语权。一说
  大牌，在大家嘴边的都是国外品牌。”中国“时尚女魔头”洪晃一语道破中国服装
  业的怪现状，“这在哪个国家都是不正常的，都是这个国家的从业人员要去改变
  的。”

- [[https://mp.weixin.qq.com/s/v2QMRvB32C1iFnP9OgZTRQ][《中国制造之困》]]

  随着人口红利逐渐消失，中国制造的成本优势难再续。2012-2018年，我国劳动
  年龄人口的数量和比重连续7年出现双降，7年间减少了2600多万人，2018年年末
  全国就业人员总量也首次出现下降。然而，劳动力成本上升只是中国制造困境的
  冰山一角。中国制造的真正挑战是被困在一个庞大的宏观系统之中。本文从经济
  学的角度剖析中国制造的系统性困境。

- [[https://mp.weixin.qq.com/s/upx7hR15KerV7cWNV9_JZA][《中国一线城市房价高不高：全球比较》]]

  与全球大多数国家类似，房价的地区差异极大，中国大部分三四线城市的绝对房
  价和房价收入比基本合理，但是一线城市具有特殊性。在考虑持有成本后，中国
  一线城市绝对房价、相对房价依然位居全球前列，宇宙的中心。究其原因在于人
  口流入但土地供给严重不足、优质公共资源富集以及货币超发，中国一二线城市
  房价并非由当地中位数收入人群决定，而是由全国高收入人群决定。

** 2021-04-21
- [[https://mp.weixin.qq.com/s/hlZKXb-03je3b-hQtmNtQg][《新电商七雄》]]

  这一个月来，关于电商的消息很多，电商是一个旧战场，最激烈的交锋发生在
  2012年前后，当时的电商赛道，出现了七雄争霸的格局，时称“电商七雄”，分别
  为阿里巴巴、京东商城、苏宁易购、国美、易迅、当当网和1号店。几经鏖战，
  新的电商七雄已经诞生了，阿里巴巴坐稳了老大了位置，紧随其后的是京东，然
  后是微信、拼多多，抖音和快手，苏宁易购保住了最后一名的位置。

- [[https://mp.weixin.qq.com/s/sZ8TIqNh-TgM89RTAE66yA][《任天堂不可模仿》]]

  任天堂是一个已经有着130年历史的世界级IP，任天堂不仅没有倒下，还做到了
  百年长青。任天堂在某些事情的做法上非常“日本”，他们拒绝过能赚更多钱的策
  略，并且惧怕因为太追求财务目标而失去用户，打法非常保守。问题是，在游戏
  市场俨然已经进入移动时代的大背景下，任天堂这位老牌玩家还能死磕多久？

- [[https://mp.weixin.qq.com/s/0C09t3wG-JGib-sIYbhN0A][《万字解读：企业如何在消费者主权时代构建增长策略？》]]

  在深入各行各业研究了许久后发现：只有很少企业真正做到“以用户为中心”，
  随着生产力的发展，我们已经迎来消费者主权时代，而真正从战略上开始行动的
  企业还是少数。在数字化的驱动下， 这个时代到底发生了什么？企业战略又该
  如何战？如何略呢？本文介绍了消费零售企业如何制定"以用户为中心"的数字化
  战略和战术系统。

- [[https://mp.weixin.qq.com/s/h532vYJ1N2KbdlkkijKXjg][《抖音为什么要做兴趣电商？》]]

  电商是中国互联网最为成熟的赛道之一，作为电商这一成熟赛道的新晋玩家，坐
  拥6亿日活的抖音会如何切入电商市场呢？在第一届抖音电商生态大会上，抖音
  电商总裁康泽宇的答案是——兴趣电商。兴趣电商，这是一个新名词，它到底是什
  么？它是不是新瓶装旧酒？它对抖音而言意味着什么？抖音又为什么要做以及会
  如何做兴趣电商？

- [[https://mp.weixin.qq.com/s/Judq18Zv714l_0_FmUmNpQ][《疯狂30年，教三亿人英语的李阳去哪儿了？》]]

  2004年，李阳的自传书里，他写下了十条疯狂名言。一句是“我的生命贱如街上
  的野狗”，还有一句是“中国不需要为情所困的人。”这本《我疯狂我成功》10年
  内发行了1000万册，个人成功的神话被不停讲述，李阳在全国范围内，掀起了
  “疯狂”的英语热。但几年后，李阳因家暴被告上法庭，接着加入了安利公司，又
  称自己皈依了佛门。他在采访中说，其实自己一直是个自卑的人。
** 2021-04-20
- [[https://mp.weixin.qq.com/s/GmDkqxdAO-8X5kH00nyOmw][《别人家展车，特斯拉展示韭菜》]]

  特斯拉惹了众怒。4月19日，在上海车展的媒体日上，特斯拉展台成为焦点，一
  名年轻女子身穿白色T恤，衣服上印着“刹车失灵”四个红色大字，爬上特斯拉展
  车车顶喊话维权。特斯拉的刹车失灵事件，已经被媒体报道过数十起。而特斯拉
  屡次都将事故原因认定为车主操作不当。后台数据在特斯拉手里，既当运动员又
  当裁判员的行为让车主不满。抛开情绪，这里面究竟发生了什么？特斯拉是不是
  甩锅？为什么特斯拉会发生多起刹车失灵事件？

- [[https://mp.weixin.qq.com/s/x_WZUYz4sZjVk-N7TGiuBw][《硬核干货丨为啥皮克斯的电影剧本总在大气层？》]]

  皮克斯为何总能产出成功的动画电影？近日《玩具总动员3》的编剧迈克尔·阿恩
  特将个人的一节内部编剧教程，免费发布到网上，让很多皮克斯迷惊呼新奇且有
  用。在这个70多分钟长度的视频中，他坦诚描述了自己曾经历的皮克斯内部故事
  创作流程，他在其中感叹，在皮克斯的编剧工作“宛如地狱”，并向观众安利了一
  个皮克斯在电影剧本创作上的法宝：一个十分机械化、“反人性”的流程。

- [[https://mp.weixin.qq.com/s/dwZ8SCFAQmOyRgHKgqQmRA][《扎克伯格的社交帝国：以抄袭续命，靠收购永生》]]

  今天，Facebook正式打包发布了一系列音频产品，仔细一品这些新功能发现
  Facebook不仅抄了Clubhouse，还变了个花样又抄了一次TikTok，并顺手把
  Twitter、苹果、Discord等全部放到狙击范围之内。“不要因为太骄傲而不去抄
  袭”这早已是Facebook公开的信条。虽然在Messenger之后Facebook几乎再也没有
  过现象级创新产品，但走着“抄袭、模仿、收购”这条野路子的Facebook，如今的
  商业版图却也越铺越大，仍然展现着顽强的生命力。

- [[https://mp.weixin.qq.com/s/HVJit9uolsVq-otOtcKLGQ][《全球芯片荒：从造车盛宴到芯片短缺》]]

  自2020年底开始，芯片荒席卷全球。奥迪、大众、福特、戴姆勒、丰田等汽车巨
  头纷纷因芯片短缺而减产、推迟汽车交付，部分工厂甚至停工。除了汽车领域，
  消费电子、物联网等市场也出现不同程度的芯片荒。全球芯片制造巨头台积电
  CEO魏哲家预测：“芯片需求将持续高涨，短缺状况将持续今年全年，并可能延长
  至2022年。”为何全球突现芯片荒？本文从经济学的角度简单分析全球芯片荒现
  象。

- [[https://mp.weixin.qq.com/s/X76bSuaFA70oNG1R-5iY6A][《盛产“老铁”的东北，没有直播带货神话》]]

  东北没有电商生态。东北这片黑土地的直播生态现状，这里的姑娘美、小伙靓，
  嘴皮子更是巴巴响，天生幽默乐呵，就像东北小品一样，逗得人咯咯笑，传说中
  的快手6大家族，5个都出自东北；这里仿佛有天然的直播带货土壤，但这里却无
  法诞生过千亿GMV的神话。

** 2021-04-19
- [[https://mp.weixin.qq.com/s/oDALBIt_ejdnuNzmKOiM2g][《王兴，带头围观了华为第一辆车》]]

  千呼万唤，华为第一辆车正式亮相了。昨晚（4月17日），北汽新能源旗下高端
  品牌极狐联合华为发布了极狐阿尔法S华为HI版。有趣的是，美团创始人王兴围
  观了华为第一辆车，还罕见下场评价：“特斯拉终于遇到一个技术实力和忽悠能
  力旗鼓相当的对手了”。今年以来，造车江湖风起云涌，一位位财富自由的大佬
  前赴后继造车，还有一波科技新贵正在赶来的路上。

- [[https://mp.weixin.qq.com/s/cq9uYIMPjLtiuHewel45UQ][《创业公司实现增长的48条军规》]]

  对于创业者来说，“增长”乃是一切战略决策和市场行为的核心，随着注册制的实
  施和各产业全面数字化进程的加速，创业公司能否实现快速“增长”，已经成为识
  别其方向、商业模式选择以及组织、市场策略是否正确的关键准绳。那么，如何
  实现增长？什么是创业公司需要的增长？到哪里去寻找增长的动力和势能？这些
  问题的答案，对于今日的创业者来说就显得尤为重要。

- [[https://mp.weixin.qq.com/s/2PuDoFcXvqVETvj8-TRgvw][《给互联网人的反侦查手册》]]

  几乎每家互联网公司里，程度更低的隐私侵犯几乎无处不在。办工场所公司会监
  控员工的几乎一切行为，比如查看内部系统某些信息的次数、社交软件上的聊天
  内容、午休时间浏览的网页、离开工位的时长、加班的时长、如厕的时长。即使
  在一个员工离职后，监控也不会停止，入职一家存在竞争关系的公司，可能会让
  这个员工赔偿上百万元。

- [[https://mp.weixin.qq.com/s/Oo-4h8UhBBP-xj8uD4G18w][《“劈柴”掌权这几年，谷歌怎么就成了另一个百度》]]

  现在的谷歌处于一个十分微妙的时刻，反垄断调查，组织管理和运作的方式都在
  经历一次大考，现在正是谷歌需要强势整合它旗下五花八门的各类业务的时候，
  但谷歌仍然是一家核心搜索/广告业务占绝对大头的公司，核心之外的业务仍然
  没有太大进展，公司管理面临多重难题，这难免让今天的谷歌，看起来有点像曾
  经的百度：创立多年后仍然过度依赖核心业务，跟不上时代的潮流，诸多转型尝
  试无疾而终。

- [[https://mp.weixin.qq.com/s/xp1W4yxY09blAcNFvA80Ew][《重磅丨专访林毅夫：中美能躲过“修昔底德陷阱”吗？》]]

  2020年，中美经济总量差距进一步缩小，中国GDP占美国的比重升至约70%。而20
  年前，中国经济总量仅为美国的十分之一左右。这一数字变化的背后是中国的崛
  起。“当一个大国崛起，会对之前的大国形成挑战，往往会带来摩擦和冲突”，这
  是“修昔底德陷阱”的定义。当崛起中的中国，遇上掌握全球霸权的美国，全球竞
  争格局会发生何种变化？中美能躲过“修昔底德陷阱”吗？

** 2021-04-16
- [[https://mp.weixin.qq.com/s/XDDegEwQvahfeTbzEoc03g][《新冠mRNA疫苗幕后英雄：曾不断被贬职拒绝，默默无闻30载，年收未过6万》]]

  被学界、被社会、被投资人连续否定、拒绝30余载的66岁老人终于得到了全世界
  的认可。此前，她在学界的地位非常边缘化，职位只是学术地位很低的兼职研究
  助理教授，没有任何常任职位，年收入不到6万美金。而现在，她成了新的希望
  和救星。正是她用大半生研究的mRNA技术，让辉瑞和Moderna在疫情爆发后可以
  迅速研发新冠疫苗，把人们从令人绝望的疫情中拯救出来。

- [[https://mp.weixin.qq.com/s/Wcb05M4plcpEI5d3vZ-fNA][《拥有1.2亿基民的基金行业，面临大变局》]]

  中国基金市场快速扩容。伴随着最近两年的牛市，基金市场上涌入一大批新用户。
  MOB研究院数据显示，去年一年就有6000万新基民加入基金的狂欢，互联网基民
  用户规模突破1.2亿。随着春节后A股大幅调整，让新基金发行盛况不再，甚至多
  次出现基金发行失败的状况。基金要成功发行，必须达到“基金份额不少于2亿份
  且基金认购人数不少于200人”的标准，而这些基金都没达到这个标准。

- [[https://mp.weixin.qq.com/s/XrXW7sv-qMBKrWj75hK4Jg][《我们有自由意志吗？》]]

  又到了新一天的早晨，你起床，洗漱，换好衣服，出门上班，重复着每天的日常
  惯例。每一天，我们所产生的这些想法、念头、行为，它们是由我们自己所产生
  的吗？还是由某些我们所不知道的外物所决定的？我想很多朋友应该都思考过类
  似的问题。那么今天，我想好好跟你聊一下。

- [[https://mp.weixin.qq.com/s/Gn9PmhPqbeH4zPIf-XRbwQ][《王慧文：高手如何做决策？》]]

  王慧文用自己与王兴创业的经历，详细讲述了自己如何理解战略，如何理解规模
  效应、马太效应、产业链，如何进行商业判断。比如说：如果一件事情一开始什
  么都完美，你的同行们还没有脱颖而出，那说明你进入了一个错误的行业。几乎
  所有的领域，大部分决策者都没有有效信息、知识结构和判断方法做出独立判断，
  大家只能依赖专家或者从众，因此产生马太效应。

- [[https://mp.weixin.qq.com/s/Y0ygKhW8yKOB75i79j6apA][《CEO 贝佐斯的最后一封信：世界想让你做普通人，别信》]]

  4 月 15 日，CEO 杰夫·贝佐斯发出了最后一封致股东信，如果用简短的一段话
  概括这封信，就是：亚马逊有今天的成就，因为我们一直在创造价值。对于客户
  来说，这个价值可能是 Prime 会员把用户购物时间节省下来，AWS 提升了软件
  开发的速度，但是这不意味着亚马逊完美无缺，在给员工和社会创造价值方面，
  还需要做更多。同时别忘了，亚马逊何以走到现在，源于它的独特性和不可替代，
  一直做好为此付出代价的准备。 
** 2021-04-15
- [[https://mp.weixin.qq.com/s/yCKQJk6OUdQaMhxblfIn9A][《围攻美团》]]

     在过去的数年间，本地生活服务一直都只有一个寡头。美团通过“无限杠杆”
     的商业模式不断扩张，目前业务几乎涵盖了生活的方方面面，成为众多消费
     者寻求经济、优质的餐饮、旅游、娱乐等服务的一站式平台。但如今，美团
     正在被围攻。抖音、快手、哈啰、饿了么、滴滴、百度、字节、国美等大小
     巨头都在加入赛道，本地生活成了香饽饽，美团的市场地位，正在遭受挑战。

- [[https://mp.weixin.qq.com/s/jUlta3CsBPqxOlj2qdqJmg][《深度复盘：乐视网财务造假十年，贾跃亭是怎么瞒天过海的？》]]

  由于连续十年财务造假及非公开发行欺诈发行等行为，乐视网和贾跃亭分别被处
  2.4亿元罚款。十年财务造假的消息震惊业界，也证实了乐视网与贾跃亭并非“梦
  想家”，而早已沦为“骗子”。乐视网的衰败并非突然，一直以来的业绩也靠着灰
  色的资本手段腾挪而来，从资金到业务，都是一本糊涂账，但在长达数年的时间
  里却被掩盖、遮蔽。

- [[https://mp.weixin.qq.com/s/VzlTXW55uXhjzz6V5bjyMg][《「缺芯」风暴：自救与求生丨深氪Lite》]]

  芯片缺货，产品无法交货，手机、电脑、IoT、汽车芯片全线急缺，甚至从前供
  货充足的中小容量内存芯片，2021年也出现紧缺。犹如多米诺骨牌，小小晶圆的
  短缺最终给庞大的全球消费电子市场蒙上阴影。这场“缺芯”风暴是怎样发生的？
  产业链条上焦虑、无助的人们，又是如何背水一战？

- [[https://mp.weixin.qq.com/s/1GJvmM2tXZR1XI_R_wwRXg][《拼抖快都来抢饭碗，淘宝还能打吗？》]]

  近来，阿里过得不太平。4月10日，阿里收到了市场监管总局182.28亿元的罚单，
  4月12日，蚂蚁集团再次被四部门联合约谈，身后还有同行们步步紧逼。拼多多、
  抖音电商、快手电商都是其有力的竞争对手，微信、B站等APP也在抢夺用户时间，
  淘宝的流量似乎也出现了下滑的趋势。不少人疑惑，内忧外患下，电商老大哥淘
  宝落后了吗？发展了快20年的淘宝，护城河到底是什么？

- [[https://mp.weixin.qq.com/s/8ZLWI9oCqEge7h9RKrA8Eg][《微博狂轰滥炸，知乎暗度陈仓，小说推广的路子能有多野？》]]

  当现代人高频率利用小说打发时间，小说的身价也水涨船高。这种趋利心理也导
  致了可能你不看小说，但是各平台不会允许你看不见小说广告。知乎、抖音、微
  博、微信等各大平台都在用各种方式打着小说广告，无论是为了变现而在小说领
  域开疆拓土的，还是为了赚快钱而跨平台引流的，本质都是基于对小说价值的预
  期。可见，为了乘上小说这股东风，各平台们的推广路子五花八门，甚至野出天
  际。

** 2021-04-13
- [[https://mp.weixin.qq.com/s/mgLBcv41Lyc9-ya3j9u8hA][《日本到底行不行？》]]

  日本政府正式决定两年后将福岛第一核电站的核废水排放大海。很多人嘲讽，传
  说日本人不扔一张废纸，如今为何直接倒核废水？日本是一个令人迷惑的矛盾体：
  日本的核技术颇为顶尖，但核废水只能靠海洋吸收来解决。日本是一个实力强劲
  的经济体，但政府无力承担核废水处理的成本。日本是世界上最长寿、贫富悬殊
  最小的国家之一，但也是深度老龄化、少子化的国家。日本到底行不行？本文从
  资产定价的角度分析“日本现象”。

- [[https://mp.weixin.qq.com/s/MRQHLgO__gl4T7DxEvetPg][《重罚阿里，美团大跌》]]

  4月10日，对阿里巴巴反垄断调查终于有了结果，阿里巴巴因滥用市场支配地位
  行为被国家市场监督管理总局处以182.28亿元的反垄断罚款。市场的判断是“利
  空出尽为利好”，当天，阿里巴巴港股股价大涨，最高涨幅达8.99%，收盘时涨幅
  6.51%。随后，阿里巴巴美股股价也大涨，收盘时涨9.35%。但重罚阿里后，下一
  个是谁？资本市场的反映要直接的多，4月12日，美团股价大跌5.03%，腾讯股价
  跌1.13%，京东股价跌2.15%，拼多多股价跌2.80%。

- [[https://mp.weixin.qq.com/s/a6HVoClCxxLS9jDr9NeQfg][《万字代糖行业研究报告：什么才是真0糖？》]]

  近年来，全民刮起“无糖”风，从外资食品饮料巨头到本土传统企业和新锐品牌，
  纷纷推出多种新型代糖甚至是零糖产品。但关于0糖、0蔗糖、低糖和代糖的概念
  经常被滥用，国家提倡的减糖，减的是什么“糖”？宣称0糖0卡0脂肪的产品是不
  是真0糖？被热炒的赤藓糖醇到底是什么？本文将从制糖业、甜味剂和2C糖类消
  费品三个方面剖析糖行业。

- [[https://mp.weixin.qq.com/s/MZFXa-2kXZ0uAp-S8VA77g][《站在B站幕后的三巨头：掌舵人曾是铁杆用户，创始人选择退居“二线”》]]

  2021年3月29日，B站在香港二次上市，距离第一次在纳斯达克上市，刚过去了三
  年。在纳斯达克敲钟现场，我们看到了B站董事长陈睿、创始人徐逸以及COO李旎。
  而这一次，敲钟现场也有陈睿、李旎、徐逸。对大部分人来说，徐逸甚至是陌生
  的，作为创始人，徐逸如何一步步淡出B站？陈睿又是如何获得B站掌舵权？今天
  为大家捋一捋。揭秘B站的三位幕后大佬：他们是怎样的人？

- [[https://mp.weixin.qq.com/s/PV5ekRfy9XFCw3G_pUxakw][《悄悄地，VR「起死回生」》]]

  新技术的发展，从来都不是线性的。权威咨询机构Gartner为此总结了一条技术
  成熟度曲线，它被广泛用来预测新技术成熟演变的模型：一般可分为5个阶段：
  技术萌芽期、期望膨胀期、泡沫破裂谷底期、稳步爬升复苏期、生产成熟期。VR
  行业也在走一条类似的路。不过，目前只是走了前半程。2016年VR元年；2019年
  VR行业跌入低谷。现在VR行业正在沉默着静待爆发，苹果收购了VR初创公司
  NextVR，索尼宣布正在为PS5开发一款新的VR设备……这一次，VR真的迎来春天了
  吗？

** 2021-04-07
- [[https://mp.weixin.qq.com/s/cIw8kGl000SyHuN-XZlXng][《科创板IPO大撤退》]]

  又一家企业撤回了IPO申请。 4月2日晚间，上交所发布公告称，因京东数科撤回
  发行上市申请或者保荐人撤销保荐，将终止其科创板发行上市审核。 这意味着，
  这个估值高达2000亿的独角兽，在历经7个月冲击科创板后，最终以撤回退场。
  这是今年以来的七十多家IPO撤回案例之一，也是估值最大的企业IPO撤回案例。
  以去年12月为分水岭，“IPO撤回潮”一直持续到现在。

- [[https://mp.weixin.qq.com/s/9Aly                JnAW2gtwWaPqZwycZA][《快手vs抖音：终于活成了彼此讨厌的模样 | 深网》]]

  在当下这个时点，中国的互联网，早已经脱去了一切理想主义的外壳，蜕变出一
  条逻辑——验证产品成功的是流量，验证生意成功的是变现，验证成功本身的，是
  资本市场。“老铁”的快手、小姐姐的“抖音”这样的标签化定义也早已过时。融资、
  IPO、股价、市值面前，“人设”已经不重要，财务报表、用户数据、电商占位、
  网红争夺、广告PK……这才是短视频的中场战事。

- [[https://mp.weixin.qq.com/s/dldi7PIgvt          Jd3bdPekt9Wg][《李宁球鞋炒到5万元，得物被骂冤不冤？》]]

  近日，当红国潮品牌李宁和潮品交易平台得物一同登上了热搜。起因是，几款李
  宁球鞋在得物平台上被炒到了几千甚至几万元，最高的一款，标价48889元，相
  比原价涨幅达33倍。如今，球鞋交易平台在给用户提供便利的同时，在炒鞋热潮
  中扮演着什么角色？得物们究竟是他们声称的不参与定价的第三方开放平台，还
  是炒鞋的助推器？

- [[https://mp.weixin.qq.com/s/9P4xC37V8tnL-oXWk1cOUw][《2021泡沫之王》]]

  今年前两个月在美国上市的公司里，有三分之二都是里面空空如也的“空白支票”
  公司，而他们已经募到了超过3500亿人民币。根据高盛的统计，现在有超过1000
  亿美元的SPAC资金在市场上四处游荡，寻找收购目标，而如果按现在的速度继续
  发展，在未来两年时间里，SPAC公司收购的公司价值将超过7000亿美元。

- [[https://mp.weixin.qq.com/s/AKhk4HcwpLqRw5R8Eil9DQ][《小米、百度纷纷造车，“前浪”比亚迪还有多大机会？》]]

  2020年，国内新能源车销量整体增长10.9%，但比亚迪新能源车销量却同比下滑
  12.5%；汽车是其最大收入来源，却增收不增利，公司利润主要来自手机电子业
  务。其股价自2月触顶273.37元后，持续下跌，目前在170元左右徘徊。随着小米、
  百度等第二波造车巨头入局，比亚迪堪称强敌环伺，压力山大。
** 2021-04-06
- [[https://mp.weixin.qq.com/s/2                   jifSX5vVl2ffbPAgK jkVQ][《这就是新经济 | 五万字拆解中国养老全产业链，80后是养老压力最大的一代人》]]

   养老问题是未来中国乃至全球的大问题。全球正以惊人的速度迈向老龄化。根
  据穆迪的报告，到2020年，13个国家将成为“超高龄”国，即20%以上的人口超过
  65岁，而到2030年“超高龄”国家数量将升至34个。中国不仅面临全球共性的养老
  问题，也需要解决特有的养老挑战，我国老龄人口已经迈过7年加速期，即将迎
  来14年加速，2017-2022年将成为中国养老产业发展的关键期。

- [[https://mp.weixin.qq.com/s/BnRLwAYaTk_utfc_caKNhQ][《穿越废墟：共享单车剧未终》]]

  2020年被称作“共享电单车野蛮生长和激烈竞争的元年”。“这种场面已经很多年
  没见过了。”一位同时亲历单车、电单车两场大仗的人士说。单车交锋集中在一
  线城市，最多下沉到部分二线；而电单车“战火早就烧到镇上，都快下乡了”，战
  事演变为一场“寸土必争”的恶战。这场战役堪称互联网史上最昂贵的钢铁大战，
  它曾如何走向废墟之地，而今又如何重起硝烟？

- [[https://mp.weixin.qq.com/s/Ca0DtTq9CIhDoQeNrN5i7A][《卷入反垄断漩涡的平台经济》]]

  中国互联网经过20多年的发展，平台的能力和资源进一步集中、强化，不少平台
  处于绝对优势地位，但同时也带来了垄断和资本无序扩张的隐患。在国家三番五
  次强调“强化反垄断和防止资本无序扩张”的背景下，平台经济何去何从？

- [[https://mp.weixin.qq.com/s/5qZwgFc6P           JPlGcD8bmLh-g][《独家专访罗永浩：6亿债务年底还完！今年会推音乐节目 | 红像》]]

  4月1日是罗永浩开播一周年的日子。当晚，他没有带货，而是在抖音上新开了一
  档情感类聊天节目“老罗和他的朋友们”。可能很多人想问：直播一年，罗永浩和
  交个朋友做了些什么？生意怎么样？债还多少了？近日，新浪科技专访了罗永浩
  及交个朋友创始人黄贺。从巅峰到回落，走过三个拐点后找到节奏，大主播罗永
  浩和他的团队，都经历了怎样的一年？未来将向何处？

- [[https://mp.weixin.qq.com/s/nBZvTmvz2_HQSnMFqIlxHw][《张一鸣：手里有刀，心里有佛》]]

   “吃饭时好好吃饭，睡觉时好好睡觉”，“All-in有时候是偷懒”，“不把外因当内
  因，不把运气当能力”这些更灵活的说法，是张一鸣对“平常心”这个佛源词更细
  微、更多面的感悟。张一鸣在字节跳动9周年的主题演讲，本质是字节跳动企业
  文化的一种输出。只不过，更出圈的是张一鸣对“互联网黑话”的吐槽，那些抽象
  复杂的词汇存在于各大互联网公司，与“平常心”形成鲜明的对比，这种批评自然
  也引得一片互联网人的演绎和附和。

** 2021-04-01
- [[https://mp.weixin.qq.com/s/Q9wXkOV2Wi5iekHa3GEDzA][《深度｜字节跳动的OKR也有不OK的时候》]]

  3月31日，字节跳动创始人张一鸣在公司成立九周年的庆典上的演讲刷屏了，张一鸣通过各种“心得”，来呼吁字节跳动内部能维持一种简单和直接的沟通方式，而字节跳动最为外界所熟知的管理制度——OKR正是承载这种理念的制度载体。选择在一年中最重要的一次内部沟通上，向“变味”的公司文化和管理方式以及业务心态开炮，其实体现了字节跳动当下面临的一个重要挑战——公司自成立以来基本没改变过的OKR制度，是否还适合已然庞大的体量。

- [[https://mp.weixin.qq.com/s/3R                  JGh               JdL1f1zFnwCuDRNWQ][《哥斯拉大战金刚，想象力的匮乏》]]

  随着电影艺术的发源，原本只存在于文字、绘画、雕塑与想象中的形象开始会叫、
  会动了。1933年，《金刚》在大银幕上初现时，带给观众极大的心理冲击。日本
  人受到启示，也随之开启了近半个世纪的《哥斯拉》系列。一周前，《哥斯拉大
  战金刚》上映，截至发稿，拿下了接近6亿的人民币票房，成绩只能算得上平平。
  时隔近五十年，两个上古IP再度相聚，冲击却早已不再，只剩下无聊的叹息。

- [[https://mp.weixin.qq.com/s/ERTa5OpAhVhg7aC0CtsGYA][《对话何小鹏：最重要的是节奏感》]]

  前天（3 月 30 日），雷军宣布造车的当晚，何小鹏住在上海的酒店，他在 3
  月 31 日（昨天）凌晨 4 点 35 分发了一条朋友圈：“人生很短，应多鼓起勇气，
  追求自己的精彩。我们要为勇敢者鼓掌，无论结果如何，当越来越多人这样之时，
  世界才会更灿烂。”当天下午，本是小鹏汽车庆祝一个重要进展的时刻：其今年
  1 月发布并开始公测的 NGP，在国内完成了 3000 公里试驾。为此，小鹏汽车
  CEO 何小鹏接受了一个小范围的采访。

- [[https://mp.weixin.qq.com/s/B7yPgIS_Rzp         jfyXrke488A][《亚马逊的 1.7 万亿市值与贝索斯的 24 封信》]]

  亚马逊创始人贝索斯每年会给亚马逊员工写一封信件，里面会透露了自己今年的
  想法和计划，从1997年的专注长期发展，到2020 辞任 CEO，专注在新产品和其
  他早期计划，期间从未间断，每一年都有新的思索，每一封信都是互联网创业者
  的营养来源。

- [[https://mp.weixin.qq.com/s/IsLaS_Geubyoomicq0xqWQ][《奔驰、宝马、奥迪正被特斯拉、蔚来超车》]]

  光刻机技术从干式到浸润式的革新成就了ASML，淘汰了尼康、佳能；苹果IOS生
  态的构建令手机进入真正的智能时代，而诺基亚帝国“轰然”崩塌。如今在汽车行
  业，技术革新以及商业模式的变革正在同步发生。纵观全球车企，无不因造车新
  势力的崛起而面临挑战。大众丰田都在“勒紧裤腰带、省钱谋转型”，而特斯拉、
  蔚来却烧着投资人的钱大肆扩张。居安思危，与传统汽车市场暗淡不同的豪华车
  市场，虽然赚钱能力依旧突出。

* 三月
** 2021-03-31
- [[https://mp.weixin.qq.com/s/zi9uG-92nzzooDYbNOm3Jw][《大科技停滞时代》]]

  十年匆匆而过，各种型号的笔记本电脑蓬勃发展，全面屏手机成为标配，摄像头
  从800万提到1亿像素，指纹解锁、面容识别、快充技术也不再新鲜……一切都在变
  化，顺应时代发展。一切又仿佛没有改变，从1990年到现在，锂电池技术几乎原
  地踏步，进展缓慢。电池这玩意涉及到材料学，而材料学但凡想做出突破，没有
  多少捷径可走，就是不断换材料进行重复实验，什么时候出成果，不知道，简称
  薛定谔的材料。

- [[https://mp.weixin.qq.com/s/M7VPpmKQKh          jnkTHIG_l4NA][《社区团购中场战事：边开仓、边撤点，巨头们的账也快算不过来了》]]

  历经半年疯狂的攻城略地之后，社区团购开始暗中降火。社区团购经过最近半年
  多的圈地阶段，存量市场（社区资源）基本已经被瓜分殆尽。同时，在快速扩张
  时，从数据上来看，公司已经对优劣社区做出了区分，搭建起精细化运营的模型。

- [[https://mp.weixin.qq.com/s/lNAL9OrLlg2Gzkk9m5o4cw][《张一鸣最新演讲：外部波澜起伏，内心平静如常 | 字节9周年》]]

  世界在动态变化，外部波澜起伏，内心要保持平静如常。3月30日，在公司9周年
  庆上，字节跳动创始 人张一鸣发表了演讲《平常心做非常事》，分享了他对于
  “平常心”的思考：如何以 平常心对待自身、公司业务、行业竞争、成功和失败。
  平常心有个直白定义，就是 “吃饭的时候好好吃饭，睡觉的时候好好睡觉”。张
  一鸣说，保持平常心 ，接受当下的自己，把自己做好，往往就能把事情做好，
  “平常人也可以做非常事”。

- [[https://mp.weixin.qq.com/s/5Gc5cS              JM7d0ArLodDtGtkg][《关于知乎的那些人和那些事》]]

  知乎被称为中国版的Quora ，我们与Quora的人聊过，问过一个问题，他们为什
  么不做个中文版，回答是，英文表达的门槛更高一些，中文版容易水化。不过，
  对于知乎的起源，除了早期融资要借Quora这个概念说事外，周源提得最多有二，
  一是他在老东家《IT经理世界》做的N3—一个新技术、新商业、新趋势的网站，
  当时和周源一起做这个网站的还有3 个人，《商业价值》杂志的技术总监林森；
  小米生态链的产品总监夏勇峰；成远则成为知乎早期创始团队的成员。

- [[https://mp.weixin.qq.com/s/gvtYTNnygpbXvTwdg5-Upw][《大国博弈的演变》]]

  在没有特朗普的日子里，一些人期许世界变得安静一些。但是，拜登执掌白宫不
  到三个月，一系列事件令很多人感到震惊与不解。他是一个更狠的角色吗？大国
  博弈会朝什么方向演进？本文继《大国冲突的假象》后，继续探索拜登时代国际
  政治格局的演变。

** 2021-03-30

- [[https://mp.weixin.qq.com/s/5eP7TYSetFPFsmtWBcF3tQ][《小米投资百亿造汽车：雷军任CEO 将助推市值破千亿美元》]]

  小米今日发布公告，称公司拟成立一家全资子公司，负责智能电动汽车业务。首
  期投资为100亿元人民币，预计未来10年投资额100亿美元，集团首席执行官雷军
  将兼任智能电动汽车业务的首席执行官。小米将把汽车组装外包给合同制造商，
  也就是其智能手机所使用的模式。据雷帝网了解，小米将在今日晚间披露造车细
  节。小米为何要涉足智能汽车市场呢？

- [[https://mp.weixin.qq.com/s/yIAP0cI5hpOWBF5Tdk8FIw][《江西苦彩礼久矣》]]

  在知乎“为何全国那么多高彩礼地区就江西出名了呢？”的提问中，就有人表示：
  “地处赣南小农村，彩礼近十年来水涨船高，现在（2021年1月10日）平均25万。
  彩礼只是小头，林林总总加起来，花费将近百万，但大多数人并没有这样的资金
  实力，借“彩礼”就成了江西非常普遍的情况。3月16日，九江银行推出的“彩礼贷”引
  发关注，随后，该产品不断受到关注和质疑，银行推说“并未正式上线”，但江西
  彩礼之高，可见一斑。

- [[https://mp.weixin.qq.com/s/I2yBmFIUQq1gGbABGd7GDg][《12000字解读元气森林：套利与降维的游戏》]]

  当红饮料品牌元气森林在过去4年时间里的成绩 - 根据我们推算元气森林2020年
  在零售终端完成了超过25亿的销量。我们用了两个月时间查阅百篇公开资料、访
  谈多 位行业专家、分析百万销售数据、混入社群进行潜伏，我们观察到了元气
  森林身上 一些与众不同的地方，以下从6个方面与大家分享对于元气森林的研究
  成果：游戏 老兵为何能跨界做饮料、挖掘爆款的“套利思维”、数据驱动的新品
  测试、以用户为中心的“补贴模式”、扁平化的渠道管理、用私域构建DTC渠道。

- [[https://mp.weixin.qq.com/s/LG4BrsMPE_pG4GR5V2pcNw][《职场精英的下半场：辞职，卖保险》]]

  在职场上，35岁是个“荣枯分水岭”，大多数招聘岗位将入职年龄限定在35岁以下，
  这一规定加剧了当代人的“中年危机”。职场内卷日趋严重，“35岁现象”就像推倒
  的多米诺骨牌，将引发一系列现实问题及连带风险。职场精英比普通人更早嗅到
  了危险的气息，这些世人眼里的“学霸”、“精英”、“赢家”在21世纪的第2个十年
  里，不约而同递出辞职信，决定去“卖保险”。

- [[https://mp.weixin.qq.com/s/5h8YRKqSnO3zhcN3R1aW5Q][《TikTok 的新敌人 | YS 特别版》]]

  短视频战争在国内暂告一断落。但对字节而言，即便手握TikTok，海外格局也还
  未定。过去几年，有几款产品曾被大家认为可能在竖屏、短视频领域分一杯羹，
  甚至成为TikTok的麻烦，但是很显然，直到今天，他们均未掀起什么波澜。能够
  对TikTok形成潜在威胁的下一个对手是谁？YouTube。

** 2021-03-29
- [[https://mp.weixin.qq.com/s/vHwlAi6iOpS_-FZQWdPYuQ][《用不起的充电宝，骑不起的自行车，共享经济“举起镰刀”》]]

  共享充电宝用不起后，共享单车也骑不起了。大多数共享经济项目，都已经在潮
  水退去时消失。共享单车和共享充电宝创业公司们，也经过了一番洗牌，坚持到
  现在的头部公司中，哈啰单车和怪兽充电、小电科技都传出过拟冲刺上市的消息。
  但随着市场被头部公司们分割，现在原本便宜的共享经济们”举起镰刀”纷纷涨价，
  也引来了网友的议论。共享经济的最后，都将走向“资本收割韭菜”吗？

- [[https://mp.weixin.qq.com/s/1x6599Ql65q-uiZ7h_PYCg][《投得好不如退得好！B站和它率先离场的投资人》]]

  毫无意外地，B站破发了。在新经济公司中——尤以具备平台型特点的公司为甚，
  最陡峭的成长曲线往往诞生于公司上市后，也就是二级市场阶段。比如Facebook、
  腾讯、网易等都是曾获得百倍增长的股票。而B站，是更极尽的演绎者。然而，
  就在B站即将迎来最陡峭的K线前，一批曾陪伴了这家公司四五年的投资人相继离
  场。

- [[https://mp.weixin.qq.com/s/7qflu               j2-m66Rfg3d5Y     Jp_Q][《独立游戏谢绝腾讯招安》]]

  腾讯游戏依旧是印钞机，但在过去的一年里，各路敌手和这个中国乃至世界游戏
  巨无霸的距离正在缩小。多款与腾讯无关的爆款游戏，正在打破腾讯游戏一家独
  大的局面——从2018年年底开始，收入Top30的游戏中，腾讯和网易所占比例开始
  降低。目前崛起的新秀虽不至于威胁到腾讯游戏行业第一的地位，但这足以让腾
  讯产生焦虑，这些新崛起的公司不仅拒绝了腾讯的投资，甚至大多数都从未与腾
  讯合作过，他们与腾讯保持了明显的界限。

- [[https://mp.weixin.qq.com/s/Z7PAz               jiRO6KQENfZqXaamg][《睡不着的年轻人，与难逃软色情的“哄睡师”》]]

  曾经，快手抖音让你彻夜不想睡；如今，有人在快手抖音上专门哄睡。全中国超
  3亿人存在睡眠障碍，有人在网络上求哄睡，也不足为奇。奇怪的是，当点开快
  手等视频平台上所谓的“哄睡助眠”直播间，不少都是衣着暴露、美颜开满、不时
  作出挑逗性动作的女主播。与能不能让人入睡相比，她们似乎更在意有没有人刷
  礼物。曾经玩坏ASMR，如今又打着“哄睡助眠”的幌子，此类“软色情”擦边球在视
  频平台上有卷土重来的-迹象。

- [[https://mp.weixin.qq.com/s/FtwASSRw1eqtzs9CWtQxJA][《B站上市现场敲锣的12位UP主，都是谁？》]]

  某种意义上，“UP主”近乎等同于“B站”。在B站寂寂无名时，UP主创作了最初的内
  容；当B站登上更大的舞台后，UP主也收获了越来越多的关注与喜爱。最好的缘
  分，莫过于相互成全。3年前，B站登陆纳斯达克，邀请了多位UP主一同敲锣；今
  天，12岁的B站回港二次上市，我们也邀请了12位UP主共同见证。
** 2021-03-26
- [[https://mp.weixin.qq.com/s/4KK                 j0zEozkXpd_5_w67OsQ][《我们翻了13万字黄峥专访及公开信实录，发现了这些秘密》]]

  3月17日，拼多多创始人黄峥的一封致股东信掀起轩然大波。在拼多多成为中国
  用户规模最大的电商平台之际，黄峥宣布辞任拼多多董事长。引发业内及媒体圈
  对黄峥此举背后深意及内幕的猜测与讨论。我们翻阅了自2015年至今，黄峥几乎
  所有公开声音，试图探寻他选择“急流勇退”的真实动机，同时也看到了黄峥对创
  业、对成功、对实现自我价值清晰且理智地思考。

- [[https://mp.weixin.qq.com/s/r0svuNwW7iHS_4kd8pRtqw][《「李子柒」为什么会让你上瘾》]]
  城市作为一个由无数高效的、机械化的房屋构成的巨大机器，似乎已经成为了无
  法从单一视角窥其全貌的巨型迷宫。在 20 世纪末，它逐渐成为一种图像、一个
  奇观和欲望的化身，而在 21 世纪，互联网或许也是如此。我们必须承认，人似
  乎不能将柯布西耶口中「已死」的概念完全从心灵和精神上消除。我们仍然对于
  城市和互联网带来的过多刺激感到疲倦，很多时候，对更「原始」的生活和创造
  有着本能的热爱。

- [[https://mp.weixin.qq.com/s/qqwQhU6Gy8z0sOu     Jra               jtNg][《离开字节跳动的人》]]
   “在字节，别把自己当人，把自己打碎，当做好用的工具就好了。”，业务不断
   调整在字节跳动几乎是常态，伴随而来的还有中层的调换。“我觉得这里一切都
   是短期导向。”一位离开字节跳动的前部门总监有更深刻的看法，“某种程度上
   来说，这个巨大的App工厂通过迭代中层来推进业务。这和它的组织架构有关。”许
   多离开字节的人聊起这家公司，印象最深的就是其扁平化管理。

- [[https://mp.weixin.qq.com/s/ZEeKSWoDllW49pMFBOaO1Q][《潜望｜对话清流资本王梦秋：没有争抢欲的人》]]
  王梦秋是一个棱角鲜明的人，共事过的人评价她：「聪明、犀利、强势、有号召
  力」。一个佛系、不捕风口、女性主导的小基金“清流”，如何在弱肉强食、雄性
  激素分泌旺盛的投资界存活下来，甚至活的还不错，此次跟她聊了聊投资与人性、
  遗憾与超然，以及她眼中的自我和世界。当然，围绕王梦秋和清流的种种古怪也
  成为重点话题之一。

- [[https://mp.weixin.qq.com/s/ViT4TpcaLtdE        j4                jy_8     JhLQ][《阿里云盘的算盘》]]
  沉寂已久的网盘市场终于热闹起来，对于在上次网盘大战中“坐收渔利”的一众用
  户而言，显然对此喜闻乐见。随着阿里云盘的全面开放，相关议论声不绝于耳，
  有用户认为阿里云盘或将改变国内网盘市场的格局，也有经历过网盘限速“教育”
  的用户提出疑问——阿里云盘以后会限速吗？此外，和以往网盘业务的级别不同，
  此次阿里云盘的主体是阿里云，在2020年第四季度，阿里云成立以来首次实现季
  度盈利。在此前提下，阿里云盘到底打的什么算盘？

** 2021-03-25
- [[https://mp.weixin.qq.com/s/RPL0D6BQoI3r0ZFOlBO0VA][《100 亿美元，微软收购了一个有 3 亿人口的「互联网社会」》]]

  又一家「中型创业公司」顶不住了。微软正考虑收购 Discord，价格超百亿美元。后者去
  年夏天刚获得 1 亿美元投资，估值 35 亿美元。如果收购最终成立，意味着 Discord 的
  价值在一年内翻了三倍。对微软来说，收购 Discord，一方面意味着能接触到 1 亿多粘
  性用户，另一方面也意味着，它能从一个新的角度，尝试构建未来的「互联网社会」。

- [[https://mp.weixin.qq.com/s/Mz5IW7kOMIzdCLxdHMa9lA][《拼多多没有二号人物》]]

  3月17日，黄峥宣布辞职，将董事长一职交给了联合创始人兼CEO陈磊。由此，拼多多正式
  迈入陈磊时代。在外界看来，拼多多是“属于”黄峥的，陈磊只是黄峥退居幕后选出来的
  “影子武士”。但实际上，从黄峥创业初始，陈磊就一直伴随左右共同进退，扮演着合伙人
  的重要角色，从某种意义来说，陈磊不是黄峥的接班人，而是合伙人。

- [[https://mp.weixin.qq.com/s/TooIHw70U11bW6UlX99SLQ][《新兴国家正濒临货币危机》]]

  三月，土耳其里拉崩盘。自今年二月以来，土耳其里拉已经跌去逾23%。里拉崩盘引发土
  耳其金融地震，土耳其里拉崩盘，只是个开始。如今，美元正在进入流动性拐点，新一轮
  紧缩周期的预期越来越强，土耳其里拉率先崩盘，紧接着，俄罗斯、巴西、阿根廷、印尼、
  印度等会遭遇何种命运？中国会受到怎样的冲击？新兴国家的这种“幽灵”为何会如期而至？
  本文从经济学的角度分析新兴国家的周期性货币危机。

- [[https://mp.weixin.qq.com/s/0BimvA-Hu6cqRS0CzcN_dQ][《全网最便宜硕士” ：留学白俄罗斯，泡沫还是骗局？》]]

  不需要雅思成绩、个人简历，也不需要教授推荐信，只花了不到3万元人民币，李建波就
  成为白俄罗斯某大学的一名留学生。每年的职称评定，雷冬都因为本科学历而无法晋升，
  虽然他毕业于QS排名前50的高校，但依旧被研究生学历“卡”住脖子。由于上网课的人太多，
  有些大学的老师已经不够用了，乃至于中介还要帮忙招聘老师上课。“很多人在国内一直
  被学历所限制，内卷得很严重，来读一个白俄罗斯的硕士，难道不是避免内卷的一个方式
  吗？”

- [[https://mp.weixin.qq.com/s/LNY8XE9sS4e36CVaahyrfg][《长期主义者的10条认知 ｜ 深度》]]

  最近“长期价值主义”这个提法比较火。之所以火，我认为是源于中国企业的现实生存问题。
  其实，长期和短期本来是不可分割，从时间这个维度来讲，长期和短期两者是一体的，并
  不是说追求长期就不要短期，长期目标恰恰是由短期目标积累起来的。如何平衡长期战略
  和短期策略？如何兼顾理想与现实？如何在战略、组织能力、绩效管理等方面实践长期主
  义？

** 2021-03-22
- [[https://mp.weixin.qq.com/s/L0VOUpRiqeGhrBlaeXvSxg][《一人食，一人玩，一人住，为孤独埋单的9200万单身青年》]]

  2018年中国单身成年人口高达2.4亿人，超过英法德三国人口总数，其中超过7700万处于
  独居状态。预计到2021年，这个数字将上升到9200万。半份菜、一斤装大米、一人嗨火
  锅……针对单人消费的餐饮业态正在涌现。外观小巧、方便快捷的小家电抓住了绝大多数年
  轻人的心理：宁愿单身，也不愿将就。单身一族在宠物主中占比达32.5%，人均单只宠物
  犬、宠物猫的消费分别达6082元、4755元。

- [[https://mp.weixin.qq.com/s/8v7a6zggout-Y0g89SnKkQ][《搜索广告代理商讲述：灰色广告是怎么洗白的？》]]

  互联网上的虚假广告是历年315晚会的常客了，今年315，360搜索、UC浏览器上的虚假医
  药广告中招了。只要投放资金到位，这两个平台的广告代理公司可以提供从广告资质、广
  告内容，到网页设备、账户维护、虚假评论和点赞等一条龙服务。这类广告是从何而来？
  央视记者只提供了一个微信号和产品类型，很快，代理公司就复刻出了类似的广告内容。

- [[https://mp.weixin.qq.com/s/xbVRPxoh            js5QfPqUE         jgVYg][《所有东西都涨价，为什么大家只骂海底捞》]]
  近日，#海底捞牛肉粒变素了#成了刷屏话题。起因是有消费者反映，部分海底捞门店将牛
  肉粒替换成了大豆素肉制品“味伴侣”。其后，海底捞客服回应称味伴侣目前仅在上海试点，
  主要是“为了应对顾客无限量使用牛肉粒小料造成的浪费”。看似只是一次简单的小料替换，
  网友却反应激烈，这不是海底捞第一次因涨价被吐槽。同是涨价，有些消费品却可以明目
  张胆，并且消费者还依旧买单。那么为什么有些消费品能轻易涨价，有些却一涨就被吐槽？

- [[https://mp.weixin.qq.com/s/AMdLu0Rfg           jHOzQA1S4fEbA][《李丰独家授课：华为、戴森、三顿半崛起背后的新消费底层逻辑》]]
  谁取悦用户取悦得更好，就会在供过于求的时候有更大的机会。所以，峰瑞资本的李丰老
  师告诉我们：任何一类商品，从供不应求，到供求平衡，再到供过于求之后，很可能会出
  现另一个新的“供不应求”，这被称为消费升级。大部分情况下你要分清楚，你所在领域的
  供求关系，处在哪个位置？将技术创新“翻译”成用户可感知的产品力创新，可以更好地放
  大品牌。优秀的产品力+流量媒介+供应链，是持续获得品类红利、创造持久力品牌的公式。

- [[https://mp.weixin.qq.com/s/ANVur2w_0Vf         jXK6SBHhV6g][《芒格：我如何用五个通用观念，解决复杂问题》]]

  这篇文章是一篇芒格的演讲，来自最新版本的《查理·芒格传：巴菲特幕后智囊》，本书
  是国内唯一经过芒格及巴菲特授权的传记，从这篇演讲中我们可以看到芒格独特的逆向思
  维，以及五个他自称“超级简单”的通用观念。在演讲中，芒格给读者出了一道思考题，如
  果你穿越回1884年，那么你该做些什么，才能够创造一个在150年后价值达到2万亿美元的
  公司呢？如果有一家公司全都做到了，那么它值不值得投资呢？

** 2021-03-15

- [[https://mp.weixin.qq.com/s/evtV5om1yC3DMCGcqZ7ZJw][《新冠之谜：为什么疫情在某些国家看起来更严重？》]]

  新冠疫情在不同地区导致的死亡率是无差别的吗？答案是否定并且出人意料的。简单来说，
  与拥有完善医疗体系的富裕国家相比，那些相对贫困的国家——特别是南亚和撒哈拉以南非
  洲大部地区——死亡率竟然低得令人惊讶。获得普利策奖的印度裔美国医生、科学家
  Siddhartha Mukher                                jee，他在全球范围内访谈了多位统计学家、病毒学家和公共卫生专家，
  试图解释这一令人困惑的现象。

- [[https://mp.weixin.qq.com/s/SM-ghDv5SvTvo48dxuZbFg][《国内刚开始萌芽的播客，已经成了美国巨头们的主战场》]]

  在全球市场上，苹果音乐服务还在紧紧追赶 Spotify，但它原本领先的播客服务却被
  Spotify 突袭超越了。自 2015 年 Apple Music 问世，苹果花了 4 年，在美国本土超越
  Spotify，成为全美付费订户最多的流媒体音乐服务。在世界范围内，Spotify 保持着用
  户数上的绝对领先，且优势越来越大。Spotify 2021 年在美国的播客用户数将增至 2820
  万，超越苹果的播客 App。

- [[https://mp.weixin.qq.com/s/uP54h70ebCOT4bv6bQxkaA][《第一个投中快手的人》]]

  9年前，一个人给一个工具产品投资了一笔钱，在后来的融资中又多次下注，如今，按公
  司上市当天的收盘价，他所在的投资机构获利216亿美元，回报超过107倍。跟暴涨的财富、
  从天而降的运气相关的故事，总是能最快引发人们的兴趣。随着快手今年2月初在香港上
  市，这个名叫张斐的投资人与他担任合伙人的五源资本的故事，开始在互联网上传播。

- [[https://mp.weixin.qq.com/s/zX9a6g7WyHAd        jLbpyy1SOw][《一切中国互联网产品的归宿都是相亲网站？》]]

  从网友们在中国互联网各个角落里的真实行为来看，他们虽然一边吐槽着父母催婚一边拒
  绝着线下被“包办”的相亲，其实另一边身体还是很诚实——相亲交友不仅对他们来说很重要，
  而且还被这届年轻人玩出了新花样。现在最热闹的互联网相亲地，早就不是那些垂直领域
  的交友软件，也不是基于微信微博豆瓣等泛社交平台的交友小组。如今最积极相亲的年轻
  人们活跃在一些跟恋爱交友八杆子打不着的App上，比如时下正处于风口浪尖的基金圈。

- [[https://mp.weixin.qq.com/s/6d52e9Gyhp02nFVGBw-HaQ][《为什么中国现在老被骂》]]

  皮尤研究中心最近在2021年2月对美国成年人的调查，对中国的看法呈现负面的美国人比
  例从2018年的46%上升到了2021年的67%, 呈现较大的上升。这里面因为疫情怪罪中国是一
  个很大的因素，但是更大的背景是美国特朗普政府对中国的敌对态度，简单的说，疫情只
  不过是一个加速项，实际上随着中美国力的不断逼近，美国必然会开始对中国的压制，其
  中就包括舆论上的攻击，而这必然会影响到民众对中国的看法。

** 2021-03-12
- [[https://mp.weixin.qq.com/s/KTFPHcXg9zzx9H9U72poWQ][《抖音电商大变局：品牌自播吃肉 达人喝汤 小主播被迫转行｜深网》]]

  抖音直播电商是一片蓝海，也是一座待挖掘的金矿。在抖音电商不断变化的流量规则里，
  主播、达人、品牌方都成了其战略目标的“螺丝钉”。随着抖音电商战略和布局的变化，这
  些“螺丝钉”在平台的位置、生态乃至生死等都在随之改变。在2021年抖音电商将品牌自播
  作为战略级项目的背景下，品牌自播“吃肉”，达人“喝汤” ，小主播被迫转行的局面正在
  形成。

- [[https://mp.weixin.qq.com/s/                    JhAulBaTdq0o1DelCZsT3g][《科技公司集体进军养猪，底层逻辑是什么？》]]

  要致富，少生孩子多养猪。人们没有想到，这句农村经典刷墙语录，现在成了科技公司的
  「座右铭」。过去几年间，华为、网易、阿里巴巴、京东、万科、碧桂园、恒大都盯上了
  养猪行业。尽管，它们来自 ICT、互联网、房地产不同行业，却都因养猪事业有了共同交
  集。「不好好读书，回家养猪」在今天可能需要反向解读，好好读书才能有机会科学养猪。
  养猪究竟有多香，让大厂不惜跨界争相布局，而不是牛羊禽类养殖？

- [[https://mp.weixin.qq.com/s/I2HY                j4YhOhokPZCoVLSpFg][《Mac 版微信 3.0，可以看朋友圈了》]]

  Mac 版微信 3.0 还没正式发布，拿到的是 beta 8，这个版本最吸引的功能自然是可以在
  Mac 上刷朋友圈喽。这次 Mac 版微信 3.0 提供了三个新特性：1、可以浏览朋友圈；2、
  可以浏览聊天中分享的视频号视频和视频号直播；3、在OS X 10.14 版本及以上系统支持
  深色模式。目前的 3.0 还是 beta 版，估计大家很快就能见到正式版了。

- [[https://mp.weixin.qq.com/s/f                   JNeOSq45qVPB      Jn8euzsKw][《实探山东“拉面哥”：疯狂燃烧的荒诞和欲望》]]

  程运付“拉面哥”，因15年坚持以3元价格卖一碗面而忽然间在抖音、微博、快手等平台走
  红。最近的两个星期，无数全国各地的主播和围观者涌入这个偏僻山村，将镜头对准“拉
  面哥”的家门口；也有当地人在闹剧中寻找商机，兜售流量卡、WIFI设备、充电宝；也有
  人什么都不要，一切免费。在沂蒙山余脉的春日迷蒙雨雾中，刺猬公社亲眼目睹了这场略
  显荒诞的乡村直播秀。

- [[https://mp.weixin.qq.com/s/2kHHw55Zs95xOYUbQUqx_Q][《何加盐：影响10位企业大佬的10本书》]]

  很多企业界的大佬都有一个共同点：特别爱看书。甚至有些企业家，其今天的成功，跟他
  年轻时看过的某一本书，有很大关系。今天我们盘点一下曾经影响过10位企业大佬的10本
  书：1. 雷军与《硅谷之火》2. 马云与《人生》3. 马斯克与《基地》4. 孙正义与《龙马
  来了》5. 芒格与《富兰克林自传》6. 段永平与《穷查理宝典》7. 王兴与《有限与无限
  的游戏》8. 张一鸣与《少有人走的路》9. 贝佐斯与《从优秀到卓越》10. 任正非与《毛
  泽东选集》

** 2021-03-11
- [[https://mp.weixin.qq.com/s/o-1QSeNFF           Jphw              jPIvOrqEg][《大熊市，才是改变人生的最好机会》]]

  在股市里，做容易的选择是轻松的。涨的时候进场，跌的时候离场。这样的选择，是大多
  数人的做法，也是大多数人在股市里赚不到钱的原因。什么是艰难的选择？是下跌时耐得
  住，守得住，还能坚持加仓，受得了回撤，守得了云开。经历这次大跌，我们一起来复盘，
  怎么磨出自己的性子，怎么磨出回报。大熊市，才是改变人生的最好机会。

- [[https://mp.weixin.qq.com/s/bnGu2I6-XR2qAaHhhc_cSA][《真正的高手，相信逻辑而不是现实》]]

  人类日常生活中常用的两种基本逻辑方式：一种是归纳法；另一种是演绎法。归纳法是人
  类最基础、最常见的用智形式，这是一种内置在人类基因中的思维定式。演绎法是理性思
  维的主要方式之一，它是一种很奇怪的思维，它是一种逻辑自证的学问。归纳法与演绎法
  是人类主要的两种思维方式，只有了解了这两种思维方式，我们才能进入第一性原理的语
  境当中，才能知道第一性原理能够在哪些领域发挥作用。

- [[https://mp.weixin.qq.com/s/Go6lx9_btuzgNAHVAW-8TQ][《中国广告的两大路线之争》]]

  中国广告几十年来的两大路线：一个叫用户路线，一个叫产品路线。产品路线回答三个问
  题：1、产品是干啥的？2、产品有什么功能作用？3、相比于竞品，产品有什么优势？中
  国的本土营销公司喜欢走产品路线。而用户路线回答另外三个问题：1、品牌的目标用户
  是谁？他们是一群什么样的人？2、用户有什么样的情感、个性与态度？3、品牌带给消费
  者的体验和心理价值是什么？4A公司喜欢走用户路线。

- [[https://mp.weixin.qq.com/s/X0dCy2Ys470CQ       j7678cBcA][《比尔·盖茨再度警示：下一次灾难，将是疫情的5倍》]]

  对于领导者来说，主要做两件事，一个是看到未来的机会，一个是看到未来的灾难。没有
  看到未来的机会，就无法激励员工；相反，如果能看到社会未来一定会遇到的麻烦，提前
  做好解决的准备，就会获得成功。所以，当所有的人都开始提心吊胆，对未来没有信心的
  时候，领导者必须看到希望所在；而当所有人都在畅想未来的时候，领导者必须看到灾难
  所在。

- [[https://mp.weixin.qq.com/s/ACti_o5Uno3TSi      jXsm9cng][《湖南人为什么最爱嚼槟榔｜大象公会》]]

  中国什么地方的人最爱嚼槟榔？台湾、海南、广西等槟榔原产地都有嚼槟榔的习俗，其中
  台湾更发展出闻名世界的「槟榔西施」文化。但在湖南人面前，他们通通相形见绌——据统
  计，台湾约 10%的人口有嚼槟榔习惯，而湖南人嚼槟榔的比例达到 38.42%，其中 30 至
  40 岁人群更高达 50.36%，作为中国最大的槟榔产地，海南对槟榔的热爱也远不及湖南。
  那么湖南人为什么这么爱吃槟榔？

** 2021-03-10
- [[https://mp.weixin.qq.com/s/t48bbKDDWcAsLYwG5aw6rQ][《推荐和视频开始侵蚀各行各业》]]

  过去十年，在人跟信息连接这个领域里面，其实最大的机会在我看来就是两个，第一个就
  是信息怎么组织，明显的就是从搜索变到了推荐。另外一个就是内容怎么生产，就是从图
  文变向短视频。视频未必是最高效率的信息消费方式，但视频化的信息却是最容易消费的，
  理论上视频可以触达所有人群。内容生产端，短视频大规模扩大了创作者数量，让人人都
  是创作者成为可能。

- [[https://mp.weixin.qq.com/s/u1x9x7z6d7VQQKeew3YVsg][《35岁，他们决定考研》]]

  教育部公布的数据显示，全国硕士研究生招生考试报考人数从2015年的164.9万人增加到
  2021年的377万人。学生们的「画像」是：35岁上下，大部分已经成家，职业多样，百分
  之七八十考非全日制研究生。「成年人生活的苦，你躺在床上它就来了。但学习上要吃的
  苦，是自找的。」，很多人不能理解这群逆行的大龄考研人，但「甭管抱着什么目的考研，
  至少是求变求进步的一群人」。

- [[https://mp.weixin.qq.com/s/iBbuqHKaLLU5492H    jdhYCg][《中国人最爱的算命项目，星座和塔罗牌输给了它》]]

  互联网算命这事儿并不新鲜，毫不夸张地说，在某搜索引擎上打下“免费算命”四个字，相
  关结果多达 6 千万个。昔日的街头算命先生，如今已经转战线上，迎来了事业的第二春。
  这里面甚至还有看面相的“AI 算命”，分分钟就能生成一篇比你毕业论文还长的命理分析
  报告。有多少年轻人算过命？玄学的背后有多少生意？热衷于算命背后又是什么心理？

- [[https://mp.weixin.qq.com/s/MBvnW97Bi5CaVeydOkGGkQ][《中国芯片“卡脖子”，造芯怎么这么难？》]]

  国内之前掀起了百城造芯热，但是目前相对成功的仅有上海无锡合肥西安北京这几个城市，
  前段时段武汉弘芯项目更是把我国芯片制造业推上风口浪尖。这次将会在制程技术，资金，
  人力，设备，市场，供应链，水电气，环保，政策九个维度和读者们聊聊建立一座现代化
  晶圆厂的难度（晶圆是指制作硅半导体电路所用的硅晶片），试图用寥寥千言展示如何完
  成一项大工业项目的全貌，以及我国当下芯片产业的难处。

- [[https://mp.weixin.qq.com/s/ES4uv4uRZfGdm1HLQSUSgA][《焦虑的抖音，要做另一个“微信”》]]

  TikTok在海外受挫后，字节跳动一直焦虑未来的增长在哪，而日活突破6亿的抖音被寄予
  厚望。面对增长放缓的短视频行业，抖音四处出击：电商、支付、社交、搜索以及最近突
  然大力招兵买马的本地生活，字节跳动试图把抖音打造成另一个超级APP“微信”。为了承
  载张一鸣的野心，也为了促成今年港交所最大的一笔IPO，抖音急了。

** 2021-03-09
- [[https://mp.weixin.qq.com/s/yc0b-cYYdDIK2TpQbPN3WQ][《深V反弹失败，A股跌够了吗？》]]

  3月9日，A股依然一片绿，市场仍在跌跌不休，机构纷纷做起了“心理按摩”。综合受访机
  构人士观点来看，近期市场的波动一方面是由美债收益率上行对估值造成的压力，另一方
  面来自于市场情绪层面的担忧。随着第一阶段调整到位，部分资产的投资价值逐步显现。
  我国的经济增长动能仍较为强劲，将对A股提供盈利端的支撑，无需过度悲观。

- [[https://mp.weixin.qq.com/s/IsLzc3WBSY5DElED-QndlQ][《抖音搜索降维打击微博》]]

  春节后，抖音公布其视频搜索月活已超5.5亿，字节跳动CEO张楠表示，未来一年，抖音将
  加大对搜索的投入力度。这被视作字节与百度搜索战争的扩大化，一个重要角色却被忽略
  了，那就是微博。抖音主动发起的搜索战争，明面上是在和百度争搜索商业化的市场份额，
  实则是一项双线任务。这场搜索战争的另一任务，是成为批量制造热搜话题的舆论广场，
  而在中文互联网世界，这一位置已由微博担当多年。

- [[https://mp.weixin.qq.com/s/Zfy68uH-356_cGPrybkFPQ][《大厂月入3万，不如回家考公？| 谷雨数据》]]

  2020年，在互联网大厂做游戏工程师的李洋决定辞职，月入三万的他从西二旗回到小城市
  参加公务员考试。经过疫情，他终于“想明白了”：在大厂里收入可观，但因为长期加班失
  去生活；大城市里租房的生活让人感到漂泊不定，小镇里的安全感则相比起来更让人安心。
  李洋选择考公的理由，可能也是如今众多考公年轻人心态的缩影。

- [[https://mp.weixin.qq.com/s/ruIfpT3pHtP-p7sfh9u8BA][《互联网不幸福》]]

  根据脉脉官方发布的2020年职场报告，IT互联网行业是人才净流入最多的行业，但与此同
  时，IT互联网行业是整体幸福感最低的三大行业之一，并列的是零售、贸易、批发与农林
  牧渔产业。在脉脉平台“职言”社区里，则到处流传着互联网大厂中关于“内卷”的轶闻与糗
  事，在亿万营收与技术创新的幕布下，这里就像互联网大厂的“聊斋志异”。互联网到底幸
  不幸福，这是一个复杂的问题。

- [[https://mp.weixin.qq.com/s/XxhwdodfuUOaR3mwf7O5Rg][《传道士与雇佣兵：“电商之王”杰夫·贝佐斯传奇》]]

  从1994年成立亚马逊并就任CEO，到2021年离任，贝佐斯创造了无限的辉煌，也留下了无
  限的争议。人从来都是复杂的，企业家更复杂。我们很难用一个简单的标签来形容如此深
  刻地影响过世界的一个企业家，也许，这样的企业家，本身就是一半传道士，一半雇佣兵，
  没有传道士的精神，他们走不远；没有雇佣兵的手段，他们活不长。左手持经、右手执剑，
  才造就了今天的他们。

** 2021-03-04
- [[https://mp.weixin.qq.com/s/-G6HBaW7IDlp        JukTlTQYEw][《为什么老板画大饼越来越没用了？》]]

  一个完整的战略思维通常包含三个层次的内容：战略起点（认知层）、战略结构（结构层）
  和战略涌现（业务层），今天我们先来探讨第一个层次：战略起点。其中有两种不同的战
  略逻辑，第一种是从愿景出发，从“是什么”开始；第二种是从使命出发，从“为什么”开始。
  这两种逻辑孰优孰劣？愿景和使命各自的内涵是什么？为什么相对愿景，使命才是一个更
  好的战略起点？实现使命的方法又有哪些？

- [[https://mp.weixin.qq.com/s/Y1                  jyF7Boc3          JY3vmZFbNZXQ][《为什么你身边的东北人感觉都很有钱？》]]

  很多人不解，东北明明经济不行，为啥还给人感觉贼有钱？首先，东北人“有钱”，绝对不
  是错觉。国家统计局数据显示，2020年居民人均可支配收入，辽宁在全国31个省份中排名
  第九，人均住户存款仅次于北上浙，位居全国第四。民间有种说法，东北只有有钱人和穷
  人两种，没有中间层。不是说东北没有穷人，而是跟其他地区相比，东北人更会“花钱”。
  同样是100块钱，到东北人手里就能花出110块的感觉。

- [[https://mp.weixin.qq.com/s/BKS6G8pSrVSit       jDqIKAF-Q][《人口危机》]]

  最近，生育及养老问题，再次引发广泛关注。低生育及老龄化这两大难题，在未来会越来
  越突出，将深刻地影响经济增长和社会演变。人口危机已是一个世界性问题，但很少人意
  识到，中国面临的问题与欧美日等国存在根本性差异。本文从经济学角度简单探讨中国的
  人口危机。

- [[https://mp.weixin.qq.com/s/cz_3cxYUEpE_C02S2HM0Lw][《小镇青年的秘密，都藏在手机APP里》]]

  在过去几年，移动互联网快速下沉，小镇青年被贴上了“收入不高”、“没啥文化”、“缺乏
  品位”的标签。尤其是在一些一二线城市所谓的“精英互联网人士”眼中，小镇青年是处在
  互联网底端的一群人，但真实的小镇青年们，可能并不服气。我们通过手机里的APP，一
  窥小镇青年的真实生活，让我们能够知道，他们在做什么、想什么、玩什么。

- [[https://mp.weixin.qq.com/s/dk2STHQ7A7mfke7K2aADPw][《请不要叫我做题家》]]

  在2003年，“寒门贵子”是个100%的励志词汇，但到了2020年，这个词却被一个充满戏谑的
  “做题家”所取代了。做题家全称“小镇做题家”，多指出身低线城镇或者农村、通过题海战
  术杀入名校、坚信读书能够改变命运、但毕业后在大城市却只能勉强立足的普通人。很多
  人对“做题”以及背后等若国本的高考体系也产生了怀疑。为什么人们质疑“做题”？如何正
  确看待“做题”？社会欠年轻人们一个答案。

** 2021-03-01
- [[https://mp.weixin.qq.com/s/_ZfrE38z7g3fHtaxiZx__w][《为了劝我妈，我开了个老年公众号》]]

  如果你家里的长辈总转发一些看着就荒唐的鸡汤和谣言，而且已经影响到他们和你的生活
  怎么办？最近，豆瓣的哈组上出现了一个热帖——朋友开了个老年公众号劝自己的妈妈。发
  帖人的朋友为了抵制老妈的“深度好文”，让老妈听得进自己的话，专门模仿“深度好文”的
  模式开了个号，取名为“国学爱生活”。

- [[https://mp.weixin.qq.com/s/0wcM7X_49mZ8NrHhlL1TIg][《医美机构是不是下一个“爱尔眼科”？》]]

  如果说中年人的过年三件套是中华烟、茅台酒和金华火腿，那么对于年轻爱美女性，她们
  的过年三件套正在渐渐变成水光针、玻尿酸和光子嫩肤。在这个原地过年的春节里，生意
  红火的除了电影院、电商平台以外，还有近年来在一二线城市如雨后春笋般涌现的医美机
  构。医美生意火爆的背后，是医美机构狂轰滥炸的低价营销。

- [[https://mp.weixin.qq.com/s/FSzaRh              JY2WnY15egZdWWig][《金球奖得主赵婷：“我这辈子都是个局外人”》]]

  第78届美国金球奖揭晓，华人女导演赵婷凭借《无依之地》获得最佳导演奖。她成为首位
  获得这一奖项的亚裔女性导演。以小成本独立制作成名，到执导大IP漫改电影、进入主流
  工业体系，赵婷走过的路，比她身上所有标签所传达出的含义要丰富许多。国族、性别与
  时代选择，最终都要落在一个具体的创作者身上，由她讲述那些她必须去讲的故事。

- [[https://mp.weixin.qq.com/s/cpLStfBtqqLm        jvQobPFi7Q][《生育“零成本”，为何无法阻止日本生育率断崖式下降？》]]

    日本年轻人的问题并不在于生育时，而在于生育前的结婚意愿，以及生育后的抚养阶段。
  随着房子单价和总价都越来越高，日本年轻人发现一个问题，住20平米的房子怎么找对象
  呢？女性社会地位、收入水平不断抬高，择偶的标准、要求也相应提高，因此能够匹配并
  结婚的适龄男女数量大大减少。

- [[https://mp.weixin.qq.com/s/-n1g                Jh-4UqBInwSqe3BDig][《单身经济没有下沉市场》]]

    据民政部数据显示，2018年我国的单身成年人口高达2.4亿人，其中有超过7700万成年
  人是独居状态，预计到2021年，这一数字会上升到9200万人。正如克里南伯格在《单身社
  会》一书中所预言，单身社会正在成为一次空前强大、无可避免的社会变革。而单身群体
  扩大的背后，则蕴藏着无限的商机。但这场备受资本追捧的单身经济的狂欢似乎只发生在
  一二线城市，与下沉市场并无很强关联，单身经济没有下沉市场。

* 二月
** 2021-02-25
- [[https://mp.weixin.qq.com/s/1-RUPpkImy          JEp5H8rUNilw][《7图深扒中国百亿票房演员，第5名你想不到》]]

    在刚过去不久的春节档，电影《你好，李焕英》成为一匹黑马，贾玲的这部导演处女作，
  甚至在整个中国电影市场都诞生了不少属于它的纪录，2月21日冲进了中国影史票房的前
  五名。影视寒冬阴霾下的电影市场，因为春节档的火热而激起不小的水花，在电影票房增
  长的背后，关于百亿票房演员的讨论也变得热闹起来。今天我们就用票房数据来看看，代
  表中国影人票房巅峰的百亿俱乐部里又发生了什么变化，哪些影人成为百亿黑马？他们又
  是凭什么登顶？


- [[https://mp.weixin.qq.com/s/ZwuTo11iz6z24u_YU   J3XbQ][《狂奔的视频电商，撑起万亿GMV？》]]

    视频电商已经杀到古典电商城下。快手市值已经飙到1.5万亿港元，超过京东，直逼拼
  多多。如果古典电商解决了传统零售品类不足的问题，视频电商则在解决古典电商的用户
  消费意愿问题。流量瓶颈下，传统电商的获客成本骤然攀升，以短视频平台为代表，优质
  流量入口成为品牌商家们的重点争夺对象。视频电商的强势，集中体现在GMV数据上。


- [[https://mp.weixin.qq.com/s/Ked                 JcO1S1hE          JO-Kwf0HfoA][《张一鸣怎样跳出“增长的痛苦”？》]]

    高薪加公司上市在即的期权诱惑，让字节跳动像一个巨大的磁铁，不断吸引人从五湖四
  海涌入，截至2020年年底，字节跳动的员工数突破了10万人。字节跳动之所以能够高速成
  长，得力于“人才充足率”这一指标与公司营收增长高度匹配。张一鸣曾在采访中承认自己
  “不合适掌兵”，然而他现在却实打实地统帅十万员工，同时还最大程度地激发了他们的创
  新能力——张一鸣的魔法到底是什么？


- [[https://mp.weixin.qq.com/s/T7BZlX68md1_OC-dSGRHHw][《朝夕光年，字节跳动的游戏梦》]]

    字节跳动和腾讯的竞争愈发贴身肉搏。2月22日，字节跳动又放出一个大瓜，旗下游戏
  官网——朝夕光年正式上线，字节跳动在中重度游戏内容研发上迈出了第一步。中重度手游
  需要较长时间的积累，字节跳动要在游戏领域拉近与腾讯、网易等游戏巨头的身位，小程
  序游戏就成了另一条捷径。


- [[https://mp.weixin.qq.com/s/-y4DY_              Jmc0ffInqP6dBIyQ][《Clubhouse：网红App究竟能火多久》]]

    Clubhouse的成功在哪儿呢？可以肯定的是，显然不是由技术力量驱动的。从产品的生
  命周期看，Clubhouse现在应该还处在幼年，因而要预测其未来的走向是十分困难的。不
  过，如果这款产品要保持持续的成功，并不是那么容易。它需要解决的问题还有很多。

** 2021-02-23
- [[https://mp.weixin.qq.com/s/7rsEbd3qo           jgYQi_EapRsSw][《有钱的码农，基金募资最后的「新大陆」》]]

    如果说，每家投资机构都有一张潜在LP的“捕猎”名单，伴随着过去几年声势浩荡的IPO
  钟声，那些获得惊人财富的founders正在成为GP们的关键目标。中国一级市场基金再次看
  见了新大陆：一拨new money正风尘仆仆而来，相比尽调周期更长、投资决策更为审慎、
  极度偏好“白马”的机构LP们，new money开始成为很多GP募资的最后希望。


- [[https://mp.weixin.qq.com/s/i                   j8au8ZPDR9G       J3GsfMb  j_Q][《哔哩哔哩80页深度——从“人货场”看B站社区生态的养成》]]

    这篇专题深度报告，核心解决了以下问题：B站相比其他视频平台的核心竞争力在哪里？
  B站独特的社区生态是如何养成的？B站如何实现破圈？B站组织架构和管理团队有何特征？
  B站用户画像？B站用户未来还有多少增长空间？如何理解B站内容与创作者生态？B站在内
  容生态上采取怎样的发展策略？B站OGV和PUGV内容各自发展情况和差异化优势所在？B站
  UP主生态如何实现正向循环？B站平台的运营政策以及产品的底层设计如何帮助建立良性
  社区？


- [[https://mp.weixin.qq.com/s/Gmg3me-0_YTb2uh7fVP JFw][《李录：中国未来20年的经济大趋势》]]

    当我们投资一个国家的一家企业时，从某种意义而言，我们也是在投资这个国家。我们
  需要对这个国家有大致的了解。作为投资人，我们关注的是对未来大概率正确的预测，我
  们的分析尽量保持客观理性，摒弃任何意识形态及情感带来的偏见。今天会分为五个部分
  讲：中西方的历史文化差异；中国的现代化历程及近四十年的经济奇迹；当前投资人尤其
  是海外投资人对中国的悲观情绪；经济发展的三个不同阶段：今天中国与西方的位置；中
  国经济的增长潜力。


- [[https://mp.weixin.qq.com/s/zVsOa1              jkPyrTQCUCllXOOw][《中国婚姻报告2021》]]

    婚姻是家庭的基本组成部分，但近年来，多种选择和无奈之下，中国人结婚少了、结婚
  晚了、离婚多了。随着社会发展，一方面新一代年轻人追求独立自由，认为婚姻是束缚。
  另一方面，高婚育成本使年轻人实现家庭变得更加困难。从人口角度看，人口少子老龄化
  问题正在削减适婚年龄人数，结婚“主力军”减少。“婚都不想结，还生什么孩子”，正成为
  一批年轻人的选择，结婚率下降、生育率下降和老龄化加重是互为因果的。


- [[https://mp.weixin.qq.com/s/qYnopUvEIfAtkHG8ML4xQg][《长期主义：做你余生中最重要的事》]]

    长期主义到底是什么？如何兼顾“长期主义”和“当下行动”呢？长期主义追求不变，而行
  动需要随机应变。这二者如何调和呢？本文将以乔布斯人生中最重要的决策原则为例，用
  一个独特的“双线模型”，来回答这个问题。这个“双线模型”，用大白话来说，就是：永远
  去做你余生中最重要的那件事。
** 2021-02-22
- [[https://mp.weixin.qq.com/s/w0wNA6rK            jxAqW4OsLACxwg][《这个「视频版 Clubhouse」，成立一年就盈利，估值 21 亿美元》]]

    马斯克的「站台」让上线不到一年的 Clubhouse 彻底火了，然而无论是 Clubhouse 还
  是它的学徒们，都没能解决盈利的问题，但Hopin 做到了，在一年的时间里实现了
  ARR(年度经常性收入)3000 万美元，从 2020 年 2 月份开始，8 个月的时间里，Hopin
  的注册用户从 5000 增长到 350 万，企业会员达到 5 万个，估值达到 21 亿美元。

- [[https://mp.weixin.qq.com/s/gu                  JQPKqFB2ivGYKMiZhP0g][《疯狂涌入整形医院的年轻人》]]

    市场飞速增长、消费观念变化、医美生活化、行业洗牌来临，随着资本入局、医美概念
  股引起资本市场注意，这一千亿级市场已然成为备受追捧的黄金赛道，不过不可否认的是，
  黑医美、安全问题依然是阻碍行业发展的绊脚石。同时在疫情的试炼之下，大浪淘沙的时
  代很快来临，医美行业将走向何方？

- [[https://mp.weixin.qq.com/s/lvPiMvpEaiQSsxiqbuyf-Q][《为什么这届年轻人不愿多生娃》]]

    “生孩子是一个非常复杂的系统，不单纯是经济原因，一对适婚适孕的夫妻背后面临很
  多东西，除了孩子，还有父母养老的问题，以及35岁以后自己的社会竞争力能不能保持
  住。”一位采访对象的观点或许代表了生育率低背后的普遍原因。提高生育率并非一朝一
  夕就能实现，我们采访了几位处于不同人生阶段的东北人和北漂，了解他们对生育率低的
  看法。

- [[https://mp.weixin.qq.com/s/GcIq_2yVbCkM-PuF4RUAVw][《芯征程丨苹果造芯三十年》]]

    从2010年拿出首款自研手机芯片A4开始，围绕着苹果芯片实力的争议始终未曾间断。事
  实上，在过去30年间，苹果已经通过一系列的自研、并购，甚至是打压、挖角、“威逼利
  诱”，即便在老首领去世后也未曾失去方向，坚定不移地践行着乔布斯当年的路线，最终，
  建立起一个庞大的芯片帝国。跟所有伟大的故事一样，苹果芯片帝国的成功，始于一次失
  败。

- [[https://mp.weixin.qq.com/s/4kN65Eu_mYKmC-GLig082g][《“打工”不是一切——与五位学者对谈互联网加班文化及其他》]]

    近两年，互联网公司的员工们开始越来越多地反思自己为了工作究竟付出了什么。
  “996”、“打工人”，与超时工作相关的关键词被反复提起，让更多人质疑，推动技术进步
  的大公司正在将我们带入一个怎样的未来。互联网公司在颠覆市场之后应当承担怎样的社
  会责任？企业追逐效率与员工追求幸福之间应当存有怎样的边界？奋斗精神与个人自由空
  间应当如何平衡？

** 2021-02-18
- [[https://mp.weixin.qq.com/s/INbSIgFtCiaIKzya    jGdaeA][《你殊死进攻，也拼不过巨头一个部门？王兴切了三刀后……》]]

    很多创业公司老板都喜欢把“没有想不到，只有做不到”这句话贴在墙上，认为只要有伟
  大的梦想，就一定能够做到。但我们往往忽视了，创业是为了生存，不是为了死于竞争之
  中。竞争不过是创业中的一个环节而已，不到万不得已，没必要把自己逼到跟巨头正面殊
  死进攻的路上去。在竞争当中如何扬长避短，以弱胜强，这对每一个人都是第一命题。那
  么，该如何破题？

- [[https://mp.weixin.qq.com/s/vhNDY9YE6YrZwNurCNzUXw][《为什么年轻人都不愿生孩子了》]]

    人人都在担忧新生人口的骤减。在猝死频发、福报996、狼性007下生活的我们，曾有网
  友评论：这样的环境，生孩子给资本家做奴工？上野千鹤子还曾发出警告：当生育成本如
  此之高时，变得让“饱食穷民”们无法企及，养育孩子是否形成了再生产分配的新的阶级等
  级？

- [[https://mp.weixin.qq.com/s/gcvDoXmdReNX_Tt62PXVQg][《国运2021 | 后疫情时代的中国及世界》]]

    2020，大疫之年，艰难之年。新冠疫情及救市行动加剧了世界的分化与撕裂：穷人在通
  缩，富人在通胀。2021年，世界进入后疫情时代。各国头号政治任务是加紧注射新冠疫苗，
  打破一年来的“与世隔绝”。如此，人们将逐渐回到那熟悉的生活状态。然而，在回归熟悉
  与稳定的路上，大疫之年显现的冲突依然延续。本文从系统、空间与时间三大冲突，回顾
  2020，展望2021。

- [[https://mp.weixin.qq.com/s/eRAsxlkHTRAyYAUNV_Rd3Q][《辣条即将上市，深扒卫龙如何靠营销狂赚500亿》]]

    辣条，是许多人小时候魂牵梦萦的神级美食。然而，就像我们早已不是当年在学校门口
  分一包零食的小学生，辣条也不是当年的辣条了。前段时间，辣条界一哥卫龙爆出今年将
  赴香港IPO，募资10亿美元。接下来，我们就一起来看看，刘卫平是如何带着卫龙踏上IPO
  之路的。

- [[https://mp.weixin.qq.com/s/G6ZAOikQMW          JL                Jc_ESrHczQ][《温顺的人，必将继承世界》]]

    说起温顺，你也许会想起羔羊，温顺，温柔，温和。不错，我们喜欢这些词汇，然而，
  喜欢并不代表“立场”，就像我们喜欢好人，却未必愿当好人，我们的话语体系里，温顺象
  征着弱势：人善被人欺，没本事才老实。我们推崇胜者为王，重利害而轻是非，愿意先有
  屠刀然后再放下来成佛。既然如此，温顺的人，何以继承这个世界？

** 2021-02-05
- [[https://mp.weixin.qq.com/s/gXgPgxRDuvfbTyCQYIv8zw][《核酸检测是门好生意吗？上市公司净利润暴涨数十倍》]]

    随着春节一天天临近，核酸证明成了归乡人必不可少的通行证。据交通运输部预计，今
  年全国春运期间发送旅客17亿人次左右，日均约4000万人次。若以80元/次官方指导价且
  不计隔7日需复测来算，光一趟春运，核酸检测市场收入就至少高达1360亿元。拥有对千
  亿级别的市场增量，核酸检测跃上风口，很多人没发现，这笔生意可太赚了。

- [[https://mp.weixin.qq.com/s/pF67tcyL9cQCmlAOdENE_Q][《从降维打击到败走中国，谁偷走了ZARA们的光环》]]

    今年1月，Inditex宣布将关闭旗下ZARA姐妹品牌Bershka、Pull&Bear和Stradivarius在
  中国的所有实体门店，在疫情冲击下，Inditex2020年上半年净销售额缩水超30%，亏损约
  15亿元。行业龙头尚且如此，其他快时尚品牌的境况不言自明，从2018年以来，国外快时
  尚品牌在中国市场接连受挫，从光芒万丈到跌落神坛，是什么拿走了快时尚的光环？

- [[https://mp.weixin.qq.com/s/hw1aR8HqsgytUK_hqhALow][《散户能赢，只是个传说》]]

    散户抱团斗华尔街的神话正在破灭，北京时间2月5日美股收盘，散户抱团股游戏驿站暴
  跌42%。2021年开年，美股为全球投资者上演了一场散户和华尔街空头机构的对决大戏，
  双方暗流涌动，较量远未停止。散户的钱包是有限的，他们背后的对冲基金才是真正的华
  尔街之狼，这是美国金融界两大狼群之间的战争，散户不一定赚到了钱，以散户之名默默
  操作这些的才是真正的赢家。

- [[https://mp.weixin.qq.com/s/155MoO8uPGQQ4T6lfULqnQ][《快手暴涨造富：有人三年狂揽9000万，创始人财富逼近刘强东》]]

    今日快手在港上市，钟声响起，交易开始，快手的涨幅迅速冲至193%，开盘股价报338
  港元每股，市值突破13880亿港元，折合11592亿人民币，1791亿美元。以此计算，快手市
  值超过京东（1466.65亿美元），成为中国互联网第五大上市公司。而快手两大创始人宿
  华、程一笑身家分别为1637.38亿港元（211.20亿美元）和1299.06亿港元（167.56亿美
  元）。

- [[https://mp.weixin.qq.com/s/                    JLeHWb4Ks7Oa053LWRjOfg][《年入几十万的硅谷人，失去了外卖奶茶自由》]]

    湾区10米家底，仍然外卖不自由，疫情这一年，财富上升的速度好像永远赶不上菜价、
  房价，甚至是奶茶外卖价格往上跑的速度，生活用品的价格上涨速度不断加快，这让美国
  大多数人的日常花销增加。但是谁剥夺了硅谷人民的外卖自由呢？这些在硅谷年收入几十
  万，甚至上百万美金的家庭却又说不清楚。

** 2021-02-04
- [[https://mp.weixin.qq.com/s/RwA4FH80MY-1GaMovFa-gQ][《快手上市，高光与隐忧》]]

    2月5日，“短视频第一股”快手科技将在港交所正式挂牌上市。然而，在响亮的敲锣声背
  后，面对前路的未知和强大的竞争对手，以及各种风险和隐忧，快手必须跑得更快，才能
  为解决这些已知的问题争取更充足的时间。

- [[https://mp.weixin.qq.com/s/kbXDy               jwKmDpa           JW       j7jWz8ug][《5家门店，50亿估值；素颜进去，全妆出来》]]

    疫情笼罩下的2020年，线下零售业哀鸿遍野，但一股美妆新势力却在猛然崛起。美妆集
  合店话梅（HARMAY）靠着仓储式购物场景，颜值极高的装潢风格，以及琳琅满目的大牌小
  样，迅速成为全国潮流男女的时尚风向标。话梅爆火的背后，其实是本土美妆集合店崛起
  的大趋势，以话梅为代表的新一代美妆集成店，为什么能在这两年逆势爆发？

- [[https://mp.weixin.qq.com/s/tMsxexOLh1vWCE5OQotM4w][《抖音起诉腾讯，反垄断开年“第一枪”如何收场？》]]

    抖音和腾讯又“打”起来了。 2月2日，抖音在北京知识产权法院向腾讯提起反垄断诉讼。
  有专家认为，此次抖音对腾讯的诉讼应避免上纲上线，有利于平台经济的发展，“至少减
  少了关于未来发展的不确定因素。很多情形下，规则的模糊性要比规则本身更致命”。

- [[https://mp.weixin.qq.com/s/6QBOquI0i356OcdvSsoGXw][《如何快速判断一个行业是否值得加入？》]]

    俗话说：“男怕入错行，女怕嫁错郎。”其实对任何人来说，选择一个行业都是一件值得
  斟酌的事。但是，很多人想尝试拓展一下职业道路的可能性，却也苦于找不准方向。 这
  时，快速判断一个行业是否值得加入，就尤为重要。

- [[https://mp.weixin.qq.com/s/Uc2ZY42bAhqXwdGCRYv4pg][《贝索斯全职追赶马斯克》]]

    零售巨头亚马逊宣布，公司创始人杰夫·贝索斯将于今年第三季度卸任CEO，贝索斯解释
  未来在继续参与亚马逊重要项目之外，更多时间将被分配给蓝色起源（Blue Origin）太
  空飞船公司，他曾说蓝色起源是他手头最重要的工作，没有之一，而埃隆·马斯克旗下的
  Space X，更是成为蓝色起源最大的竞争对手，这场太空竞赛也是彼时的世界首富和第二
  富之间的较量，太空探索开始成为两人之间的一场另类“星球大战”。

** 2021-02-03
- [[https://mp.weixin.qq.com/s/Q5D0x               JZ                jKTV-mC_1G6asig][《我所经历的字幕组消亡》]]

    字幕组，曾被誉为近五十年最出色的文化交流使者，让无数影视发烧友折腰。随着版权
  保护的加强，字幕组的风云江湖日渐凋零。国内的字幕组，兴起于2001 年，2006 年字幕
  组走进公众视野并进入鼎盛期。这种风光没有持续太久，2014 年，美国电影协会列出一
  批提供影视盗版下载链接的网站，其中就包括国内最大、也最具代表性的人人影视字幕组。
  人人影视在微博中说：「需要我们的时代已经离去。」

- [[https://mp.weixin.qq.com/s/s2hH8tsQIqn9mf1he   jB_FA][《Ray Dalio最新万字长文：比特币，我是这么看的》]]

    那些支持比特币的人，把它吹成了一边倒的一个模样，而那些反对比特币的人，把它吹
  成了另一边倒的另一个模样。这种观点的分化，让我很担心。就像我过去写的所有文章那
  样，我尽量、尽量尝试展示事物的机遇与风险、好与坏、正与反，我尽量精确地传达、描
  述我理解的，比特币的真实价值和现实意义。

- [[https://mp.weixin.qq.com/s/in4FZS-_wynotz2-shmmHg][《独家 | 美团登顶之后：饿了么前高管首度披露与王兴对决的日子》]]

    美团、达达、饿了么的未来竞争焦点在于，谁更能满足消费者的即时需求？从外卖到即
  时零售，阿里本地生活能否“一剑封喉”？近日，多名从饿了么出走的管理层接受了独家采
  访，经过近十年创业，在一场又一场的大战中，他们收获成功的喜悦，也经历了不得不退
  场的暗淡。他们依然认为，当年阿里巴巴给出95亿美元的估值，是没有选择的选择，又是
  最好的选择，而美团被他们称为“无情的执行机器”。

- [[https://mp.weixin.qq.com/s/We                  J4VfWfMm2C7AR0    jyNCsw][《我不看好 Clubhouse 在国内能火起来！》]]

    Clubhouse 这两天很火，是一个实时在线的语音聊天室，而Clubhouse 上的国内房间，
  大部分都是聊 Clubhouse 本身的，单独的声音体验，毕竟有局限性。所以Clubhouse 在
  国内之所以受到关注，大部分都是猎奇，圈内一些优质人群的关注，也带来了一拨观众。
  但是，热度终将过去。话题谢幕后，用什么来维持Clubhouse 的热闹呢。

- [[https://mp.weixin.qq.com/s/LfaH-PipPYO-kz5HMTGlpQ][《如何避免陷入“内卷化”的系统》]]

    每个人付出的努力更多，但总收益并没有变化，甚至变少了，这就是“内卷化”，“内卷
  化”一旦发生，在没有外力作用的情况下，身处局中的人是很难避开的。不过，“内卷化”
  这个本来很严谨的学术名词被全民讨论了半年后，有被滥用的趋势，常常跟“竞争”混淆。
  事实上，并非所有的竞争都是“内卷化”，所以讨论的前提是要分清楚，这个现象是不是
  “内卷化”。

** 2021-02-02
- [[https://mp.weixin.qq.com/s/quRq8zrUUXeOwlYnZx5RrA][《2021，残酷的K型复苏》]]

    跟很多人印象中大灾之后是大萧条不同， 2021被普遍认为会大反弹。疫情按下的是暂
  停键，金融体系、生产体系等没有崩溃。疫苗推广，刺激加码，社会重回常态，立马会迎
  来大反弹。IMF预测全球增长会达到5.2%，中国则会达到8%-10%。但这次复苏的轨迹会很
  特别，诸多机构认为是K型复苏。

- [[https://mp.weixin.qq.com/s/4X6O7               JNQ               JmixezP6fQNzgg][《“互联网留守儿童”：大厂员工的下一代》]]

    在一线城市，新闻联播开始的时候往往是大厂员工加班的开始，尤其是在互联网双职工
  家庭看来，陪伴孩子更成了一种奢侈。作为互联网职工的父母，孩子虽然在大城市由老人
  或保姆照顾，但父母忙碌于工作，孩子几乎得不到陪伴，“互联网留守儿童”的苗头随之出
  现，说“互联网留守儿童”是新一代的“留守儿童”，并非危言耸听。

- [[https://mp.weixin.qq.com/s/MX6xvCC9TqfqRWF8hnHsDQ][《爆火全网的Clubhouse怎么玩？中国用户这样说》]]

    Clubhouse 是近期很火热的一个产品，除了在“本土市场”美国火，在日本已经窜到了
  App Store 总榜第一。目前采用邀请制，中国用户不多。用了几天，在此记录一些零碎的
  想法。后面还有几位 Clubhouse 用户的使用感受，也一起分享下。

- [[https://mp.weixin.qq.com/s/y                   JVab1kLWdfw0cFPnSqtWw][《为什么美国版「今日头条」长成了「58同城」？》]]

    字节跳动旗下的海外版「今日头条」——TOPBUZZ 已经逐步关闭。而由华人创立的News
  Break却快速增长，开始长期盘踞在美国新闻类第一的位置，人们可以在上面买卖二手车、
  找工作、叫家政服务、获取优惠券、报名本地活动、失物招领等等——俨然是一个「58 同
  城」。一家华人主导的新闻 App，为何能在美国的舆论环境中迅速崛起？一个新闻 App
  为何要干「58 同城」的活儿？这或许源自其独特的产品价值观。

- [[https://mp.weixin.qq.com/s/N7FPOAZkczzm_Pt9LTEmzQ][《TikTok 改变美国》]]

    2020年上半年，突如其来的疫情给势头正劲的 TikToK加了一把火，下载量稳居全球第
  一，下半年，来自美国的“禁用危机” 步步紧逼，TikTok在重压下挣扎求生，和美国商务
  部之间的拉锯战至今还未落下帷幕，在进入美国短短3年多的时间里，这个诞生于中国、
  年轻的应用程序，已经悄然渗入到了美国社会的方方面面，并推动各个领域发生着意想不
  到的改变。

** 2021-02-01
- [[https://mp.weixin.qq.com/s/Q_0swDRzP7TXbdoHNSp8WQ][《吴声：2021，疫后商业的新去处》]]

    如何总结数字商业的2020？对于用户更加数字化、更有效率的深入，「私域流量」成为
  过去两年的商业主命题。但我们谈论「以数字化运营人」太久，而这个关系与尺度的问题，
  在不确定环境中更加逼近答案。对私域流量的反思，是亲密场景的思考缘起。从「私域流
  量」到「亲密场景」，指向商业与人更合理关系的可能。人是场景，而非流量。

- [[https://mp.weixin.qq.com/s/1umcs74trh1OcZA8yi  juWw][《香橼投降后，中概股们在被窝里笑出了声》]]

    这两天，美利坚韭菜揭竿而起闹得沸沸扬扬，坚决要把大空头按在地上摩擦摩擦，整个
  晋西北哦不华尔街已经乱成了一锅粥。甚至把香橼逼到了对大家说“对不起，我不做空了”。
  为啥机构这么热衷于做空？因为你不知道做空有多赚钱，知道做空机构有多赚后，你就知
  道为什么散户揭竿而起了。

- [[https://mp.weixin.qq.com/s/WQhaITPuefcv        JSqRCrss4g][《独家｜抖音大战春晚红包： 社交、支付、电商齐上阵》]]

    今年抖音成为春晚独家红包互动伙伴，在玩法上实现了多样化的突破，包含锦鲤红包、
  春晚红包、点亮灯笼分红包等。抖音借春晚拉新和引流的巨大流量池，推动刚推出不久的
  抖音支付的快速启动，同时切入社交。抖音逐渐从一种娱乐方式变成一种社交方式，甚至
  是一个生活方式。而春节大战，对于抖音的这场改变而言，无疑是一次绝佳的机会。

- [[https://mp.weixin.qq.com/s/S1n7g0kH_plTb29hStig7w][《社区团购没熄火，他们春节还要发动一场「战争」》]]

    疯狂的低价促销让监管在2020年12月出台社区团购“九不得”政策，但这一盆冷水并未浇
  灭玩家们的热情。巨头们一方面拼命下沉，另一方面在北京、上海等一线城市悄悄扩土，
  以送券打起新价格战。疫情反复给社区团购打开了新的窗口期，农历春节就是一场关键战
  役。

- [[https://mp.weixin.qq.com/s/WdXurDCc_3_GAKlKbNzVaA][《B站底层UP主生存图鉴》]]

    墨茶的去世，撕开了B站部分底层UP主残酷生存真相的一角。基于对墨茶的缅怀，采访
  了数位90后底部UP主，他们中有人逃离，有人把UP主当作救命稻草，有人在忙碌的996之
  外，用UP主治愈孤单……他们的流量价值在B站内容生态中或许无足轻重，但作为“沉默的大
  多数”，他们的选择却更能展露B站生态中的生存真相。

* 一月
** 2021-01-29
- [[https://mp.weixin.qq.com/s/Pkv0ooZ2POkn-no2qW7YwQ][《为什么微信的“视频动态”失败了，但视频号却成功了？》]]

    什么是微信的视频动态？从数据的角度，微信的“视频动态”毫无疑问是一个失败的功
  能，对比“视频号”两者的渗透率是1.25%VS16.5%，这两个数据可谓天壤之别。那么为什
  么会出现如此悬殊的结果呢？为什么一个被国外证明过的成熟功能会如此水土不服呢？为
  什么视频动态在微信重视的情况下数据却如此难看呢？

- [[https://mp.weixin.qq.com/s/i                   joc4zi-M_qRm7eAtg8gKQ][《为什么苹果、微软现在才开始造芯？》]]

    放眼国际，谷歌、苹果、亚马逊在芯片方面也相继投资，使用自行研发的芯片。芯片行
  业整体的风向变了，这仅仅是因为英特尔在制程上落后了吗？为什么这些顶尖的公司都不
  约而同在这个在这个时间节点上开始自研芯片呢？明明是产业分工的发展逻辑，现在又闯
  入了几个实力强劲的搅局者，苹果、微软、谷歌们可以成功吗？

- [[https://mp.weixin.qq.com/s/SD7c9XWPbmxIr       jqYXK4S0Q][《李一诺：女性别把评判自己的权力拱手让人》]]

    在长江商学院的课堂上，主持人问李一诺。如果评价自己的人生和选择，她会打多少分。
  李一诺想也不想：“100分。”她说，其实这是一个典型的女性更频繁提出，也更在意答
  案的问题。“男性才不会到处问别人，你给我打多少分。”她语速极快：“女性总是把评
  判自己的权力拱手让人。”

- [[https://mp.weixin.qq.com/s/wOITKe7lOhL         jufz-hi5RwA][《小众社交围剿腾讯》]]

    关于腾讯在社交上的动作，大多数人的目光都只会聚集到微信和QQ身上，鲜有人注意到，
  在过去的两年时间里，腾讯在小众社交赛道做了诸多尝试。近些年层出不穷的陌生人社交
  产品，不断分食着社交这块“大饼”，使得以社交起家的腾讯不得不战略性反击，频频推
  出陌生人社交产品试水。社交赛道已然暗潮涌动，腾讯亟需找到行业突破口，再次为自己
  续命。

- [[https://mp.weixin.qq.com/s/                    jRq7pgazhUfhlRwlnIXYdQ][《科技巨头都来造车，打的什么算盘？》]]

    继社区卖菜之后，科技巨头又盯上了造车。一年前，新造车这个赛道里，最活跃的是特
  斯拉，以及以蔚来、小鹏、理想为代表的造车新势力，如今，名单里增加了百度、阿里、
  华为、富士康、苹果，如果算上投资这种形式，还有腾讯、美团——大大小小的科技巨头，
  都在抢造车这块蛋糕。为什么科技巨头都在造车？新造车股价暴涨、疯狂造富之后，巨头
  们又在打一个什么样的算盘？

** 2021-01-28
- [[https://mp.weixin.qq.com/s/tEW8npHbzX84-TV2ogmm5g][《美国政治的起源与挑战》]]

    全球政治秩序的不确定性将成为21世纪第三个十年的首要挑战。中美脱钩、科技泡沫、
  债务危机、贫富分化、中产下沉、社会撕裂……政治成为了全球主要矛盾的制造者。当政
  治正确、政治选票与政治自利压倒了国民理性、国民诉求与国民利益时，这场斗争便给全
  球政治学界带来了极大的困扰：是民主政治正在退化，还是一切矛盾正被美国宪政内化？
  到底是群体大众的反叛，还是知识精英的背叛？

- [[https://mp.weixin.qq.com/s/WugAqSDdzehE3I41lK09mQ][《大浪淘沙：中国保险三十年》]]

    复盘中国保险三十年，沉浮起落，皆是时势使然。如果一家公司只想着利用金融牌照套
  取各种融资，买贷循环，在政商关系中纠葛不清，注定难以走远。而如果一家公司可以沉
  潜下来稳扎稳打，并能够抓住历史进程中的金融和科技关键节点，它又怎么会走不远？大
  浪淘沙，谁能立于浪潮不倒？归根结底，在不忘初心、守正出奇。

- [[https://mp.weixin.qq.com/s/XE7bqR3w0IGBTofyqSS_cw][《抖音抢走了拼多多的支付 “核按钮”》]]

    支付宝和微信支付双雄并峙，并不意味着支付市 场上缺乏竞争——争夺移动支付第三名
  的发令枪在2020年就已打响，而决出雌雄的关键时刻已经到来，那就是近在眼前的2021年
  春节。这场竞争的参与者壁垒分明：一类是交易型公司，如美团、滴滴、拼多多、携程；
  另一类是内容型公司，如字节跳动、快手、B站。

- [[https://mp.weixin.qq.com/s/FAi05CRrT6DfmDRCt1MxkQ][《深氪｜深度调查：千亿芯片大骗局》]]

    为什么仅仅时隔一个月，千辛万苦求来的宝贝“光 刻机”，就被抵押出去换钱了？诸
  多地方官员愤怒声讨：“凭什么说（弘芯）投了1000 个亿？那不就是骗子！”弘芯最初
  的几个攒局人是怎么把武汉政府、业绩泰斗蒋尚义，以及众多合作公司，一步步骗进入了
  这个“千亿骗局”？更重要的是，对于诸多急于“造芯”的各地政府、各路资金，怎么避
  免再次踏入“弘芯式骗局”？

- [[https://mp.weixin.qq.com/s/SFfpWxaizhdI        JCNNNIAVoA][《视频号不是抖音》]]

    随着视频号的出圈，很多人对于视频号的分发推荐逻辑感到好奇。为什么同样的一条内
  容，在不同的平台差别这么大？一条内容究竟是如何出现在视频号上的？如何才能让自己
  的视频号被更多人关注到？另外，微信是一个去中心化的工具，视频号却有中心化的推荐
  机制，二者如何平衡？本文将从视频号的推荐机制，分析到底是谁在影响你所看到的视频
  号。

** 2021-01-27
- [[https://mp.weixin.qq.com/s/9P7vmpTNvsb         JxGsdLT5tsw][《职场生存指南 2021 版》]]

    过去没有所谓的铁饭碗，现在没有铁饭碗，以后也不会有。即使是国企，也未必有机会
  一路轻轻松松做到退休。所以，随时要琢磨自己职业生涯的各种可能性。如果你已经可以
  看到自己职业的终点，那我建议还是趁早换工作。一眼望到头的日子，不会有什么乐趣。

- [[https://mp.weixin.qq.com/s/KqGsAu0SNqKlwewOudop2Q][《中金：就地过年影响几何？》]]

    近期国内多地报告本土散发病例和聚集性疫情，就地过年将是不少人的选择，这个变化
  如何影响一季度GDP增长？就地过年和疫情防控对于2021年第一季度GDP的影响有正有负，
  总体影响可能尚需视疫情的演变以及春节期间生产和其他活动的安排而定。目前我们仍然
  维持2021年第一季度实际GDP同比增速19.5%的预测。

- [[https://mp.weixin.qq.com/s/MyYaOWuUx3bcaAbs    JOuyMg][《新消费品牌崛起的动力与创业机会 | 2021创业何处去》]]

  2020，百年一遇的疫情让许多满怀信心的创业者折戟沉沙。幸运的是，中国经济环境因果
  断的防疫措施而稳定，产业结构的调整，技术与商业模式的更替，因为稳定的国内环境而
  继续。2021年开年系列文章以「2021创业何处去」为主题，梳理一些我们看好的方向赛道，
  希望对创业CEO们找方向有帮助。

- [[https://mp.weixin.qq.com/s/kOqtDv5lzvqpvby8rFFsjg][《潜望｜专访比尔·盖茨：新冠疫情正在重新定义我们这一代人的生活》]]

    作为将关注全球健康作为使命的盖茨基金会，在过去一年不仅见证了新冠疫情的发展，
  积极投身到抗击疫情的第一线。在2021年题为“全球健康与你我休戚与共”的公开信发布
  之际，比尔·盖茨他表示，正如第二次世界大战是我们父母那一代的决定性事件，我们正
  在经历的这场新冠肺炎疫情也将重新定义我们这代人的生活。

- [[https://mp.weixin.qq.com/s/m2EqAP0EncAn2LLfy_64fQ][《暴富制造机，茅台通往全民信仰之路》]]

    绞尽脑汁抢茅台的消费者、“哄抢”茅台股的基金公司、茅台股价越长越高......疯狂
  之下所有人都恐慌：何时会崩？当前1322家基金持有茅台，仍然稳坐公募基金第一大重仓
  股宝座， 跌不起的茅台同样焦虑，如何维持长期暴利是茅台要为二级市场续写的神话。
  经销商、电商、机构、股民、消费者都坐上了茅台这张赌桌，现在他们都想赢，现实吗？

** 2021-01-26
- [[https://mp.weixin.qq.com/s/2zs8gS09-ubS12tzf1PNwQ][《新消费创业狂欢背后：95% 的品牌是平庸的》]]

    从渠道、消费者、品牌三个角度去分析，新的渠道是否加速了新品牌的出现与消失，消
  费者正在发生怎样的变化，下一个新品牌到底会 以怎样的方式出现？

- [[https://mp.weixin.qq.com/s/_y6d43VvzRoL_OLndSREWQ][《QuestMobile2020 中国移动互联网年度大报告》]]

    今天跟大家分享2020年中国移动互联网总结，将从全盘维度，以八大关键词，全面展示
  新变化，跟大家分享一下大盘存量时代，沉闷而压抑的市场格局中，新生如何在寒冬中孕
  育，变局如何在僵局中破茧、后浪如何在困顿中突围！

- [[https://mp.weixin.qq.com/s/LOxVudqdz           J8                J1TUSOrfZJQ][《便利蜂庄辰超：人的效率低下，我们用算法大规模扩张》]]

    便利蜂创始人庄辰超曾非常细致地讲述了他是如何分析市场机会，找到了创业切入点，
  创立了便利蜂，并且如何用一套强大的算法系统来实现经营决策的无人化。人类员工很难
  综合考量做出决策，大家都在说数据赋能人类决策，但对于一个复杂的店铺，数据就算赋
  能，一个店长也无法决策。今天我们回顾一下庄辰超的经典课《便利蜂：算法驱动，升级
  便利店体验》

- [[https://mp.weixin.qq.com/s/dcHmLA_iclaX6_UZx0YIFw][《快手失去4000万“老铁”》]]

    2020年在春晚庞大的流量冲击下，快手抗住了前所未有的峰值，远超快手制定的K3战役
  目标——3亿DAU。然而2021年1月24日，在上市前夕，快手更新了招股书，并披露了2020年
  下半年的用户数据：截至2020年11月30日止11个月，快手的平均DAU为2.638亿，和之前的
  峰值相比，至少4000万“老铁”消失了。

- [[https://mp.weixin.qq.com/s/Rl0Ks-v25Aa5EyIYp_QmJQ][《电商大战二十年》]]

    亚马逊的CEO贝索斯曾说：“个人品牌就是你离开房间后，房间里这群人对你的评价。”
  随后，贝首富的负面新闻被曝光，这位大佬一度被美国劳工协会称为“魔鬼”。不过，这并
  不阻碍贝索斯个人品牌的漂洋过海，在中国做电商创业的，几乎都是贝索斯的信徒，在贝
  爷的影响下，风起云涌，一场绵延二十年的电商大战就此拉开序幕。

- [[https://mp.weixin.qq.com/s/OC                  JCpBeLNZoM0WHV8   JigsA][《中国为什么需要“双循环”》]]

    今年下半年，国家提出“深化供给侧结构性改革，充分发挥我国超大规模市场优势和内
  需潜力， 构建国内国际双循环相互促进的新发展格局”。中国外贸的“动脉”供应链，“双
  循环”战略之下，在疫情、国际政治、国内变局的多重影响下，供应链是否还是优势？中
  国外贸业将会迎来什么变局？

** 2021-01-25
- [[https://mp.weixin.qq.com/s/nS_x7ldRXsfH0-xZX8eqUw][《微信为什么要做输入法？》]]

     张小龙公开课演讲中提到的五大实验性项目，大部分都已经 在微信8.0版更新中得到
  呈现，唯一漏掉的是在张小龙看来依然“值得投入”去做的微信输入 法。张小龙点出市面
  上已有的输入法产品存在监控用户聊天记录的弊端，其实微信做输入法 除了提到的保护
  用户隐私外，还有更深层次考量:通过输入法优化聊天体验，提高微信搜索的效率，并借
  此加 大对微信内部公域流量的开发运营。

- [[https://mp.weixin.qq.com/s/BB5i4-I             JhkcQqI30Muql9w][《连麦张小龙：谈微信 8.0 背后的思考》]]

    时隔两年， 微信终于在它十周 年之际发布了最新 的 8.0 版本。涉及表情、状态等一
  些功能的 迭代，引发了不少讨论。1 月 22 日晚间，在 视频号直播间里，极客公园创始
  人张鹏和科技评论作者潘乱跟微信创始人张小龙进行了一场 连麦，聊了聊微信 8.0 背后
  的思考。

- [[https://mp.weixin.qq.com/s/9VhMwivL6Dp1gTK7plWHTQ][《脉脉成为互联网大厂公敌》]]

     拼多多和B站的两件大事，把脉脉推上了舆论漩涡。这家2013 年成立的公司因为“职场
  匿名”正在逐渐成为“各大互联网公司的内幕中心”，有人将之成为树 洞，也有人将之称为
  “互联网茶 水间”，但同时，脉脉也引起了越老越多的互联网大厂的不满， 成为互联网大
  厂 们的“公敌”。

- [[https://mp.weixin.qq.com/s/vlLZoN-4aUHlBQvprtXSaQ][《我的年终奖，泡汤了》]]

    还 有半个月就要放假过春节了，北上 广深的打工人，纷纷开始讨 论起两个话题，一
  是春节能不能回 老家，二是今年还有没有年终奖。随着疫情又开始出现， 有人开始盘算，
  今年估计是回不 了老家了，这剩下半个月打工的日子，就指望年终奖了。但 是，对于一
  些人而言，老家回 不了，年终奖，可能也没了。

- [[https://mp.weixin.qq.com/s/S3YpNBi_ddlw6NI1OGki3A][《独家丨虾米关停之际，抖音快手借道音乐暗战TME》]]

    2月5日，走过12个年头的虾米音乐将正式关停，国内的头部音乐公司仅剩下腾讯音乐娱
  乐集团和网易云音乐。有行业人士认为，以后除了这两家外，很难再有新的竞争者出现，
  打破音乐市场两极的格局。但是，随着抖音、快手等两家短视频的崛起，其音乐属性正在
  不断被发掘出来，并开始转为向音乐平台进发，抖音快手两家的强势入局，或为国内的音
  乐市场带来新的改变。

** 2021-01-22
- [[https://mp.weixin.qq.com/s/iLUb8EPmZ77QYZinpbk0QA][《春晚红包里的巨头权力变迁史》]]

    2021年，“谁在春晚给全国观众发红包”这件事出现了一些波折和悬念。从2015年的微信
  摇一摇、2016年的支付宝集五福，再到2020年快手的10亿现金红包，以及2021年即将上场
  的抖音，互联网公司你方唱罢我登场，春晚这方舞台上，见证着互联网老牌巨头的更迭和
  新贵的诞生。谁在春晚上发红包，成了每年春节的一大悬念。而每次春晚谁来发红包，背
  后反映的是巨头之间的地位和格局变化。


- [[https://mp.weixin.qq.com/s/LF                  J5915hFVwZusUD-G7qxA][《谁先在视频号上赚到钱了？》]]

    “如果你在2012年错过了公众号，在2018年错过了抖音，那么在2020年，你不能再错过
  视频号了。”去年今日，全网最会赚钱的那批人集体闻风而动，视频号千呼万唤始出来。
  尽管视频号想要激发的是每个普通人创作的意愿，让每个个体都能被看见，但这并不妨碍
  有志者在这片“大水”里成为“大鱼”。


- [[https://mp.weixin.qq.com/s/zZg2Kiavda7N1Eu4eYpQ4A][《快手往事：得老铁者，失天下》]]

    2017年7月，快手总部数据团队为老板们分析了一款来势凶猛的产品：抖音。耐人寻味
  的是，汇报结束后，在座高管没反应。一年后抖音日活突破1.5亿，超过了快手，彼时，
  前者上线五百天，后者上线七年。一个产品的命运，当然要靠自我奋斗，但是也要考虑到
  历史的进程，曾经坐拥绝佳历史机遇的快手，是如何一步步沦为配角的？在快手上市前夕，
  我们复盘这个过程，看看当年到底是哪出了问题。


- [[https://mp.weixin.qq.com/s/AukVk7vTd0gLl1_rirOy9Q][《基金经理的收入有多高？》]]

    在很多人的传统印象里，基金经理是超级金领，超高收入群体，年收入随随便便几百万，
  那么基金经理的收入有多高？实际上公募基金帮客户赚的钱再多，都只能赚个管理费，而
  且大部分利润还是公司股东的，基金经理也只是拿工资的打工人。


- [[https://mp.weixin.qq.com/s/TXX                 jqqldkIn1         J5-H9    j JVbw][《虾米倒了，网易云音乐还好吗？》]]

    虾米宣布倒闭之后，在线音乐平台的生存问题重新回到公众视野。音乐平台之间的竞争
  提高了版权成本，用户尚未形成付费习惯让平台盈利难上加难。已经拥有8亿用户的网易
  云音乐，能顺利“破圈”，找到新的盈利点吗？

** 2021-01-20
- [[https://mp.weixin.qq.com/s/vTF_7tlrGuRtA-0tFK-2QQ][《腾讯控股(0700.HK) 2021年微信公开课：生态能力愈发稳固，商业化大有可为》]]

  1月19 日，2021年微信公开课PRO以“激发WeBuild”为主题开讲，并通过线上方式呈现。会
  上微信 团队带来了小程序、微信支付、企业微信、搜一搜、小游戏、视频号的最新产品
  动态。1 月19日晚，张小龙亮相“微信之夜”，发表对微信十年的产品思考。


- [[https://mp.weixin.qq.com/s/feSZkGsE4ecivPhoR2bYNg][《乔布斯罕见亲撰檄文——苹果如何加速Flash的死亡？》]]

    Flash终于在2020年12月31日正式宣布死亡了，尽管在中国还以特殊的版本苟延残喘，
  但毫无疑问Flash终将穷途末路已经板上钉钉。在此过程中，苹果是加速其死亡的关键变
  量。今天，卫夕和大家讲一讲苹果和Flash母公司Adobe交锋的一个精彩片段，这个交锋过
  程集中展示了苹果创始人乔布斯的雄辩与远见。



- [[https://mp.weixin.qq.com/s/DQs4WmfykyqVtURF8F-4xQ][《张小龙：微信十年的产品思考（附万字全文）》]]

    1月19日消息，在微信成立十周年之际， 一年一度的“微信之夜”也正式启动。在微信之
  夜上，腾讯公司高级执行副总裁、微信事业 群总裁张小龙亮相。在接近一个半小时的分
  享中，张小龙提到了关于视频号、直播等多个功 能诞生的点点滴滴，并对微信十年做了
  总结。以下为张小龙演讲实录全文。


- [[https://mp.weixin.qq.com/s/wgZEf1b             J3BZeyz5LLQrnPQ][《沸腾十五年 | 游族林奇和远去的网页游戏江湖》]]

     左林大叔今天八一八游族林奇和网页游 戏江湖。2009年，宋辰创办游族，林奇成为其
  天使。2011年，担任游族的CEO，自此，游族 也走上一条ARPG页游为王，收入狂涨的上升
  路线，2014年，游族得以借壳梅花伞上市。在 2014年后，页游江湖再无波澜，手游的全
  面崛起，诸多先行者在拥抱资本市场后并没有取得 预期是更为关键的外部因素。江 湖已
  经远去，但江湖上的人尤在，故事也还在发生。


- [[https://mp.weixin.qq.com/s/0Nqh1wz-kHOKrqOi    JmFylA][《为什么长视频没有强算法推荐的产品》]]

      当算法推荐在图文、短视频领域大杀四方、所向 无敌时，我们曾经一度以为在内容
  分发领域，算法就是无敌的、是降维打击。但是奇怪的是， 现在算法在长视频领 域依然
  没有取得主导权。那么为什么长视频没有强推荐的产品？如果要 找一个正确的维度 去看
  待这件事的话，那么考虑的点主要有两个：长视频与算法的匹配以及 商业上ROI是否可行。

** 2021-01-19
- [[https://mp.weixin.qq.com/s/xr5YxtxFZC960WA8s4ROVQ][《2021年微信公开课PRO最全干货集合，划重点啦！》]] 一年一度的微信公开课，终于来了。今日早上，期待已久的2021微信公开课PRO在广州正式开讲，本届大会以“WeBuild 激发”为主题，对视频号、小程序、微信搜一搜、企业微信、微信支付、微信小游戏等六大生态领域进行了内容分享。


- [[https://mp.weixin.qq.com/s/PnpVTrmKIXDEgDq2NYzCrA][《快手槽点重重，投资价值在哪？这篇说清楚了》]] 快手不同于B站，长线和短线逻辑确定性都很强。快手在游戏与改版上的一系列动作，明显显示出加速变现的意图，从而提高短中期业绩的成长性与确定性。因此，我们认为当前中短期变现加速才是快手当前的核心逻辑。


- [[https://mp.weixin.qq.com/s/ffHQXc9Q6s1bfeAYy   Ja_Hg][《维基 20 周年，为什么它是「互联网奇迹」？》]] 如果维基百科当年没有被创立，恐怕在今天这个碎片化、商业化的互联网世界，它根本无法诞生。在创始人Wales 看来，当下有不少人被困在「信息茧房」，也有人对国家、种族分裂异常狂热，而维基百科会永远是那道促进人们理解的桥梁。Wales 曾亲自讲述了维基百科的往事，探讨了知识和平台的关系……他所说的，最终能你更明白维基百科为什么是一个奇迹，一个关于革新的奇迹。


- [[https://mp.weixin.qq.com/s/u9-epDfMQwUaSuXRyf1iSw][《年轻人拿考公赌明天，机构用焦虑割韭菜》]] 在公考这条路上，为求“上岸”，所有人都在全力奔跑，在社会和家庭共同编制的焦虑网下，公考培训机构正在成为最大的受益者。巨大的需求刺激下，公考培训市场还在不断地扩张、再扩张，对于如何贩卖这场“焦虑”，公考教育培训产业链上的每一个参与者都在绞尽脑汁。这是一个巨大的赌场，每一个参与者都在赌。


- [[https://mp.weixin.qq.com/s/f7Nrsd0dNtddZGE9zadHlw][《郑爽回应“代孕弃养”，这背后是一条怎样的产业链？》]] 郑爽前男友张恒的一条微博“引爆”热搜，他滞留美国是因为要照顾两个孩子，而根据时间推测孩子为代孕所生。此事也引发了网友对代孕产业链的讨论，事实上，目前国内明令禁止代孕，但在美国、乌克兰、俄罗斯等国家的部分地区，代孕已经形成一条成熟的产业链。我们来看看网上流传的张恒、郑爽孩子的出生证明透露了哪些信息，以及网友们热议的代孕背后是一门怎样的生意。

** 2021-01-18
- [[https://mp.weixin.qq.com/s/MYvZ1zcG            j9NO-EHcBzmQow][《B站，终于活成了抖音的样子》]] 近日，B站APP端在内测单列信息流的沉浸模式，从外表看来和抖音的播放界面别无二致，最大的不同是，B站的“短视频模式”仍保留着弹幕功能和横屏切换选项。去年抖音博主大规模“入侵”B站，一年过去了，随着越来越多不同平台视频创作者的入驻，遗世独立了十年的B站，逐渐出现了被同化的迹象。B站越来越火，却越来越不像“B站”了。


- [[https://mp.weixin.qq.com/s/VYddE5d94FWNSAdVL9LEUg][《2020研究洞察：新消费品牌的8大增长驱动力》]] 2020年，我们研究和拜访了近百家消费零售企业后，决定思考几个更深刻、更本质的问题：为什么有的品牌能够比别人增长更快？是什么驱动了它们的高速增长？这其中既有年轻的新锐品牌，又有做出革新的传统品牌 - 我们统一将这些取得爆发式增长的品牌称之为新物种。接下来，用数据和案例为大家阐述高速增长的新物种所具备的8大特征。


- [[https://mp.weixin.qq.com/s/0Bdgk0z             Jl                jtF0tuWUGriWA][《陆铭：大城市不够大，中国区域发展的三个趋势》]] 有一个话题在接下来的十四五期间以及更为久远的时期会决定中国经济下一阶段是否能够健康可持续地发展，这个话题就是中国的城镇化。首先，我们来讨论一下在城乡和区域发展方面的结构调整空间；第二个方面，结合经济双循环的背景，来谈一谈城乡和区域的发展；最后，讨论一下城乡和区域发展方面的政策建议。


- [[https://mp.weixin.qq.com/s/TF4C80nVUwzzKUxwXN  jv_Q][《抖音需要春晚》]] 据称，拼多多不再担任2021年春晚独家红包互动合作伙伴，抖音将补位。铁打的春晚，流水的赞助商，广告争夺赛的背后，是一部中国商业权力变迁史。这其中不仅是对流量与商业话语权的争夺，也是对商业地盘的争抢。从支付领域到短视频，通过被称为“中国经济晴雨表”的春晚，可以窥探出下一个风口。


- [[https://mp.weixin.qq.com/s/4Q4GmTwnHvtD_OyXC4DooA][《2020年，全村女孩都去割了双眼皮》]] 在“容貌焦虑”的背后，是一个数千亿的医美市场。中国医美市场兴起于2008年前后，2014年前后进入爆发期，到2018年前后，一二线城市的增速开始放缓，随后，更多的医美机构，开始在下沉市场中探索机会。下沉市场相对于一二线城市来讲，竞争压力小，成本低，所以更容易盈利，因此众多医美机构也需要打开下沉市场，从而降低获客成本和扩张市场。

** 2021-01-15
- [[https://mp.weixin.qq.com/s/IPlNQ               jQ1mBD            JTRiNaQBcuw][《腾讯华为之争背后，一个时代正在落幕》]] 华为游戏中心在1月1日发布公告宣布，因“腾讯单方面就双方合作做出重大变更”，华为应用商店将全面下架腾讯游戏。腾讯与华为的这次下架事件，让游戏公司与硬件分发渠道的冲突逐渐从幕后走向台前，应用商店的黄金时代正在过去，牢不可破的市场地位已经在悄然消融，也并非是两家公司层面的斗争，而是两个行业和一个时代变革的缩影。


- [[https://mp.weixin.qq.com/s/9WfxyseqGsSIIUx4L4GcMQ][《科技公司“出硅谷记”》]] 2020年，大量的科技公司正在出走硅谷，它造成这一现象的，除了摆在台面上的加州房价、税收、监管环境因素之外，还有一些更深层次的东西：就像美国在过去几年展现出来的系统性分裂一样，硅谷也在分裂。谁走了？谁留了下来？从这些公司的对比中，你或许也能观察出不同硅谷公司，已经展现出的文化、意识形态上的分裂。而这种分裂，伴随着四年前特朗普的上任和自那以后愈发严重的美国社会整体的撕裂，早已有表征浮现。


- [[https://mp.weixin.qq.com/s/gEDCeQ905y6P_xHUzIVs2w][《在闲鱼和小红书上，我们找到了年会存在的最大意义》]] 每到年底，一些打工人的心里就越没底。这种不安的情绪常常来自两个方面，年终奖的额度和年会的组织力度。今年由于疫情影响，多地出台了相关政策，公司年会或是取消或是延期，但最近社交网络上关于年会的话题仍然不绝于耳。 我们来看看大家对于年会都在吐槽什么？大家在年会上都是怎么争奇斗艳？抽奖环节又有哪些有意思的现象？


- [[https://mp.weixin.qq.com/s/HfYNd3WY5-VXWSwla   jHi2Q][《悟空问答关停：字节跳动的第一场败仗》]] 被“战略放弃”的悟空问答，即将退出字节跳动的App阵营。2021年，当初一时风光的“悟空问答”落幕，重新回复到原本的名字，以头条问答的形式继续存在。悟空问答宣布关停的头一天，恰逢知乎10周岁生日。来势汹汹的对手划上阶段性句号，知乎成了与字节跳动对阵的各领域竞争者中，少有的获胜者。


- [[https://mp.weixin.qq.com/s/cyywLfN2YT3CLDasOGAA_g][《谁还去KTV？》]] KTV如今已不再是年轻人眼中时髦的代名词。社会的发展和互联网的普及给年轻人带来了更多元化的社交渠道和多样化的娱乐场所，对于曾经奉KTV为“潮流”的80、90后而言，深受追捧的KTV显然已成为过去，他们已经“背叛”KTV。

** 2021-01-14
- [[https://mp.weixin.qq.com/s/SOMTvXZP_dD1YISXf39Hsw][《围剿 B 站》]] 一年股价翻三倍、最新市值达 414.5 亿美元、坐拥“Z 世代”年轻人，破
  圈后的 B 站是这两年视频行业绝对的主角。B站已经向港交所正式提交上市申请，此次上
  市融资规模直线飙升，但这并不意味着它没有成长的烦恼，有一个最明显的现象是，野心
  勃勃的 B 站，正被卷入更为残酷的互联网竞争中。它赖以生存并引以为傲的 UP 主生态，
  正遭受着 BAT 们的“围剿”。


- [[https://mp.weixin.qq.com/s/RXrTI4fbNiBzxvyITlEijg][《从热爱到生意，中文播客走出「隐秘角落」| 反光镜》]] 播客是去年起被广告主新近重
  视的渠道，在 2020 年中国大陆播客的数量激增，这是继知识付费后，内容领域又一次有
  多家头部平台参与的罕见热潮。有一个现实是，在中国过往对于声音这一载体的挖掘太过
  有限，无论是生产端、消费端还是整个生态链条都没有充分发展，更别提如何赚到钱，但
  一切正在慢慢改变。


- [[https://mp.weixin.qq.com/s/gXZwukRgyN4Q59tdiA-V5Q][《2020 年，十佳 IPO 捕手》]] 2020 年，成为名副其实的全球 IPO 大年，伴随着的是创
  业者和投资机构们的狂欢，作为陪伴其成长的投资机构更是等到收获时刻。数据显示，在
  A 股 IPO 上市背后，PE/VC 渗透率超过 70%，除 PE/VC 还包括国有创投机构、产业基金、
  上市公司旗下创投基金、券商直投和险资旗下股权投资平台等。以下是按照各家机构在
  2020 年新收获的上市公司数量统计的前十名。


- [[https://mp.weixin.qq.com/s/XA_solDnK_wUPy3pCwb_Gw][《新冠疫苗已接种一个月，这里有 5 个你可能关心的问题》]] 自 2020 年 12 月 2 日起，
  人类正式列装抵御新冠病毒的 “生物防具”，疫苗。目前中国、美国、英国、欧盟等国家
  和地区已经批准六款疫苗上市。按照当前的接种速度和疫苗产能，乐观估计发达经济体在
  年中实现群体免疫，全球群体免疫可能要再等等，但满足的条件包括疫苗有效率足够高、
  接种人群足够多且快、病毒变异有限、各国面持续时间同步等。那么到目前为止，新冠疫
  苗接种出现了哪些不确定性？


- [[https://mp.weixin.qq.com/s/suOO1rxaEIqe_pzeTZZpjg][《我如何掌握了爆款IP的创作秘诀？》]] 2017 年，两点十分动漫获得了阿里巴巴数亿投资，
  跻身成为全国前五的动漫企业。曾经不被大众认可的“动画片”为什么会呈现出惊人的市场
  活力？马斯洛需求模型还能预判行业内容趋势，洞悉爆款 IP 创作逻辑？消费升级时代背景
  下，“动漫+X”的 IP 共建模式如何为品牌赋能？小行业，大格局。如何迁移行业经验、立足
  产业看企业发展布局？两点十分动漫创始人兼 CEO 王世勇就上述核心问题进行了分享。

** 2021-01-13
- [[https://mp.weixin.qq.com/s/DyC                 JNLCX3DVVD_1UmGyuww][《拼多多员工自杀背后：什么在逼迫年轻人至死方休？》]] 拼多多员工谭某林从家中 27
  楼坠落，他毕业于 2020 年，刚在拼多多转正。我们无法判断小谭究竟为何选择自杀，但
  作为入职互联网大厂的应届毕业生之一，小谭曾与入职该公司的其他年轻人一起，深嵌电
  商巨头拼多多之中。当创新、自由、尊重逐步剥离，员工们陷于打卡、绩效、和监视之中，
  除了一笔高薪，我们该怎样定义这样的工作？


- [[https://mp.weixin.qq.com/s/BVk6td8             JQ                jBF3VLfAl3twg][《信仰、教义和狂欢：蔚来卖的是车吗？》]] 蔚来最大的竞争力到底是什么？传统的 4P
  理论已经无法完全套用在蔚来身上，无论是互联网基因、中国版特斯拉、车界海底捞、小
  米衣钵的继承者，还是饭圈经济，都只是对它的片面解读甚至是误读，简单的“用户思维”
  四个字似乎也无法解释。在争议和噪音背后，这家市值已经 1000 亿美金的公司到底是在
  卖什么？


- [[https://mp.weixin.qq.com/s/b109dGf6y2Dpu47iV_cz5g][《为什么贝壳、百度、蔚来值得放在一起研究？》]] 贝壳、蔚来、百度，这三家公司的业
  务南辕北辙，放在一起比较未免有些“关公战秦琼”，完全不同的行业、完全不同历史阶段
  产生的公司、完全不同的业务阶段及财务状况，他们的可比之处在于哪里？实际上正因为
  基因与经历的不同，他们的估值涨跌正好体现出目前二级市场最主流的投资思路，也是最
  有希望在近期冲击千亿美元市值的公司。


- [[https://mp.weixin.qq.com/s/o-9sY2Nnx9CwleiII_01Eg][《为什么这届年轻人都去考公务员了？》]] 疫情的发生加重了中小企业的生存危机，公司
  举步维艰，每个身在其中的公司人都受到了直接影响，这也让原本就持续了十多年的“公
  考热”在今年继续升温，把国考的激烈竞争再次推向高潮。外面风雨太大，体制内成了年
  轻人最后的避风港。


- [[https://mp.weixin.qq.com/s/TnZ2YzF8nKDO0rueSvAN6w][《被算法监控的打工人》]] 越来越多的数字化管理手段进入企业，最普通的场景是使用 OA
  系统完成对员工考勤和工作量的全面监控，甚至可以根据企业需求编写算法，接管管理者
  的决策权乃至员工的主观能动性。对企业来说，将管理流程通过算法实施，无疑更高效精
  准，也能够降低管理成本；但对于一线的普通员工而言，则别有一番风味——这张数据大网
  密不透风，令人无处可逃，原本的工作方式和节奏被改变。

** 2021-01-12
- [[https://mp.weixin.qq.com/s/tUfTwDHheOhHhYV_K2zNKQ][《施展：一种新的世界秩序，正在到来……》]] 美国大选终局几乎落定，特朗普却仍在上演
  “最后的疯狂”。2021 年才刚开始，中美关系就迎来了一些全新变数：特朗普给制裁加码，
  禁止微信、支付宝等中国企业的准入，紧接着特朗普支持者又占领美国国会，民主党提出
  弹劾决议，指控特朗普“煽动叛乱”。高度撕裂的美国社会，还能好吗？中美两个超级大国
  的关系，又将走向何方？我们到底该如何与美国相处？


- [[https://mp.weixin.qq.com/s/7kMTN0ahCHII0ChBfawwjw][《QuestMobile2020 “Z 世代”洞察报告：3.2 亿“Z 世代”引爆消费潮流大迁移，如何抓住
  他们？》]] QuestMobile 数据显示，截止到 2020 年 11 月，95、00 后 Z 世代活跃用户
  规模已经达到 3.2 亿，占全体移动网民 28.1%；Z世代年轻、接受新事物的能力，带来了
  移动网络使用上的显著特性，社交、视频、网购、音乐、团购、游戏方面，活跃度都很高。
  这种趋势背后引发的消费潮流如何变化？又该如何抓住他们的？不妨看报告。


- [[https://mp.weixin.qq.com/s/9qPTAtm2H-bw3du19PufUA][《外卖骑手，巨头的炮灰》]] 外卖骑手是典型的平台经济下的非正规就业者，这个群体还
  包括网约车司机、代驾、快递员等。当一家家平台型公司采用外包、众包模式，快速招揽
  成千上万人为其工作，甚至简单到在 APP 上申请即可时，平台享受着廉价劳动力带来的
  资本市场溢价，但骑手的风险由谁来买单？


- [[https://mp.weixin.qq.com/s/k4Z94P4k7kFxQYPykqXCnw][《负债后，我才知道原来 200 块可以活一个月》]] 尼尔森 2019 年 11 月发布的《中国消
  费年轻人负债状况报告》显示，扣除把花呗、借呗等当做支付或理财工具并且当月还清的
  人群，90 后职场人实质欠债人群比例达到 57%，95 后职场人该指标也接近 40%。我们邀
  请了三位深陷（或曾经深陷）债务深渊的年轻人，聊聊他们都在过着怎样的生活。


- [[https://mp.weixin.qq.com/s/EZQorAzh3UQSw-awEveHvw][《燕郊离北京再近，也是河北》]] 从河北省三河市燕郊开发区进入北京，只需要跨过一条
  直线距离几百米的潮白河，隔着一条潮白河，通州的房价至少是燕郊的两倍。潮白河隔断
  的不仅仅是房价，也是北三县的尴尬地位。京津冀一体化也好，通州与北三县协同发展也
  罢，从燕郊的发展和房价来看，尚未有明显成效。“潮白河之隔，燕郊仍然是河北的燕郊。
  距离再近，北三县也不可能是北京。”

** 2021-01-11
- [[https://mp.weixin.qq.com/s/VW9KeeRGgvET        JNoB-ip7KA][《张一鸣：CEO 总想招一些便宜的人，这才是最贵的》]] 历数中国互联网圈的高光并购事
  件，创始人出走的案例并不少见。然而在新巨头字节跳动的身上，却一批优秀的被收购团
  队创始人，仍然冲锋在字节跳动的一线。字节跳动如何做到低流失率网络互联网核心人才？
  今天，聊聊字节跳动的超高人效法则，以及他们和牛逼人才的相处之道。


- [[https://mp.weixin.qq.com/s/5_wFGsu4dVoP1yaqmciceg][《长沙可以没有互联网，但不能没有吃喝玩乐》]] 纵观湖南本土互联网企业，大众能想到
  与长沙相关的公司，除传统重工企业外，几乎都与吃喝玩乐相关。长沙独特的娱乐生态系
  统，反哺了一个独特的线下娱乐消费生态，从芒果 TV 到茶颜悦色、文和友、三顿半，长
  沙就这样，靠着看似闲散的吃喝玩乐生态成了当下的城市网红顶流。


- [[https://mp.weixin.qq.com/s/7X7xQq8lkaA         J3_Xyhf7URg][《江南春：两大红利消失，商业的逻辑变了》]] 分众传媒董事长江南春出席发表了最新演
  讲，他表示，5亿新中产存在巨大消费升级空间，企业家需要好好研究，这些中产到底爱
  什么？怕什么？缺什么呢？爱吃、爱美、爱健康，怕老、怕死、怕孤独，缺爱、缺心情、
  缺刺激，三爱、三怕、三缺，如果企业家的生意在三爱、三怕、三缺当中，那么这个企业
  在未来是有空间的。


- [[https://mp.weixin.qq.com/s/5gZMcKzhOORe6EvHc3OphA][《植发、整牙、祛痘广告充斥的微博，何至于此？》]] 作为中文互联网最高效的信息集散
  地，2020 年，平均每月有 5.11 亿人在微博上浏览话题和参与讨论。然而，热闹背后，
  是微博逐渐放缓的商业化，以及战略性产品的缺失。当刷量造假成为常态，优质广告主也
  正在离开微博，这使得微博的变现之路更加困难。


- [[https://mp.weixin.qq.com/s/-7Y4qiMwYh9         jWvVyMTgSrg][《大众点评变味了？》]]众多网友最直观的感受是，大众点评变味了，看到的真实评价越来
  越少，虚假好评和恶意差评却越来越多。曾经小而美的大众点评，在被美团合并后，商业
  化导流的氛围越来越重，内容越来越杂，当一个以高质量 UGC 内容为生的社区，失去了它
  的口碑，大众点评的灵魂还在吗？

** 2021-01-08
- [[https://mp.weixin.qq.com/s/mXvAAXmeH40h6cgnaR9dvA][《李善友：2021，人生皆有意义，使命终将降临！》]] 越早的临在当下，越早找到自己的
  使命，你将越早的成为自己。我们怎么感知到自己的使命呢？我们可以间接感知它，即使
  不知道自己的使命是什么，只要我们相信使命的存在，它已经起作用了。而找到使命的关
  键一步就是把当下自己做的事作为一种修行，保持此时、此地、此事的“临在当下”状态。


- [[https://mp.weixin.qq.com/s/H923YnDSy6KAiv3qe_dFvA][《自动驾驶汽车的道德困境：如何拒绝乘客的错误命令？》]]我们对阿西莫夫的三条定律在
  自动驾驶汽车上的应用不得不有所保留，人工智能驾驶系统可以根据这些定律来设计，将
  其作为总体架构的一部分，但这些定律是一种愿望，而不是不可改变的法则。在自动驾驶
  汽车常态化之前，我们必须解决其中的道德困境。


- [[https://mp.weixin.qq.com/s/oCfHnuh9IwkZMFFulqWxnQ][《先生特稿 | 逃离拼多多的年轻人：“它的文化是不吝于用最强的恶意去揣测你”》]] “我
  不知道是从什么时候开始，有点恶意的对待身边发生的所有的事情。我觉得可能在拼多多
  这两年，让我对很多事情都充满了一种警惕性，因为它的文化是不吝于用最强的恶意去揣
  测你，就算是自己的员工。”一位离职员工如此说道。


- [[https://mp.weixin.qq.com/s/22NQIqkym8SXYhGK6b9PCw][《输赢之间：电影圈背后的资本江湖》]] 自 1994 年中国随着引进大片开始，走过近三十
  年的中国电影市场早已学会了拥抱资本，2019 年，中国电影市场已经达到 642 亿，成为
  北美之外的世界第二大电影市场，无数的资本愈加想吃下这块蛋糕，但资本可不讲蛋糕的
  味道如何，蚕食吃净才是本性。中国电影要做大，也要做好，最重要的，不能忘了来时的
  路。


- [[https://mp.weixin.qq.com/s/4N2H1bpTi3hOpeXP7tP5Qg][《微博输给了抖音们，还是输给了自己？》]] 微博近期公布了 2020 年第三季度业绩：收入
  与去年同期基本持平，归母净利润只相当于去年的约 1/4，录得 3380 万美元，看上去依旧
  普通平淡，但是竞争对手表现亮眼，令微博掉队态势明显。同期腾讯、百度，都超出市场
  预期，还有尚未上市的头条系公司也在不断蚕食着微博等竞争对手的份额。这些都令投资
  者为微博捏一把汗。微博是输给了抖音们？还是输给了它自己？翻盘还有希望吗？

** 2021-01-07
- [[https://mp.weixin.qq.com/s/m_0uHKe0KkMM1-iMmp394w][《冲刺“方便面第一股”》]] 中国快消品行业进入了一个高强度竞争的节点，今麦郎发展也
  需要突破，需要在多品牌、多场景、多品类、多渠道、多人群布局，投入会加大。如果不
  以上市的方式增强自身抗风险能力，挖宽企业护城河，企业就存在掉队风险。


- [[https://mp.weixin.qq.com/s/R6R                 jcNyDf1v          jsS4A00QlQQ][《996、竞争与内卷化：穿透现实，得见真实》]] 新一轮关于 996 的争议热潮已经席卷而
  来，996 是如何席卷互联网行业的？很多人在谈及 996 时也总不忘补上一句“你不愿意
  996，有的是愿意干 996 拿高工资的人。”这个事实判断引发下一个话题：与 996 有着千
  丝万缕联系的内卷化。从 996 到内卷化，本质都是时代红利过后的泡沫。


- [[https://mp.weixin.qq.com/s/0Xm                 jwPaO6obrA        JEuIoN4Zw][《拼多多女孩“润肺”之死》]] 这个凌晨下班的女孩，生命结束在 22 岁的最后一个午夜，
  乌鲁木齐飘过雪的街头。激荡的舆论中，不少声音提醒，拼多多能开出两倍于行业的薪水，
  应届毕业生就能拿到五十万甚至更高的薪水——但这并不是属于润肺的故事。


- [[https://mp.weixin.qq.com/s/rkGw5QMbRR-w1mh12qH--g][《疯狂的在线教育：巨头进场、烧钱、二三梯队出局》]] 2020 年在疫情和资本的催化下，
  在线教育成为互联网公司最想长出的翅膀。2020 年的在线教育市场规模将达 4800 亿，
  千亿的市场同样受到了资本的热捧，融资、烧钱、并购成为了 2020 年在线教育的关键词。
  用一句话来形容 2020 年互联网巨头做在线教育的境况就是，腾讯稳中求进，阿里在摸索，
  字节意图大力出奇迹，百度在专注 AI 教育，网易在精炼平台......


- [[https://mp.weixin.qq.com/s/xu6O34YxIBRkoT81giX2PQ][《张一鸣会造车吗？》]] 不设边界的字节跳动，2020 年除了加码在线教育外，还有一个值
  得注意的动向：进军车联网领域。5月，字节跳动向媒体确认，已组建车联网团队，并计
  划推出自己的车辆信息娱乐系统方案，实现旗下抖音、今日头条等移动互联网产品在汽车
  终端落地。在巨头掀起的第二波造车浪潮中，围绕华为、百度，相继都被传出造车消息，
  字节跳动会不会成为下一个？

** 2021-01-06
- [[https://mp.weixin.qq.com/s/Chd2P4AFMrw9gMnOtIrcWw][《字节跳动怎么都十万人了？》]] 到 10 万人，字节用了 8 年，阿里用了 19 年，腾讯还
  没到。2020 年，字节跳动的员工总数从 6 万蹿到近 10 万，一个主业在线上的公司有
  10 万员工，这在几年前还是件难以想象的事。企业家往往警惕公司规模过快扩张，其它
  公司往往二三十年才能达到的规模，字节跳动压缩到了八年，但没有任何迹象表明，字节
  跳动将因此按下暂停键。


- [[https://mp.weixin.qq.com/s/l6zdiK9AlLe3rqAcACNeEw][《95 后厂哥厂妹口述：富士康不相信爱情，昆山处处是“单身大神”》]] 没有人一直年轻，
  却一直有年轻人。全球有 18 亿年轻人，互联网让这一代年轻人拥有了前所未有的自我表
  达权利，有了与广阔世界无限接近的渠道。他们从网络中汲取养分，又用自己的创造力反
  哺这个繁荣的生态，从爱好到职场，他们的人生观和职场观与父辈有了显著的区别，那么
  该如何正确认识这一代年轻人？


- [[https://mp.weixin.qq.com/s/-Sb2l0ArSEeCG0G7VvhNRA][《体检异常率 99%，这届打工人的身体有多差？》]] 2021 年的第一个工作日，996 的工作
  模式又冲上了热搜。一边是现代人越来越看重养生，一边却是越来越普遍的亚健康问题。
  每年让打工人们最心惊的可能不是年终总结，而是体检报告，从 2013 年开始到 2018 年，
  上海白领的体检异常率从 94%上升到了将近 99%——基数非常大，异常率更是不断逼近
  100%。


- [[https://mp.weixin.qq.com/s/ufYMN1kH7kkbhZTMY3Xv1Q][《比特币暴涨，独家解密谁在控盘比特币？》]] 过去两个月中，比特币的资产价格飙升，
  引领了整个全球加密资产行业的牛市回归，种种迹象表明比特币已不在局限于小范围的资
  本游戏中。究竟谁在控盘比特币？最大的利益攸关方是谁？谁在其中谋取了最大收益？未
  来比特币筹码还将以怎样的格局继续流动？人们一直以来都在探究全球比特币持仓排行的
  疑问。


- [[https://mp.weixin.qq.com/s/cfuMC3TiDkTGtzY2aMG59A][《涌动2020 | 社区卖菜的隐喻和终局》]] 每次创新，都意味着一整批人的就业被消灭。中
  国的社会环境过去对创新是鼓励的，但在经历几年的贸易摩擦和今年的疫情冲击后，社会
  大众在 2020 年突然重拾了对创新的审视，尤其是那些专注提升“效率”，却无法兼顾“公平”
  的创新。因此，围绕社区团购的争议，会给“优先效率，还是优先公平”这个问题赋予新的
  答案吗？

** 2021-01-05
- [[https://mp.weixin.qq.com/s/Vhw                 jGkcIDPpI         J8tOxM   jTCg][《那些离开互联网大厂的年轻人》]] 在 BOSS 直聘发布的《2020 年 Q3 人才吸引力报告》
  中，互联网行业在人才吸引指数排名中依然位居第二，第一则是和它紧密相关的 IT 行业。
  与此同时，脉脉发布的《人才迁徙与流动趋势报告 2020》也指出 ，2019 年，互联网行
  业里出现了可见的人才流出。一群人争先入局，一群人失望离开，互联网大厂，已经成为
  这一代年轻人新的围城。


- [[https://mp.weixin.qq.com/s/obhp                jxEKpQwuyZV9wIS00Q][《独家调查 | 虾米真的被阿里巴巴耽误了吗？》]] 11 月末，一则“虾米音乐即将于明年 1
  月关闭”的传闻，触发很多虾米用户在社交网络上抒发各自对于这个音乐流媒体产品的怀
  旧之情，同时也有很多人在表达不满，认为“虾米是被阿里巴巴耽误的”。但虾米真的被阿
  里巴巴耽误了吗？


- [[https://mp.weixin.qq.com/s/HfrEhxIpT9XQTKZOWaUTpA][《2020 互联网没有新故事，只有新品牌》]] 2020 年是疫情下艰难的一年，处在互联网未
  诞生新风口、未出现现象级 App 的档口，资本市场因为大环境遇冷而格外谨慎，互联网
  行业极度缺乏新故事，但很少有投资机构会甘愿错过投资新消费品牌的机会，甚至，也有
  不少投资机构主动下场创立新品牌。开年之际，我们通过 6 个关键词，来回溯盘点 2020
  ——新品牌之年。

- [[https://mp.weixin.qq.com/s/                    j8MYW_zn2BXKo4luvb3xgA][《国内互联网公司为什么加班这么狠？》]] 互联网人似乎越来越忙了。就在最近，快手宣
 布展开全员大小周，为鼓励加班，字节跳动也表示要给周末加班的员工开出两倍薪水。但
 加班带来的劳累，有时候会成压死骆驼的最后一根稻草，1月 3 日晚，拼多多的一位年轻
 女员工在凌晨 1 点半回家的路上不幸猝死。是什么，让互联网人不得不以透支未来的方式
 奔跑？


- [[https://mp.weixin.qq.com/s/dBmSAzgIG-mR6g0YeUGntg][《2021，字节跳动的营收能折腾出广告圈吗？》]] 想到字节跳动，可能大部分人的第一反
  应就是“有钱”，字节重新定义了信息生产、分发、消费的关系，步步为营，字节正逐渐打
  造出了属于自己的“字节跳动系”王国。毫无疑问，字节跳动已经是中国最大的广告公司了，
  但是除了广告外，增长点在哪里？

** 2021-01-04
- [[https://mp.weixin.qq.com/s/zhIYcCMmIa-ipsurcyke3A][《特斯拉扔出了一片“二向箔”》]] 补齐轿车与 SUV 这两个最主流车型后的特斯拉，开启了
  中国本土化的新篇章。国产版 Model Y，使得特斯拉在包括燃油车在内的整个汽车市场竞
  争力大增，对比其他国产 SUV 新能源车，也是碾压级的存在；新品上市的同时，等于也
  顺手向中国汽车扔出了一片“二向箔”。特斯拉中国本土化策略由此迈入 2.0 时期，更紧
  张的贴身肉搏战揭开帷幕。


- [[https://mp.weixin.qq.com/s/DhVorf4GIqnbqXTVguY_Ww][《猝死、大小周、996：当互联网变成劳动密集型产业》]] 1 月 3 日晚，多多旗下多多买
  菜员工在凌晨一点半下班路上猝死，年仅 23 岁。有一个不可否认的趋势是，互联网对员
  工时间的挤占、对员工身体与心理造成的负担，已经成为互联网“造富”光环之下的灰暗一
  面。互联网人的工作时间正在不断延长，“996”正在取代 8 小时工作制，“大小周”也正在
  取代“双休”制度，互联网正在走向劳动密集型产业。


- [[https://mp.weixin.qq.com/s/1t2ayNR_HLSQY9fGfXpoMw][《为什么所有的 APP 都在炫富？》]] 你有没有这样一种感觉：无论打开什么 APP，都有人
  在展示自己的富裕生活，营造出一种“众人皆富你独穷”的氛围，可以说有社交的地方就有
  炫富。APP 们在变味，用户能感觉出来，从微博到知乎，从抖音到 B 站，从小红书到大
  众点评，为什么有内容分享的地方就有炫富？


- [[https://mp.weixin.qq.com/s/BN7uMLwEWdRxYXWCs1YfIQ][《榜单 | 真故 2020 年最值得阅读的 10 篇故事》]] 2020 年是一个宏大的话题，记叙
  2020 年的容器则是一个又一个渺小的个体。今天的推送中，编辑部票选出了 2020 年真
  故最值得阅读的十篇文章，并附上了推荐理由，作为记住 2020 年最后的仪式。2021 年
  我们依旧会坚持拾取、记录当下，跟我们一起，继续与真实为伍吧。


- [[https://mp.weixin.qq.com/s/Nn_b9Lv43xLFt9bY_pSwsA][《估值为什么是一种艺术而非科学 | 巴伦读书会》]] 无论是企业管理者还是普通投资者，
  都需要培养自己的金融直觉，以做出明智的金融决策。那么对于做出正确的金融决策来说，
  哪些才是最重要的财务数据，应该如何理解金融数据背后的意义？《什么是金融》总结了
  哈佛商学院金融学教授米希尔•德赛的在线热门 MBA 金融课程内容，本文整合《什么是金
  融》，解释了为什么估值是一种艺术而非科学，或者说披着科学外衣的艺术。
