#+TITLE:       总结：文件管理方法
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-10-11 Mon
#+URI:         /blog/%y/%m/%d/files-management
#+LANGUAGE:    en
#+OPTIONS:     H:5 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 借助原则和工具, 高效文件管理

在 macOS 为例, 总结一下自己的文件整理相关心得。

** 原则
1. 搜索: 尽可能使用搜索和智能文件夹功能, 减少拖动分类文件夹
2. 自动: 尽可能自动化, 减少手动命名和挪动文件位置
3. 同步: 尽可能云同步, 减少单机本地文件

** 桌面(Desktop)

根据原则一, 平时不需要根据目录去找文件, 也就不需要桌面更快到达的优势, 所
以 *桌面不放任何文件* 就是一个更好的选择。

** 下载(Downloads)

总会有些从网络下载东西到本地, 或者从聊天软件中下载文件的需求, 这些文件都
存放在哪呢?

所以这类文件, 都统一保存在 _下载_ 文件夹即可。 可以通过浏览器和聊天软件的
设置项, 修改默认下载目录, 指定为 =~/Downloads/= 目录。

这样一来, 下载目录就变成了你的守门人, 所有新进来的临时文件全部都拦在了该
目录中。

接下来, 需要做两个动作 *归档* 和 *自动删除* 。

*** 归档: QSpace

可以从 App Store 下载一个应用 =QSpace= , 该应用可看作是 Finder 的升级, 默认
即可同时展示四个目录的窗口, 极大的提升了归档文件的效率。

对于每个进入到下载目录的文件, 养成随手归档的好习惯。

对于一些明确知晓要归档到哪些目录的情况, 也可以通过软件 =Hazel= 来实现自动
化归档的功能。比如可以设定监控下载目录, 当其中有大小超过 500MB 的文件时,
自动移动该文件到 =Big Files= 目录。

*** 自动删除: Hazel

留在下载目录中的文件, 默认可以认为是不再需要的文件, 根据原则二, 可以借助
=Hazel= 的能力, 来实现每天定时自动清空下载目录的功能。

比如可以设置为, 每天清空今日之前的所有文件到 Trash 中。这样一来, 每天你打
开下载目录时, 面对的都是一个空空如也的全新目录, 实现了 =Inbox Zero= 的效果。

Hazel 甚至可以支持, 自动检测指定目录中新增的压缩包文件, 自动解压缩该文件
到同名文件夹, 自动删除该压缩包。

** 文件命名: 三段式

在地球上, 你只需要知道了经度, 纬度, 和海拔高度这三维数据, 就能定位到任意
一个位置。

在文件命名时, 我们也可以借鉴地理定位的三段式方法来命名, 例如:

- 针对照片, 可以按照[时间]-[地点]-[对象]的方式命名
- 针对文件, 可以按照[时间]-[项目]-[描述]的方式命名
