#+TITLE:       学习：如何开好会议
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-06-15 Tue
#+URI:         /blog/%y/%m/%d/how-to-meet
#+KEYWORDS:    <TODO: insert your keywords here>
#+TAGS:        <TODO: insert your tags here>
#+LANGUAGE:    en
#+OPTIONS:     H:5 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

工作中每天要花大量的时间在开会讨论上面, 为什么要开会? 开会核心是解决 =认
知一致= 的问题。针对一件具体待讨论的议题, 参会人员提供自己了解的信息和看
法, 大家共同讨论, 形成一致的决策意义和后续动作, 避免了大家各自为政, 各玩
各的, 结果玩砸的情况。

** 会前: 不开无准备的会

开会之前需要做好五个W:
1. Why: 为什么要开这个会
   会议背景是什么, 开这个会想要达到什么目的, 大家了解会议目的, 才能在开完之后评判这个会议是否开的成功。

2. Who: 谁需要参会
   需要谁来参会, 谁来发会议邀请, 谁来做会议纪要, 谁来做会议主持。

   参会人都有责任--反对的责任。 你既不是发言人, 也不是主持人, 参会时只是坐在后排旁听, 想下公司给你发工资， 让你参加这个会议, 不是让你在后面玩手机, 喝水, 自己在电脑上处理工作的。 你要听大家的发言， 一旦有任何反对意见, 哪怕你是级别最低的初级职员, 也有 =反对= 的责任。

   因为往往一线的同学对于具体的信息了解和收集最全,最敏感。你如果看出一个
   问题, 有了反对意见, 这时候没有跳出来说出你的意见, 那对于整件事可能有
   非常大的决策风险。 会议确定了决议之后再翻盘重来, 是一个非常浪费的事情。

3. When: 什么时间开会

   会议时间要精确, 协调好参会人时间后, 统一发出会议邀请。

   迟到要处罚, 一视同仁。这样才能让大家养成尊重时间的观念。

4. Where: 在哪开会

   会议室名称明确, 如果涉及到外地开会, 标注清楚目的地地址, 以及到达路线情况。

5. What: 开会的主要讨论内容是什么

   会议讨论流程预先分配好发言人和发言时间, 会议邀请时同步出来。

   在每个阶段, 需要什么材料, 需要谁准备, 都需要提前沟通好。 在会议群中,
   提前半天或一天时间, 将材料同步出来。 给参会人员留出时间消化材料内容,
   会上讨论时, 更快速地进入同一语境进行深入地讨论。



** 会中: 不要让会议发散
如果发言人表达能力不强, 主持人要帮助他提炼关键点, 并跟他确认是否为他想表
达的。

如果大家会议中有争执, 讨论有点失控, 主持人要提醒大家回到原点, 这个会议的
目的是什么, 我们要解决什么问题, 应该如何来讨论。

如果大家的争执就是不能产生结论，怎么办? 在会议纪要的 =待讨论问题= 部分，将
争执点列入其中, 和大家说明, 该问题会后再讨论, 或者再单独安排会议讨论。

会议结束之前, 将会议纪要给所有人快速过一遍, 看看是否有遗漏。确认无误后,
会后马上发出书面纪要。 这样后续随时可翻看某一次的会议结论，减少大家无谓
的争议。

** 会后: 不要让会议决议不落地

离开会议室, 只是这个会议效果的起点。会后要做到两点: 一是件件有落实, 二是
事事有回应。

1. 件件有落实

   在会议纪要中, 应该有单独的 =会议TODO= 模块, 记录着: 谁, 在什么时间之前, 做什么事情(Who do what by when)。

   这个落地工作不能依靠人员自觉，需要有人来盯。可以是会议纪录人, 或者是PMO, 要隔三岔五地看下这件事的进展, 提醒下责任人推进该事项。

2. 事事有回应

   领走待办事项的负责人有责任来跟领导反馈进展。如果事项进展顺利, 需要告
   诉领导当前进展情况; 如果事项推进受阻, 更需要告诉领导当前推进遇到的问
   题, 是否需要资源或其它协助。


千万不要有 *这事拖拖就过去了, 或者老板就忘了* 这种心态。不一定每件事我们都
能做成, 但只要你做到了 *件件有落实, 事事有回应* , 养成了这个工作习惯, 很多
事做着做着也就做成了。
