#+TITLE: 如何制定靠谱计划
#+DATE: <2020-01-15 Wed>
#+OPTIONS: toc:nil num:nil

每年新年很多人都会制定自己的新年计划, 公司也会有相应的全年规划. 但一般到年底的时候, 回顾这一年的目标完成情况, 很多计划都变成了愿望, 没完成是常态, 完成了才是意外.

把制定计划想象成, 你想走到一个目地的, 只是单纯的说我想去土耳其, 然后每天随处晃悠, 基本上是不可能走到目的地的.

如何制定靠谱计划, 让计划更好地落地实现?  可以按下面六步来进行:

* 制定目标 & 拆解目标关键要素 (目的地在哪)
明确你的目标是什么, 并拆解目标成功的关键要素. 拆解的逻辑可以是时间维度, 业务逻辑等等. 把目标首先按 =加法= 拆解, 是由哪几个因素组合构成. 然后针对每个因素, 如果没有明确认知, 将其按 =乘法= 拆解, 是由哪几个细分要素构成.

比如, 你目标是将自己公众号的收入做到一年 100 万.

首先, 将公众号收入这个事情做拆解, 公众号收入可以由 =广告收入= 和 =打赏收入= 两部分组成.


#+BEGIN_QUOTE
公众号收入 = 广告收入 + 打赏收入
#+END_QUOTE

然后, 将每个不清楚的因素做进一步分析拆解, 比如广告收入可以拆解为:

#+BEGIN_QUOTE
广告收入 = 公众号关注人数 * 文章打开率 * 广告点击率 * 广告点击单价
#+END_QUOTE

拆解到这里, 基本就可以针对每个要素做相应的提升动作安排了.

* 确定重点关注要素 (到达路径)

拆解完的要素中, 根据当前资源和擅长情况, 有节奏的选择要重点关注提升的关鍵要素.

比如, 先用一个季度时间, 想办法提升公众号关注人数, 其它要素放到后面去提升.

* 资源分配 (需要带什么装备上路)

确定好要提升的关键要素后, 需要思考提升该要素需匹配的资源. 比如公众号推广费用, 在微信群中投入时间去吸粉, 花钱找大 V 转发你的文章等等.

* 具体动作制定 (管过程, 要结果)

确定好资源后, 需要对要做的每个事情指定具体动作. 比如每天在 10 个群中转发文章, 每天花 100 块钱推广公众号等等.

* 报表制定 (量化进度)

确定好动作后, 去执行. 不要每天埋头苦干, 要抬头看路. 针对你的目标, 制定一个关键指标完成进度的查看报表, 定期(每天/每周/每月)进行 Review.

* 确定例会 (讨论进度, 修正动作)

如果是团队合作, 需要定期和团队做复盘沟通. 讨论是否需要修正你的动作, 再重复执行, 检查新动作带来的结果改进情况.


通过上述六步的操作, 你制定的计划才有完成可能, 新年计划才不会变成新年愿望.
