#+TITLE: 学习: 如何读懂财务报表
#+DATE: <2020-12-16 Wed>
#+options: toc:nil num:nil
#+URI:         /blog/%y/%m/%d/how-to-read-finance-report

#+caption: 艺术来源与生活
|----------------+------------+------------------+------------|
| 艺术来源生活   | 看实力     | 看能力           | 看财力     |
|----------------+------------+------------------+------------|
| 丈母娘 挑 女婿 | 房车存款   | 公司、职务、薪水 | 彩礼       |
|----------------+------------+------------------+------------|
| 投资 挑 公司   | 资产负债表 | 利润表           | 现金流量表 |
|----------------+------------+------------------+------------|

* 资产负债表: 实力

资产负责表包括三部分: 资产, 负债, 所有者权益.

会计恒等式告诉我们“资产=负债+所有者权益”，“资产”反映男青年有几套房子几辆车，“负债”和“所有者权益”告诉我们，他的房子和车是借来的还是自己买的。

** 资产
#+begin_quote
资产，是企业拥有的，并预期能使未来经营受益的经济资源，未来可以给企业带来正的现金流量。
#+end_quote

简言之就是“钱”和“能来钱的资源”。
** 负债
#+begin_quote
负债，是指财务义务或债务，代表企业未来负的现金流量。
#+end_quote

简言之就是“借来的钱”和“未来要还的债”。
** 所有者权益
#+begin_quote
所有者权益，代表所有者对企业资产的要求权。也就是说，在债权人要求权全部满足后，所有者拥有企业的剩余资产。
#+end_quote

简言之就是“真正属于自己的钱”。

* 利润表: 能力
如果说资产负债表显示目前了企业可用的资源，利润表展示的，就是一段时间内企业利用资源带来回报的能力和效率，也就是挣钱能力如何。

利润表由两部分组成:

1. 经营部分: 主业(努力干活)

   报告公司经营活动产生的收入和费用

2. 非经营部分: 副业(彩票中奖)

   报告公司次要或附属活动的收入和费用


除关注收入和利润的数字大小外, 还需关注两个重要指标:

1. 毛利率: 反映公司的成本控制能力

   扣除的是销售商品的成本

2. 净利率: 反映公司的盈利能力

   在毛利的基础上, 再扣除三费:
   - 销售费用
   - 管理费用
   - 财务费用

* 现金流量表: 财力
企业日三省吾身:
1. 钱从哪来
2. 钱花哪了
3. 还剩多少

现金的流入和流出与三类活动相关——经营活动、投资活动、筹资活动。

首先, 我们要重视“经营活动现金流量”，因为这个数字可以反映运营利润的质量。

经营活动的现金净流入越多，说明利润真实度越高，丈母娘心里就越踏实。

其次, 可以看“流动现金负债保障比率”，翻译成人话就是“债主来收钱了你能不能还
上”，它表示企业能否用一年内生产经营产生的现金来偿付流动债务。

这个比率越高，还不上钱的风险越小，女婿越可靠。

通过经营活动现金量，还可以计算出“自由现金流量”。常见的方法就是从经营活动
净现金流量中减去资本性支出和股利支付后的净现金额。这一数额意味着公司在满
足企业经营全部需求之后，企业可以用来任意使用的现金流量。

在丈母娘眼中，“自由现金流”就是女婿在满足基本生活开销之后，能够给女儿买买
买的钱！
