#+TITLE: 学习: 五险一金
#+DATE: <2019-09-30 Mon>
#+OPTIONS: toc:nil num:nil

* 五险一金是什么
年轻时身强力壮, 加班拼搏没啥好说的. 但人都有个生老病死, 后面干不动的时候怎么办?

为了解决这个后顾之忧, 有了社会保障制度, 简称 =社保= .

社保也就是常常听说的 =五险= , 具体包括:

#+begin_quote
- 生育(生)
- 养老(老)
- 医疗(病)
- 工伤(病)
- 失业(倒霉)
#+end_quote

一金指的是 =住房公积金=, 每月固定交一小部分的钱, 解决租房买房的忧虑.
* 五险一金交多少
五险一金由两部分组成, 个人和公司各交一部分.

个人只需要交三险一金(小头): 养老/失业/医疗/公积金;

企业需要交五险一金(大头): 生育/养老/医疗/工伤/失业/公积金.

具体要交多少呢? 有一个公式:

#+begin_example
应缴金额 = 缴费基数 * 缴费比例
#+end_example

一个城市中, 总是有人赚的多, 有人赚的少, 但有一个平均工资, 在这基础上可以设置一个上限和下限.

如果你工资比设置的下限还低, 缴费基数就按下限来计算;
如果你工资比设置的上限还高, 缴费基数就按上限来计算;
如果你工资在上下限中间, 缴费基数就按你实际工资来计算.

缴费比例各城市具体定义.

你的税前签约工资, 扣除五险一金, 再扣除个人所得税, 到手的钱就是税后工资.

* 五险一金怎么用
我们交的五险一金, 最终存进了两个钱包:

1. 你自己交的那部分, 进入你的个人账户
2. 公司帮你缴的那部分, 进入统筹基金账户(国家帮你管着)

那这些钱需要用的时候, 怎么花呢? 得分开来看:

** 养老保险
养老保险的钱统一入了养老保险基金账户, 国家用这钱给现在的老年人发养老金.

等你退休后, 才能领养老金, 但有个前提:

#+begin_example
你退休前, 养老保险缴费 15 年.
#+end_example

如果你没交够 15 年养老保险, 那你自己缴的那些钱退还给你, 但公司交的那部分就和你没关系了.

** 医疗保险
你自己交的那部分进入到了你个人医保账户, 也就是你的 =医保卡=.

平时头疼脑热看病买药, 都可以刷这卡, 就和刷银行卡一样. 当然, 有些药不在医保范围内的, 不能刷卡使用.

小病用医保卡, 大病咋办?

公司帮你缴的医疗保险费用大部分进了统筹基金, 要看大病时, 可以帮你报销一部分.

** 失业保险
当你缴满一年的失业保险, 并且被公司开除了, 可以去社保局填表申请, 但钱数基本可以忽略.

** 工伤保险
在你工作时, 受伤了;

上下班路上出了交通事故;

有些职业会有职业病.

这些都可以走工伤保险.

** 生育保险
女同学生小孩, 可以有带薪产假/生育津贴/医疗费报销.

男同学可以休带薪陪产假.

** 住房公积金
你没房子时, 可以将公积金取来用于:

  - 租房
  - 自己盖房
  - 自建房翻修

当然, 公积金最重要的用处在于, 买房时可以申请公积金贷款(利率有优惠).
