#+title: 互联网概念
#+options: toc:nil num:nil

* 人口红利
所谓人口红利，从社会学角度讲，是指一个国家的劳动年龄人口占总人口比重较大，抚养率
比较低，为经济发展创造了有利的人口条件。

互联网的人口红利则不同，指的是互联网用户不断增多，企业可以用较小成本快速获得流量。
* 网络效应
又称网络外部性（network externality），指在经济学或商业中，消费者选用某项商品或
服务，其所获得的效用与“使用该商品或服务的其他用户人数”具有相关性时，此商品或服务
即被称为具有网路外部性。

最常见的例子是电话或社群网路服务：采用某一种社交媒体的用户人数越多，每一位用户获
得越高的使用价值。

这个概念在罗伯特·梅特卡夫宣扬之下而广为人知。 梅特卡夫定律指出：

=一个网路的价值与联网的用户数的平方成正比=

也就是每位用户所获得的效益并非常数，而是大约随著网路用户总人数成线性成长。
* 国民总时间
GNT(Gross National Time) = W(网民总数) * T(网民日均上网时间)

互联网的空间无限性, 遇到了网民的时间有限性, 整个互联网的竞争格局发生了明显变化,
所有人都是争抢用户时间的对手.

* 消费互联网
消费互联网面对的是消费者个人, 它的商业模式以“眼球经济”为主，即通过内容和信息来获
得流量，从而通过流量变现的形式吸引投资商，最终形成完整的产业链条。

消费互联网讲爆款、流量、体验、唯快不破、链接节点较短、交易高频次低价值
* 产业互联网
产业互联网，必须是“产业+互联网”，而不是“互联网+场景应用”，它是以产业为基础，从产
业出发，而不是从互联网出发；产业是基础、产业的互联网是技术手段、价值的实现是根本.

产业互联网讲的是供应链的协同集成与优化、十分看重价值实现、需要一定的产业隐形知识
的积累、讲究地推、较长的价值链条的整合、低频高值、决策难度大。
* 物联网
[[https://www.wikiwand.com/zh-hans/%25E7%2589%25A9%25E8%2581%2594%25E7%25BD%2591][物联网]]（英语：Internet of Things，缩写 IoT）是互联网、传统电信网等资讯承载体，让
所有能行使独立功能的普通物体实现互联互通的网络。

物联网的实现需要给每个物体分配唯一的标识或地址。最早的可定址性想法是基于 RFID 标签
和电子产品唯一编码来实现的。

物联网的核心和基础仍将是互联网。但互联网需要一系列技术升级才能满足物联网的需求，
例如 IPv6、Web_3.0。
* 人工智能
[[https://www.wikiwand.com/zh-hans/%25E4%25BA%25BA%25E5%25B7%25A5%25E6%2599%25BA%25E8%2583%25BD][人工智能]]（英语：artificial intelligence，缩写为 AI）亦称机器智能，指由人制造出来
的机器所表现出来的智能。
