#+TITLE:       读书: 投资至简
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-03-09 Tue
#+URI:         /blog/%y/%m/%d/investment-is-simple
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

** 投资体系
#+begin_quote
投资体系是投资者关于投资的认知和行为的集合，包含了投资者对投资目的和投资意义的选
择，包含了投资者的资产观、市场观和风险观，也包含了投资者在资产配置、标的选择和市
场择时（择价）的具体做法。

投资体系在深层次是投资者世界观、人生观、价值观和方法论的反映。
#+end_quote

有没有一句话可以总结出投资的本质和全部精髓。甚至以这句话为原点出发，就可以推导出
整个投资体系呢? 我们认为是存在的，这句话就是：

#+begin_quote
投资就是:

放弃一种资产，获得另一种资产更多的 _未来现金流的折现值_ 。
#+end_quote

这句总结, 就是价值投资体系的地基。

现金流折现是评估一切资产价值的统一标准。不论你买的是股票,黄金,还是一只老母鸡, 都可以用其未来现金流折现来统一评估其价值。

你买一棵苹果树, 它的内在价值就等于: (A + B - C) 折现值

- A: 这棵苹果树从现在一直到枯死期间, 一共摘下的所有苹果的价值
- B: 最后卖掉枯萎苹果树的清算价值
- C: 这期间所有的成本

你买一套房子, 它的内在价值就等于: (A + B - C) 折现值
- A: 房子出租赚到的钱
- B: 最后结束出租, 卖掉房子赚到的钱
- C: 维护成本

*任何资产的 _内在价值_ , 都是其未来现金流的折现。*

有了投资体系的地基, 我们可以由此推理出四面墙体:

1. 企业思维

   因为你想要的是股权公司未来的现金流，所以短线的低卖高卖就不应该是你的追求。你
   追求的是这家公司的股权，有了股权，你才可以分享到这家公司未来的现金流。

   也就是说, 你买一家公司的股票, 就是买入了这家公司的一部分。买入之后, 你的买入
   成本价就不再是你的关心对象, 你关心的是手上持有的股权比例, 以及这家企业未来发
   展是否如你预期。短期的上涨和下跌, 你不需要特别关注。

   在企业思维下, 并不存在止盈止损的概念。 你需要考虑的永远只有两个问题:

   - 这家企业的内在价值是否越来越高?

   - 我在这公司持有的股权比例能否越来越大?

2. 安全边际

   因为企业的未来现金流没有办法精确计算, 只能粗略预估, 所以你需要给自己留出点余
   地, 用来容错, 容你估算逻辑的误差，容企业未来发展道路上的黑天鹅。

   比如你计算出一家企业未来现金流折现值是10块至20块之间, 你不应该以10块的价格买
   入, 要给自己留出Buffer, 比如 5块买入。 5块到10块之间的5元空间，就是你给自己留
   的Buffer。 这样就算后面企业发展不如预期, 你也不至于损失惨重。

   唯一可以用来判断是否拥有安全边际的标准, 就是计算一家企业未来现金流的折现值相
   对于当前的市值。

   有了安全边际, 你就可以用同样的钱, 买入更多的股权。

3. 市场先生

   因为股票的价格，并不是由一个两个人说了算, 而是所有参与该公司股票的股民共同决
   定, 可以把这个共同意识称作 ="市场先生"= , 它时而冷静理性, 时而狂热激进, 时而悲
   观保守。

   股价在短期内和给定时间点具有随机性, 完全不可预测。

   也正是因为市场先生的脾气捉摸不透, 才会有市场低估的时候(你应该买入更多好公司股
   权), 也会有市场高估的时候(你可以考虑暂时卖出被高估的股权, 待市场先生冷静后再
   低价购入)。

4. 能力圈

   所谓能力圈, 就是我们能够判断现金流折现的范围。

   计算一家企业未来现金流, 是一件非常困难的事情。所以, 我们更应该坚守在自己的能
   力圈范围之内, 去评估自己相对更了解, 更能看的懂的行业中的优秀企业。更通俗的说
   法就是 *不懂不做* 。

   一个人的能力圈的大小不重要, 知道能力圈的边界在哪里最重要。我们应该终身学习，
   不断拓展能力圈的边界。在不出边界的前提下, 能力圈越大越好。

有了地基和这四面墙体, 我们的价值投资体系基本搭建完成了。

投资这件事, 战略的部分就基本在这里结束了, 剩下的就是一些战术问题了。

** 投资什么?

首先要回答的问题, 投资什么? 买房? 炒股? 存银行？ 买比特币?

这里首先需要了解下 =投资策略= 。

投资的策略涉及 _资产配置_ , _标的选择_ , _市场择时_ 三个方面。

*资产配置* 主要是回答投资组合包括哪些大类资产, 每种类别资产所占的比例各是多少。

*标的选择* 主要是回答每个单独的资产类别, 选择哪些具体标的。

*市场择时* 主要是回答针对选中的具体标的, 在什么时间以什么价格买入多少。

在这三者之中, *资产配置* 是投资的首要决策。

每个人,无论是否意识到, 都在时刻做资产配置: 现金, 银行存款, 余额宝, 基金, 股权,房
产等等。 富人在全球配置股权或房产是一种资产配置，农村老太太把积攒一辈子的钱埋在
床底下也是一种资产配置。 所以人人都在做投资，即使你担心投资的风险, 决定什么都不
做, 实际上你也做了一项投资决策--不改变当前的资产配置(继续持有现金)。

所有资产类别中, 股权类资产是中长期收益最高的资产。 上市公司股权是股权类的一个类
别, 可以便利化标准化获得和转让(也就是"炒股"); 创业公司股权也是股权类的一个类别,
参与创业的一大好处就是能获得其未在二级市场交易的股权。
** 什么价格买?
是否买入的唯一的判断标准, 就是当前股价与未来现金流折现值的差距。

这个差距具体要到多少才叫合理买入价格？ 答案是因人而异。

所谓的 *合理价格* , 就是在自己能力圈内对所有投资机会不断进行比较, 最终选出的风险最
低, 收益最高的机会价格。

因为每个人能力圈不同, 机会成本也不同。所以, 对同一只股票, 每个人面临的合理价格是不同的。

对于张三来说, 他只了解互联网公司, 比较一圈下来, 预计腾讯股票未来10年有10%的收益
率, 这高于他手上其它的几个选择--债券,余额宝--那么腾讯股票现在的股价对于张三就是
合理买入价格。 对于李四来说, 他不仅了解互联网公司, 还了解白酒行业, 茅台的未来10
年有20%的收益率, 那么腾讯现在的股价对于李四来说, 就不是合理的买入价格, 而是高估
的。 如果李四选择了腾讯, 根据机会成本的概率, 李四其实是亏损10% 的。
** 应该买多少?
AT&T 的物理学家凯利, 通过研究信息率, 发现可以在知道胜率和赔率的情况下, 确定最优
的下流比例, 从而使自己的长期复合收益最大化, 这就是著名的凯利公式:

$$f = (p * R_w - (1 - p) * R_l) / R_w * R_l$$

- f 为最优的下注比例
- p 为赢的概率
- 1-p 为输的概率
- R_w 为赢时的净收益率(能赚多少倍)
- R_l 为输时的净亏损率(能赔多少倍)

比如你现在有100万元闲置资金， 朋友有一个创业项目, 想拉你投资。你觉得这个项目有八
成概率能赚到200万元, 两成概率会赔光所有钱。你该不该投入，或者说你应该投资多少呢?

带入凯利公式计算一下:

$$(0.8 * 2 - 0.2 * 1) / (2 * 1) = 0.7$$

也就是说, 这个项目你可以拿出70万元来投资，是最佳的投资比例。


** 什么时候卖?
是否卖出的唯一的判断标准, 就是当前股价与未来现金流折现值的差距。

有四个时机是应该卖出的时候:

1. 发现当初对企业 *看错了*

   价值投资者没有 *止损* 一说, 但应该坚决 *止错* 。

   如果对企业价值评估失误，也就是当初买入时对 =价格和现金流折现值比较= 做了错误的
   判断, 一旦发现应该立即卖出, 不论这个时候股份是跌了很多还是涨了很多。

2. 企业后来的基本面发生了 *长期的恶化*

   如果后面企业发展过程中, 出现了一些错误决策, 或者行业情况出现了根本性的变化,
   导致企业的基本面发生了恶化, 并且长期来看也不会好转, 你应该卖掉。

3. 企业价值被 *极度高估*

   你要买入一棵苹果树, 预估未来产出的苹果价值折现是100块, 你用了50块买入, 这笔投
   资很不错.

   如果第二天, 有人出价1000块要买这棵苹果树, 你当然应该卖给他。这就是价值被极度高估了。

4. 发现了 *明显更好* 的投资机会

   在持有A 公司的过程中, 发现了B 公司, 它可能和A 一样优秀甚至更加优秀, 估值还更
   低, 那么卖出A, 买入B 也是可以的。
** 总结
#+begin_quote
不预测市场，但利用市场已经给出的机会，不断将自有资产转换为少数价格合理，且我们可
以深刻理解的优质股权尽量多的份额，逐步构建一个稳健均衡的优质股权资产组合，耐心持
有这些公司，伴随其尽可能长的经营时间。
#+end_quote
