#+TITLE:       学习: 高效学习的策略
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2020-05-06 Wed
#+URI:         /blog/%y/%m/%d/学习-高效学习的策略
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t


最近读了 [[https://www.scotthyoung.com/][Scott Young]] 关于如何高效学习的电子书, 里面介绍了他是如何在一年内完成 MIT 四年的课程,如何在一年内学会了四门外语,战果颇有说服力。电子书中主要讲了他学习不同内容时,使用的七种通用策略：

** 设计你的学习项目
1. 仔细挑选你的限制条件

   不要一上来就什么都学，无限的细节总会让你烦到想放弃。

   上来先限定一下学习范围,比如学习 Emacs，可以先从学习 Orgmode 开始。

2. 留出足够的学习时间

   学习需要时间，留出专门的学习时间来。

3. 限定你的学习资料

   不要拿七八十来本参考资料, 也不要一本都不找,有问题全凭 Google（容易钻进兔子洞出不来）。

** 训练专注力和产出力
1. 排除干扰
   戒网、戒手机、戒电视，戒让你分开的东西。

   可以采用番茄钟的方法，学习 25 分钟,休息 5 分钟，用来喝水，走两步等。

2. 做好日程管理

   做一个掌握自己时间的人，你不做计划，就意味着你让别人来计划你的时间。

   定好日程计划和优化级，尽可能按计划来做。

3. 渐进式锻炼专注力

   你只能专注 15 分钟?那就练下专注 20 分钟。

   做到了之后，再试下挑战专注 25 分钟。

** 主动式学习

所谓主动式学习，就是 =练= 。

拿你学的东西去解决问题，去回答别人的问题，去教别人。

当你在主动式学习遇到困难时，比如概念的意义理解不够，对各概念之间的关系没有理解
清楚等，回到被动式学习上来，重读你的资料，听老师讲，看视频学。

** 加速反馈回路

所谓反馈回路， 就是你应用了你到的东西后，可以获得你哪里可以改进的信息。

重点有三：
1. 反馈越快越好（小步快跑，敏捷实践）
2. 反馈越强越好（做个大项目，涉及方方面面）
3. 反馈越准越好（找个领路人，踩过坑）

** 艾宾浩斯遗忘曲线

=一次性学五个小时= ，和 =每天学一小时学五天= ，哪个效果好？

关于人类记忆，已经有现成的科学结论，尽量使用 Anki 之类的软件，来定期复习学习。

** 用点子智慧

学习不要只是在书上画重点，摘抄笔记。

要用点子智慧，像金圣叹读水浒一样，写下你的理解，你收获会更大。

** 温故而知新

学习前期很容易感受到明显的成长进步， 但终究会遇到成长瓶颈。

这时候静下心，继续练那些你已经学会的知识，剩下的交给时间，看看老树是否开新花。
