#+TITLE:       读书: 如何解决复杂问题
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-10-13 Wed
#+URI:         /blog/%y/%m/%d/life-finds-a-way
#+LANGUAGE:    en
#+OPTIONS:     H:5 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

#+begin_quote
进化, 是指种群里的基因频率的改变。
#+end_quote

*<如何解决复杂问题>* 这书主要介绍了生物进化历程中的三大决定性力量: 自然选
 择(基因突变), 基因漂变和基因重组。以及作者发现的, 在解决复杂问题时, 创
 新方案的出现过程和生物进化过程的相似性。

#+begin_quote
基因突变, 是指细胞中的遗传基因发生的改变。
#+end_quote

基因突变, 是进化的原始动力所在。突变后的基因, 经历自然选择, 适合生存的新
基因得以存活下来, 并不断在群体中传播。

推演到个人身上, 如果你也想获得认知进化, 就需要把自己的 =meme= 频率做些改变。
最常用的三种方式就是 =读书= , =交流= 和 =旅游= 。 这三种方式都是在让你接触新鲜
的世界和观点, 从而不断地打破之前的认知, 更新提升自己。

#+begin_quote
基因漂变, 是指种群中基因库在代际发生随机改变的一种现象。
#+end_quote

基因漂变, 是让基因频率发生变化的另一股力量。可以简化想象一个钢珠丛林的游
戏, 一堆钢珠, 有红和绿两种颜色, 数量相等, 从上往下穿过各种钢钉, 最终漏到
最下方出口的那个钢珠, 颜色是随机的, 但最终只有一个颜色得以通过, 另一种颜
色就消失在了后续的游戏(传播)中了。

推演到个人身上, 联想到了 =信息茧房= 的概念。如果你长期只接触固定的信息源或
信息圈子, 那么很有可能你最终会形成一种固定的思维模式, 而忽略了其它多样性
的视角。 针对同一主题, 要养成了解多方说法的习惯, 看看左派的说法, 再瞅瞅
右派的视角, 拿这些观点和自己的认知做个碰撞, 得到自己的结论。

#+begin_quote
基因重组, 是指在生物体进行有性生殖的过程中，控制不同性状的基因重新组合。
#+end_quote

基因重组, 有点类似游戏中的 =闪现= 技能, 虽然这个闪现的方向不一定是你想要的。

推演到个人身上, 联想到了学到一个完全不同的新思维的情况。比如记笔记, 之前
的思维是一事一记, 定期复盘。后来接触了卡片笔记法, 和之前的思维就完全不同。
这两种笔记方式如何整合, 形成适合自己的笔记方法, 就是一种认知重组。
