#+TITLE:       总结：如何完成一个目标
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-07-21 Wed
#+URI:         /blog/%y/%m/%d/ljg-gtd
#+LANGUAGE:    en
#+OPTIONS:     H:5 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

设想你设定了一个想要实现的目标(比如三个月时间考过英语六级), 对着这个宏伟
的目标, 先从哪下手呢?

当对一个东西无从下手的时候, 最好的办法就是将其大而化小, 小到你知道怎么下
手为止。

具体来说, 两步走:

1. 将复杂目标拆解成任务

2. 按 GTD 流程完成这些任务

** 拆解目标为任务

   *为什么要拆解?*

   拆解之后, 一个大的问题就变成了一堆小问题的集合。 通过解决一个个知道如
   何解决的小问题, 实现解决大的问题。

   *如何将目标拆解成子目标?*

   可以通过 _加法_ 或 _乘法_ 的方式来拆解目标。 加法是指目标是由 A + B + C
   三部分组合而成, 分别解决 A, B, C 就解决了我们的目标。 乘法是指目标是
   由 A * B * C 三个变量因素关联而成, 我们需要针对 A, B, C 专项讨论提升,
   进而解决目标。

   *子目标什么时候才会被称作任务?*

   当你把目标拆解成子目标(组成因素)之后, 如果面对子目标, 仍然无从下手,
   就可针对某个子目标, 同样使用 _加法_ 或 _乘法_ 的方式, 做进一步的拆解, 直
   到拆解出的子目标可以被你轻松解决为止。

   如何判断 *轻松解决* 呢? 当一个子目标可以被 *谁* *在什么时间* *做什么事情*
   (Who do what by when) 很容易的描述时, 就可以被称作是 _任务_ (Task) 了。

** 执行任务流程

   那拆解完成后, 得到了一堆的任务, 这时候怎么办呢?

   用 *GTD* 流程来将这些任务一个个解决即可。

   GTD 流程可以分为这么四步:

*** 收集(Capture)
    将上面的任务, 统一按照下面的方式整理到一个文件:

    #+begin_example
    @某人: 做什么 (Deadline)
    #+end_example

    在这个录入过程中, 需要思考:
    1. 删除: 这个任务是不是可以删除不做, 也不会影响
    2. 委托: 这个任务是不是可以交给其它人来帮忙做
    3. 时间：这个任务的最终完成时间是什么时候

*** 处理(Process)

    将上一步收集并设定 Deadline 的任务, 在你的日历中呈现。

    每天从中挑出当天需要完成的任务即可。

*** 复盘(Fupan)

    参照 [[https://www.lijigang.com/blog/2021/07/05/how-to-fupan/][TMD 复盘法]]
