#+title: 神逻辑
#+author: 李继刚
#+options: toc:nil

#+BEGIN_QUOTE
「You can you up, no can no bb」.

「你知道他有多努力吗?」

「还说我不支持正版, 你就没有在网上下载过电影?」

......
#+END_QUOTE

如果你听到这些话, 总感觉哪里不对, 但又说出来个所以然的话, 推荐你读下[[https://book.douban.com/subject/26753478/][「神逻辑」]] 这本书.

这书总共就 50 来页, 一共讲了 19 个常见的「逻辑谬误」, 每个谬误都用一页纸来说清楚, 并配一张插图说明.

需要先了解下逻辑学中的三个基本概念:

=命题=: 一个陈述, 或为真, 或为假, 但不能亦真亦假.

=论证=: 一组 *命题*  集合, 其目的是以推理说服他人.

=逻辑谬误=: 从一个 *命题*  推衍至下一个命题的过程中发生的错误, 最终导致错误的 *论证*.

书中介绍的 19 个逻辑谬误可以分为三大类:

* 形式谬误
#+BEGIN_QUOTE
因结构缺陷而导致论证不合逻辑的错误.

对于这类谬误, 只需要分析论证的形式, 就能发现错误. 不需要分析其内容.
#+END_QUOTE

** 肯定后件谬误

常用的论证形式之一是: 如果 A 则 C; A 成立, 因此 C 成立.

这里 A 被称为「前件」, C 被称为「后件」.

而 =肯定后件= 的形式谬误表现为: 如果 A 则 C; C 成立, 因此 A 成立.

#+BEGIN_EXAMPLE
如果那人是男人, 那人可以结婚.

但因那人可以结婚, 而推断那人是男人.  这就犯了肯定后件谬误.
#+END_EXAMPLE

** 否定前件谬误

该谬误表现为: 如果 A 则 C; A 不成立, 因此 C 也不成立.

#+BEGIN_EXAMPLE
如果那人是男人, 那人可以结婚.

但因那人不是男人, 而推断那人不可能结婚, 这就犯了否定前件谬误.
#+END_EXAMPLE

* 无关转移

#+BEGIN_QUOTE
使论证偏离了最初的命题.
#+END_QUOTE

** 诉诸结果谬误

该谬误是指住所某观点 *如果* 成立(或不成立)所产生的结果好坏, 来判断一个观点是否正确.

但一个命题导致不利的结果, 并不意味着该命题就是假的. 因一个命题导致有利的结果, 也不意
味着该命题就是真的.

#+BEGIN_EXAMPLE
上帝若不存在, 人们便能为所欲为.
#+END_EXAMPLE

且不说人们是否真的会为所欲为, 就算果真如此, 也不能用来说明上帝的存在.

** 诉诸恐惧谬误

该谬误是指利用听众的恐惧, 设想某命题若被接受将产生一个可怕的未来.

#+BEGIN_EXAMPLE
如果他当选了, 你们所有人都将失业.
#+END_EXAMPLE

** 诉诸潮流谬误

该谬误是指以许多人均相信某命题的事实为依据, 来证明该命题一定是真的.

#+BEGIN_EXAMPLE
太阳是地球转? 还是地球绕太阳转?
#+END_EXAMPLE
** 罪恶关联谬误

该谬误是指通过指出某个被社会妖魔化的个人或群体也认同某观点, 以诋毁该观点.

#+BEGIN_EXAMPLE
我的对手主张, 应该在教育上投入更多的钱.

你们知道还有谁这么认为吗? 这个独裁者!
#+END_EXAMPLE
** 稻草人谬误

该谬误是指有意地滑稽模仿他人论点, 以达到攻击模仿出来的论点而非实际论点的目的.

稻草人论点通常是歪曲、错误引用、曲解或将对方立场过分简单化, 更容易攻击这个修改后的论
点.

#+BEGIN_EXAMPLE
达尔文说我们是从那些在树上摇来荡去的黑猩猩变过来的, 这真太可笑了.
#+END_EXAMPLE

这是对进化生物学的一种扭曲, 进化论的实际陈述是: 人类和黑猩猩在数百万年前拥有共同的祖
先.

** 起源谬误

该谬误是指仅仅因为某观点的起源就贬低或维护它.

#+BEGIN_EXAMPLE
他当然支持那些罢工的工人, 说到底, 他们都是一个村子里的人.
#+END_EXAMPLE

** 诉诸无关权威谬误

该谬误是指以其它领域无关权威的观点做为论据.

#+BEGIN_EXAMPLE
「风水盛行于古中国, 集合了古代中国人的智慧.」
#+END_EXAMPLE

** 人身攻击谬误

该谬误是指通过攻击一个人本身, 而不是攻击其论点, 以转移讨论话题, 最终达到诋毁其论点的
目的.

#+BEGIN_EXAMPLE
你又不是真正关心降低城市犯罪率, 你只是想要人们投票给你!
#+END_EXAMPLE
** 诉诸虚伪谬误

该谬误是指通过指出某人的观点与其本人的行为或以往陈述相矛盾来反驳该观点.

也就是: 用指控来回答指挥, 把注意力从观点本身转移到提出观点的人身上.

#+BEGIN_EXAMPLE
A: 你干吗一直偷吃我的粥?

B: 你不也一直偷吃妈妈的蜂蜜?
#+END_EXAMPLE

* 非形式谬误

#+BEGIN_QUOTE
因内容和语境而非形式, 导致论证不合逻辑的错误.
#+END_QUOTE

** 词义模糊谬误

该谬误是指利用语言的歧义, 在论证过程中通过改变词义来支持一个无事实根据的结论.

#+BEGIN_EXAMPLE
你隔天可以吃一次果酱, 但今天绝对不行, 因为「今天」不是「隔天」.
#+END_EXAMPLE

** 修改定义谬误

该谬误是指 A 对一组事物下了一般性的断言, B 提出证据质疑该断言, A 就通过修改该组事物成员
的资格来回避该质疑.

#+BEGIN_EXAMPLE
A: 程序员都有社交障碍!
B: John 就是一个程序员, 他一点没有社交障碍.
A: John 并不是一个 *真正的程序员*
#+END_EXAMPLE

** 乱赋因果谬误

该谬误是指「后此即因此」以及「伴此即因此」.

后此即因此: 只因为事件 A 在事件 B 之前发生, 就被认为是 B 发生的原因.

伴此即因此: 只因为事件 A 和 B 同时发生, 就被认为是 B 发生的原因.

#+BEGIN_EXAMPLE
每当长夜将尽、破晓之前, 我在山顶呼唤太阳出现. 太阳总是如约而至.
#+END_EXAMPLE

** 滑坡谬误

该谬误是指: 试图证明接受某命题将无可避免地导致一系列事件, 且其中的一个或多个事件是不
受欢迎的, 以此来诋毁该命题.

但实际上, 尽量这一系列事件 *有可能* 会发生, 但该论证假设每一步都是 *不可避免* 的, 却
没有提供证据证明.

#+BEGIN_EXAMPLE
如果你允许一个陌生人进入你的前院, 第二天他就会登堂入室, 第三天他就会偷光你所有东西.
#+END_EXAMPLE
** 虚假两难谬误

该谬误是指给出一个由两种范畴组成的有限集合, 并假设讨论范围内的一切事物都必须属于该集
合. 因此, 拒绝其中一个范畴, 便只好接受另一个.

#+BEGIN_EXAMPLE
在这场战争中, 谁都不能置身事外. 你若不站在我这边, 就在敌人那边.
#+END_EXAMPLE

** 合成&分解 谬误

合成谬误是指从所有局部拥有某属性就推断出总体也一定具有该属性.

分解谬误是指只因总体拥有某属性, 就推断某局部也一定拥有该属性.

#+BEGIN_EXAMPLE
我们队所向披靡, 因此我们队的任何一名队员都能单挑赢另一队的任一球员!
#+END_EXAMPLE
** 循环论证谬误

该谬误是指待证明的结论被含蓄或明白地置入了一个或多个前提中.

#+BEGIN_EXAMPLE
你完全错了, 因为你说的没有道理.
#+END_EXAMPLE
** 轻率归纳谬误

访谬误是指当论证者从某样本得出结论, 而该样本太小或太特殊, 以至于缺乏代表性.

#+BEGIN_EXAMPLE
在大街上问题了十个人, 对国家税收的看法, 就评估说国家税收较轻.
#+END_EXAMPLE

** 诉诸无知谬误

该谬误是指仅仅因为没有证据证明某命题是假的, 就认为它是真的.

#+BEGIN_EXAMPLE
没有令人信服的证据表明 UFO 从未拜访过地球, 因此, UFO 是存在的.
#+END_EXAMPLE
