#+title: 哲学了没: 哲学到底是什么
#+DATE: <2019-11-17 Sun 19:41>
#+options: toc:nil num:nil

#+BEGIN_QUOTE
人们出于对智慧的热爱所探究的问题, 可被视为「哲学问题」
#+END_QUOTE

与其将哲学视为一门「学科」，不如说哲学是一门教导我们如何运用理性来思考的「方法」。理性可以有很多种，仅从目的而言，哲学最常使用的理性能力为「逻辑能力」。

通过观察，我们对各种事物及概念做出性质上的区别与分类，接着使用逻辑来做出论证。哲学理论的说服力奠基于逻辑论证之上，因此，想要学习哲学思考，必定要先了解如何建构一个符合逻辑的论证。

一般来说，哲学论证可以通过两种方法来呈现：演绎法（deduction）与归纳法（induction）。

西方哲学有三大基本问题: 形而上学, 知识论, 伦理学.

* 形而上学
形而上学又被称为「第一哲学」, 它是一门研究事物本质和基本原理的学问. 从古到今, 从来没有任何一个形而上学问题被解决.

典型的形而上学问题例如:
1. 世界的本质是什么? 世界是由什么构成的?
2. 上帝是否存在?
3. 人类到底有没有自由意志?

因为对于形而上学探讨已久却无法获得任何真理，哲学家们分成了两派。其中一派哲学家认为，我们之所以没办法获得任何真理，原因在于形而上学问题的答案超越了人类的能力。我们的心智能力与认知能力都有极限，想获得形而上学的答案或者真理，对人类来说是不可能的。人类不可能获得关于世界的真理，就好像蚂蚁永远不可能理解三维空间的向度到底是什么。

另外一派哲学家则认为，形而上学问题根本就不是真正的问题，它只是一连串通过适当的文法与语词包装出来的句子，看起来好像真有这么一回事，实际上完全没有任何意义。

* 知识论
一直到了科学革命后，人们理解到这世界不像基督教或其他宗教所描述的那样，以前从教堂及传教士口中所获得的知识大多是假的，或者说，那些根本就不算知识。从教堂里获得知识的渠道已经崩溃，人们需要思考另外一种获得知识的途径，以及获得知识的方法。

试想一下, 你自己才能确认自己真的「知道」了上海现在正在下雨这个「知识」?

在哲学上，要说一个人拥有某项知识，初步看来要满足三个条件: 信念、事实、证据。

首先, 你得真的相信上海现在正在下雨; 其次, 上海现在正下雨得是件事实; 最后你相信上海在上雨的理由得充分.

要是你说你做梦梦到上海正在下雨, 所以就坚信这个. 那这是瞎蒙, 不叫掌握知识.

* 伦理学
人是群居动物, 人与人之间必须要有所联系，有所关联。既然人际之间必须有所关联，自然
而然就会有一些大家共同遵守的规范产生。这些规范让人与人之间可以安定平稳地生活在一
起，一旦有人违背了规范，此人将在很大程度上面临他人的谴责及排斥。

除了这些规范，人类还倾向于追求其他的东西, 比如说真善美.
