#+TITLE: 读书摘抄
#+DATE: <2019-06-16 Sun>
#+OPTIONS: toc:nil num:nil

#+BEGIN_QUOTE
在上位的人， 生活安逸， 只求名望； 在下位的人， 像个面团， 只捣糨糊。

对这种官场习气， 这么多年看惯了， 也受够了， 郁积在心， 不平则鸣。

为了改变三四十年来黑白不分，不痛不痒的风气， 我做官，说话开始变的慷慨激
昂，正大刚猛。

但积习牢不可破， 矫枉必然过正， 我有时免不了考虑不周全， 意气用事， 由此
经常被嘀咕， 被埋怨， 被讥讽， 被怨恨。

仁人君子， 同道中人， 别要求我行中庸之道， 请怜惜我的奋起， 矫正的一片苦心。

[[https://book.douban.com/subject/33420594/][成事]]
#+END_QUOTE

#+BEGIN_QUOTE
科学决策的下一个境界是把决策水平和运气分开。

假设摆在你面前有两个选项：选 A， 成功率是 65%； 选 B，成功率只有 35%。

科学的决策是坚决选 A。

如果你选了 A 之后却发现结果是 B 正确，你能说当初不该选 A 吗？

扑克选手能做的是选赢钱概率大的选项。至于结果没成功，那只是运气问题。

头脑清醒的人必须能区分 =决策= 和 =运气= 。


[[https://book.douban.com/subject/30347596/][对赌]]
#+END_QUOTE

#+BEGIN_QUOTE
不可知论不是消极， 而是要求我们的视野从客体转向主体， 要求我们的态度从 =傲慢= 变为 =谦逊= 。

不可知论要求我们必须不停地去寻找认知， 永远保持空杯心态。

MVP 是一种思维方式， 更是一种生活哲学。

要永远保持一种新鲜的心灵，过去的成功， 很可能成为未来的阻碍。过去所做的
所有事情，都是为了获得今天的认知， 认知成为我们一切的起点和抓手，我们所
有的存量都是为了获得认知， 获得增量。

由此， 你的视野才从过去转向未来， 从客体转向主体。

[[https://book.douban.com/subject/26344853/][互联网世界观]]
#+END_QUOTE

#+BEGIN_QUOTE
在我看来， 能给人抄袭的公司都是好公司， 因为垃圾的公司才没人抄袭呢。

而且， 越要让竞争对手抄袭才越好， 因为一旦抄袭养成了习惯， 他们就永远丧
失了创造力， 也就没办法超越我们了。

=分享， 是一种最好的教化， 可以让大部分竞争对手变成守株待兔的人。=

当然要有一个绝对的前提， 就是你要不断地超越自己， 不断地推翻以前的内容，
不断地提升， 这就是一种软实力， 一种设计战略。

[[https://book.douban.com/subject/27004664/][一个电商运营总监的自白]]
#+END_QUOTE

#+BEGIN_QUOTE
如果有办法「观察」一件事物, 这件事物就能被某种方法衡量. 无论这项衡量有多
「模糊」, 只要能让你知道得比以前多, 它就是一项衡量.

=衡量: 根据一项或多项观察, 以数量表达的方式降低不确定性.=

[[https://book.douban.com/subject/25810463/][如何衡量萬事萬物]]
#+END_QUOTE

#+BEGIN_QUOTE
=完美= 不是添无可添, 而是再没有可以拿走的了.

[[https://book.douban.com/subject/25831390/][追寻优雅]]
#+END_QUOTE

#+BEGIN_QUOTE
=胜负在于潜在顾客的心智= ， 这是定位理论中最基本的概念。

......

定位的最新定义是： =如何让你在潜在客户的心智中与众不同=

[[https://book.douban.com/subject/1017180/][定位]]
#+END_QUOTE

#+BEGIN_QUOTE
哥德尔第一定理：任何一个体系，它必是内部和外部自洽的，这样才能有效运行。
但是任何一个内部逻辑完全自洽的体系，一定存在自身的边界，一旦越过边界，这
套体系一定是失效的，边界外是一个新的体系。

[[https://book.douban.com/subject/26383733/][颠覆式创新]]
#+END_QUOTE

#+BEGIN_QUOTE
当你身居高位，位高权重， 要推行大政的时候，必定会触犯许多人的利益，这个时候需做的一件事就是拉人下水， 只要是与这件事无关的人， 能拉下水一个就是一个， 太子 宦官 皇宫 商人 勋贵 男人 女人 狗， 有一个算一个， 千万不要只顾着埋头去做事， 别等做了一半， 抬头四顾时， 才发现自己没了朋友。

-- 明朝败家子
#+END_QUOTE

#+BEGIN_QUOTE
世界哲学大致可分三派:
1. 印度/犹太/埃及等东方国家, 专注重人与神的关系
2. 希腊及现代欧洲, 专注重人与物的关系
3. 中国专注重人与人的关系

儒家哲学, 范围广博. 概括说起来, 其用功所在, 可以<论语> "修己安人" 一语括之.

其学问最高目的, 可以<庄子> "内圣外王" 一语括之.

-- 儒学六讲
#+END_QUOTE
