#+TITLE: Rime: 输入法神器
#+DATE: <2020-04-19 Sun>
#+OPTIONS: toc:nil num:nil ^:nil
#+URI:         /blog/%y/%m/%d/rime-tools-for-god

有些工具, 属于前期投入成本高, 但价值半衰弱期长, 对应到重要不紧急的象限, 值得你花时间去研究, 输入法就属于这类工具.

* 环境
- 你： 最好会写（或者抄）一点配置代码
- 系统： macOS
- 方案： 五笔 86
- Rime： 鼠须管

通过 Rime 官网下载安装后，会在 =~/Library/Rime= 目录下存储你的用户配置，后续的所有更改都在该目录下进行。

* 道生一： Rime 是什么
使用电脑过程中，打字是必不可少的操作。对于必要操作的效率的效率提升，可以大幅提升你的整体工作效率。

Rime 是一个输入法框架，基于这套抽象出来的通用框架，你可以基于自己的喜好，随意的打扮它，不论是样式或者是词库。它可以让输入法不再是厂商提供的已有功能项，而是让你随心所欲地定制属于你自己的独有输入法。

安装 Rime 后，默认的已经有了一个基本可用的初级输入法。但它真正强大的地方并不在于这个输入法，而是后续你的自定义配置。你的配置就像是给初级输入法打了个补丁，五笔、拼音、日文等等，只要你愿意，都可以定制出来。

是可谓，道生一。

* 一生二： 方案定义和对应词典
一个属于你的个性化输入法补丁，就是你使用 Rime 约定的语言（YAML），告诉它你准备怎么玩。

这个补丁包含两部分： 玩法定义和玩法词典。

Rime 会将你的这两部分 =插入= 到它的框架中， 编译生成一个可运行的个性化输入法。

这两个自定义文件，在 Rime 中被命名为 =你的玩法名称_schema.yaml= 和 =你的玩法名称.dict.yaml=

比如我定义玩法名称为 wubi86_jidian, 那对应的两个配置文件就应该是 wubi86_jidian.schema.yaml 和 wubi86_jidian.dict.yaml

** 玩法定义

以 =wubi86_jidian.schema.yaml= 为例:

#+begin_example
schema:
  schema_id: wubi86_jidian  #Rime 识别的 ID
  name: "极点五笔 86"       #选择方案时显示的名称
  version: "1.0"
  author:
    - 创始人 王永民先生
  description: |
    五笔字形 86 极点极爽版
  dependencies:
    - pinyin_simp
#+end_example

在该文件中描述你的五笔输入法的个性化使用需求，对应的配置项参照官网文档即可。
** 玩法词典

词典文件以 =wubi86_jidian.dict.yaml= 为例:
#+begin_example
name: wubi86_jidian
version: "4.3"
sort: by_weight #by_weight/权重 original/原始
import_tables: #此处是添加用户自定义词库的地方
  - wubi86_jidian_user
columns: #码表格式
  - text #文字
  - code #输入码
  - weight #权重
  - stem
#+end_example

在该文件中存储你的五笔输入法词典（导出你现有的，或者从网上找别人导出现成的都可以）。
* 二生三：拼音反查

如果突然遇到不会打的字（忘掉如何拆解五笔）怎么办？

可以再搞一个拼音输入法备着， 设置一个快捷键，可以随时从五笔输入切换到拼音输入救急。

再搞一个输入法的方法还是同样的，新建 pinyin_simp.schema.yaml 和 pinyin_simp.dict.yaml 文件，分别在其中描述你对拼音输入法的想法。

#+begin_src yaml
# From wubi86_jidian.schema.yaml

reverse_lookup:
  dictionary: pinyin_simp
  #按z键进入拼音输入法
  prefix: "z"
  suffix: "'"
  tips: [拼音]
  preedit_format:
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/
#+end_src
* 三生万物： 自定义词典
有了上面的玩法定义和玩法词典文件，已经可以编译生成属于你的五笔输入法了。

但如果除了默认加载的那个词典，还有一些个性化词组想添加的话，怎么办？

可以单独建一个 wubi86_jidian_user.dict.yaml (看后缀即可知它也是一个词典文件），在你的 wubi86_jidian.dict.yaml 文件中引用它即可。

这样，如果你经常
- 看电视剧，电影，可以把常见的相关词组放进 wubi86_jidian_movie.dict.yaml
- 玩王者荣耀， 可以把相关词组放进 wubi86_jidian_king.dict.yaml
- ...

#+begin_src yaml
# From wubi86_jidian_dict.yaml

import_tables: #此处是添加用户自定义词库的地方
  - wubi86_jidian_user                # 个人私有词库
#+end_src
* 变漂亮点
Hard core 部分上面已经全部完成，剩下的就是一些皮毛的东西。

皮毛样式的修改，Rime 有约定俗成的文件命名。

1. 设置输入法皮肤

   建立 squirrel.custom.yaml 文件， 在其中按你想法来随便定制。

    #+begin_src yaml
    # From squirrel.custom.yaml
    patch:
      style:
        color_scheme: ink
        horizontal: true
        font_point: 28
        label_font_point: 11
        fullscreen: true
        inline_preedit: true # 单行显示
        corner_radius: 6     # 窗口圆角半径

      preset_color_schemes:
        ink:
          name: 墨池／Ink
          author: 佛振 <chen.sst@gmail.com>
          text_color: 0x000000
          back_color: 0xeeffffff
          candidate_text_color: 0x000000
          hilited_text_color: 0x000000
          hilited_back_color: 0xdddddd
          hilited_candidate_text_color: 0xffffff
          hilited_candidate_back_color: 0xcc000000
          comment_text_color: 0x5a5a5a
          hilited_comment_text_color: 0x808080
    #+end_src

2. 修改默认配置项

     #+begin_src yaml
     # From default.custom.yaml
     patch:
       schema_list:
         - schema: wubi86_jidian
         - schema: numbers
         - schema: wubi86_jidian_pinyin
         - schema: wubi86_jidian_trad
         - schema: pinyin_simp

       # Menu
       menu:
         page_size: 5                    # 候选词数量
       switcher:
         hotkeys:
           - "Control+0"
         abbreviate_options: true
         caption: "【 输入法设置 】"
         option_list_separator: "｜"
     #+end_src

3. 重新布署

  Rime 的所有定制修改，都需要重新编译，方法也特别简单，在系统输入法菜单中选择「重新布署」即可.
