#+title: 如何实现目标
#+author: 李继刚
#+options: toc:nil

我们所有人每天都在和各种「目标」打交道. 有些是自己制定的目标, 有些是老板拍
下来的目标, 但并不是每个目标都能如愿以偿地被我们实现.

关于如何制定目标, 我们对于不同目标的心态和思维方式有什么区别, 最近读了 [[http://book.douban.com/subject/22994632/][成
功，动机与目标]] 一书, 里面的一些讨论具体很高的实践意义, 推荐阅读.

首先, 我们讨论下关于制定目标时候的措词. 有些人平时自己制定目标的时候, 总是
喜欢用「尽力做到...」等语句来描述目标, 比如「尽力做到每天都去健身」, 「尽
力做到每天都早睡早起」等等. 这些语句描述的目标, 其实就已经埋下了失败的种子.

原因也很简单, 我们要实现目标, 首先得要知道目标在哪, 知道了目的地, 才能讨论
如何到达的事. 但上面的那种描述目标的语句, 其实并没有清晰的指出目标在哪, 也
就更谈不上如何实现它了.

那么应该怎么描述目标呢? 使用「具体而艰巨(具有可能性)的目标」. 这里包括两部
分, 一是具体: 同样是要早睡早起, 你如果描述成「每天晚上9点之后不看电脑和手
机, 10点准时关灯上床睡觉」, 目标就很清晰了. 二是艰巨: 当目标比你现有能力要
稍高一些时, 反而会更有动力去参与实现目标. 比如你之前都是晚上2点睡觉的, 现
在制定成晚上10点上床, 这个就是比较艰巨的目标了.

其次, 再来说下动机. 我们有动力去做某件事的因素可以归结为两个: 期望和价值.

期望指的是我们做某事有多大可能会成功. 价值指的是我们能从中收获多大利益.

当你制定了要每周一三五早上7:30到8:30健身的计划后, 如何才能坚持下来? 这里又
涉及到两种思维方式: Why思维和What思维.

Why思维指的是我们为什么要去做这件事. 这种思维一般适用于你做某事已经很熟练
的时候, 可以把一件小事和「意义」, 「目的」这些思维联系在一起, 激励你去做它.

What思维指的是我们做的这件事是什么. 这种思维一般适用于你刚开始做某事的时候,
可以让你关注细节, 把一件很困难的事情给分解成具体的小任务, 可以防止拖延.

比如当你刚开始健身的时候, 你不知道那些器械和动作要怎么进行. 可以用What思维,
把一个具体的动作给拆解开, 先学会起始动作, 中间怎么动作, 终止动作是什么样,
呼吸要怎么配合. 等你把所有动作都已熟练掌握, 还是在某些时候偷懒不想去健身房
的时候, 可以用Why思维, 来想下去健身的目的是什么, 健身对你的意义是什么.

最后, 说下具体执行时心态. 在实现目标的过程中, 不可避免的总会遇到挫折.

比如你想在一个月内学会弹吉它, 你练了一个星期, 基础指法还不太熟练, 更别提弹
一个曲子了. 这时候你会怎么想? 会怀疑自己是不是有弹吉它的天赋吗? 会觉得自己
不够聪明吗?

> 你的聪明程度能影响你做一件事时感受到的难度, 比如, 一道数学题要多难才能让
> 你感学到有困难, 但完全无法决定你解决困难的方式, 也无法决定你是会坚持不懈
> 还是会感到疲倦和无助.

这时候的思维方式又分为两种: 表现型和进步型.

- 表现型注重良好的表现, 从而体现自己的能力(智商, 天赋等)
- 进步型注重进步、成长, 享受学习进步的过程

在顺境时, 表现型思维有很强劲的动力, 也容易带来优异的成绩. 比如某学生成绩连
续几次年级第一, 学习动力更强, 成绩更加优异.

但逆境时, 表现型思维容易受挫, 会怀疑自己, 过早放弃. 比如一次两次考试失败,
觉得自己不想再学习, 不适合学习等.

而进步型思维, 因为出发点是自己是否获得了成长与进步, 不管顺境还是逆境, 始终
都有动力在不断尝试, 根据反馈在修正自己的方法, 从而不断进步.

一般而言, 大公司的KPI制度就属于表现型思维, 员工想的也就是要比其它人做的更
好, 老板更赏识. 而创业公司因为需求和市场的契合度还在摸索过程中, 更多地属于
「进步型思维」, 关注的是产品和市场相比之前是否更契合, 自己获得的认知是否比
之前更精确.
