#+TITLE:       总结: 目标与GAP
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-01-30 Sat
#+URI:         /blog/%y/%m/%d/target-and-gaps
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

每年年底, 除了回顾复盘当前这一年的目标及完成情况以外, 都会需要同时准备下一年的年
度目标。这个新的年度目标的数值高低, 会受老板(或者是你) 个人风格影响 (激进 or 保
守 ), 也会受对环境的预判影响。 不论如何, 最终会确定一个新的年度目标出来。

现在拿到这个目标, 你能怎么办? 你需要分析这个目标的完成路径, 将目标做拆解, 知道其
中哪些事情是有把握的, 哪些是需要冒险的, 哪些是未知的。

上面这些分拆, 可以简单地总结为一个基本， 两个GAP。

** 基本盘
你拿到目标, 做完目标完成路径拆解后, 先看下最有把握实现的部分(概率基本为100%), 能
做到多少值。 这个数值, 就是你的 *基本盘* 。基本盘是基本不需要付出额外心力就能实现
的地盘, 你需要确保这一部分不会下降, 追求如何更高效率地保持基本盘。

** GAP 1
然后你需要看下大概率能完成的部分(概率在70%以上), 能做到多少值。这个数值, 就是你
的 *GAP 1* 。GAP 1是已经基本知道怎么做, 并且大概率可以做到的地盘, 你需要安排最优势
的资源投入到这一部分, 追求如何最大赢率地打赢每一场仗, 从而确保GAP 1被完美填补上。

** GAP 2
基本盘加上GAP 1之后 , 还是够不上目标, 怎么办? 这太正常了, 如果这俩加起来就已经够
上或者超过目标, 就说明目标定的太保守了。剩下的部分就是你的 *GAP 2* 。GAP 2是你也不
知道该怎么办的地盘, 你需要自己来负责这块, 千万不要甩给下属, 直接要结果, 否则大概
率就是一个看天吃饭, 大概率吃不上饭的结果。

GAP 2 是你当前岗位目标中 [[http://www.lijigang.com/blog/2021/01/30/attention-management/][价值系数]] 最高的部分。你需要花费大量时间在这块进行探索,
可能需要经常找其它部门同事或者行业里的朋友交流讨论碰撞, 可能需要经常找你的老板申
请一些资源, 可能需要时不时做些敏捷测试来验证你的想法, 等等。

** 总结

工作也好, 生活也罢, 总归有些事情是你要去做的。在做事的过程中, 明确目标(SMART原则)之
后, 需要你对目标做进一步拆解。看下完成目标的基本盘是什么, 看下以你目前认知水平能
找到的GAP 1 是什么, 同时看下剩下的GAP 2是什么。分解之后, 将你手上的牌放在合适的
区域去实现对应的目标。

不疾不徐, 胸有成竹, 稳步前进。
