#+TITLE:       读书：金字塔原理
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2022-01-05 Wed
#+URI:         /blog/%y/%m/%d/The-Pyramid-Principle
#+LANGUAGE:    en
#+OPTIONS:     H:5 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

#+begin_quote
“这人脑子不清楚，表达没有逻辑”
#+end_quote

什么是表达逻辑? 如何练习提升自己的表达逻辑? 如果只能选一本书, 那一定非
《金字塔原理》莫属了。

*《金字塔原理》* 一书, 一言以蔽之, 无非 *上下左右* 四字。

设想一个场景, 针对一个要解决的问题, 在你收集信息, 调研分析, 各种操作做完
之后, 针对这个问题的所有信息都摆在你眼前的桌面上, 并且都被标上了序号。

现在你要怎么向别人快速表达出来这些信息? 从 1 到 N 的一个个念吗? 这里的标号
有可能是你收集信息的顺序, 这个顺序讲出来, 正常人估计都得骂你一声 "脑子有
病"吧?

金字塔原理这书中提出了一个方法, 就是分为 *上下* 和 *左右* 两步解决这个问题。

* 上下
金字塔原理表达的结构, 你可以理解成把那些信息摆成金字塔形状, 然后从上往下,
从左往右的表达出来就可以了。

上下怎么摆? 谁在上面, 谁在下面?

很简单，上面的那个结点代表的是下面一层结点的抽象总结。

第一层抽象总结了第二层的节点, 第二层的节点, 又抽象总结了第三层的节点, 以
此类推。

* 左右

左右怎么摆? 谁在左边, 谁在右边?

更简单，你只要选定一个确定的逻辑，按这个逻辑顺序来摆就可以了。

这个 *确定的逻辑* 可以是时间顺序(第一年,第二年, 第三年)，可以是空间顺序(北
京, 上海, 深圳)，可以是按值大小降序(最大值, 次大值, 其它)，可以是演绎顺
序(大前提, 小前提, 结论), 等等。

* 示例

没有逻辑的表达:
#+begin_quote
你在办公室，忽然下属进来了，对你说：“老板，我注意到原材料的价格，发现很
多钢材都涨价了，还有刚才物流公司打电话来说提价，我又比较了几家的价格，但
是还是没有办法说服他不涨价；另外，其他的几个竞争品牌最近也涨价了，我看
到……；对了，最近广告花销也比较多，如果……可能……”
#+end_quote

金字塔原理式的表达:
#+begin_quote
老板，我建议涨价 20%。理由如下：

第一，原材料价格最近涨了 30%；

第二，竞争品牌也全部都调价 10%～20%；

第三，广告费也超标了。

老板，综上所述，我认为我们应该涨价 20%，你觉得是否可行？
#+end_quote
