#+TITLE:       学习：时间就是金钱
#+AUTHOR:      lijigang
#+EMAIL:       i@lijigang.com
#+DATE:        2021-01-14 Thu
#+URI:         /blog/%y/%m/%d/time-value
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

这个世界上，人唯一可以做为通用度量的资源，是 =时间= 。

你应该每时每刻去思考，如何才能让你的时间收益最大化。

有三个方法可以提升你的时间价值，这三个方法的提升效率也依次上升。

* 专业化： 提升单位时间价值

产品总监对比产品助理，因为更专业，单位时间价值就更高。

CTO 对比一线研发人员，因为更专业，单位时间价值就更高。

专业化这个杠杆是你最容易使用的工具，也是唯一一个你自己完全可控的工具。

*选好要进入的领域，不断学习精进，提升自己的 =专业化= ， 从而提升自己单位时间的价值。*

* 团队化： 提升整体可用时间

一个人的专业化提升到极致，单位时间的价值也是有天花板的，打工人年薪一两百万已经是绝大多数人的天花板了。

这时候，可以使用第二个杠杆 =团队化= 来提升你的时间价值。

通过调动更多人的时间来做一件事情，只要事情的收益大于为这些人支付的时间成本，这里的利润空间就可以被计入你的单位时间价值中。

可能因为你在一个风口赛道上，事情收益极高，利润空间（也就是你的单位时间价值）也相应的远大于你自己专业化对应的时间价值。（互联网行业/金融行业/等等）

也可能因为你在一个管理幅度极高的团队中，通过压缩团队的成本，来增大利润空间。（HR/财务/行政/等等）

*利用团队的力量（时间），来做出利润空间， 提升你的单位时间价值。*

* 产品化： 提升时间重复利用率

人的时间，属于不可再生资源。

不管是你的时间，还是团队成员的时间，都是每天 24 小时。

但通过第三个杠杆 =产品化= ， 你可以实现时间价值的重复利用。

你用了一年时间，出版了一本书， 这本书就是你的产品。

通过产品化，你实现了一台时间重复计费的睡后收入机器。

即便过了三五年，只要你的书足够有价值，仍然会源源不断地给你带来收入，虽然你只在这书上投入了之前的一年时间。

*尽一切可能，将你的时间投入到产品化的事情中，将你的时间价值最大化。*
