#+title: 未来简史: 人类如何从智人到神人
#+DATE: <2019-04-12 Fri>
#+options: toc:nil num:nil date:t

** 宗教统治世界
宗教给世界带来了秩序, 也为社会带来了意义.

=原始宗教=: 泛灵论认为万物有灵, 一切物品都有灵魂, 并且它们之间, 乃至它们与人类都可以进行交流.

=早期宗教=: 早期宗教来自于人类对自然的崇拜. 古代人无法理解自然现象, 只能将
难以得到解释的事情归结于一个更高等的存在.

=宗教伦理=: 神圣的宗教为世界带来了伦理. 伦理指的是在社会当中得到广泛认可的行文准则.

=宗教秩序=: 有了伦理, 有了规则, 也就有了秩序. 有秩序的世界才能正常运转.

神创造了世界, 还给予了世界一个明确的目的或者结局, 那么世界的存在意义就寄
托在了宗教身上. 假如神圣的宗教作出错误判断, 被人指正出来, 那宗教的神圣性
就会受到怀疑. 由宗教赋予了意义的世界, 也将失去存在的意义.

** 人文主义征服世界
近代以后, 人文主义诞生了, 它认为 =人= 才是世界的根本意义.

=人文主义=: 人是世界的中心, 人的判断能赋予其他事物以意义, 因此人才是世界的
价值所在. 人用自己给世界重新赋予了意义.

=自由人文主义=: 这种观点认为, 自由与自由产生的思想具有至高无上的价值. 因此,
必须尽量尊重个人的自由意志.

=社会人文主义=: 这种观点认为, 个人意志散漫而没有条理, 应当合理地统合人的意
志, 从集体的利益和需要出发, 从而更好地满足作为整体的社会.

=进化人文主义=: 这种观点也承认人是世界的最高价值, 但是依据进化论, 人与人之
间也存在优劣, 因此要通过激烈的竞争让优秀的人生存下去.

现在的人文主义依旧由自由主义人文主义主导. 基于人文主义的观念, 人类追求的
理想应当是无穷无尽的物质财富和不老不死的身躯. 人类正走在实现这一目标的路
上.

** 数据主义接管世界
现代生物科学将人的行为看作是体内生物算法的作用表现, 输入数据, 算法预算后
得出结果, 而生物在受到刺激后作出适当反应.

在数据算法的冲击下, 个人在军事上以及经济上的地位被更加高效的自动化, 智能
化器械替代. 由于可产生价值的降低, 一方面大量智人失去了工作, 另一方面一部
分智人为满足需求需要听从算法的意愿进行工作.

人文主义兴起的实用性基础俢被数据算法逐渐取代, 人文主义宣称的每个人不同人
生体验具有同等价值的观念, 在日益突出差异化中逐渐失去了市场.

算法将揭开新时代的序幕, 碳基生物的思考过程依靠的其实也是算法, 但是硅基电
路能够展开更可靠, 更可控, 更快速的计算, 那时碳基算法将失去优势.

自由与意识是否还会继续有意义?

智能与意识到底哪个才更接近事物本质?

我们真的会过度信赖智能, 就此退出历史舞台吗?
