#+title: 工作心态的六个层级
#+DATE: <2018-07-07 Sat 20:06>
#+options: toc:nil num:nil

今天看到[[https://swellandcut.com/2018/01/17/the-hierarchy-of-work/?utm_source=wanqu.co&utm_campaign=Wanqu+Daily&utm_medium=website][一篇文章]], 将面对工作的心态分成了六个层级. 虽然不太认同作者画的那
个金字塔形状的描绘, 但对于这六个层级还是比较认可的, 在实际工作中, 也确实
遇到了这六种心态的同事.

** 第一层: Minimal(得过且过)
对于这种心态的人来说, 在工作中能少做就尽量少做, 能不做就不做. 目标就是不
会被开除掉就行. 他们的心态就是「混」, 有活来了就和 =杠精= 一样, 各种推拖,
一会说这个要慎重考量, 一会说要老板审批, 一会说要内部会审, 总之就是找一堆
看起来光明正大的理由, 先拖着不做这事再说.

** 第二层: Average(等价交换)
对于这种心态的人来说, 拿多少钱干多少活. 职场中遇到的大多数人其实都属于这
个层级. 工作安排下来, 按自己的节奏正常往前走, 不推不挡, 也不急不躁, 偶尔
遇到急事加个班也能接受.

** 第三层: Hard(加班狂人)
踏实认真, 投入大量时间在工作上. 表现为每天到的早, 走的晚, 勤劳小蜜蜂. 这
种类型的同事已经比较难得, 虽然不一定加班一定出成果, 但起码态度上让老板没
话说, 遇到这种员工, 赚大了.

** 第四层: Smart(逻辑清晰)
上学的时候, 都遇到过平时看着不怎么学习, 但考试时成绩贼好的同学. 这些人上
班后竟然也能一以贯之, 平时下班到点就闪人, 很少见他们加班拼命, 但沟通事情
往往可以很快聊到点上, 做事情也很容易产出结果. 外部合作伙伴和这些人接触后,
往往会评价一句, 「那小伙脑子很活」.

** 第五层: Smart + Hard (智商高还努力)
起点比你高, 还比你更加努力, 你身边一定有这种人的存在. 他们脑子清楚, 而且
干起活来不要命的拼. 站在他们旁边, 你心里兴不起吐嘈的念头, 只能默默叹气,
跟着一起往前冲.

** 第六层: Smart + Hard, 24/7 (活着就是为了工作)
这个层级的人, 一般就是 CEO 那个 Level 了. 工作在他们眼中已经不再是工作, 工作
就是人生, 工作就是全部. 生活也是在配合着工作的节奏进行. 他们不会觉得上班
开会讨论事情损耗精力, 反而会从中吸取能量, 加班不再是加班, 而是在持续地爽.
